### ISSUE TITLE
Total videos archived count is off if playlist contains duplicated videos

### ISSUE THREAD

**Issue by nonmaterialistically** [tubearchivist/tubearchivist#154]
### Issue

When a playlist contains the same video multiple times, it only gets counted once againts the total videos archived count.

### How to reproduce

1. Create a playlist and add a video
2. Add a different video, twice
3. Download the playlist with 3 items (2 videos appear on the download queue)
4. The playlist now says: "Total Videos archived: 2/3"

For any given video, it should probably be counted how many times it appears in a playlist.

**Comment by bbilly1** [comment]
I think a good solution here would be to just not index duplicates in the first place. With the downside that the total videos in the playlist of Tube Archivist won't match with the total on YouTube...

**Comment by nonmaterialistically** [comment]
The latest yt-dlp release includes a new `playlist_count` field in the playlists .info.json. Maybe we could display that in the UI  as the total videos on YouTube, and then display a "unique videos" which is our TA total.

**Comment by bbilly1** [comment]
Closing old issues. Nobody wanted to take this on, as this is working in TA without any problems and mostly cosmetic. If you feel strongly about that, feel free to implement it.
