### ISSUE TITLE
Download and transcode workflow question

### ISSUE THREAD

**Issue by Extarys** [tubearchivist/tubearchivist#174]
I'm looking to create the following workflow:
- TA download the video
- A script on my computer scan for new files
- If the video codec is h264, transcode to AV1 and replace the existing file

I don't know how TA works internally, but will it break something if TA expect a video to be h264, and it's an AV1 file locally? What about changing mp4 to mkv if needed, will TA pick up the change?

BTW thanks for adding subtitle support, I was waiting for that feature to run my instance :heart:

**Comment by bbilly1** [comment]
Check out the [known limitations](https://github.com/bbilly1/tubearchivist#known-limitations) section on the readme. 
So the video file needs to be playable in your browser, that will exclude mkv. Also you can't change the filename, that's not configurable.
Also yt-dlp can download av1 streams directly, no need for any complicated conversion. Check out their documentation on [format selection](https://github.com/yt-dlp/yt-dlp#format-selection).
