### ISSUE TITLE
[Feature request] Transcode/Resize video for mobile streaming

### ISSUE THREAD

**Issue by Aroy-Art** [tubearchivist/tubearchivist#186]
If you archive a video at 4k then it's almost impossible to play on mobile and on a slower connection.

I think if you could transcode/resize on-demand that would be awesome

**Comment by bbilly1** [comment]
I have been thinking about that as well. Transocding is one way to achieve that, but quite complicated. 

Another way to achieve that would be to store multiple versions in different resolutions. I think that would be a better way to do that.

**Comment by PiotrKrzyzek** [comment]
My worry about storing multiple versions, rather than live transcoding, is the additional storage requirements.

**Comment by bbilly1** [comment]
I think it's unrealistic that this project will implement transcoding any time soon. There are many more low hanging fruits that are easier to achieve and bring a bigger benefit for more people. I'd say for now, select the format and resolution that works best for you and your devices.

But who knows what the future holds. if somebody wants to implement this, please reach out.
