### ISSUE TITLE
Some videos doesn't get downloaded, subtitle parsing failes with KeyError('dDurationMs') 

### ISSUE THREAD

**Issue by runkaiz** [tubearchivist/tubearchivist#196]
They don't get removed from the queue either, and I would get errors like this in the log.

[2022-03-27 15:05:08,354: ERROR/ForkPoolWorker-9] Task download_pending[f3dc5974-3157-4669-b18a-6b6fbd2951d9] raised unexpected: KeyError('dDurationMs')

**Comment by bbilly1** [comment]
Thanks for reporting that, looks like an issue with parsing of the subtitles. 

Which video fails? And what subtitle settings do you have? Also a complete stacktrace would be helpful to reproduce the issue, you might have to rebuild the container with the environment variable `DJANGO_DEBUG=True` set, then run the download of the video in question again to get the complete error message in the docker logs.

**Comment by runkaiz** [comment]
Alright so one of the videos are this: https://www.youtube.com/watch?v=LW6ihn4_0gc
By setting subtitles to user generated only solved the issue.

**Comment by bbilly1** [comment]
@runkaiz any progress on this one?

**Comment by PhuriousGeorge** [comment]
This video has the same issue https://www.youtube.com/watch?v=G_TcAxAKCAI

**Comment by bbilly1** [comment]
@PhuriousGeorge Thank you for the link, I was able to reproduce the issue. 

Looks like some environment describing cues in the subtitles don't have a duration, YouTube must handle that separately somehow. Probably best just to skip these except to guess how long that should be displayed.

**Comment by bbilly1** [comment]
Thanks for the help, this is now released in v0.1.4, please update.

**Comment by Jay4242** [comment]
Also got it on v0.1.4 for https://www.youtube.com/watch?v=Mwt35SEeR9w
These also failed for some reason, -40wXsVTcjc, QX2Nxxns4EM, ZAaD24x3PVI

**Comment by bbilly1** [comment]
Works fine for me with downloading auto generated English subtitles. Are you sure you are on v0.1.4? Please provide full docker error logs.

**Comment by Jay4242** [comment]
It says TubeArchivist v0.1.4 in the webUI.
This is what I see when I run a download with those videos in the queue, https://gist.github.com/Jay4242/977c6a2376b73dbf399e33c807341aec

**Comment by Jay4242** [comment]
ok, I'm on v0.1.5 now and it seems to download those fine.
