### ISSUE TITLE
Adding controls for playbackRate

### ISSUE THREAD

**Issue by iarp** [tubearchivist/tubearchivist#205]
I'd like to ask if theres any issues adding playbackRate controls (and default setting) for the speed of videos.

The video element supports the following

    document.querySelector('#video-item').playbackRate = 1.25;

I'm not sure I've seen it built into the player like youtube does otherwise having buttons somewhere to control this. Also a default setting would be great.

Where would the controls best be placed though. That i'm unsure of.

**Comment by bbilly1** [comment]
So far we are only using html native video controls. I think adding additional player controls will require implementing all controls. These native video players are very different from browser to browser and placing a button somewhere on the video will work on some platforms but not on others as it will overlay other controls. 

Or do you know of any way how playback speed could be added to the existing controls without having to reimplement everything?

**Comment by iarp** [comment]
I see what you mean. I just loaded Brave and its player is very different than firefoxs'. I'm not a UI person so I'm not really sure what would work best.

**Comment by ainsey11** [comment]
I had a look into this one and it would seem that both ffox and chrome have support for adjusting playback speed built in to their video players,

Here's firefox:
![image](https://user-images.githubusercontent.com/6608275/163502180-15cde6c3-d4a0-428f-8194-73fecb080d39.png)

And here's chrome:
![image](https://user-images.githubusercontent.com/6608275/163502213-6d1ed7c6-15f7-4fab-9498-9431dd97da07.png)

Though it't not as visible to users as well as the YouTube player itself, The only way I think we could do it is by implementing buttons or a dropdown undernearth the video player, which then trigger a js function to set the playbackRate property as exampled by @iarp 

```function adjustPlaybackSpeed(speed){
    document.querySelector(''video).playbackRate = speed
}
```
then called with button like
```
<button onclick="adjustPlaybackSpeed(1.25)">1.25x</button?
```
The downside of course, is it's more items in the UI, though could be combated by making it a config setting to enable / disable the UI elements

Just my 10 pence!

**Comment by bbilly1** [comment]
I think in any case, this will have to way until we got the new frontend up and working. Then we can decide if it's worth it to re-implement all the player controls. But I think that's quite far down the road from now.

**Comment by bbilly1** [comment]
Closing this for now. We'll see if we revisit that topic if we end up building our own player in the future.
