### ISSUE TITLE
Update Regex Syntax Check For Settings

### ISSUE THREAD

**Issue by birdy0101** [tubearchivist/tubearchivist#209]
Some humans don't know what they are doing so best to make sure we baby proof critical variables that can brick the app from their grubby hands. It's for their own good!

Final Error Output:
tubearchivist      | ValueError: Couldn't import 'home.tasks': Invalid end range: 24 > 23.

Temporary Solution:
Use the following command to reset settings to factory default: 
docker exec -it archivist-redis redis-cli JSON.DEL ta:config
*important to do so while the image is running, preferably before it blows up

Reason:
If someone doesn't understand how Cron Timing Format work they may enter an invalid input that will evade current checks which is invalid. For example, for the error above an input of "0 24 *" would be saved and since "0 24 *" is an invalid time, well, it goes boom on load.

**Comment by bbilly1** [comment]
nice, thanks for reaching out. looks like this needs some better validation there.

**Comment by bbilly1** [comment]
Thanks for reaching out. v0.1.4 has now a better validator, hopefully covering all invalid schedules.
