### ISSUE TITLE
Can't download video (urlopen error [Errno -3])

### ISSUE THREAD

**Issue by V5RM** [tubearchivist/tubearchivist#214]
After reinstalling container with updated es I can't download anything anymore. Whenever I give it a new url to download or have it rescan my library to regenerate thumbnails or anything related to youtube it gives me 
` [2022-04-09 03:57:39,431: WARNING/ForkPoolWorker-2] WARNING: [youtube:tab] <urlopen error [Errno -3] Temporary failure in name resolution>. Retrying ...`
until eventually I get 
`[2022-04-09 03:58:39,490: WARNING/ForkPoolWorker-2] ERROR: [youtube:tab] UCYO_jab_esuFRV4b17AJtAw: Unable to download API page: <urlopen error [Errno -3] Temporary failure in name resolution> (caused by URLError(gaierror(-3, 'Temporary failure in name resolution')))`
And I can't download any video or fetch any metadata from youtube. 

The container is installed with the docker compose file provided. 

I don't think the issue with es v7.17 though since the logs there didn't give me any errors.

**Comment by bbilly1** [comment]
I think you have networking issues, this doesn't look like it's related with Tube Archivist. Could also be that you are getting blocked by YouTube.
