### ISSUE TITLE
Feature Request: Channel Folders and Tags

### ISSUE THREAD

**Issue by Marthisdil** [tubearchivist/tubearchivist#215]
Would be a great feature to be able to create folders for channels to be able to group like-channels into sections to be easier to find when you have a large number of channels.

Also, being able to put tags on each channel with keywords for searching would also be nice.

**Comment by bbilly1** [comment]
For the media files and folders, there is currently no flexibility, its in the [known limitations](https://github.com/bbilly1/tubearchivist#known-limitations).

For the custom notes and tags for channels and playlists, we already have that on the roadmap:
```Custom searchable notes to videos, channels, playlists```

Do you want to work on that?
