### ISSUE TITLE
Feature Request: Playback Shuffles

### ISSUE THREAD

**Issue by HStep20** [tubearchivist/tubearchivist#220]
Since the app is meant as a 'replacement' for media servers, It would be nice if it had some shuffle options available in it. For example there could be:
- a video shuffle, that plays any random videos. 
- A playlist shuffle, that shuffles videos in a playlist
- Channel Shuffle 

Also echoing Autoplay in relation to this request, which I know is on the roadmap.

**Comment by bbilly1** [comment]
So just to clarify, we don't want to replace any media servers here. The goal is to be its own media server.

For playback control, we already have user created playlists on the roadmap, I have updated the wording there to include that, as that is not really a new feature but an extension. 

So we just need you to start working on that! :-)
