### ISSUE TITLE
Support for nebula possible/legal?

### ISSUE THREAD

**Issue by Extarys** [tubearchivist/tubearchivist#229]
I would like to pre-download nebula subscriptions. I tried setting a `--cooloe` parameter but it's clear TubeArchivist is only meant to deal with YT stuff :)

Would it be legally dangerous to support Nebula? Yt-dlp already supports it from what I've read.

**Comment by bbilly1** [comment]
Your question has an answer in the FAQ: https://github.com/tubearchivist/tubearchivist/wiki/FAQ
There are currently no plans to extend this beyond YouTube.

**Comment by mcinj** [comment]
No work done yet, but would a PR toward this effort be considered?

**Comment by bbilly1** [comment]
Docs are linked at the top of the repo: https://docs.tubearchivist.com/, FAQ is there with the scope of this project. Also see here: https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#contributions-beyond-the-scope.

Short answer: No, PR extending the scope won't be considered.
