### ISSUE TITLE
[Feature Request] Enabling an import of config/settings.py overrides

### ISSUE THREAD

**Issue by iarp** [tubearchivist/tubearchivist#232]
There are various options that django supports that I would like to enable and configure. One such option is [REMOTE_USER authentication](https://docs.djangoproject.com/en/dev/howto/auth-remote-user/). As it stands without forking the repo I don't see much of a way of adding my own settings I want.

One method I've seen used is to try/except [importing a local_settings file](https://github.com/pennersr/django-allauth/blob/master/example/example/settings.py#L174) and that would allow me to make the necessary changes I want.

I do use docker currently and I was trying to think of ways of using mapped volumes to achieve this sort of customization. Perhaps something like

At the bottom of  `config/settings.py`:

```python
try:
    from config.overrides.settings import *
except ImportError:
    pass
```

Where the `config/overrides/` is a mapped volume where I can add my own `__init__.py` and whatever necessary files I want to achieve my settings.

**Comment by iarp** [comment]
I went into the docker container and edited the config/settings.py with the above code. I then mapped the overrides volume accordingly and it works.

**Comment by bbilly1** [comment]
I see the temptation of doing it like you suggested. 

This has a few major downsides: That's practically impossible to support and debug, arbitrary settings import like that will make your installation unique and might behave in unexpected ways and any future errors might or might not be related to any incompatible settings you have set. Also that is very likely to break things in your installation if the project for instance changes something in the authentication methods, from your example.

That being said, I absolutely see the usecase of REMOTE_USER authentication. Why don't you implement that for real, in the project as a supported and documented feature? Also any other feature you'd like to implement? Reach out on Discord and we can discuss!
