### ISSUE TITLE
ffmpeg postprocessing error

### ISSUE THREAD

**Issue by naamval** [tubearchivist/tubearchivist#234]
Running the latest version on Docker (arm64), I cannot add any new videos. Either via download or manual import, the logs keep showing this error:

`[2022-04-26 21:37:11,005: WARNING/ForkPoolWorker-4] ERROR: Postprocessing: ffmpeg: error while loading shared libraries: libavdevice.so.58: cannot open shared object file: No such file or directory`

In the cache/download folder, for each video I tried to download I see a few separate files (webp, webm, mp4) so I guess it's unable to merge them for some reason.

**Comment by bbilly1** [comment]
Thanks for reaching out. Looks like there is an issue with the ffmpeg installation. I've restructured the Dockerfile, that might have broken things in the arm64 build. So immediate solution would be to manually reinstall ffmpeg in the container:

```
apt update && apt install ffmpeg -y
```

Then I'll have to check the build again. Please reach out on Discord, I could use your help with testing.

**Comment by naamval** [comment]
That works, thanks! I'll join the discord.

**Comment by bbilly1** [comment]
Thanks for your help. If you can, please follow the discord messages, I'll reach out when making any build changes so you can test them for arm64 first.
