### ISSUE TITLE
Re-Downloading Videos

### ISSUE THREAD

**Issue by Jay4242** [tubearchivist/tubearchivist#244]
Hello, thanks for TA.  I just started using it yesterday.

I noticed that after an initial 'Rescan subscriptions' and 'Start Download' that my TA is re-downloading some of the videos for a second time.
For instance, it's grabbing a video now, but if I search something related to the video it's already indexed and ready to view.
I didn't see an issue about this.  In a different issue, it's even mentioned that it shouldn't do this. ( https://github.com/tubearchivist/tubearchivist/issues/173 )
Not sure if there's anything useful in the logs that I can pass forward.  Or if I have something configured wrong?
I'm on v0.1.4.

I can stop it, of course, just seemed odd that it was doing a second round.

**Comment by bbilly1** [comment]
This indeed shouldn't happen. When adding a video to the queue, there is a check looking what's already queued and what's already index, and it shouldn't add it in that case. But that is video ID based, is it possible the same video got uploaded multiple times but got different video IDs?

Otherwise, we'll need steps to reproduce, which videos are affected? Or only for certain channel?

**Comment by Jay4242** [comment]
It was a range of channels.  I was grabbing the last 7 videos of something around 55 channels and it reached the end of those groups of 7, then instead of going to videos I had added to the queue since then (complete channel mirrors) it went back to those 55 channels with the 7 videos.
I don't think there was anything odd about the channels.

**Comment by Jay4242** [comment]
When it got to the end of my long download queue it started looping again, [screenshot](https://bafybeieokxbp6iyrv3bgrmnembjipidelcufriyme33zwuaqekbg7n7dpe.ipfs.infura-ipfs.io/tubearchivist_Screenshot_2022-05-06_19-23-21.png) of it downloading a video and then when I search the video was already there.  
It had been past that point for a while, this was at the end of grabbing like 1,500 videos.

**Comment by bbilly1** [comment]
Ok, tried to reproduce that with these steps:
- set channel page size to: 7
- subscribe to: https://www.youtube.com/c/realscience, has total of 46 videos
- rescan subscriptions: adds 7 to download queue
- download 7 videos

Then
- add same channel to download queue with form
- this adds the missing 39 videos to the queue
- rescan subscriptions: doesn't do anything, all videos are now downloaded or queued

Then
- download 39 videos in queue
- there are now 46 videos downloaded, queue is empty

Then
- rescan subscriptions, nothing happens, as all is downloaded
- add to download: https://www.youtube.com/c/realscience, nothing happens, as all is downloaded
- add to download: https://www.youtube.com/watch?v=R1HAEGyk4Co, last video of channel, nothing happens, as this video is already downloaded

What am I doing differently to you? Or provide your own steps to reproduce.

**Comment by bbilly1** [comment]
Sorry, couldn't reproduce. Closing due to lack of response.
