### ISSUE TITLE
TubeArchivist failing to add new subscribed playlist videos to download queue

### ISSUE THREAD

**Issue by MachineGalaxy** [tubearchivist/tubearchivist#255]
Environment: TubeArchivist v0.1.5, TubeArchivist-ES v7.17.3, TubeArchivist-RedisJSON v2.0.9 

Steps to reproduce: 1. Login to TubeArchivist 2. Go to Playlists page 3. Add a new playlist 4. Confirm playlist is subscribed 5. Go to downloads page 6. Run rescan subscriptions 

Expected result: New playlist videos are added to the download queue 
Actual result: No new playlist videos are added to the download queue

**Comment by bbilly1** [comment]
Thank you for opening this here and helping to look into this on Discord.

**Comment by bbilly1** [comment]
Turns out this was a duplicate of #171 all along. needs a option to reverse playlist order scan.
