### ISSUE TITLE
API: TaskAPIView does not include a GET to request active tasks

### ISSUE THREAD

**Issue by lamusmaser** [tubearchivist/tubearchivist#257]
TaskAPIView only includes the POST request to run a new task, but does not have a method to request if there is an ongoing task, and the POST response adds to the the requested task to the queue of tasks, if able.

Request:
Add a GET call to TaskAPIView that will return either the active task (optional: current stage ongoing task is at) or a POST call that requests if that type of task is currently ongoing.

**Comment by lamusmaser** [comment]
I can look into making this into a PR if I get some time, but wanted to make sure the request was made here in case someone else is able to get to it before I can.

**Comment by bbilly1** [comment]
So far, you can see your running tasks in `/progress/`, that's also how the notifications are built. But yes, for a rest full approach, this should be done in `/api/task/`. Then a GET request would return a list of messages? Associated with a task or a interaction from the frontend? I wanted to avoid making dedicated endpoints for each task, e.g. `/api/task/download_pending/` etc to not have this extend endlessly, but not sure if that is the right approach. 

So I'd be very happy if you could look into this.

**Comment by lamusmaser** [comment]
I think having the one task response (since only one task can be running at a time) should be fine. The current method of making a request to `/progress` is not as compatible with the current REST API requests, since you have to login via the `/login/` and pickup the CSRF token from there to get it to work properly.

**Comment by lamusmaser** [comment]
Will be closed with next version; PR accepted and merged successfully.
