### ISSUE TITLE
Unable to subscribe to private playlist

### ISSUE THREAD

**Issue by Filippilny** [tubearchivist/tubearchivist#266]
Hi, 

I connected the TA instance with the chrome addon successfully, as it shows the green check mark.

So I'd suppose it should now have the cookies to be able to download my private playlists, however uppon adding the playlist, either via the addon, or manually via webpage, it throws an error in docker logs:

tubearchivist      | [2022-07-03 16:58:22,679: INFO/MainProcess] Task home.tasks.subscribe_to[b64df23d-d749-4ccd-961b-801b346108e5] received
tubearchivist      | [2022-07-03 16:58:22,680: WARNING/ForkPoolWorker-8] processing: https://www.youtube.com/playlist?list=PLcw5rG1cPoadIRNh0Cnj1oe82Fbwm-Anl
tubearchivist      | [2022-07-03 16:58:22,680: WARNING/ForkPoolWorker-8] ParseResult(scheme='https', netloc='www.youtube.com', path='/playlist', params='', query='list=PLcw5rG1cPoadIRNh0Cnj1oe82Fbwm-Anl', fragment='')
tubearchivist      | [2022-07-03 16:58:22,699: WARNING/ForkPoolWorker-8] PLcw5rG1cPoadIRNh0Cnj1oe82Fbwm-Anl: get metadata from es
tubearchivist      | [2022-07-03 16:58:22,703: WARNING/ForkPoolWorker-8] {"_index":"ta_playlist","_type":"_doc","_id":"PLcw5rG1cPoadIRNh0Cnj1oe82Fbwm-Anl","found":false}
tubearchivist      | [2022-07-03 16:58:22,703: WARNING/ForkPoolWorker-8] PLcw5rG1cPoadIRNh0Cnj1oe82Fbwm-Anl: get metadata from youtube
tubearchivist      | [2022-07-03 16:58:22,941: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] YouTube said: The playlist does not exist.
tubearchivist      | [2022-07-03 16:58:22,944: WARNING/ForkPoolWorker-8] ERROR: [youtube:tab] PLcw5rG1cPoadIRNh0Cnj1oe82Fbwm-Anl: YouTube said: The playlist does not exist.
tubearchivist      | [2022-07-03 16:58:22,944: WARNING/ForkPoolWorker-8] https://www.youtube.com/playlist?list=PLcw5rG1cPoadIRNh0Cnj1oe82Fbwm-Anl: failed to get info from youtube
tubearchivist      | [2022-07-03 16:58:22,945: ERROR/ForkPoolWorker-8] Task home.tasks.subscribe_to[b64df23d-d749-4ccd-961b-801b346108e5] raised unexpected: TypeError("'bool' object is not subscriptable")
tubearchivist      | Traceback (most recent call last):
tubearchivist      |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
tubearchivist      |     R = retval = fun(*args, **kwargs)
tubearchivist      |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
tubearchivist      |     return self.run(*args, **kwargs)
tubearchivist      |   File "/app/home/tasks.py", line 232, in subscribe_to
tubearchivist      |     new_thumbs = PlaylistSubscription().process_url_str([item])
tubearchivist      |   File "/app/home/src/download/subscriptions.py", line 142, in process_url_str
tubearchivist      |     playlist_h.build_json()
tubearchivist      |   File "/app/home/src/index/playlist.py", line 41, in build_json
tubearchivist      |     self.process_youtube_meta()
tubearchivist      |   File "/app/home/src/index/playlist.py", line 52, in process_youtube_meta
tubearchivist      |     "playlist_name": self.youtube_meta["title"],
tubearchivist      | TypeError: 'bool' object is not subscriptable

**Comment by bbilly1** [comment]
Can you validate the cookie from the settings page? I've just pushed updates for both Tube Archivist and Tube Archivist Companion, did you already get them?

**Comment by Filippilny** [comment]
That might be it... the addon is still on .2
Not sure how long should validating the cookie take, but it's been several minutes, and it still says "processing"
tubearchivist      | validating cookie -- in logs, nothing more then

I'll give it a few minutes more, then I'll probably update the addon manually and try again

**Comment by bbilly1** [comment]
Firefox is already live, Chrome usually takes 2-3 days for validations to pass. you can also activate debug with the env var `DJANGO_DEBUG=True` to get more info. 

Probably needs some more error handling there too...

**Comment by Filippilny** [comment]
Soo, validating the cookie never finished, probably cause the cookie wasn't there? 
But, after manually updating the extension to .3, cookie synced immediately, validating immediately said it was ok, and private playlists can now be added.

So the issue is most likely oslved with the .3 extension updated :)

**Comment by bbilly1** [comment]
yes, and some better error handling and timeouts. let's keep this open so we can look I to it a bit further. do you want to take a look at it?

**Comment by Filippilny** [comment]
Sure thing, if you need any more testing from me, let me know :) PS: just joined the dc server, so you can lmk there

**Comment by bbilly1** [comment]
Forgot to tag the commits here, but in v0.2.0 there are a bunch of additional checks and verification to hopefully avoid your situation. 

I was able to reproduce the errors, I think... Thank you for the feedback!
