### ISSUE TITLE
Subtitles in the player?

### ISSUE THREAD

**Issue by runkaiz** [tubearchivist/tubearchivist#267]
I am not entirely sure if it is implemented or just that my configuration is wrong, so in the TubeArchivist player I don't see an option to turn on subtitles. In iOS or iPadOS browsers there is a subtitle selection but no video loads on those platforms for some reason. I have it configured to download subtitles and I don't see a lot of mentions of it in the roadmap or in issues. So is there subtitles?

**Comment by bbilly1** [comment]
Did you see the subtitles section in the wiki here: https://github.com/tubearchivist/tubearchivist/wiki/Settings#subtitles, based on your configuration this will create vtt files that your browser's media player should be able to read. 

For iOS compatible codecs, there is an example in the getting started section https://github.com/tubearchivist/tubearchivist#getting-started as well as on your settings page.

**Comment by runkaiz** [comment]
Oh gosh I totally missed those, the missing subtitles might actually be because I opted for user submitted only and there wasn't any. As for the videos, is there a good way to transcode existing videos in bulk to an iOS compatible format? Thanks

**Comment by bbilly1** [comment]
there are various converters, depending on your OS. ffmpeg would be my preferred choice. but in any case look for AVC video codecs. as long as you don't change the filename Tube Archivist should be able to pick up the converted files without issue.

**Comment by runkaiz** [comment]
It does seem like Safari doesn't support h.265, but I also found this thread which is interesting. A possible solution perhaps? https://www.reddit.com/r/ShinobiCCTV/comments/hh4ueo/howto_get_h265_playback_working_on_safari/

**Comment by runkaiz** [comment]
This is more tricky that I had imagined, the quality of the videos downloaded through limiting codec to h.264 or avc1 is... not very good. A lot of compression artifacts and lower framerates. The subtitles are working correctly for me now on the other hand so that is resolved. Thanks for the assistance!
