### ISSUE TITLE
Video description concealed by default?

### ISSUE THREAD

**Issue by p0358** [tubearchivist/tubearchivist#269]
On the video page I've noticed that the video description is concealed by default, and you need to press the "Show" button in order to show it every time. Why is that? I know it's consistent with what YouTube does, however I'm not sure if that's a good UX decision.

If there aren't any arguments towards doing that, I'd propose to remove the Show/Hide feature and just show the description revealed under all videos. If this is an actually desired feature by others, then I'd propose adding a setting to change the default behavior between shown/hidden.

**Comment by bbilly1** [comment]
There was a short discussion some time ago about that: #81. 

Basically the description can be huge, taking up multiple screen heights, potentially full of sponsored links right at the top there... And a big description will push the playlist navigation down the screen. Additionally to the familiarity to how YT does that, I landed on collapsed by default but it's just a click away if you want to open it...

Or maybe you have an other consideration?

**Comment by p0358** [comment]
Ah, I didn't know the playlist controls are displayed below since I didn't yet download any. In such case, I think the best solution would be to just show the first few lines with a button to reveal the whole thing, similar to what YouTube does (I think they show only 2 lines, which might be a bit too little, something like 5 lines could be more comfortable). That'd still allow you to gaze at the description easily and decide if it's worth expanding it to read the whole thing (if it didn't fit within what's revealed by default). Also if there's no playlist or anything else below, it could default to a different setting, for example showing many more lines by default (10? 20?) or even just the whole thing.

To visualize, taking the 5 lines idea into account, a description like this would always be displayed in whole, not taking much more space than the concealed box itself would (in this case it's 4 lines):
![obraz](https://user-images.githubusercontent.com/5182588/178978899-af0f29e4-bdbd-43f7-a84e-fc1b7b7ac935.png)

And when there's nothing like playlist controls below this, then it would make sense to display much more (I now think that something like 30 lines limit would still make sense in such case just in case the description is really obnoxiously long)
