### ISSUE TITLE
[cosmetic] Download status does not display non-Latin characters in video name

### ISSUE THREAD

**Issue by p0358** [tubearchivist/tubearchivist#271]
When downloading a video, I noticed a progress message is like this with missing letters:
![obraz](https://user-images.githubusercontent.com/5182588/179047636-4bef7a10-39c0-40df-89c0-bfc65f43f6fa.png)
while the video title is `Ważna wiadomość od Boxdela i Bagietki`

Which is honestly not a big deal, since the video title in the queue and in downloaded video metadata is displayed properly. But I figured I should still report this as when someone downloads a video with its title in some language that has no latin characters at all, they'd just see `Downloading: <nothing>`. Glancing at code, it seems the title to display comes from some filename, although the sanitization process must then be different from what's used for the resulting filename, as the video ended up saved as `20220714_yJ_OO8pv7co_Wazna wiadomosc od Boxdela i Bagietki.mp4`, where the non-latin characters were at least replaced with their latin equivalents.

**Comment by bbilly1** [comment]
That comes from the `restrictfilenames` options for yt-dlp to saveguard against writing files with illegal characters for any of the countless filesystems and OSs out there. The progress hook is implemented here: 
https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/src/download/yt_dlp_handler.py#L242-L264

Yt-dlp's implementation passes only the filename and not the title to the hook, so currently there is no way to access that:
https://github.com/yt-dlp/yt-dlp/blob/a7dc6a89f66c9bf3c8cff5ef7c8e775d57a5b917/yt_dlp/YoutubeDL.py#L339-L360

Maybe that would be a good issue to raise with the yt-dlp team? I'll do some more research first to see if there is another way to handle that.

Alternatively, if there is no characters left after the `restrictfilenames` sanitation, we could fallback to the video id, to at least show *something* there.

**Comment by p0358** [comment]
Just to visualize, downloading a video with whole Korean title:
![obraz](https://user-images.githubusercontent.com/5182588/179380372-962e1def-e06a-4366-b743-96116395b087.png)

**Comment by bbilly1** [comment]
Hmm, looks like the `info_dict` has been added to the progress hook for some time already: https://github.com/yt-dlp/yt-dlp/blob/master/Changelog.md#20210724

So that makes things drastically easier. We can write the cache download file before moving it to the archive simply as `%(id)s.mp4` while still having the full title in the progress message from `info_dict` without having to worry about sanitizing the filename during the download process, only when moving it to the archive.

Shows it's worth revisiting previous assumptions from time to time. :-)

**Comment by bbilly1** [comment]
Thanks for your input. That is now published in v0.2.0.
