### ISSUE TITLE
Backup Job Conflict

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#278]
Need protections to ensure both automatic and manual backups aren't run concurrently.

If currently running a manual backup and the automatic backup job is initiated, it runs two separate workers, both writing to the same json, duplicating the size of whichever job started first and causes the second to be anemic and missing data.

**Comment by bbilly1** [comment]
Excellent point. That doesn't have the same locking mechanism as the other tasks.

**Comment by bbilly1** [comment]
Backup tasks have now a lock in v0.2.1, so this shouldn't happen again. Thanks for reporting.
