### ISSUE TITLE
Keep getting name resolution failure when downloading videos

### ISSUE THREAD

**Issue by danmed** [tubearchivist/tubearchivist#280]
When downloading the queue, every few videos (some times 1 sometimes 20) i get the below error and have to tell it to start downloading again..

tubearchivist    | [2022-07-24 16:37:00,659: INFO/MainProcess] Task download_pending[00463533-a742-43a6-897e-df9b18cf4aab] received
tubearchivist    | [2022-07-24 16:39:33,281: ERROR/ForkPoolWorker-4] Task download_pending[00463533-a742-43a6-897e-df9b18cf4aab] raised unexpected: ConnectionError('Error -3 connecting to archivist-redis:6379. Temporary failure in name resolution.')
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
tubearchivist    |     sock = self.retry.call_with_retry(
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
tubearchivist    |     return do()
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
tubearchivist    |     lambda: self._connect(), lambda error: self.disconnect(error)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 645, in _connect
tubearchivist    |     for res in socket.getaddrinfo(
tubearchivist    |   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
tubearchivist    |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
tubearchivist    | socket.gaierror: [Errno -3] Temporary failure in name resolution
tubearchivist    | 
tubearchivist    | During handling of the above exception, another exception occurred:
tubearchivist    | 
tubearchivist    | Traceback (most recent call last):
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
tubearchivist    |     R = retval = fun(*args, **kwargs)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
tubearchivist    |     return self.run(*args, **kwargs)
tubearchivist    |   File "/app/home/tasks.py", line 89, in download_pending
tubearchivist    |     downloader.run_queue()
tubearchivist    |   File "/app/home/src/download/yt_dlp_handler.py", line 174, in run_queue
tubearchivist    |     success = self._dl_single_vid(youtube_id)
tubearchivist    |   File "/app/home/src/download/yt_dlp_handler.py", line 360, in _dl_single_vid
tubearchivist    |     success = YtWrap(obs, self.config).download(youtube_id)
tubearchivist    |   File "/app/home/src/download/yt_dlp_base.py", line 48, in download
tubearchivist    |     ydl.download([url])
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3281, in download
tubearchivist    |     self.__download_wrapper(self.extract_info)(
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3257, in wrapper
tubearchivist    |     res = func(*args, **kwargs)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1422, in extract_info
tubearchivist    |     return self.__extract_info(url, self.get_info_extractor(ie_key), download, extra_info, process)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1431, in wrapper
tubearchivist    |     return func(self, *args, **kwargs)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1521, in __extract_info
tubearchivist    |     return self.process_ie_result(ie_result, download, extra_info)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1578, in process_ie_result
tubearchivist    |     ie_result = self.process_video_result(ie_result, download=download)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2661, in process_video_result
tubearchivist    |     self.process_info(new_info)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3142, in process_info
tubearchivist    |     partial_success, real_download = self.dl(fname, new_info)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2860, in dl
tubearchivist    |     return fd.download(name, new_info, subtitle)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 444, in download
tubearchivist    |     ret = self.real_download(filename, info_dict)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 376, in real_download
tubearchivist    |     return download()
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 311, in download
tubearchivist    |     self._hook_progress({
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 459, in _hook_progress
tubearchivist    |     ph(status)
tubearchivist    |   File "/app/home/src/download/yt_dlp_handler.py", line 261, in _progress_hook
tubearchivist    |     RedisArchivist().set_message(self.MSG, mess_dict, expire=True)
tubearchivist    |   File "/app/home/src/ta/ta_redis.py", line 39, in set_message
tubearchivist    |     self.conn.execute_command(
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
tubearchivist    |     conn = self.connection or pool.get_connection(command_name, **options)
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
tubearchivist    |     connection.connect()
tubearchivist    |   File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
tubearchivist    |     raise ConnectionError(self._error_message(e))
tubearchivist    | redis.exceptions.ConnectionError: Error -3 connecting to archivist-redis:6379. Temporary failure in name resolution.
archivist-redis  | 1:M 24 Jul 2022 20:39:39.019 * 100 changes in 300 seconds. Saving...
archivist-redis  | 1:M 24 Jul 2022 20:39:39.020 * Background saving started by pid 22
archivist-redis  | 22:C 24 Jul 2022 20:39:39.039 * DB saved on disk
archivist-redis  | 22:C 24 Jul 2022 20:39:39.040 * RDB: 0 MB of memory used by copy-on-write
archivist-redis  | 1:M 24 Jul 2022 20:39:39.121 * Background saving terminated with success

**Comment by pairofcrocs** [comment]
#72

**Comment by bbilly1** [comment]
As far as I can tell, this looks like a internal networking issue: 
> redis.exceptions.ConnectionError: Error -3 connecting to archivist-redis:6379. Temporary failure in name resolution.

Meaning the *Tube Archivist* container can't reach the *Redis* container. Could be that your system is overloaded? Some other container interfering with each others? Sometimes it helps, to use a dedicated docker network to isolate things.

**Comment by danmed** [comment]
I'm actually running tubearchivist in it's own docker environment with
nothing else on it at the moment..

2GB and 4 CPU

**Comment by bbilly1** [comment]
Maybe give it a little bit more memory? But I don't think that is the issue here. The error suggests, that this is a docker internal networking issue. That's close to impossible to debug without being able to reproduce it, as this is unique to your setup. 

I can see if we can implement some kind o retry logic there. But as you say, this happens frequently, that might not solve your issue.

**Comment by EsEnZeT** [comment]
@bbilly1 can we open that ticket? I'm getting same errors after TA container was running and downloading videos for some time.

`[2022-10-07 18:51:33,542: ERROR/ForkPoolWorker-8] Task download_pending[ab93bfb6-dad1-47cd-834b-4af39dc8af0a] raised unexpected: ConnectionError('Error -3 connecting to tubearchivist-redis:6379. Temporary failure in name resolution.')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/root/.local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 645, in _connect
    for res in socket.getaddrinfo(
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 89, in download_pending
    downloader.run_queue()
  File "/app/home/src/download/yt_dlp_handler.py", line 174, in run_queue
    success = self._dl_single_vid(youtube_id)
  File "/app/home/src/download/yt_dlp_handler.py", line 360, in _dl_single_vid
    success = YtWrap(obs, self.config).download(youtube_id)
  File "/app/home/src/download/yt_dlp_base.py", line 49, in download
    ydl.download([url])
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3293, in download
    self.__download_wrapper(self.extract_info)(
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3268, in wrapper
    res = func(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1448, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1459, in wrapper
    return func(self, *args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1556, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 1614, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2712, in process_video_result
    self.process_info(new_info)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 3153, in process_info
    partial_success, real_download = self.dl(fname, new_info)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/YoutubeDL.py", line 2895, in dl
    return fd.download(name, new_info, subtitle)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 443, in download
    ret = self.real_download(filename, info_dict)
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 372, in real_download
    return download()
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/http.py", line 309, in download
    self._hook_progress({
  File "/root/.local/lib/python3.10/site-packages/yt_dlp/downloader/common.py", line 458, in _hook_progress
    ph(status)
  File "/app/home/src/download/yt_dlp_handler.py", line 261, in _progress_hook
    RedisArchivist().set_message(self.MSG, mess_dict, expire=True)
  File "/app/home/src/ta/ta_redis.py", line 39, in set_message
    self.conn.execute_command(
  File "/root/.local/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()
  File "/root/.local/lib/python3.10/site-packages/redis/connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to tubearchivist-redis:6379. Temporary failure in name resolution.
`

**Comment by bbilly1** [comment]
I think the solution for that was to fix the gateway address in the container internal */etc/hosts* file, or just rebuild the container to fix it automatically. 

I guess this happens if the docker daemon changes it's networking addresses for some reason. So as far as I can tell, this not an application error but a host issue.

**Comment by hellofaduck** [comment]
Same problem here, archiver works about 5-10 minutes without problem, but after that it stop doing anything because exactly same error:"redis.exceptions.ConnectionError: Error -3 connecting to tubearchivist-redis:6379. Temporary failure in name resolution.". From archivist container i can ping redis server and can connect to 6479 port with telnet. After restarting redis container all works ok, but it so strange...i am trying to investigate problem more deeply

**Comment by bbilly1** [comment]
Also see #302, particularly https://github.com/tubearchivist/tubearchivist/issues/302#issuecomment-1207343266.

**Comment by hellofaduck** [comment]
Thanks for that link, i will try to dig in this direction!
