### ISSUE TITLE
Queue doesn't download the same queue order as shown on the download page

### ISSUE THREAD

**Issue by scumola** [tubearchivist/tubearchivist#285]
Image shows what's downloading, but that video is way down on the list of downloads according to the download page.  The order was correct, but has kind of forgotten about a video here and there and the active download has slowly moved down in the queue on the download page over time.

![image](https://user-images.githubusercontent.com/386016/181274426-791b3848-674d-4865-9ac5-6ef7395891a7.png)

**Comment by pairofcrocs** [comment]
The download page doesn't automatically refresh.

Is it possible that those first couple of videos are already downloaded?

**Comment by scumola** [comment]
Scraper has been running all morning.  Lots of page refreshes have been done.  Restarted the container.  Lots of videos have been downloaded.  Notice that the same green circle video is still at slot number one in the list of videos as before.

![image](https://user-images.githubusercontent.com/386016/181349240-a1b6786b-95a4-425d-b41f-e03585c51883.png)

**Comment by bbilly1** [comment]
Can't see why this would happen. Maybe you changed the TZ value in between? Is there any issue with the Asteroid Discovery video? Does it download when you click "Download now" for that video?

**Comment by scumola** [comment]
Cleaning out the tubearchivist_cache volume's "import" folder and restarting the stack (leaving all other volumes alone) fixed this issue.
