### ISSUE TITLE
400 errors and can't see the screen. Is there a solution?

### ISSUE THREAD

**Issue by nompangyi19** [tubearchivist/tubearchivist#291]
[pid: 40|app: 0|req: 3/3] 192.168.80.1 () {40 vars in 698 bytes} [Sun Jul 31 01:55:37 2022] GET /favicon.ico => generated 143 bytes in 48 msecs (HTTP/1.1 400) 5 headers in 171 bytes (1 switches on core 0)

Installing on the Synology Docker. I keep getting 400 errors and can't see the screen. Is there a solution?

**Comment by bbilly1** [comment]
Probably `TA_HOST` is not configured correctly?

**Comment by nompangyi19** [comment]
> Probably `TA_HOST` is not configured correctly

Yes, I finished setting the ta_host, but I keep getting 400 error

**Comment by nompangyi19** [comment]
> Probably `TA_HOST` is not configured correctly?

TA_HOST=synology.local

**Comment by bbilly1** [comment]
is that your hostname for your synology? check the Readme, TA_HOST needs to be wherever you are running tube archivist from. for example the IP address of your synology.

**Comment by nompangyi19** [comment]
> is that your hostname for your synology? check the Readme, TA_HOST needs to be wherever you are running tube archivist from. for example the IP address of your synology.

[2022-07-31 16:52:34,034: INFO/MainProcess] celery@tubearchivist ready.
[pid: 31|app: 0|req: 3/3] 172.17.0.1 () {42 vars in 792 bytes} [Sun Jul 31 16:52:56 2022] GET / => generated 143 bytes in 113 msecs (HTTP/1.1 400) 5 headers in 171 bytes (1 switches on core 0)
[pid: 31|app: 0|req: 4/4] 172.17.0.1 () {40 vars in 719 bytes} [Sun Jul 31 16:52:57 2022] GET /favicon.ico => generated 143 bytes in 114 msecs (HTTP/1.1 400) 5 headers in 171 bytes (1 switches on core 0)

It keeps coming out like this, and there are 400 errors.

Does ip address include protocol?(TA_HOST)

**Comment by bbilly1** [comment]
all your questions here have an answer jn the readme:

> Set the environment variable TA_HOST to match with the system running Tube Archivist. This can be a domain like example.com, a subdomain like ta.example.com or an IP address like 192.168.1.20, add without the protocol and without the port. You can add multiple hostnames separated with a space.

**Comment by bbilly1** [comment]
Please don't open any further issues here if you aren't prepared to do the bare minimum yourself.

**Comment by nompangyi19** [comment]
> Please don't open any further issues here if you aren't prepared to do the bare minimum yourself.

I'm sorry.

**Comment by nompangyi19** [comment]
> Please don't open any further issues here if you aren't prepared to do the bare minimum yourself.

I'm sorry, but it worked out thanks to you. Thank you. I'm a beginner, but I think it's a good project.
