### ISSUE TITLE
N/A when displaying video file size during downloading

### ISSUE THREAD

**Issue by runkaiz** [tubearchivist/tubearchivist#292]
![image](https://user-images.githubusercontent.com/34772239/182009343-2178d62a-1420-4fc4-a02b-3960f29965ac.png)

Currently, it only seems to be true for this video. I will follow up if I find any others.

**Comment by runkaiz** [comment]
![image](https://user-images.githubusercontent.com/34772239/182009452-44f209b6-e21a-497b-9b57-a0b67b46332f.png)

Alright this one as well, same channel.

**Comment by bbilly1** [comment]
This is just some error handling when yt-dlp can't determine the stream size. That's only during downloading, after downloading for indexing we can use ffprobe to get the exact values.

So this is working as intended.

**Comment by runkaiz** [comment]
Ah I see, I thought it was a parser problem, thanks for the heads up. I will close this now.
