### ISSUE TITLE
Proper way to update (with docker)

### ISSUE THREAD

**Issue by koopernick** [tubearchivist/tubearchivist#293]
Hello,

What's the proper way to update via docker ? (using the default setting for the redis container).

I did => docker-compose pull
and then => docker-compose up -d 
but I had this error

`ERROR: for tubearchivist  Cannot create container for service tubearchivist: Conflict. The container name "/tubearchivist" is already in use by container "dfd99a624a0d2cf11c689f5e5b6c2bb27644c57a7550c3f5f44c4fd644aaa4bb". You have to remove (or rename) that container to be able to reuse that name.`

I removed the 3 containers : 
tubearchivist
archivist-redis
archivist-es

and did => docker-compose up -d

But I had to restore the manual backup since all the settings / metadata was lost.
Btw, the backup didn't restore the settings, only the metadata.

This can't be the right way ^^ 

Thank you.

**Comment by bbilly1** [comment]
That is the correct way to update any docker project. Hard to say, what exactly happened in your case here, maybe when you deleted the containers, you also deleted the volumes? 

In any case, let's keep these issues here relevant to Tube Archivist only.
