### ISSUE TITLE
TubeArchivist can't start after backup

### ISSUE THREAD

**Issue by adminbyme** [tubearchivist/tubearchivist#294]
Hi,

I hope you have a good day.

I can't start TubeArchivist any more I red this in the log "./run.sh: line 16: TA_HOST: Missing required environment variable." This happened out of the blue after unraid back up dockers last nice. It was working fine before the backup.

Is there a way to fix it or I have to reinstall it again from the begging?

Thank you.

**Comment by zarevskaya** [comment]
Hi,

Add/Set TA_HOST to your hostname or IP in your main Docker of Tube Archivist.

Like this: TA_HOST=YOUR_IP

**Comment by pairofcrocs** [comment]
^^
![Screenshot_2022-07-23_091929](https://user-images.githubusercontent.com/34723037/182190196-fa1acc18-e593-4d6d-926b-b1ee03db8686.png)

**Comment by adminbyme** [comment]
It started but can't be reached.


---- log
ErrorWarningSystemArrayLogin


{
"name" : "a11323f6b671",
"cluster_name" : "docker-cluster",
"cluster_uuid" : "CcwSY0XTT1Kdyg_Koawn3Q",
"version" : {

"number" : "7.17.1",
"build_flavor" : "default",
"build_type" : "docker",
"build_hash" : "e5acb99f822233d62d6444ce45a4543dc1c8059a",
"build_date" : "2022-02-23T22:20:54.153567231Z",
"build_snapshot" : false,
"lucene_version" : "8.11.1",
"minimum_wire_compatibility_version" : "6.8.0",
"minimum_index_compatibility_version" : "6.0.0-beta1"
},
"tagline" : "You Know, for Search"
}
run startup checks
required elasticsearch version: 8.0

run startup checks
required elasticsearch version: 8.0

[33;1m[WARNING][0m This is not the first run! Skipping superuser creation.

To force it, remove /cache/initsu.lock
run startup checks
required elasticsearch version: 8.0

[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.20 (64bit) on [Mon Aug 1 19:38:27 2022] ***
compiled with version: 10.2.1 20210110 on 21 July 2022 13:15:52

os: Linux-5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021
nodename: 4def22c5a5da
machine: x86_64
clock source: unix
detected number of CPU cores: 8
current working directory: /app
writing pidfile to /tmp/project-master.pid
detected binary path: /root/.local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***

your processes number limit is 126653
your memory page size is 4096 bytes
detected max file descriptor number: 40960
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8080 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***

Python version: 3.10.5 (main, Jul 13 2022, 05:45:22) [GCC 10.2.1 20210110]

*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55d40c135e70
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***

your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 154000 bytes (150 KB) for 1 cores
*** Operational MODE: single process ***
celery beat v5.2.7 (dawn-chorus) is starting.
run startup checks
required elasticsearch version: 8.0

run startup checks
required elasticsearch version: 8.0

run startup checks
VACUUM: pidfile removed.
required elasticsearch version: 8.0

**Comment by adminbyme** [comment]
and it keep stopping.

**Comment by bbilly1** [comment]
> required elasticsearch version: 8.0  

Read the release notes with all breaking changes.
