### ISSUE TITLE
Reverse proxy returns bad request

### ISSUE THREAD

**Issue by djakhada** [tubearchivist/tubearchivist#295]
Hello,
I'm trying to set up a reverse proxy for my local tubearchivist server.
Accessing it locally via the forwarded port from docker (with the ip of the server) works fine. 
When I try to access it externally via a subdomain, set up over nginx proxy manager the request arrives at the container but I only get a 400 Bad request.
The logs only show the following:
`[pid: 38|app: 0|req: 77/77] 172.18.0.11 () {68 vars in 1209 bytes} [Tue Aug  2 20:25:38 2022] GET /favicon.ico => generated 143 bytes in 34 msecs (HTTP/1.1 400) 5 headers in 171 bytes (1 switches on core 0)
[pid: 38|app: 0|req: 76/76] 172.18.0.11 () {72 vars in 1314 bytes} [Tue Aug  2 20:25:38 2022] GET / => generated 143 bytes in 370 msecs (HTTP/1.1 400) 5 headers in 171 bytes (1 switches on core 0)`

Is there some setting I am missing for my nginx configs?
I also tried the nginx settings:
```
location /{
proxy_pass http://tubearchivist:8000;
proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

to no avail.

I'm also using cloudflare proxy tunnels to route my domain.

Any ideas?

**Comment by djakhada** [comment]
I rescind my issue. I forgot I had to add the hostname to the TA_Host env variable. My bad.

**Comment by ConnorEMacLean** [comment]
Hey @djakhada could you explain what you mean for add hostname to the TA_Host env variable. I've attempted to change my TA_Host name to subdomain.domain.com but still seem to have an issue. Thanks!
