### ISSUE TITLE
[REQUEST] A message to tell us if the downloaded video was deleted from the channel

### ISSUE THREAD

**Issue by SmartPhoneLover** [tubearchivist/tubearchivist#298]
Hello again, this is another feature request that I would like to ask to be added, if possible.
I was thinking on the situation that you already have downloaded a video from a given channel, but it was deleted from the channel for whatever reason. So, would be nice that TA could tell us what videos don't exist anymore on the source, so we can determine to keep or [delete them manually](https://github.com/tubearchivist/tubearchivist/issues/297).

An example of what I'm talking about could be...
- An icon, similar (or any more appropriate) to the one shown in red (or could have the same color as the other elements) below, and a small message telling us: 'This video has been deleted from source'.

![pic_2 copia](https://user-images.githubusercontent.com/42898749/183115649-159f1709-fff3-4607-9eec-f71448a6a868.jpg)

TA will have to collect this information on the next index task, and compare the information stored on the server with the one from YouTube. But this will add a small problem: we must configure the Rescan Subscriptions option with a number according to the videos that our channels could have. So, if we keep the recommended value (50) or smaller, TA won't be able to reach that video if it's located in the position 450/600.

Just an idea...

**Comment by PhuriousGeorge** [comment]
Other than an obvious icon, TA already does this if configured as such.  Reference [Refresh Metadata](https://github.com/tubearchivist/tubearchivist/wiki/Settings#refresh-metadata) and [Video](https://github.com/tubearchivist/tubearchivist/wiki/Search#video)

This is currently visible via the video page:
![image](https://user-images.githubusercontent.com/1485658/183238892-d8529f12-8798-4c59-907c-c565db3d06e3.png)

**Comment by SmartPhoneLover** [comment]
Ohh, didn't take attention to this part if the Wiki.
Thank you!
