### ISSUE TITLE
UX: Cannot add a playlist from a combined video + playlist URL

### ISSUE THREAD

**Issue by coderbot16** [tubearchivist/tubearchivist#299]
When copying a playlist URL from the playlists page on someone's channel, you actually get a video URL with the playlist as part of it (`https://www.youtube.com/watch?v=_lmIiJ1aAXY&list=PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-`). But, when you paste this URL into the "Subscribe to Playlists" box, TubeArchivist appears to get confused and does not import the playlist:

```
tubearchivist      | https://www.youtube.com/watch?v=RLMcDPZcTg8&list=PL7j0JO-w0xWn0H3jfOwgHXjen9lNvsEJc
tubearchivist      | [2022-08-05 23:24:40,899: INFO/MainProcess] Task home.tasks.subscribe_to[ee0a1f27-d8f9-461f-9030-0328f0352d3c] received
tubearchivist      | [2022-08-05 23:24:40,900: WARNING/ForkPoolWorker-4] processing: https://www.youtube.com/watch?v=RLMcDPZcTg8&list=PL7j0JO-w0xWn0H3jfOwgHXjen9lNvsEJc
tubearchivist      | [2022-08-05 23:24:40,900: WARNING/ForkPoolWorker-4] ParseResult(scheme='https', netloc='www.youtube.com', path='/watch', params='', query='v=RLMcDPZcTg8&list=PL7j0JO-w0xWn0H3jfOwgHXjen9lNvsEJc', fragment='')
tubearchivist      | [2022-08-05 23:24:42,453: WARNING/ForkPoolWorker-4] UCJTWU5K7kl9EE109HBeoldA: get metadata from es
tubearchivist      | [2022-08-05 23:24:42,671: INFO/ForkPoolWorker-4] Task home.tasks.subscribe_to[ee0a1f27-d8f9-461f-9030-0328f0352d3c] succeeded in 1.7714336740318686s: None
```

However, if I remove the `v=RLMcDPZcTg8&` fragment, it imports the playlist successfully:

```
tubearchivist      | https://www.youtube.com/watch?list=PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-
tubearchivist      | [2022-08-05 23:26:00,647: INFO/MainProcess] Task home.tasks.subscribe_to[98a1c513-bb10-4130-8af3-45b93474623c] received
tubearchivist      | [2022-08-05 23:26:00,648: WARNING/ForkPoolWorker-4] processing: https://www.youtube.com/watch?list=PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-
tubearchivist      | [2022-08-05 23:26:00,649: WARNING/ForkPoolWorker-4] ParseResult(scheme='https', netloc='www.youtube.com', path='/watch', params='', query='list=PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-', fragment='')
tubearchivist      | [2022-08-05 23:26:00,671: WARNING/ForkPoolWorker-4] PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-: get metadata from es
tubearchivist      | [2022-08-05 23:26:00,676: WARNING/ForkPoolWorker-4] {"_index":"ta_playlist","_id":"PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-","found":false}
tubearchivist      | [2022-08-05 23:26:00,677: WARNING/ForkPoolWorker-4] PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-: get metadata from youtube
tubearchivist      | [2022-08-05 23:26:01,650: WARNING/ForkPoolWorker-4] downloading 0 playlist artwork
archivist-es       | {"@timestamp":"2022-08-06T03:26:01.771Z", "log.level": "INFO", "message":"[ta_playlist/BffAFl4VSCeLLiU1FeZvTA] update_mapping [_doc]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[69187076aaff][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.metadata.MetadataMappingService","elasticsearch.cluster.uuid":"CHANeAUhRBad6jLCcDGSWQ","elasticsearch.node.id":"RDv7xLDsTx2dpIR2cvMZHg","elasticsearch.node.name":"69187076aaff","elasticsearch.cluster.name":"docker-cluster"}
tubearchivist      | [2022-08-05 23:26:02,089: WARNING/ForkPoolWorker-4] UCJTWU5K7kl9EE109HBeoldA: get metadata from es
tubearchivist      | [2022-08-05 23:26:02,097: WARNING/ForkPoolWorker-4] downloading 1 playlist artwork
tubearchivist      | [2022-08-05 23:26:02,233: INFO/ForkPoolWorker-4] Task home.tasks.subscribe_to[98a1c513-bb10-4130-8af3-45b93474623c] succeeded in 1.5848213830031455s: None
```

I'd expect this to work, since this is the default link format that you get from YouTube and otherwise it's necessary to manually edit the link.

Also, as an aside, thanks for creating this! I previously tried to hack together something with Jellyfin but it didn't work too well for YT, but this is exactly what I was looking for.

**Comment by bbilly1** [comment]
It depends what you copy, if you copy the link from *play all*, you'll copy the video url of the first video with the playlist navigation as parameters. But ultimately, that's a video link and not a playlist, so that would be your first example.

If you copy the link from *VIEW FULL PLAYLIST* you'll get the playlist link, from your example `https://www.youtube.com/playlist?list=PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-`. So Tube Archivist tries to imitate the same behavior, */watch* is a video and `/playlist` is a playlist. That's the same behavior throughout the whole application, for example here too: https://github.com/tubearchivist/tubearchivist/wiki/Downloads#add-to-download-queue.

So that is working as intended.

**Comment by coderbot16** [comment]
That makes sense, and the ambiguity is fair - it's possible that users are watching through a playlist and expect that copy pasting the video URL only downloads that video instead of a whole playlist. I think that the behavior could still be changed though, since there's no feedback from the application when entering such a combined watch+playlist URL into the Subscribe to Playlist input box that the URL wasn't accepted since it wasn't a playlist URL.

**Comment by bbilly1** [comment]
Yes, you are right, the error isn't handled there for some reason...

**Comment by bbilly1** [comment]
that's now properly validated in v0.4.1.
