### ISSUE TITLE
Only the first 50 videos of any playlist are added to the download queue

### ISSUE THREAD

**Issue by coderbot16** [tubearchivist/tubearchivist#300]
Only up to the first 50 videos of a playlist are added to the download queue:

![image](https://user-images.githubusercontent.com/22420959/183235224-c145c93c-b227-4d52-9d10-7958eff56907.png)

After downloading all of the videos that get added to the queue, we get stuck into this state, and refreshing subscriptions doesn't add any new videos to the queue:

![image](https://user-images.githubusercontent.com/22420959/183235252-4ff7d83c-fac1-4ce4-aed6-1fb558776ef2.png)

This seems like a potential pagination issue?

Playlist that reproduces the issue: `PL7j0JO-w0xWltFhrD8ksJrm8K6QYbMSf-`

**Comment by PhuriousGeorge** [comment]
I'm assuming you just added the playlist to subscribed playlists?  If so, this works as intended. Reference Settings Page "Current Page Size".  If you want to download the whole playlist, add the playlist URL to the "Add to download queue" on the downloads page.

**Comment by coderbot16** [comment]
I didn't realize either of those things, thanks for letting me know! Maybe this description could be updated to say that playlists & channels are valid as well, I didn't realize that you didn't have to subscribe to playlists to download them:

![image](https://user-images.githubusercontent.com/22420959/183238873-142f535f-a722-45cb-8811-bdc76f550f90.png)

**Comment by bbilly1** [comment]
Yes, you are right. This could be worded better to make it more obvious what you can enter there. Suggestions?

**Comment by coderbot16** [comment]
I don't have any super creative ones off the top of my head, but maybe this would work:

> **Add to download queue**
>
> Enter at least one video, channel, or playlist id/URL here...

**Comment by industrial64** [comment]
As requested; suggested re-word of section:

FROM:
`Subscriptions`
`Current page size: XXX`
`Recent videos for channels and playlist to check when running Rescan subscriptions, max recommended 50.`

TO:
`Subscription Limit`
`YouTube page size limit: XXX`
`The YouTube page size limits the Subscription search depth, this may need to be increased for first time Subscriptions to large Channels. (Default 50)`

Since I've found/felt after using it that 50 is merely a suggestion, and a very low one at that (when starting out)

**Comment by PhuriousGeorge** [comment]
Not a bad rewrite, just want to be certain I understand here, is it "page size" as in pagination, or... words escape me... more like video backlog depth?  If it's number of videos to search in upload history, "page" is probably the wrong termination for the common user.

**Comment by bbilly1** [comment]
Thanks for reaching out. Wording is now improved in v0.2.1.
