### ISSUE TITLE
truenas scale "error: unable to upgrade connection: container not found ("tubearchivist-custom-app")"

### ISSUE THREAD

**Issue by billxsand** [tubearchivist/tubearchivist#304]
Hey guys I am installing to Truenas Scale / kubernetes and i followed the instructions [here ](https://heavysetup.info/applications/tube-archivist/tube-installation/)down to the letter. I set up all 3 custom applications but only ta-redis successfully deploys.

![image](https://user-images.githubusercontent.com/36315936/184057334-589b6f89-e837-4033-b761-e2d90fbd47a8.png)

When i open the shell for the tubearchivist custom app, it says,
`error: unable to upgrade connection: container not found ("tubearchivist-custom-app")`

and in ta-elastic custom app,
`error: unable to upgrade connection: container not found ("ta-elastic-custom-app")`

Can anyone help? Perhaps it has something to do with [this part](https://heavysetup.info/applications/tube-archivist/tube-installation/#dns)? That seems to be what is happening here

![image](https://user-images.githubusercontent.com/36315936/184058732-3ae7ce76-616b-4feb-8d85-e58b5db94829.png)
![image](https://user-images.githubusercontent.com/36315936/184058750-c87def14-e402-4816-81c7-df609e856848.png)

as you can see they are both named correctly

**Comment by bbilly1** [comment]
@Heavybullets8 created the truenas guide. Definitely needs logs and any other relevant information. You can also reach out on Discord, sometimes that's easier than here in the GitHub issues.

**Comment by Heavybullets8** [comment]
My applications are running fine with that setup. But, if yours isn't I'm sure I can help. 

Can you either open a support ticket on the Tube archivist Discord and tag me, or just message me on discord? heavybullets#5535

I'll need to see all of your logs, and pictures of your setup.

**Comment by Heavybullets8** [comment]
Issue was resolved, and my documentation has been updated. 

See the issue, and solution here:
https://discord.com/channels/920056098122248193/1007346611451596911
