### ISSUE TITLE
[Bug]: Does marking a video as 'Watched' trigger the Auto Delete?

### ISSUE THREAD

**Issue by Jay4242** [tubearchivist/tubearchivist#309]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Linux, Docker-Compose

## Describe the bug
Is it just me, or does clicking the 'watched' box or clicking a channel's 'Mark as watched' button not trigger the Auto Delete for the videos?
Videos I actually watched seem to be gone, ones that I marked as watched seem to still be there after x days.
## Steps To Reproduce
Set a channel to auto-delete.  Download some videos.  Mark them as watched without actually watching.
## Expected behavior
The videos would be deleted after x days of being marked as watched.

### Relevant log output

```shell
Not sure what I'm looking for in the log.
```

### Anything else?

Only 2-3 channels are set to auto-delete via the channel about pages.

**Comment by bbilly1** [comment]
Can anybody using the auto delete functionality verify that?

**Comment by Jay4242** [comment]
Maybe something is wrong on my end then?
I'll try to attach screenshots of a channel that I download but have set to delete after 7 days.
There are definitely videos that have been sitting there for over a month now.

![TubeArchivist_Screenshot_2022-08-22_09-15-19](https://user-images.githubusercontent.com/96741732/185969815-a19933e7-be2e-48c6-a168-c15a1eaf9174.png)
![TubeArchivist_Screenshot_2022-08-22_09-16-21](https://user-images.githubusercontent.com/96741732/185969839-1f30f917-9abc-4fe5-9089-a5ac2161bd75.png)

My Rescan & Downloads are set every two hours.  My global setting for Deletion is set to False.

**Comment by birdwing** [comment]
Oh, I have my global deletion set to 1 day.
Perhaps it's a channel specific issue.

**Comment by Jay4242** [comment]
Well, it's been a week and I still have the same videos as https://github.com/tubearchivist/tubearchivist/issues/309#issuecomment-1222600206 screenshots.  So I can at least confirm it's not working on my machine.  If there was a way to manually scan for those to remove them that would be nice.

**Comment by bbilly1** [comment]
Sorry to let this lying around here. Did some testing, this functionality is working fine for me, for both, per channel auto delete, plus auto delete over all videos.

To debug this, you can you verify the timestamps, just to make sure there isn't an issue there? You can use the API, `/api/video/<video-id>/` from a video that should have been deleted, in the browser while logged in to Tube Archivist. Then verify that the channel overwrite is set correctly in the `channel` key, and within the `player` key verify that `watched` is set to `true` and the `watched_date` (seconds since epoch, [convert](https://www.epochconverter.com/)) is later than your selected days.

Then verify that the task runs, after your download queue finishes, and provide the logs for that.

**Comment by Jay4242** [comment]
Likewise, sorry for taking a while to look at this again.

channel_overwrites looks right.  watched is set to true.

I don't have a watched_date in the api page.  Could that be it?

How would I check the logs for that?

**Comment by Jay4242** [comment]
Ok, after letting some videos build up that I didn't want to watch, I checked one with /api/video/ before hitting the 'Mark as watched' button.

It did not add a watched_date to the /api/video/ information even though it set "watched": true.

Is this the line that would set that to watched through the channel page?  https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/src/frontend/watched.py#L70

Does that set the watched_date?

**Comment by bbilly1** [comment]
Ah, now I see it. The date doesn't get set for the channel "mark as watched" button, only for the video "marked as watched". Yeah, so the auto delete will never get triggered. Yeah, that's unfortunate. The code line you linked above is in deed where the boolean value `watched` gets set, but this should also set the date.

Huhh, OK, quick fix would be use the video level mark as watched, with the checkbox, then we'll need to fix that script there to also set the date correctly. 

Thanks for sticking with this and for pointing it out.

**Comment by Jay4242** [comment]
Great!  Yeah, I was simply incorrect in the initial issue including the checkbox with the problem, just my faulty memory, when checking the API that does work.

I noticed that un-clicking the box also added/updated a watched_date, should that maybe remove the watched_date in case someone is trying to prevent deletion by unclicking it?

Yeah, welcome, thanks for the great system.

**Comment by bbilly1** [comment]
this is now fixed in v0.2.3, thanks for helping with that.
