### ISSUE TITLE
[Bug]: LDAPS doesnt work with selfsigned cert.

### ISSUE THREAD

**Issue by lue30499** [tubearchivist/tubearchivist#313]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

linux

## Describe the bug
Using LDAPS doesn't work with I assume a selfsigned certificate.
I run IPA and with an internal domain that isn't a proper tld. Therefore I still run certificates but I do not care to validate them or have a CA on my network.

**Is there a way to not do certficate validation or is it that LDAPS isn't supported?**

Standard LDAP does work.

## Steps To Reproduce

This doesn't work:
TA_LDAP_SERVER_URI=ldaps://ipa-01.domain.internal:636
This does work:
TA_LDAP_SERVER_URI=ldap://ipa-01.domain.internal:389

## Expected behavior
when using LDAPS for logins to authenticate.

### Relevant log output

```shell
N/A
```

**Comment by bbilly1** [comment]
@DanielBatteryStapler: Can this be implemented? Like a disable cert validation?

**Comment by lue30499** [comment]
Like for example in Gitea, they have this:

![Screenshot from 2022-08-20 18-42-36](https://user-images.githubusercontent.com/63104612/185736809-8ef36f51-f477-4498-b0b6-1bc1adf6f369.png)

**Comment by bbilly1** [comment]
In any case, I don't think we can call this a bug, as it sounds like this is working as intended. :-)

**Comment by lue30499** [comment]
sure sure. rename if you wish.
