### ISSUE TITLE
[Bug]: /api/ping responds with status 403

### ISSUE THREAD

**Issue by insuusvenerati** [tubearchivist/tubearchivist#321]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Linux

## Describe the bug
When trying to get a 200 status from `/api/ping` for the sake of liveness or readiness probes in kubernetes, the api responds with 403 forbidden. This issue exists in v0.1.7 as well as v0.2.1. 

## Steps To Reproduce
A simple repro can be done by spinning up a local instance of TA with docker-compose and running `curl -I http://localhost:8000/api/ping`

## Expected behavior

Should get http status 200 from `/api/ping`

### Relevant log output

GET response:

```json
{
    "detail": "Authentication credentials were not provided."
}
```

App logs:
```
[pid: 35|app: 0|req: 1/1] 172.17.0.1 () {34 vars in 387 bytes} [Wed Aug 31 11:35:34 2022] GET /api/ping => generated 143 bytes in 88 msecs (HTTP/1.1 400) 5 headers in 171 bytes (1 switches on core 0)

```

**Comment by SmartPhoneLover** [comment]
It's working for me.

Maybe you didn't pass the "Authentication: Token <token_id>" header in the GET call.

or

You didn't include (/) at the end of the URL:
- No: http://host_ip:port/api/ping
- Yes: http://host_ip:port/api/ping/

**Comment by bbilly1** [comment]
So from our discussion on Discord, this is not a bug, but expected behavior. All except the login API endpoints are authenticated, and you'll have to pass the auth header.
