### ISSUE TITLE
[FEATURE] Viewing Profiles

### ISSUE THREAD

**Issue by Marthisdil** [tubearchivist/tubearchivist#322]
Nice feature would be to have viewing profiles on TA.  For example, to have one for Parents and another for Kids.  Parents can see all channels (as selected), but the Kids can only see a subset of channels...could be integrated into the user's system where each user account can have All-Channel access or Select-Channel (where an admin can set the channels that the Select-Channel user can see).

Useful where you have some kid specific channels and don't want the kids to see non-kid stuff, etc.

**Comment by bbilly1** [comment]
That's on the roadmap with the user roles.
