### ISSUE TITLE
[Feature Request]: Comment Archival and Reproduction

### ISSUE THREAD

**Issue by AROAH1337** [tubearchivist/tubearchivist#323]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations).

## Describe the solution you'd like
Capture and reproduction of YouTube comments as part of the archival process, complete with threads being maintained and user icons.

## Additional context
As many would likely agree, comments are a major part of YouTube. In my current archiving solution (aka a cron job that runs a very long yt-dlp command), I grab all the comments for a given video, since there is often important contextual information contained therein, and they're placed inside the video's info.json file. I'd like to suggest adding the option to parse and reproduce these comments. The user icon URLs are also grabbed as a part of this, so it would be nice to be able to include those.

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
That's already on the roadmap, waiting for you to implement it! :-)
