### ISSUE TITLE
[Bug]: HTTP 403 Error & CSRF failure on /process endpoint. Can't download anything or run any actions

### ISSUE THREAD

**Issue by pawelmalak** [tubearchivist/tubearchivist#324]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Unraid

### Your Bug Report

After adding video to the download queue and pressing `Start download` or `Download now` nothing is happening. Same thing when I want to clear queue from Actions section in settings.

Both POST requests are resulting with 403 Forbidden error:
```md
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
```

Other settings like `Application Configurations` with POST requests to `/settings` endpoint are resolved correctly with 200 status.

I'm **not** running it behind any reverse proxy, just normal Docker container with exposed port.

### Relevant log output

```shell
[pid: 26|app: 0|req: 9/9] 192.168.0.150 () {50 vars in 4040 bytes} [Thu Sep 15 23:54:40 2022] POST /process/ => generated 1019 bytes in 3 msecs (HTTP/1.1 403) 7 headers in 214 bytes (1 switches on core 0)
```

**Comment by pawelmalak** [comment]
### Additional details
Checked other browsers and it seems to be working in some of them:
- ❌Opera v90.0.4480.84
- ✔️Google Chrome v105.0.5195.125
- ✔️Firefox Developer Edition v105.0b9

**Comment by bbilly1** [comment]
Opera, that's a blast from the past. :-)

Downloaded a blank installation of the browser, everything works fine for me. `/process/` as well as regular API endpoints. So not sure what's going on, but probably some browser configurations? Maybe browser cache? Did you do the usual debugging, clearing cache, incognito window, full refresh of the page... ?

**Comment by pawelmalak** [comment]
Installed the same version of Opera on another PC and it's working there so something is wrong with my browser. Closing this issue
