### ISSUE TITLE
[Feature Request]: View what account is signed in by having a profile picture/icon

### ISSUE THREAD

**Issue by rdangdev** [tubearchivist/tubearchivist#326]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.
Not necessarily a marked issue, but an amazing quality of life improvement. I manage several accounts and there is not a single indicator anywhere(even in settings) that tells you what account you are logged into. 
## Describe the solution you'd like
The easiest implementation would be to just print the username in the left side of the bar(home, channels, playlist..). It is quite empty and seems to be the perfect place to put one. 

Another implementation would be a Profile Icon(maybe gravatar support in the future?) to be able to visually see logged in account easily. 
### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
You can see the user logged on the top right in in the admin interface at `/admin/` or accessible from the bottom of the settings page. 

I know, not ideal, this will need improvement once implementing the *user roles* on the roadmap, to make this a real multi user application.
