### ISSUE TITLE
[Feature Request]: Hide Channels from Home

### ISSUE THREAD

**Issue by TjohAGq6VQWLt7gKMo** [tubearchivist/tubearchivist#330]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

Hi All - 

I would like to have the ability to hide all videos (and future videos) for chosen channels from the home page.

There are a number of channels I archive that I don't watch regularly and having them on the home page makes it difficult to find the videos for channels I watch daily.

Thanks!

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
i can see how this could be usefull. but problem is going to be to find these hidden videos and channels again.

**Comment by TjohAGq6VQWLt7gKMo** [comment]
My thought was to keep the channel in the channel view page, however, include a toggle within the channel page settings that hides all of the videos from the channel from the home page.

Alternatively, maybe we can have an additional page where all unwatched videos for "featured" channels would be displayed?

**Comment by suckerfish** [comment]
I definitely support and endorse this feature. There are channels I want to archive but do not care about them on a day-to-day basis. So when I look at my Recent videos I wouldn't want them there.  Toggle hidden from recent while in the channels page. Untoggle to let them show up again. 

A tagging system for channels would accomplish the same thing with more flexibility. Tag some channels as 'games' or 'educational' or 'politics' or 'archiveonly' and then set your Recent videos to show all tags except 'archiveonly' and 'politics' or whatever. Though that could be more down the road.

**Comment by bbilly1** [comment]
I'm closing this as not planned for now. I don't see how this could be implemented intuitively. There is already a good amount of filtering and sorting available, browse through channels or playlists, and oc the search functionality.

efforts will be spent in extending and improving these existing functionalities instead.
