### ISSUE TITLE
[Feature Request]: Import Previously downloaded videos

### ISSUE THREAD

**Issue by CasaPas** [tubearchivist/tubearchivist#333]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.
I have already downloaded tonnes of videos for archive purposes using Youtube-dl, I would like to include them in TubeArchivist to avoid them downloading again.

Also it would be great to be able to import my existing Channels list (channels.txt) from Youtube-dl

## Describe the solution you'd like
The ability to import "archive.txt" made by YouTube-dl
The ability to import "channels.txt" made by YouTube-dl

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
that is already implemented, as you have checked the box I'm sure you have found it in the wiki: https://github.com/tubearchivist/tubearchivist/wiki/Settings#manual-media-files-import
