### ISSUE TITLE
[Installation]: Import of previously downloaded files

### ISSUE THREAD

**Issue by masterdot** [tubearchivist/tubearchivist#338]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [potential pitfalls](https://github.com/tubearchivist/tubearchivist#potential-pitfalls) section.

### Operating System

Unraid 

### Your installation or setup question

Hey there,
I wanted to ask if there is any way to import a collection of downloads.
The files are all named like this here. All .mp4 and best quality.
Would really save lot of bandwidth :) 

Random Acts of Kindness - Restoring Faith in Humanity 5-Video That Will Make Your Day Better.mp4
Random Acts of Kindness - Restoring Faith in Humanity 6-Video That Will Heal Your Soul.mp4
Random Acts of Kindness - Restoring Faith in Humanity 7-Video That You Will Not Forget.mp4
Random Acts of Kindness - Restoring Faith in Humanity 8-Video That Will Fill You With Hope.mp4
Random Acts of Kindness - Restoring Faith in Humanity 9-Video That Will Fill Make You Feel.mp4
Random Acts of Kindness - Restoring Faith in Humanity 10-Video That Will Bring you Happiness.mp4
Random Acts of Kindness - Restoring Faith in Humanity 11-Video That Will Bring Happiness To Anyone.mp4

### Relevant log output

```shell
none
```

**Comment by masterdot** [comment]
I did do everything I did find in the manual under https://github.com/tubearchivist/tubearchivist/wiki/Settings#manual-media-files-import

But even a new File, named with <date (e.g. 20221015)>_<youtube_id>_name-of-the-episode.mp4 placed in the cache/import/ directory is not added.

**Comment by PhuriousGeorge** [comment]
Your original example with file names containing no ID is going to be a large issue unless you have the accompanying json file with the ID in there. 

I had the same issue if I didn't have the accompanying metadata (json) file alongside my videos and I imported multiple thousands of files.  What I eventually did was create a script to extract the YouTubeID and put it in the missing json file.

Overall though, I had demonstrated that the manual import had issues pulling the YTID out previously and seems it might still have issues.  I absolutely stink at RegEx, but just for giggles, this is the AHK script I came up with:
```
list_files(Directory)
{
	files =
	Loop %Directory%\*.mp4
	{
		If inStr(A_LoopFileName, "[") {
			;MsgBox % A_WorkingDir
			files = %files%`n%A_LoopFileName%
			YTID := RegexReplace(A_LoopFileName,".*\[(.+?)\].*","$1")
			FileName := RegexReplace(A_LoopFileName,"^.+\\|\.[^.]+$")
			JSONTXT = {"id": "%YTID%"}
			FileAppend, %JSONTXT%, %Directory%\%FileName%.json
		}
	}
	return files
}
```

Regardless, would be nice to fix

**Comment by bbilly1** [comment]
> But even a new File, named with <date (e.g. 20221015)>_<youtube_id>_name-of-the-episode.mp4 placed in the cache/import/ directory is not added.

See the part in the wiki again about the required naming convention, if you don't have the json file, the video ID needs to be in square brackets at the end of the filename, that's the default of yt-dlp naming. 

I remember scripting something that uses the youtube API to search for videos from a channel based on filenames. But that failed more often than it worked... 

So realistically, I don't think we'll implement an additional import method as the two described in the wiki.

**Comment by masterdot** [comment]
Ahh... ID​ in brackets....​ I did try some things out, but not that :)
It works with importing, now I have to find something to rename my previously downloaded stuff.
I dont know what language the code snippet is and where to put it. I wolud prefer a small stand alone script for searching and renaming...
Thanks for your help! Hope I'll have a chance to import my tbs of downloads :) 

Am 17. Oktober 2022 12:08:41 MESZ schrieb Simon ***@***.***>:

**Comment by bbilly1** [comment]
The script above will take the video id from the square brackets in the filename and write it to a json file for importing. But if you don't have the video ID, there is not much you can do.
