### ISSUE TITLE
[Installation]: Native installation without Docker?

### ISSUE THREAD

**Issue by SpaceAgeHero** [tubearchivist/tubearchivist#339]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [potential pitfalls](https://github.com/tubearchivist/tubearchivist#potential-pitfalls) section.

### Operating System

Arch Linux aarch64

### Your installation or setup question

I'd like to use TubeArchivist on my Raspberry Pi 4 without Docker.
How can it be installed natively?

### Relevant log output

```shell
N/A
```

**Comment by bbilly1** [comment]
Your question is answered right there in the FAQ: https://github.com/tubearchivist/tubearchivist/wiki/FAQ, plus already asked, here #149 for example. In short, docker is the only supported installation method.
