### ISSUE TITLE
[Feature Request]: keyboard shortcuts in the player

### ISSUE THREAD

**Issue by bakkot** [tubearchivist/tubearchivist#341]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

I'd like to have at least some keyboard shortcuts available on the video player. The ones I use on Youtube all the time are:

- `>`/`<` to change video speed (maybe going up to 3x instead of 2x?)
- `c` to toggle captions
- left and right arrow to skip around in 5 second increments

Happy to implement these myself (assuming I can figure out the dev flow...) if you're amenable.

### Your help is needed!

- [X] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
Sounds good! Makes it familiar to regular YouTube. I have been using browser based shortcuts, Firefox for example: https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox, but yeah, that doesn't support all options, just like play/pause...

In any case, please look into this. There is some help with setting up your dev environment in the [Contributing.md](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md), also don't hesitate to reach out on Discord if you get stuck.

**Comment by bakkot** [comment]
Closing as fixed by https://github.com/tubearchivist/tubearchivist/pull/342.
