### ISSUE TITLE
[Bug]: Github Actions and `deploy.sh` can become out of sync and produce different results for local and online testing

### ISSUE THREAD

**Issue by lamusmaser** [tubearchivist/tubearchivist#346]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Not Applicable/Linux

## Describe the bug
As noted in https://github.com/tubearchivist/tubearchivist/pull/345#issuecomment-1289768021, there can be a dereference between `deploy.sh` and the Github Actions regarding tests (which means that local and PR testing can change).

This means that we need to update the Github Actions to call `deploy.sh` and reference the output for linting/testing results.

## Steps To Reproduce
Create a PR with a modified `deploy.sh`, which causes different results for testing locally.

## Expected behavior
Local and Actions testing should be maintained until either more sophisticated testing replaces them or a better alternative is developed to replace the calls in `deploy.sh`.

### Relevant log output

```shell
Reference the Actions Logs before https://github.com/tubearchivist/tubearchivist/pull/345#issuecomment-1289768021.
```

**Comment by bbilly1** [comment]
Yeah, sounds good. Just checked, last change on the linting rules was 7 months ago, so this hasn't changed very frequently. :-)

In any case, even better if we can do this once and once only and call deploy.sh from the workflow.

**Comment by lamusmaser** [comment]
Yeah, it should be fairly simple. I just want to make a couple of checks on the `deploy.sh` script beforehand, and then I'll get the PR made. Not sure if I'll have time this week, but I am planning to work on it before the weekend. Mostly wanted to make sure that we had this called out here so @bakkot's concerns were captured appropriately, and for an Issue to reference for the PR.

**Comment by bbilly1** [comment]
this is implemented and merged on master branch.
