### ISSUE TITLE
[Bug]: Offline import filename parser issue splitting the file extension

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#349]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Unraid

## Describe the bug
Manual Import fails when desired import contains a period within the file name (ref #311 for previous itteration)

## Steps To Reproduce
Current example of a failed import is a file with the name:
`CG_Figures - 20201113 - CGFigures_Community_Showcase_6_-_Conceptualized.tech [dDCL9N7j0YU].mp4`

Remove the period and importing works as expected

## Expected behavior
Suck in all the files! :)

### Relevant log output

```shell
ERROR/ForkPoolWorker-1] Task home.tasks.run_manual_import[83482b02-3340-4156-a480-c2fa082df3db] raised unexpected: ValueError()
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 153, in run_manual_import
    ImportFolderScanner().scan()
  File "/app/home/src/index/filesystem.py", line 189, in scan
    self.process_videos()
  File "/app/home/src/index/filesystem.py", line 268, in process_videos
    raise ValueError
ValueError
```

**Comment by bbilly1** [comment]
hmm, that worked fine for me. Not sure what is going on. That value error there is usually raised because the media file doesn't match the subtitle or thumbnail file, is that possible?

**Comment by PhuriousGeorge** [comment]
No, I deleted that same period on the .mp4, .json and whatever extension the thumbnail was in order to get the import to take place.  I do seem to remember trying to work through this previously and just another attempt to import would work when the 1st had failed.  Maybe an intermittent issue though not sure what would influence the intermittency?

**Comment by bbilly1** [comment]
hard to say after the fact... well, if it's working... :-)

there are so many variables in manual import, maybe that wasn't such a good idea to implement...

**Comment by PhuriousGeorge** [comment]
It seems you beat yourself up on it, but once you find the ways around the quirkyness, it works great.  I wouldn't be here without it (0.5 mil videos manually imported) ;)

**Comment by bbilly1** [comment]
OK, if we find a reproducible issue, we'll can look into it again.
