### ISSUE TITLE
[Feature Request]: Button to scan subscribed channels for missing videos

### ISSUE THREAD

**Issue by Marthisdil** [tubearchivist/tubearchivist#350]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Describe the solution you'd like: Would like a button/menu entry to rescan a subscribed channel for missing videos.  Can be for ALL subscribed channels or within each channel itself.

Missed videos happen...however, there's no method to find them now outside of pasting the URL for the channel into the download queue and doing that.  If you have a lot of subscriptions, having to do that for each channel is VERY tedious.

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
You can increase the channel page size on the settings page to a higher number, then do a single rescan to make sure you get all videos from the channels you are subscribed to, then set it back to a lower number for future rescans to only get new videos, to avoid making unnecessary requests to YouTube. 

But you shouldn't have to do that more than once per channel, I don't think you can publish a video with an old date. Basically when you subscribe to a new channel, you can descide if you also need the whole catalog or just the new videos. So I think you can do what you need with minimal effort.

**Comment by Marthisdil** [comment]
Nothing to do with publishing a video with an old date - just sometimes ":stuff happens" and it doesn't get a video when adding the /videos link for a channel to the download list.  later on, if you use the same /videos url to rescan the whole channel to find videos TA hasn't downloaded, it'll add em to the queue and go about its business.

Can't say there's a rhyme or reason, but it happens, especially on larger channels - Khan Academy, Lofi Records, and others - but it does happen....and sometimes even a rescan doesn't seem to get them all.

There's no real pattern, and for larger channels the only real way to know if you've missed videos iis to compare the count of what you've downloaded, plus whatever new a rescan finds (for a subscribed channel), then compare to their /videos link and compare the totals to see.

Increasing the channel page to 10000 (or higher) to cover really large channels, while may be a solution, not sure if it's a good/best solution, when effectively could have a button for each channel in the channel page that does that (or similar to adding the /videos url to the download list) so it's targeted and not wanting to do it for all subscribed channels at that time.

Not really a good/easy solution regardless of how its looked at.

**Comment by bbilly1** [comment]
I think there are enough features waiting to be implemented, without already multiple ways to accomplish it. If anybody wants to circle back to that in the future, please do.
