### ISSUE TITLE
[Bug]: Unable to play video on iOS

### ISSUE THREAD

**Issue by matiasvc** [tubearchivist/tubearchivist#356]
### Latest and Greatest

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).

### Operating System

Synology

## Describe the bug

When I try to play any video using firefox on my desktop or laptop the video works fine. If I try to play a video using my iPhone I simply get a black video window and nothing happens, as shown in the below screenshot:
![TubeArchivist](https://user-images.githubusercontent.com/389051/199112235-0f5d8864-7cb9-4d8d-8f3e-4bf41f0345e1.png)

Happy to collect any additional information that would help in debugging this.

## Steps To Reproduce

Open any video using an iPhone running iOS 16.0.2.

## Expected behavior

Expected the video to play using an iPhone.

### Relevant log output

```shell
ta_video/_doc/yQRW6PGGhpU

ta_video/_doc/yQRW6PGGhpU
```

**Comment by pairofcrocs** [comment]
What are your download settings?

We have a [recommended profile ](https://github.com/tubearchivist/tubearchivist#getting-started)for IOS devices :)

**Comment by matiasvc** [comment]
Yup. That was the issue. Got it working once I set the right profile and re-downloaded. Thanks!
Closing this issue.
