### ISSUE TITLE
[Installation]: Installation instructions need updating for v0.2.4

### ISSUE THREAD

**Issue by lamusmaser** [tubearchivist/tubearchivist#360]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [potential pitfalls](https://github.com/tubearchivist/tubearchivist#potential-pitfalls) section.

### Operating System

Synology

### Your installation or setup question

Instructions require update for v0.2.4.

### Relevant log output

```shell
Not required. This is for tracking required changes for documentation.
```

**Comment by lamusmaser** [comment]
As a note for which items have been completed:

- [ ] Unraid (Application and screenshot require updates)
- [x] TrueNAS Scale (HeavySetup reference has been updated with ES setting updates)
- [x] Synology (Wiki reference has been updated with ES setting updates)

**Comment by bbilly1** [comment]
Excellent, thanks for getting that setup. Yeah, unraid needs an update, is missing the TA_HOST variable too there. That's for both the documentation as well as for the unraid templates. Then, when updating the unraid templates, let's also use the opportunity to change the old project link there from billy1/tubearchivist to tubearchivist/tubearchivist.

Maybe we need @pairofcrocs to look into this?

**Comment by bbilly1** [comment]
that's now completed with #373, thanks everybody for your help!
