### ISSUE TITLE
[Installation]: Could you add a note on how to make sure this web app is rerun at server system startup?

### ISSUE THREAD

**Issue by jleaders** [tubearchivist/tubearchivist#365]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Ubuntu

### Your installation or setup question

Perhaps I'm new to docker/systemd, but I think it'd be nice to notate in the readme how this web app would survive system reboots?

### Relevant log output

```shell
.
```

**Comment by bbilly1** [comment]
If you are using the official docker-compose.yml file as a template, you'll have `restart: unless-stopped` set for all your containers, like [here](https://github.com/tubearchivist/tubearchivist/blob/master/docker-compose.yml#L6).

That's how docker knows what to do at startup. You can look up more details in the docker compose specifications, here for example: https://github.com/compose-spec/compose-spec/blob/master/spec.md#restart.

But yeah, that's about how to use docker, not really about how to install this application, so I don't think we need to duplicate that here again.

**Comment by jleaders** [comment]
That makes sense. Thank you
