### ISSUE TITLE
[Bug]: The example format specifier for 1080p iOS-compatible downloads is wrong on the settings page

### ISSUE THREAD

**Issue by 3ster** [tubearchivist/tubearchivist#369]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Unraid

## Describe the bug
The example format specifier for the iOS-compatible downloads is incorrect on the settings page, capitalizing both "VCODEC" and "ACODEC". Due to the format being case-sensitive, this causes yt-dlp to fall back to the (default?) 720p resolution download.

## Steps To Reproduce
Copy + paste the example Max 1080p video height with iOS compatible video and audio codecs format specifier from the settings page into the format specifier box.

## Expected behavior
1080p video is downloaded, if available.

### Relevant log output

```shell
n/a
```

### Anything else?

Below are dry runs using the correct (lowercase) capitalization, and the incorrect (uppercase) capitalization found on the settings page.
```
root@334be6e79a7d:/app# yt-dlp --list-formats https://www.youtube.com/watch?v=su2RDMzsZoE
[youtube] su2RDMzsZoE: Downloading webpage
[youtube] su2RDMzsZoE: Downloading android player API JSON
[info] Available formats for su2RDMzsZoE:
ID  EXT   RESOLUTION FPS CH │   FILESIZE   TBR PROTO │ VCODEC          VBR ACODEC      ABR ASR MORE INFO
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
[...]
140 m4a   audio only      2 │    5.09MiB  129k https │ audio only          mp4a.40.2  129k 44k medium, m4a_dash
[...]
22  mp4   1280x720    30  2 │ ~ 61.35MiB 1523k https │ avc1.64001F   1523k mp4a.40.2    0k 44k 720p
[...]
299 mp4   1920x1080   60    │  119.68MiB 3047k https │ avc1.64002a   3047k video only          1080p60, mp4_dash
root@334be6e79a7d:/app# yt-dlp --format "bestvideo[height<=1080][vcodec*=avc1]+bestaudio[acodec*=mp4a]/mp4" --simulate https://www.youtube.com/watch?v=su2RDMzsZoE
[youtube] su2RDMzsZoE: Downloading webpage
[youtube] su2RDMzsZoE: Downloading android player API JSON
[info] su2RDMzsZoE: Downloading 1 format(s): 299+140
root@334be6e79a7d:/app# yt-dlp --format "bestvideo[height<=1080][VCODEC*=avc1]+bestaudio[ACODEC*=mp4a]/mp4" --simulate https://www.youtube.com/watch?v=su2RDMzsZoE
[youtube] su2RDMzsZoE: Downloading webpage
[youtube] su2RDMzsZoE: Downloading android player API JSON
[info] su2RDMzsZoE: Downloading 1 format(s): 22
```

**Comment by pairofcrocs** [comment]
Hey there!

Nice catch, I can confirm this is affecting my installation too.

If you'd like, you can open a PR with that corrected change so that you can be credited as a contributor [here.](https://github.com/tubearchivist/tubearchivist/blob/2fa907c47892a3b6f026ac8a4636b6bfc1694fc0/tubearchivist/home/templates/home/settings.html)

Thanks!

**Comment by bbilly1** [comment]
Thanks a lot for looking into that. Looks like we messed this up in previous testing. Thanks for looking out.
