### ISSUE TITLE
[Hotfix published]: Compatibility issue: v0.3.0 requires v0.2.4 to be installed first, KeyError enable_snapshot

### ISSUE THREAD

**Issue by a-jackson** [tubearchivist/tubearchivist#372]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux, Ubuntu 20.04

## Describe the bug

Crash on startup since pulling latest image 0.3.0.

## Steps To Reproduce

Happens every time on startup. Stuck in a restart loop. I tried clearing ta-cache with no effect.

## Expected behavior

Application starts

### Relevant log output

```shell
tubearchivist  |   File "/app/manage.py", line 23, in <module>
tubearchivist  |     main()
tubearchivist  |   File "/app/manage.py", line 19, in main
tubearchivist  |     execute_from_command_line(sys.argv)
tubearchivist  |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line
 446, in execute_from_command_line
tubearchivist  |     utility.execute()
tubearchivist  |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line
 420, in execute
tubearchivist  |     django.setup()
tubearchivist  |   File "/root/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
tubearchivist  |     apps.populate(settings.INSTALLED_APPS)
tubearchivist  |   File "/root/.local/lib/python3.10/site-packages/django/apps/registry.py", line 124, in po
pulate
tubearchivist  |     app_config.ready()
tubearchivist  |   File "/app/home/apps.py", line 135, in ready
tubearchivist  |     startup.run()
tubearchivist  |   File "/app/home/apps.py", line 31, in run
tubearchivist  |     ElasitIndexWrap().setup()
tubearchivist  |   File "/app/home/src/es/index_setup.py", line 160, in setup
tubearchivist  |     self._check_backup()
tubearchivist  |   File "/app/home/src/es/index_setup.py", line 203, in _check_backup
tubearchivist  |     if config["application"]["enable_snapshot"]:
tubearchivist  | KeyError: 'enable_snapshot'
```

**Comment by bbilly1** [comment]
I see how this slipped through. Am I right in assuming you skipped the last release? Try to install v0.2.4 first, then upgrade to v0.3.0, that should take care of that.

In any case I need to fix the startup checks there to first sync new config vars before checking the snapshot there.

**Comment by a-jackson** [comment]
Yes that must have been it. Updating through 0.2.4 first worked. It's running on 0.3.0 now. Thanks

**Comment by bbilly1** [comment]
Thanks for confirming that. I'll push an update later. Let's keep this issue open for some days, so people can easily see it.
