### ISSUE TITLE
[Feature Request]: Multiple categories and views

### ISSUE THREAD

**Issue by barrelltitor** [tubearchivist/tubearchivist#378]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.
Finding a specific type of video to watch can be problematic, as well as organizing or separating the videos in any way.
## Describe the solution you'd like
Add a way to create new tags/categories which can be assigned to channels. When a new category is made, you will have the option to view all the videos inside it somewhere on the home page.

Maybe as a new "Categories" button next to the existing home,channels&etc buttons which would take you to a page where you can select a category

Another option for the placement of this would be to have something similar to YouTube's existing horizontal bar which shows you "All, Gaming, Electrican Engineering, Compsci, etcetc" 
## Additional context

This should also solve #330

**Comment by bbilly1** [comment]
So we have the `Custom searchable notes to videos, channels, playlists` on the roadmap. You could create your tags or categories there, or any thing you'd like to filter or search.

**Comment by barrelltitor** [comment]
I see, I completely misunderstood what that feature was intended for. 

I initially believed this was meant to be a sort of notepad for noting down key points or such from the videos, e.g for research purposes, since the original request wanted it for recipe storing.
