### ISSUE TITLE
[Feature Request]: Manual "Delete + Ignore All Watched Videos Now" Button

### ISSUE THREAD

**Issue by Brancliff** [tubearchivist/tubearchivist#380]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Additional context
The auto-deletion of watched videos can at minimum be set to 1 day. By creating a way to manually delete watched videos, a user wouldn't have to wait 24 hours to delete + ignore watched videos.
It is possible to hit the delete button on watched videos individually, or to delete the videos from the file system and hit the "rescan filesystem" button, but neither option seems to also add the video to the ignore list. (Which may be intended, and that's okay - I just want to say why I don't think this would be a good workaround for this use case)

## Describe the solution you'd like
In the settings, the "Actions" section has a few buttons you can use to issue one-time commands. This would fit perfectly in there.

## Is your feature request related to a problem? Please describe.
I do have some videos that I've marked as "watched" that didn't get deleted. But it seems like a really specific problem, I can't imagine how I could help someone reproduce this problem. (I'd be willing to try, but I wouldn't have an idea on where to start)

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
Honestly, I don't really see the problem, the videos will delete automatically, automatically is always better than manually. Just let it do it's thing. :-)

The *1 day* issue is a matter of form parsing on the settings page, but that's an unrelated issue and deserves some future improvements anyways.  

For the delete video, see #286, one of the countless ideas on the backlog. For the watched videos, that didn't get deleted, that could be related to #309. 

Right now how autodelete works, is that it's tied to the download task, it would require quite some refactoring to put this into a separate task to be triggered independently. 

I hope you understand, there are a lot of more pressing improvements, that don't already have a working solution. I hope you can understand.

**Comment by tommyboy180** [comment]
I second this feature request.
