### ISSUE TITLE
[Feature Request]: "Lite" Version? Elastic Search is *heavy*

### ISSUE THREAD

**Issue by jleaders** [tubearchivist/tubearchivist#384]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.

I had to uninstall TubeArchivist after I noticed it seems to be eating up most of my server putting Load average to 12+, using a gig of RAM, and numerous threads.

This is a fantastic app for serious archival of youtube, but for a light user who only wants to save a few favorites (recipe videos, home videos) can we add a liter config?

## Describe the solution you'd like
Just updating the README to have a config setup that describes a lighter, less resource intensive install. Think Raspberry Pi or Home NAS.
* Can Elastic Search expose some docker vars to limit to a single worker thread? 
* Can we add Technical Specifications area that describes the intended server? Is this for large enterprise systems, or microservers? Its not clear 

## Additional context
My server was bogging down, and here's the htop of what triggered my concerns. Keep in mind I run many many other services on this server and this one is rarely used and has probably less that 150 vids on it. Makes me want to just use youtube-dl in a folder because it makes no sense for a gig of memory to search 150 vids that already finished indexing a week prior, what on earth is it doing?

![tubearchivist slow](https://user-images.githubusercontent.com/2430917/206296233-29f87dc7-e8c3-43a4-913a-a664f9242ac0.jpg)

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
This has come up a few times before, you can find various issues in this repo, for example #19.

There are some minimal system requirements in the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating). I can add *minimal dual core, preferably quad core* there. 

But yeah, single core is going to struggle, particularly with with a bunch of other things running. If you want to try to mess with the countless ES configuration options, please do: [FAQ](https://github.com/tubearchivist/tubearchivist/wiki/FAQ#4-finetuning-elasticsearch), let me know if you find anything interesting. Or that might be the time to invest into the next level of server hardware?

But yes, a youtube archive media server makes maybe most sense for 10k+ videos? I mean I was doing quite well for a long time with a bash script and a little rofi wrapper, until things got out of hand, inspiring me to write this project. 

I'm not going to tell you what you can or can not do on your hardware.

**Comment by onedr0p** [comment]
@bbilly1 maybe a different software instead of Elasticsearch like [manticoresearch](https://github.com/manticoresoftware/manticoresearch) would be better? It is written in C++ and has some ambitious performance over elasticsearch.

It has a [python library](https://github.com/manticoresoftware/manticoresearch-python) as well!

**Comment by bbilly1** [comment]
Elasticsearch is what I know, is what I'm familiar with. I know there are various projects out there that claim to be a drop in replacement, so far, none of them have been.

I doubt that I'll be rewriting this project anytime soon to use anything else, just to save a few MBs of memory.
