### ISSUE TITLE
[Feature Request]: Delete videos after 28 days?

### ISSUE THREAD

**Issue by thisisawesome1994** [tubearchivist/tubearchivist#387]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.
Hi. Would it be possible to add a countdown (1-28 days), after which all videos older then x amount of days will automatically be deleted, regardless if watched or not. I would love that, since libraries with limited amount of space could use this, so they can still archive a lot of channels on that limited space.
## Describe the solution you'd like
I like this solution so that I can watch the videos without using youtube, and have a "temporary" local backup. I also like the tubearchivist overview of videos more then the overview on youtube.
## Additional context
Nothing perticulair.

### Your help is needed!

- [x] Yes I can help with this feature request!

**Comment by thisisawesome1994** [comment]
It might also be a possibility to keep only the x amount of newest videos, for example, if you download the 50 latest videos per channel (setting default), when downloading more videos later, the older videos get deleted (older then the latest 50)

**Comment by bbilly1** [comment]
There is already an issue open about that, with somebody interested to implement that: #337
