### ISSUE TITLE
[Feature Request]: Download stop schedule

### ISSUE THREAD

**Issue by florensie** [tubearchivist/tubearchivist#388]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.
My internet plan has a monthly download cap measured only between certain hours. I want to only download during non-limited hours.

## Describe the solution you'd like
It's already possible to automatically start the download queue at a certain schedule, but I'd like to also have a schedule to stop the queue. This could also be solved by #198, but this (temporary) solution is much simpler to implement, and probably covers many of the use cases of that feature request.

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
Please add all download schedule things to the other issue you mentioned: #198, to have this concise and help to stay organized.
