### ISSUE TITLE
[Installation]: Download schedule not fast enough and only downloads a handful

### ISSUE THREAD

**Issue by voarsh2** [tubearchivist/tubearchivist#390]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

### Your installation or setup question

My setup has over 1K downloads and the queue doesn't really go down.

Download schedule is currently 0 12 * - I don't quite understand this non-standard cron style format, Ideally I want it every 1 hour, but not sure how to set that. I know how to do it "normal" cron style though.

When I check my download queue and do "start download" it seems to only download a handful of videos and then stops.... until.... the next download schedule?

At this rate, my installation won't be catching up with the downloads that become available from the number of new videos it picks up from 18 channels.

### Relevant log output

```shell
NA
```

**Comment by bbilly1** [comment]
Check the wiki for an explanation, but basically the format just implements the first three fields, minutes, hours and days, and will assume `*` for the others. But wiki has you covered. 

Download queue will continue until it's finished, if it's not, this means that there is another issue. Maybe your storage is full? Maybe your internet drops?

**Comment by bbilly1** [comment]
Stay tuned for a realtime monitoring solution in the future. That will eliminate the constant rescanning. :-)
