### ISSUE TITLE
[Feature Request]: Per channel/playlist hide watched status

### ISSUE THREAD

**Issue by trinsic** [tubearchivist/tubearchivist#392]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Describe the solution you'd like

The hide watch feature is a nice addition on the home page as I can see the content I haven't watched yet. However I don't always need it on channels and playlists if I want to find older watched content. This means turning it on and off all the time.

Can the option be done on a per channel/playlist rather than a global setting?

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
It's just a click away. :-) Let's not over complicate things. 

To have additional options per channel, then you never knowing if you set this per channel or not, would probably be more complicated than just a single click to choose what you need.
