### ISSUE TITLE
[Installation]: Getting an Operation Not Permitted error related to setting the rlimit at startup

### ISSUE THREAD

**Issue by tokenwizard** [tubearchivist/tubearchivist#393]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux (Proxmox LXC)

### Your installation or setup question

I am following along the instruction for the docker-compose.yml and have updated my file as described. 
WHen I try and run for the first time, I am geting this error. 

FYI, I am running in a Proxmox LXC with Ubuntu 22.04 as the Template. I am running as root to test. 
I run quite a few other Docker containers in these LXCs without issue. This is my first time seeing this error. 

### Relevant log output

```shell
Digest: sha256:d823a714014cc78332f4ad5f71cab57d494f155225bc57edabbe52094af2f18e
Status: Downloaded newer image for bbilly1/tubearchivist:latest
Creating archivist-es ... error

ERROR: for archivist-es  Cannot start service archivist-es: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown

ERROR: for archivist-es  Cannot start service archivist-es: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting rlimits for ready process: error setting rlimit type 8: operation not permitted: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by bbilly1** [comment]
Google shows a bunch of results when you search for that error, looks like that's a LXC thing, for example you could start here: https://discuss.linuxcontainers.org/t/error-setting-rlimits-type-8-operation-not-permitted-unknown-in-lxd-container/9976

Here they suggest that setting the ulimits might cause the issue? https://github.com/docker/compose-cli/issues/1769

Let me know what else you find in your research.
