### ISSUE TITLE
[Bug]: (not really) Typo in settings.

### ISSUE THREAD

**Issue by hugalafutro** [tubearchivist/tubearchivist#398]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux

### Your Bug Report

Hi,

in the settings page
![image](https://user-images.githubusercontent.com/30209689/210133256-67c95703-87f3-4a39-9ffc-4c5b8f3dda44.png)

shouldn't it say `single LINE` ? As in make sure the yt-dlp parameters are all in a single string without line breaks, or do I misunderstand the whole thing completely?

I'm apparently also too thick to figure github at times as I wanted to open a pr and edit the line in the file, but the edit button was greyed out, but then I wasn't sure if I'm actually right and so here we are 😄 

### Relevant log output

```shell
nada
```

### Anything else?

Happy new year 🎉

**Comment by bbilly1** [comment]
You might be tempted to select a format to download different streams as separate files, from the yt-dlp docs [here](https://github.com/yt-dlp/yt-dlp#format-selection):

> If you want to download several formats of the same video use a comma as a separator, e.g. -f 22,17,18 will download all these three formats, of course if they are available. Or a more sophisticated example combined with the precedence feature: -f 136/137/mp4/bestvideo,140/m4a/bestaudio.
You can merge the video and audio of multiple formats into a single file using -f <format1>+<format2>+... (requires ffmpeg installed); e.g. -f bestvideo+bestaudio will download the best video-only format, the best audio-only format and mux them together with ffmpeg.

So you'll have to use the `+` symbol to merge the different streams like audio + video into a single file, if you use the `,` they will remain as separate files. That's what is meant with *Make sure your custom format gets merged into a single file* 

But yeah, if you have newline characters in there, the selector might not do what you expect, but that's on you. :-)

**Comment by hugalafutro** [comment]
I see, thanks for the explanation, it now makes sense as it is written and sorry for bothering you with non-issues.

**Comment by bbilly1** [comment]
Don't worry about it. :-)

For future occasions: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Basically, fork this repo, make changes in your fork, and a pull request button will manifest it self. :-)
