### ISSUE TITLE
[Feature Request]: Make ignored downloads filterable

### ISSUE THREAD

**Issue by samdoshi** [tubearchivist/tubearchivist#401]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.

When adding videos via the extension or the web interface, videos that are on the ignore list are not re-added, this is particularly confusing as no feedback is given.

## Describe the solution you'd like

When a video is added to the download queue that is ignored, it should be un-ignored.

## Additional context

Currently I have to search through my ignored video list to find the video, which has ~1700 items in it.

I am happy to help with this, but I am hoping that is something very easy to change for someone who is experienced with the codebase. Thanks!

### Your help is needed!

- [X] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
I think what you really mean is to make the downloads page searchable, no?

I mean if you ignore a video, you hopefully ignored it for a reason, that would be very confusing if ignoring the video will still add it, basically ignoring your ignoring. :-)

You also need to think about that you might want to download a playlist or a full channel, where your ignored video is a part of, so you will want to skip it as well in that occasion.

But yeah, feedback wise, the extension just sends the link, then the server is doing the rest, you wouldn't want to make the extension wait until the server has extracted the video or even a complete channel. But it's on the roadmap, to better integrate that with the API, to for example not build a download link, if the video is already downloaded, etc...

**Comment by bbilly1** [comment]
I don't think it's a good idea for an application to make assumptions about intent, that's probably going to be wrong more often than right. If you ignored a video it should be ignored, until you unignore it. Anything else will be confusing, making me feel like the application doesn't respect me. :-)

Making the channel filter dropdown on the downloads page work for the ignored videos should be straight forward. 

> I am happy to help with this, but I am hoping that is something very easy to change for someone who is experienced with the codebase.

This could be you! Please contribute and help with that.

**Comment by bbilly1** [comment]
Download queue filter is now fixed in v0.3.3, please update.
