### ISSUE TITLE
[Feature Request]: Remote user support

### ISSUE THREAD

**Issue by thijsa** [tubearchivist/tubearchivist#403]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.
I am using authentik (https://goauthentik.io/) in front of Tube Archivist. This handles the authentication for the users and is capable of sending some authentication info using headers to the application. Currently, users always need to sign in using the credentials in Tube Archivist after authenticating in authentik. 

## Describe the solution you'd like
Django has support for using the authentication information sent by the reverse proxy. See https://docs.djangoproject.com/en/4.1/howto/auth-remote-user/. I would like a setting / env variable that would allow enabling this feature so that users don't have to enter their credentials twice.

## Additional context
This feature should not be enabled by default because it would allow anyone to login with just the username if they don't have a proper reverse proxy setup. This warning is also present on the Django documentation page.

### Your help is needed!

- [x] Yes I can help with this feature request!

**Comment by ionlights** [comment]
@thijsa Have you looked into using [`django-allauth`][allauth]? (This is slightly tangential to `REMOTE_USER` – if `tubearchivist` used `django-allauth` this would allow for OIDC authN/authZ.)

[Tandoor (Recipes)][tandoor] (which is also a Django app) uses `django-allauth`. A recent PR to `django-allauth` allowed for generic OIDC (which means Authentik now have proper support), I've been using it for a few weeks without issue.

[allauth]: https://django-allauth.readthedocs.io/en/latest/
[tandoor]: https://github.com/tandoorrecipes/recipes/

**Comment by zerosnugget** [comment]
> @thijsa Have you looked into using [`django-allauth`](https://django-allauth.readthedocs.io/en/latest/)? (This is slightly tangential to `REMOTE_USER` – if `tubearchivist` used `django-allauth` this would allow for OIDC authN/authZ.)
> 
> [Tandoor (Recipes)](https://github.com/tandoorrecipes/recipes/) (which is also a Django app) uses `django-allauth`. A recent PR to `django-allauth` allowed for generic OIDC (which means Authentik now have proper support), I've been using it for a few weeks without issue.

I also would look forward to this and the djano-allauth plugin is working well for me with tandoor too so +1 for this feature.

**Comment by bbilly1** [comment]
that's now implemented in v0.4.2.

**Comment by CrazyWolf13** [comment]
are there any plans to include SSO support for example by adding OIDC compatibility?

This would allow an even more standardized and simpler way to connect tubearchivist to authentik or any other provider, as oidc is the de facto standard.
