### ISSUE TITLE
[Bug]: Synology instructions wrong

### ISSUE THREAD

**Issue by hasso** [tubearchivist/tubearchivist#407]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Synology

## Describe the bug

Synology instructions say to configure ES container with "xpack.security.enabled=true" which makes encryption required and tubearchiver container to use ES from http://tubearchivist-es:9200 which can't work.

## Steps To Reproduce

Install according to instructions in https://github.com/tubearchivist/tubearchivist/blob/master/docs/Installation.md

## Expected behavior

I'm not familiar of methods how it would be possible to use encryption between containers using selfsigned certificates, so for now I'd use xpack.security.enabled=false in ES container.

### Relevant log output

```shell
{"@timestamp":"2023-01-15T09:50:55.944Z", "log.level": "WARN", "message":"received plaintext http traffic on an https channel, closing connection Netty4HttpChannel{localAddress=/172.17.0.2:9200, remoteAddress=/172.17.0.4:59490}", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[tubearchivist-es][transport_worker][T#4]","log.logger":"org.elasticsearch.xpack.security.transport.netty4.SecurityNetty4HttpServerTransport","elasticsearch.cluster.uuid":"<stripped>","elasticsearch.node.id":"<stripped>","elasticsearch.node.name":"tubearchivist-es","elasticsearch.cluster.name":"docker-cluster"}
```

**Comment by bbilly1** [comment]
This shouldn't fail? `xpack.security.enabled=true` is for being able to use basic auth to access elasticsearch, you *can* use https if you want to, maybe you have an ES instance in the cloud somewhere, but you don't have to.

**Comment by hasso** [comment]
If my memory serves me well, then since ES8 security is configured automatically in first start and TLS is made mandatory as well. Another "works if upgraded, but broken for new installs" issue?

**Comment by bbilly1** [comment]
According to the documentation, TLS is only a requirement, if you run a multi node cluster: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-minimal-setup.html

But that's not the case on a single node, I've been running a similar configuration as in the example docker compose file, I guess we all have, also tested it in a new installation. If your ES isn't starting, that's probably another problem. 

`ES_URL=http://tubearchivist-es:9200` or whatever you have configured, should be fine.
