### ISSUE TITLE
[Feature Request]: Add small badge to distinguish between video/stream/short (download queue)

### ISSUE THREAD

**Issue by SmartPhoneLover** [tubearchivist/tubearchivist#410]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

Hello, I think that adding something like a small badge or some kind of element inside every video box, to tell us if it's a video, stream or short to download, would be a plus to help us to distinguish what kind of video we are going to download. It would be easier to identify them.

Or maybe, create some categorization (tabs) to organize all the videos of the same type.

What do you think?

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
That's already there, hover over the video to see it's type.

**Comment by SmartPhoneLover** [comment]
Sorry to re-open de issue, but when I hover the mouse over the preview of the video, it always shows: 'video'. It doesn't show short or any kind, other than: video.

**Comment by lamusmaser** [comment]
Can you open a new issue and also include some examples of videos that are expected to be `shorts`/`lives` that are showing as `video`? I can confirm that `shorts` are showing as expected within my test instance.

**Comment by bbilly1** [comment]
probably old items in the queue from before the update? they will all be defaulted to "videos" type, and will get categorized correctly with the refresh task. or delete and recreate the queue. then new items added to the queue should get categorized correctly.
