### ISSUE TITLE
[Feature Request]: Replace unprintable special characters with a placeholder

### ISSUE THREAD

**Issue by astrobyte** [tubearchivist/tubearchivist#416]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

## Is your feature request related to a problem? Please describe.

If a video name has certain special characters, they will be removed from the resulting filename, ie: 

I ✴ Like ✴ Pie ✴ a lot

results in
I Like Pie a lot.mp4

Often the special characters are a delimiter, so removing them breaks regex matching for naming in third party apps.

## Describe the solution you'd like

Replace these types of special characters with a standard delimiter, such as -

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
You might want to use the API for things like that, that will have the original unicode title as text, same the generated file path, so you won't face such problems for your integrations. 

In any case, as you know, this is a know limitation, probably will work on creating a flexible naming template at some point, but probably not any time soon.
