### ISSUE TITLE
Dockerfile for bbilly1/tubearchivist-es

### ISSUE THREAD

**Issue by DrMurx** [tubearchivist/tubearchivist#418]
I'd appreciate if you could publish the Dockerfile and additional assets from which you build `bbilly1/tubearchivist-es`.

**Comment by bbilly1** [comment]
There is no Dockerfile, that's just a *docker pull* && *docker tag* && *docker push*. Technically this uses the same Dockerfile as official ES does, if you want to take a look at that. It's build from our fancy build server: https://github.com/tubearchivist/tubearchivist-server/blob/master/tubearchivist/web/src/webhook_base.py#L27-L32

But if you are concerned about integrity, you can always use the official ES image, but as they don't have a *latest* tag, you'll just have to update that regularly manually: https://github.com/tubearchivist/tubearchivist#updating-tube-archivist

**Comment by DrMurx** [comment]
Thank you for the clarification.
