### ISSUE TITLE
[Feature Request]: Flexible naming structure, feature requirements

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#419]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

This is for documenting what a flexible file naming scheme would need to entail. 

Ideally this would be *real* flexibility, similar as an output template from yt-dlp implementing at least some of the fields, this would cover all usecases, but much harder to implement and even more so to make foolproof.

Alternatively, this could also be *partial* flexibility, creating a selection of possible naming schemes.

But in anycase this requires:
- Backwards compatibility, meaning your existing videos need to be renamed to the new naming scheme.
- This also needs to change the naming scheme of subtitles, both old and new.
- The new url needs to be updated in ES during the process.
- The video ID needs to be programmatically detectable with an index in the title string, for example at the end of the name, at the beginning, after the date...
- The *reindex* task needs to be able to deal with any naming scheme.
- The *rescan your filesystem* task needs to be able to pickup media files that are not indexed

That's just a selection of the obvious challenges before actually working on the implementation.

This is a help needed feature, this is currently not in the scope of this project. If you want to work on that, please reach out!

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by Vandekieft** [comment]
This would be a big +

TubeArchivist is a more stable platform vs TubeSync (which is a tiny project but still great), but lacks some features the TubeSync does offer.

I know this is meant to be a local viewing self hosted media center, which is great. But adding this feature would take a lot of the pain of making this compatible with other devices in the future. This is really the main feature that I would wan't, for the non local viewing. If YouTube-Agent support is added, this would fix mobility issue.

https://github.com/ZeroQI/YouTube-Agent.bundle

As YouTube-Agent is to help with other media centers an properly displaying the metadata, letting me set how my file names out put would let me have a shared TubeArchivist and Plex library.  This way, I can my videos sync with my phone via the plex app and have them for my daily commute to work.. My wife can watch her shows on her xbox., etc....

Right now, embedding the metadata help, but having the weird naming format still messes with YouTube-Agent in plex. All we really need is the ability to add the YT Channel ID to the channel directory, and ability to embedded the Video ID in a custom spot, identified with square brackets.

**Comment by jamesdesmond** [comment]
I also agree with these above points, and will look myself into what code changes are necessary to change how the filenames are saved. 
This would be a very useful feature as it would help integrate with the YouTubeAgent, which is the missing link in getting automatic youtube downloads from TA to appear in Plex.

**Comment by bbilly1** [comment]
After extensive deliberation, this is no longer a desired feature. We couldn't even get the static title and channel name convention working reliably, so I doubt we'll ever want to implement that.

Ultimately main reason for a flexible naming convention was for the ability to import YouTube videos into Jellyfin/Plex and similar. As we now have our own Jellyfin integration [tubearchivist/tubearchivist-jf](https://github.com/tubearchivist/tubearchivist-jf), (plex is still pending), this makes that feature redundant.

If you ever need to go back to any other naming convention in the future, you can always do that by querying the API or the JSON file backups or even the embedded metadata, if you have enabled that on the config page.

And if you still really need your own custom solution, you can also implement some simlink script that renames things outside of the /youtube folder. Also see [FAQ](https://docs.tubearchivist.com/faq/#why-is-there-no-flexible-naming-structure).

I hope you fine folks out there can understand that decision.
