### ISSUE TITLE
[Feature Request]: Download only if matches a filter

### ISSUE THREAD

**Issue by AlexZorzi** [tubearchivist/tubearchivist#420]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

It would be useful to for example given a channel or playlist, download only the videos that contain a specific word or that matches a specific regex expression

for example download only videos from a channel that contain the word "tutorial"

### Your help is needed!

- [ ] Yes I can help with this feature request!

**Comment by bbilly1** [comment]
We've had ignore by keyword for some time on the roadmap, the inverse is basically the same feature. I've clarified that in the Readme.

But yeah, this project needs your help working on the backlog, we are currently not adding any new features.
