### ISSUE TITLE
[Installation]:  Tube Archivist Web Pod Failing to Start - Django Not Found

### ISSUE THREAD

**Issue by mitchross** [tubearchivist/tubearchivist#421]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux 

### Your installation or setup question

Tube Archivist Web Failing to start on k8s

### Relevant log output

```shell
"build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "f67ef2df40237445caa70e2fef79471cc608d70d",
    "build_date" : "2023-01-04T09:35:21.782467981Z",
    "build_snapshot" : false,
    "lucene_version" : "9.4.2",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
Traceback (most recent call last):
  File "/app/manage.py", line 12, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 14, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
Traceback (most recent call last):
  File "/app/manage.py", line 12, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'
```

**Comment by bbilly1** [comment]
Did you use the helm chart by @insuusvenerati? 

But yeah, ModuleNotFound, either the requirements aren't installed, or not available for import in your path. 

But yeah, there is not enough context here to know what's happening.

**Comment by mitchross** [comment]
> Did you use the helm chart by @insuusvenerati?
> 
> But yeah, ModuleNotFound, either the requirements aren't installed, or not available for import in your path.
> 
> There is not enough context here to know what's happening.

Thanks for quick reply! 


Does this help? https://github.com/mitchross/k8s-homelab-cluster-v2/blob/main/kubernetes/apps/default/tubearchivist/app/web/helmrelease.yaml

Elastic Search Pod Is working.
I am running my own Redis instance too...

**Comment by insuusvenerati** [comment]
I second using app-template. It's basically all my helm chart is anyways

**Comment by insuusvenerati** [comment]
My bad, I confused your reply as a reply from someone else. I see literally nothing wrong with your manifest. Can you try with the unstable tag?

**Comment by mitchross** [comment]
> My bad, I confused your reply as a reply from someone else. I see literally nothing wrong with your manifest. Can you try with the unstable tag?

No worries... I went to 'unstable' tag same issue


Ill try deleting everything/redeploying tomorrow.... 

```

{
  "name" : "tubearchivist-elasticsearch-0",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "-9ocvnFBQkWz90FHTCpWdQ",
  "version" : {
    "number" : "8.6.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "f67ef2df40237445caa70e2fef79471cc608d70d",
    "build_date" : "2023-01-04T09:35:21.782467981Z",
    "build_snapshot" : false,
    "lucene_version" : "9.4.2",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
Traceback (most recent call last):
```

**Comment by lamusmaser** [comment]
I thought I had remembered seeing something similar to this about a month ago. I looked back through our Discord Support posts and found a related issue.

By chance, are the containers coming through with root privileges/being installed with a root-level user?

If not, I think that may be causing the problem. The user provided doesn't have the access necessary to perform functions (like access other libraries, which we see with the django call). This was the referencing issue for #394 and is one of the reasons that feature is being considered.

If that isn't the case, let us know and we can continue the troubleshooting further.

**Comment by mitchross** [comment]
@insuusvenerati  .. Hey its been a while. I'm still having this issue -> https://github.com/mitchross/k8s-homelab-cluster-v2/blob/main/kubernetes/apps/default/tubearchivist/app/web/helmrelease.yaml


I followed this for the most part.
https://github.com/insuusvenerati/k8s-home/blob/main/cluster/apps/default/tubearchivist/tubearchivist.yaml#L87

**Comment by insuusvenerati** [comment]
Damn it's still the same error? I'll take a look at reproducing it when I get home using your manifests.

**Comment by mitchross** [comment]
> Damn it's still the same error? I'll take a look at reproducing it when I get home using your manifests.

like wise, ill try a carbon copy of your setup in another folder see if I can narrow it down.

**Comment by mitchross** [comment]
> > Damn it's still the same error? I'll take a look at reproducing it when I get home using your manifests.
> 
> like wise, ill try a carbon copy of your setup in another folder see if I can narrow it down.

@insuusvenerati  where are you setting your redis connection string in https://github.com/insuusvenerati/k8s-home/blob/main/cluster/apps/default/tubearchivist/kustomization.yaml

**Comment by insuusvenerati** [comment]
I believe it's just hardcoded in the values.yaml of the helm chart I made

**Comment by mitchross** [comment]
> I believe it's just hardcoded in the values.yaml of the helm chart I made

Alright I got two versions

1. This version is a close copy of your home lab config https://github.com/mitchross/k8s-homelab-cluster-v2/tree/main/kubernetes/apps/default/tube however its missing a link/value/setting to point to my redis cluster

2.  This version is my version but its throwing the issue about not finding django... possible pod security issue https://github.com/mitchross/k8s-homelab-cluster-v2/blob/main/kubernetes/apps/default/tubearchivist/app/web/helmrelease.yaml

**Comment by insuusvenerati** [comment]
I should be able to dive into it soon. Finishing up work

**Comment by bbilly1** [comment]
Maybe Discord is a better place for this discussion? Just so folks subscribed to the repo don't get overwhelmed with notifications. 

Then if you find a solution, you can add it here for future reference.

**Comment by mitchross** [comment]
> Maybe Discord is a better place for this discussion? Just so folks subscribed to the repo don't get overwhelmed with notifications.
> 
> Then if you find a solution, you can add it here for future reference.

https://discord.com/channels/920056098122248193/1076540527794733209

**Comment by lee-b** [comment]
Saw this in docker-compose too. Turned out that the non-root user id didn't have permissions to read to the django modules within the container.

**Comment by strassea** [comment]
i cant access the thread on the discord, please post the fix here @mitchross

**Comment by mitchross** [comment]
I dont use this tool anymore. Pretty much any questions can be solved with a little AI help these days.
