### ISSUE TITLE
[Installation]: Delete video button missing

### ISSUE THREAD

**Issue by quadcom** [tubearchivist/tubearchivist#432]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Unraid

### Your installation or setup question

I looked through the wiki about being able to delete specific videos. There was a mention of deleting videos but I don't see what is being referenced.

https://github.com/tubearchivist/tubearchivist/wiki/Video

![image](https://user-images.githubusercontent.com/7085931/219456526-e9414694-9935-4c47-aec7-f4cb3e6d006f.png)

At least in my install, there is no delete button anywhere that I can clearly see.

### Relevant log output

```shell
No logs needed (I think)
```

**Comment by lamusmaser** [comment]
This should be on the video's direct page. It will have several options:

Reindex, Download File, and Delete Video.

![Screenshot 2023-02-16 113819](https://user-images.githubusercontent.com/1940060/219457594-5180a81f-7986-48be-b37c-275f53a05221.jpg)

It would look something like the attached screenshot. If you aren't seeing that, can you provide what you are seeing?

**Comment by quadcom** [comment]
Ok, I see the problem. You don't get that page if you click the video's thumbnail, which most people would do, but you can watch the DL, so you think you are on the video page. You get the 'direct video page' only if you click the video title below the thumbnail. 

Is there really a need for two different ways to watch the DL?

**Comment by lamusmaser** [comment]
That's a good questions about the front end. @bbilly1, do you or someone else want to answer that specific part of the question? It looks like we have several layers on video presentation that could cause confusion, especially for media management of those individual videos.

**Comment by bbilly1** [comment]
That is correct, the play button opens an inline player without a page refresh, but that only has space for limited metadata. Then when clicking on the title this will open the video page with all it's metadata including a delete button.

See general navigation on the wiki: https://github.com/tubearchivist/tubearchivist/wiki#general-navigation, and also the video page itself: https://github.com/tubearchivist/tubearchivist/wiki/Video#video-page with explanation.

So I think that makes sense, sometimes if you just want to watch a video, you don't want to see all the comments, similar videos, tags and all these things. Sometimes you do, so you can do both.

So all in all, that is working as intended.
