### ISSUE TITLE
[Bug]: Wrong file permissions on downloaded files

### ISSUE THREAD

**Issue by rursache** [tubearchivist/tubearchivist#449]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki) and the [readme](https://github.com/tubearchivist/tubearchivist#installing-and-updating), particularly the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Linux - Docker

## Describe the bug
Downloaded video files are owned by root instead of the 1000 user I setup in the docker run command. The entire `/media/radu/Media/Dumps/YouTube/Channels` folder should be owned by radu:radu (1000:1000) but its root:root

## Steps To Reproduce
```
docker run -d \
  --name tubearchivist \
  --restart unless-stopped \
  -p 13560:8000 \
  -e TZ=Europe/Bucharest \
  -e HOST_UID=1000 \
  -e HOST_GID=1000 \
  -e REDIS_HOST=192.168.31.100 \
  -e REDIS_PORT=13561 \
  -e TA_HOST=192.168.31.100 \
  -e TA_USERNAME=Radu \
  -e TA_PASSWORD='pass' \
  -e ES_URL=http://192.168.31.100:13562 \
  -e ELASTIC_PASSWORD="pass"  \
  -v /media/radu/Media/Dumps/YouTube/Channels:/youtube \
  -v /home/radu/.tubearchivist:/cache \
  bbilly1/tubearchivist:latest
```
```
docker run -d \
  --name tubearchivist-redis \
  --restart always \
  -p 13561:6379 \
  -e TZ=Europe/Bucharest \
  -v /home/radu/.tubearchivist/redis:/data \
  redis/redis-stack-server:latest
```
```
docker run -d \
  --name tubearchivist-elasticsearch \
  --restart always \
  -p 13562:9200 \
  -e ELASTIC_PASSWORD="pass" \
  -e ES_JAVA_OPTS="-Xms512m -Xmx512m" \
  -e xpack.security.enabled=true \
  -e discovery.type=single-node \
  -e path.repo=/usr/share/elasticsearch/data/snapshot \
  -v /home/radu/.tubearchivist/elasticsearch:/usr/share/elasticsearch/data \
  bbilly1/tubearchivist-es:latest
```
## Expected behavior
Downloaded files should be owned by user 1000 (radu)

### Relevant log output

```shell
-
```

**Comment by bbilly1** [comment]
Yes, readme is clear about it, only media files will get chowned. You can still run hat on he folder itself if you want to.
