### ISSUE TITLE
[Feature Request]: Enable embedded subtitles or custom yt-dlp params

### ISSUE THREAD

**Issue by rursache** [tubearchivist/tubearchivist#450]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

Let me embed downloaded subtitles or provide custom yt-dlp params so i can do that myself (`--write-subs --write-auto-subs --embed-subs`)

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
You saw the template, comon man, don't be like that. Embedded subtitles requires mkv files, they wont play in your browser anymore and will require transcoding. Thats currently not planned, there have been issues here already about that.

**Comment by rursache** [comment]
The template forces me to say i will work on this and i wont, i requested a feature. mkvs are fine for me, i dont care about playing in browser.

**Comment by bbilly1** [comment]
Yes template also says that this project doesn't take any new feature requests at the moment. Please respect that.
