### ISSUE TITLE
[Feature Request]: Custom filename for downloaded videos

### ISSUE THREAD

**Issue by rursache** [tubearchivist/tubearchivist#451]
### Already implemented?

- [X] I have read through the [wiki](https://github.com/tubearchivist/tubearchivist/wiki).
- [X] I understand the [scope](https://github.com/tubearchivist/tubearchivist/wiki/FAQ) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

I would like to specify a filename format for the downloaded videos. Currently seems to be `DATE_VIDEOID_TITLE.ext`

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Why did you overwite the template? As you have seen the readme you saw the know limitations. There is also already an open issue with a list of requirements if you want to work on that.

**Comment by rursache** [comment]
I don't have plans to work on this, i opened a feature request thats it...

**Comment by PhuriousGeorge** [comment]
duplicate of #419
