### ISSUE TITLE
[Installation]: Elastic search configuration issue

### ISSUE THREAD

**Issue by vyadav33e** [tubearchivist/tubearchivist#456]
### Installation instructions

- [X] I have read and understand the [installation instructions](https://github.com/tubearchivist/tubearchivist#installing-and-updating).
- [X] My issue is not described in the [common errors](https://github.com/tubearchivist/tubearchivist#common-errors) section.

### Operating System

Ubuntu with docker compose

### Your installation or setup question

version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8001:8000
    volumes:
      - I added path here:/youtube
      - I added path here:/cache
    environment:
      - ES_URL=http://0.0.0.0:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=192.168.0.51         # set your host name
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=verysecret              # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=Asia/Kolkata                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - /I added path here:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.6.2
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - I added path here:/usr/share/elasticsearch/data
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:

### Relevant log output

```shell
#######################

[1] checking expected env vars

    ✓ all expected env vars are set

[2] set default ES user

    ✓ ES user is set to elastic

[3] check TA_PORT overwrite

    TA_PORT is not set

[4] check TA_UWSGI_PORT overwrite

    TA_UWSGI_PORT is not set

[5] check ENABLE_CAST overwrite

    ENABLE_CAST is not set

[6] create superuser

    superuser already created

#######################

#  Connection check   #

#######################

[1] connect to Redis

    ✓ Redis connection verified

[2] set Redis config

    ✓ Redis config set

[3] connect to Elastic Search

    ... waiting for ES [0/24]

    ... waiting for ES [1/24]

    ... waiting for ES [2/24]

    ... waiting for ES [3/24]

    ... waiting for ES [4/24]

    ... waiting for ES [5/24]

    ... waiting for ES [6/24]

    ... waiting for ES [7/24]

    ... waiting for ES [8/24]

    ... waiting for ES [9/24]

    ... waiting for ES [10/24]

    ... waiting for ES [11/24]

    ... waiting for ES [12/24]

    ... waiting for ES [13/24]

    ... waiting for ES [14/24]

    ... waiting for ES [15/24]

    ... waiting for ES [16/24]

    ... waiting for ES [17/24]

    ... waiting for ES [18/24]

    ... waiting for ES [19/24]

    ... waiting for ES [20/24]

    ... waiting for ES [21/24]
```

**Comment by bbilly1** [comment]
It can't find ES anymore. Why change the `ES_URL` from the default in the example docker compose file?

**Comment by bbilly1** [comment]
You say you are running `Ubuntu with docker compose`? I'd say, revert it to the default, restart and post your startup logs from TA and ES. Probably something else going on and ES isn't starting.

**Comment by vyadav33e** [comment]
I reverted already, same issue.

Here ES logs

`agw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

license [843e239e-fa0f-4790-8eeb-af61f0c145d6] mode [basic] - valid | @timestamp=2023-03-24T08:02:20.008Z log.level=INFO ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][clusterApplierService#updateTask][T#1] log.logger=org.elasticsearch.license.LicenseService elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

license mode is [basic], currently licensed security realms are [reserved/reserved,file/default_file,native/default_native] | @timestamp=2023-03-24T08:02:20.009Z log.level=INFO ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][clusterApplierService#updateTask][T#1] log.logger=org.elasticsearch.xpack.security.authc.Realms elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

recovered [9] indices into cluster_state | @timestamp=2023-03-24T08:02:20.013Z log.level=INFO ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][masterService#updateTask][T#1] log.logger=org.elasticsearch.gateway.GatewayService elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

Node [{95a06031a32d}{GseyDj7LTBa9e1giRvLZmg}] is selected as the current health node. | @timestamp=2023-03-24T08:02:20.233Z log.level=INFO ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][management][T#1] log.logger=org.elasticsearch.health.node.selection.HealthNodeTaskExecutor elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

exception during geoip databases update | @timestamp=2023-03-24T08:02:20.234Z log.level=ERROR ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][generic][T#4] log.logger=org.elasticsearch.ingest.geoip.GeoIpDownloader elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster error.type=org.elasticsearch.ElasticsearchException error.message=not all primary shards of [.geoip_databases] index are active error.stack_trace=org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
	at org.elasticsearch.ingest.geoip@8.6.2/org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:134)
	at org.elasticsearch.ingest.geoip@8.6.2/org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:274)
	at org.elasticsearch.ingest.geoip@8.6.2/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:102)
	at org.elasticsearch.ingest.geoip@8.6.2/org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:48)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:917)
	at org.elasticsearch.server@8.6.2/org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)

Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[ta_channel][0]]]). | @timestamp=2023-03-24T08:02:20.372Z log.level=INFO current.health=GREEN previous.health=RED reason=shards started [[ta_channel][0]] ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][masterService#updateTask][T#1] log.logger=org.elasticsearch.cluster.routing.allocation.AllocationService elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

successfully loaded geoip database file [GeoLite2-Country.mmdb] | @timestamp=2023-03-24T08:02:20.411Z log.level=INFO ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][generic][T#4] log.logger=org.elasticsearch.ingest.geoip.DatabaseNodeService elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

successfully loaded geoip database file [GeoLite2-ASN.mmdb] | @timestamp=2023-03-24T08:02:20.444Z log.level=INFO ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][generic][T#3] log.logger=org.elasticsearch.ingest.geoip.DatabaseNodeService elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster

successfully loaded geoip database file [GeoLite2-City.mmdb] | @timestamp=2023-03-24T08:02:20.962Z log.level=INFO ecs.version=1.2.0 service.name=ES_ECS event.dataset=elasticsearch.server process.thread.name=elasticsearch[95a06031a32d][generic][T#1] log.logger=org.elasticsearch.ingest.geoip.DatabaseNodeService elasticsearch.cluster.uuid=kVfagw1NR3CJqjvgM7TyWw elasticsearch.node.id=GseyDj7LTBa9e1giRvLZmg elasticsearch.node.name=95a06031a32d elasticsearch.cluster.name=docker-cluster`


TA logs


`LocalTime -> 2023-03-24 14:48:57

Configuration ->

    . broker -> redis://archivist-redis:6379//

    . loader -> celery.loaders.app.AppLoader

    . scheduler -> celery.beat.PersistentScheduler

    . db -> /celerybeat-schedule

    . logfile -> [stderr]@%INFO

    . maxinterval -> 5.00 minutes (300s)

[2023-03-24 14:48:57,588: INFO/MainProcess] beat: Starting...

 

 -------------- celery@8b78e4f9848a v5.2.7 (dawn-chorus)

--- ***** ----- 

-- ******* ---- Linux-5.19.0-35-generic-x86_64-with-glibc2.31 2023-03-24 14:48:57

- *** --- * --- 

- ** ---------- [config]

- ** ---------- .> app:         tasks:0x7f85b3716350

- ** ---------- .> transport:   redis://archivist-redis:6379//

- ** ---------- .> results:     disabled://

- *** --- * --- .> concurrency: 12 (prefork)

-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)

--- ***** ----- 

 -------------- [queues]

                .> celery           exchange=celery(direct) key=celery

                

[tasks]

  . check_reindex

  . download_pending

  . home.tasks.download_single

  . home.tasks.extrac_dl

  . home.tasks.index_channel_playlists

  . home.tasks.re_sync_thumbs

  . home.tasks.rescan_filesystem

  . home.tasks.run_manual_import

  . home.tasks.run_restore_backup

  . home.tasks.subscribe_to

  . run_backup

  . thumbnail_check

  . update_subscribed

  . version_check

[2023-03-24 14:48:58,059: INFO/MainProcess] Connected to redis://archivist-redis:6379//

[2023-03-24 14:48:58,062: INFO/MainProcess] mingle: searching for neighbors

[2023-03-24 14:48:59,069: INFO/MainProcess] mingle: all alone

[2023-03-24 14:48:59,074: INFO/MainProcess] celery@8b78e4f9848a ready.

[pid: 45|app: 0|req: 1/1] 172.22.0.1 () {42 vars in 915 bytes} [Fri Mar 24 14:49:00 2023] GET / => generated 143 bytes in 88 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)

[pid: 45|app: 0|req: 2/2] 172.22.0.1 () {42 vars in 915 bytes} [Fri Mar 24 14:49:01 2023] GET / => generated 143 bytes in 6 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)

[pid: 45|app: 0|req: 3/3] 172.22.0.1 () {42 vars in 915 bytes} [Fri Mar 24 14:49:10 2023] GET / => generated 143 bytes in 6 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)

[pid: 45|app: 0|req: 4/4] 172.22.0.1 () {42 vars in 915 bytes} [Fri Mar 24 14:49:35 2023] GET / => generated 143 bytes in 6 msecs (HTTP/1.1 400) 5 headers in 186 bytes (1 switches on core 0)`

**Comment by bbilly1** [comment]
Looks like it recovered? At least looks like the application started up? You can also show more debug info by setting a `DJANGO_DEBUG=True` environment variable to the Tube Archivist container to see where this 400 error is coming from.

Future reference use triple back tics \``` to format text for easy readability.

**Comment by vyadav33e** [comment]
TA logs after enabling Django Debugging

```
snapshot: policy is set.

snapshot: last snapshot is up-to-date

[MIGRATION] set default vid_type

    no videos needed updating in ta_video

    no videos needed updating in ta_download

[uWSGI] getting INI configuration from uwsgi.ini

*** Starting uWSGI 2.0.21 (64bit) on [Fri Mar 24 15:06:50 2023] ***

compiled with version: 10.2.1 20210110 on 04 March 2023 15:48:28

os: Linux-5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2

nodename: 7510a119ca3d

machine: x86_64

clock source: unix

detected number of CPU cores: 12

current working directory: /app

writing pidfile to /tmp/project-master.pid

detected binary path: /root/.local/bin/uwsgi

!!! no internal routing support, rebuild with pcre support !!!

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

your memory page size is 4096 bytes

detected max file descriptor number: 1048576

lock engine: pthread robust mutexes

thunder lock: disabled (you can enable it with --thunder-lock)

uwsgi socket 0 bound to TCP address :8080 fd 3

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

Python version: 3.10.9 (main, Feb  4 2023, 11:55:23) [GCC 10.2.1 20210110]

*** Python threads support is disabled. You can enable it with --enable-threads ***

Python main interpreter initialized at 0x558c6c411be0

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

your server socket listen backlog is limited to 100 connections

your mercy for graceful operations on workers is 60 seconds

mapped 154032 bytes (150 KB) for 1 cores

*** Operational MODE: single process ***

celery beat v5.2.7 (dawn-chorus) is starting.

WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x558c6c411be0 pid: 22 (default app)

uWSGI running as root, you can use --uid/--gid/--chroot options

*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 

*** uWSGI is running in multiple interpreter mode ***

spawned uWSGI master process (pid: 22)

spawned uWSGI worker 1 (pid: 42, cores: 1)

/root/.local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is

absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(

__    -    ... __   -        _

LocalTime -> 2023-03-24 15:06:51

Configuration ->

    . broker -> redis://archivist-redis:6379//

    . loader -> celery.loaders.app.AppLoader

    . scheduler -> celery.beat.PersistentScheduler

    . db -> /celerybeat-schedule

    . logfile -> [stderr]@%INFO

    . maxinterval -> 5.00 minutes (300s)

[2023-03-24 15:06:51,211: INFO/MainProcess] beat: Starting...

 

 -------------- celery@7510a119ca3d v5.2.7 (dawn-chorus)

--- ***** ----- 

-- ******* ---- Linux-5.19.0-35-generic-x86_64-with-glibc2.31 2023-03-24 15:06:51

- *** --- * --- 

- ** ---------- [config]

- ** ---------- .> app:         tasks:0x7f042caa1ff0

- ** ---------- .> transport:   redis://archivist-redis:6379//

- ** ---------- .> results:     disabled://

- *** --- * --- .> concurrency: 12 (prefork)

-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)

--- ***** ----- 

 -------------- [queues]

                .> celery           exchange=celery(direct) key=celery

                

[tasks]

  . check_reindex

  . download_pending

  . home.tasks.download_single

  . home.tasks.extrac_dl

  . home.tasks.index_channel_playlists

  . home.tasks.re_sync_thumbs

  . home.tasks.rescan_filesystem

  . home.tasks.run_manual_import

  . home.tasks.run_restore_backup

  . home.tasks.subscribe_to

  . run_backup

  . thumbnail_check

  . update_subscribed

  . version_check

[2023-03-24 15:06:51,618: INFO/MainProcess] Connected to redis://archivist-redis:6379//

[2023-03-24 15:06:51,619: INFO/MainProcess] mingle: searching for neighbors

[2023-03-24 15:06:52,625: INFO/MainProcess] mingle: all alone

[2023-03-24 15:06:52,654: WARNING/MainProcess] /root/.local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory

            leak, never use this setting in production environments!

  warnings.warn('''Using settings.DEBUG leads to a memory

[2023-03-24 15:06:52,654: INFO/MainProcess] celery@7510a119ca3d ready.
```

**Comment by bbilly1** [comment]
looks good. So everything is working?

**Comment by vyadav33e** [comment]
Yes everything is working now that I used the ip of my pc. It doesn't work with 0.0.0.0:8000 or 127.0.0.1:8000
Thanks now will try setting up on unraid

**Comment by vyadav33e** [comment]
However it cannot find videos stored.

And on my unraid setup it still says waiting for ES thought I updated config

**Comment by vyadav33e** [comment]
Looks like unraid has write issue
```{"@timestamp":"2023-03-24T10:03:02.752Z", "log.level":"ERROR", "message":"fatal exception while booting Elasticsearch", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.bootstrap.Elasticsearch","elasticsearch.node.name":"9c3e0e330814","elasticsearch.cluster.name":"docker-cluster","error.type":"java.lang.IllegalStateException","error.message":"failed to obtain node locks, tried [/usr/share/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?","error.stack_trace":"java.lang.IllegalStateException: failed to obtain node locks, tried [/usr/share/elasticsearch/data]; maybe these locations are not writable or multiple nodes were started on the same data path?\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:285)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.node.Node.<init>(Node.java:478)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.node.Node.<init>(Node.java:322)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.bootstrap.Elasticsearch$2.<init>(Elasticsearch.java:214)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.bootstrap.Elasticsearch.initPhase3(Elasticsearch.java:214)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:67)\nCaused by: java.io.IOException: failed to obtain lock on /usr/share/elasticsearch/data\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:230)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:198)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:277)\n\t... 5 more\nCaused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/node.lock\n\tat java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)\n\tat java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)\n\tat java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:181)\n\tat java.base/java.nio.channels.FileChannel.open(FileChannel.java:304)\n\tat java.base/java.nio.channels.FileChannel.open(FileChannel.java:363)\n\tat org.apache.lucene.core@9.4.2/org.apache.lucene.store.NativeFSLockFactory.obtainFSLock(NativeFSLockFactory.java:112)\n\tat org.apache.lucene.core@9.4.2/org.apache.lucene.store.FSLockFactory.obtainLock(FSLockFactory.java:43)\n\tat org.apache.lucene.core@9.4.2/org.apache.lucene.store.BaseDirectory.obtainLock(BaseDirectory.java:44)\n\tat org.elasticsearch.server@8.6.2/org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:223)\n\t... 7 more\n"}

** Press ANY KEY to close this window ** 
```

**Comment by bbilly1** [comment]
Maybe you have seen by now, permission issues is documented in the readme here: https://github.com/tubearchivist/tubearchivist#permissions-for-elasticsearch

And there are also more specific unraid instructions here: https://github.com/tubearchivist/tubearchivist/wiki/Installation#unraid

In any case, looks like it's working as intended and you can take it from here.
