### ISSUE TITLE
[Feature Request]: be able to rename folder where channel video's are stored

### ISSUE THREAD

**Issue by NimdaBE** [tubearchivist/tubearchivist#461]
### Already implemented?

- [X] I have read through the [docs](https://docs.tubearchivist.com/).
- [X] I understand the [scope](https://docs.tubearchivist.com/faq/) of this project and am aware of the [known limitations](https://github.com/tubearchivist/tubearchivist#known-limitations) and my idea is not already on the [roadmap](https://github.com/tubearchivist/tubearchivist#roadmap).

### Your Feature Request

Hello,

it would be nice to be able to rename the folder where the videos of a specific channel are stored. My current issue is with a channel which name ends on a dot (for example "channelname inc. ")

Because TA uses the channelname as foldername, and thus uses the dot in the foldername, this causes issues in Windows environments. I run TA on a Linux+Docker machine and i sync my media with syncthing to a Windows machine (for media consumption and backup reasons) but this specific channel folder won't sync.

If we were able to set a custom foldername for a channel instead of using the channelname as foldername this would be resolved.

many thanks for the hard work

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
you saw the template, do we really need to specify not to overwrite the template? other projects immediately ban these people...

you saw the known limitations, you saw the duplicate issue already open. 

windows shouldn't have a problem with periods at the end of a folder, if syncthing fails, you'll have to address that with them.

**Comment by NimdaBE** [comment]
I searched and I did not find a duplicate issue, that is why I opened this. If you can point me to the duplicate issue I can follow up from there.

If I was using TA on docker on Windows I would have the same issue (I guess TA wouldn't even be able to download the video). I was merely explaining how I found out about this and it was syncthing that mentioned that windows cannot handle dots and spaces at the end of folder names...

**Comment by PhuriousGeorge** [comment]
> edit: looks like windows indeed has a problem with a dot at the end of the folder name, you might want to zip the folder first for example, or any other workaround.

> windows cannot handle dots and spaces at the end of folder names...

I think closing this was a bit pre-mature.  While the title (enable renaming) of the request may not be the ultimate solution (and triggered @bbilly1 ), @NimdaBE brought up a real problem/bug that should be addressed.  Can we not at least ensure folder naming does not contain periods at the end to avoid issues with Windows?

This may be being worked on with some of the refactoring, but the underlying undesired result is a bug when working with Windows.

**Comment by NimdaBE** [comment]
Yeah, maybe my topic name wasn't chosen the best, but i found the first response a bit harsh... I just couldn't find another topic that discussed Windows + invalid folder characters. Maybe there is, maybe there isn't, but i did search...

As an example, this is a channel that causes issues: https://youtube.com/@iZotopeOfficial

**Comment by bbilly1** [comment]
Yeah, sorry about that. It was the changing of the template, we had that before from folks who just wanted to push their ideas through. The duplicate part is the flexible naming structure, that's what we had here countless of times.

OK, let's move forward, please verify the problem with steps to reproduce, is that a Docker desktop and/or WSL problem, is there a difference? Then open a new bug report with your findings, then we can go from there.

**Comment by NimdaBE** [comment]
It's not a docker problem, it's a windows problem... And I know, it's only for those rare channels on YouTube whose name happens to end in a dot.

I use docker on Linux, so it downloads just fine as Linux can handle those foldernames. Because TA uses the channelname as foldername any interaction with windows will cause issues. In my case it's trying to backup the folders to a windows machine. Even copying the folder to an external drive and using this drive on a windows machine will cause windows not being able to open the folder. There is no more reproducing to it. It's a naming issue.

**Comment by bbilly1** [comment]
The question that needs reproducing and verifying is if Tube Archivist works with docker on Windows, with channel names ending in a dot.

For backup and syncing or anything else you want to do with it, I'm sure there are many workarounds for these edge cases, that is not a primary concern of this project.
