### ISSUE TITLE
[Feature Request]: Option to skip register backup repo at boostrap

### ISSUE THREAD

**Issue by MichaelKirgus** [tubearchivist/tubearchivist#462]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

In my first attempt to set up this appliance, I tried to use my existing Elasticsearch cluster (13 nodes).
This fails because on startup the container wants to register a new repo to back up the indexes.
Unfortunately, this leads to the container not being started.
However, a powerful backup plan or strategy is usually already configured for such a multi-node instance.

The backup of the index can be switched off in the settings. Why not build in a way to skip this right at the first launch?
The user is then of course responsible for backing up his data.

I would like such a function for the container bootstrap process.
An idea here would be an optional environment variable, such as "SKIP_REGISTER_ES_REPO", with which this process is skipped.
Alternatively, simply do not let the start process abort, but issue a warning and then refer to the unsuccessfully registered backup repository in the settings.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
v0.4.2 brings additional configuration options to set where to store the snapshots with a `ES_SNAPSHOT_DIR` env var. This should cover custom setups like that.
