### ISSUE TITLE
[Installation]: Omit Elasticsearch?

### ISSUE THREAD

**Issue by IngwiePhoenix** [tubearchivist/tubearchivist#463]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

OpenWrt 22.03 on armv8/aarch64

### Your installation or setup question

I run on a FriendlyElec nanoPi R6s with 8GB of memory. Since it serves as my homeserver, figuring out how to best optimize memory usage is a little difficult. Just as an overview:

```

root@FriendlyWrt /s/s/photoprism# docker ps --format '{{.Names}}'
photoprism
photoprism-mariadb-1
tubearchivist
archivist-redis
archivist-es
homepage
homebox
homeassistant
tvheadend
shokoserver
jellyfin
trillium
```

It's quite crowded. :)

ElasticSearch consumes about 11.6% memory, according to Htop. I wondered: Is it possible to use TubeArchivist without ES - or if you know of a way to reduce it's memory footprint? I know that Java apps are typically larger in memory, but I also know that sometimes they can be optimized. :)

I mainly use TA to output to a folder read by Jellyfin - so I am basically using it as an automated means to download videos.

### Relevant log output

In addition to the docker output above, this is what my situation with all services - and Photoprism doing an import right now - looks like:

![htop](http://drachennetz.com/u/f1BYRi.png)

**Comment by bbilly1** [comment]
You can't just not install the database, that's not how any of this works. Also see FAQ.
