### ISSUE TITLE
[Bug]: youtube channelnames that end in invalid characters (like period) causes issues with windows folder names

### ISSUE THREAD

**Issue by NimdaBE** [tubearchivist/tubearchivist#464]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Windows

## Describe the bug

When you have a youtube channel which name ends in a period (like "inc.") or any other invalid character for folder names in Windows it causes a folder issue. When i download a video the downloading and processing all seems to be going well. I end up with a subfolder in my media folder that has the channelname but it ends on a period, a character that is invalid for windows folders. I cannot open the folder and i get the following error:

"location is unavailable. If the location is on this PC, make sure the device or drive is connected or the disc is inserted and then try again. If the location is on the network, make sure you 're connected to the network or Internet and then try again. If the location cannot be found, it might have been moved or deleted"

I cannot even rename or even delete this folder... I have no idea how TA was even able to create this folder with the invalid character, because i cannot create a folder manually with a period at the end...

## Steps To Reproduce

take for example this youtube channel: https://www.youtube.com/@iZotopeOfficial
add it to TA and download any video
it will download and create the folder "iZotope Inc." that you cannot access, rename or delete on windows

-----

side note: on linux this causes no issues. I already mentioned this behaviour in issue #461 where i suggested giving the option to be able to set a custom folder name for the media in TA (or be able te rename it). Another solution could be to automatically remove trailing invalid characters that can cause issues with folder names (periods, question marks,...)

Before i opened this new bug report i installed docker desktop on a windows machine, i took the docker-compose file from my linux environment and apart from a few volume changes in the compose file the rest is identical and ran it. 

Bonus points to who can help me rename or delete this invalid folder that is now stuck on my windows machine...
** update: to delete it on windows do the following in the command shell
         rd /s "\\?\C:\Docker\media\Annoying Folder."

### Relevant log output

```shell
na
```

**Comment by bbilly1** [comment]
at first glance, please confirm that you can delete the channel from the channel about page. and please also test the filesystem rescan functionality on the settings page.

**Comment by NimdaBE** [comment]
- downloading a video: folder is created
- delete channel from about page: folder is deleted
- rescan filesystem: "task completed succesfully" (both before and after deleting the channel)

So it seems that TA uses specific commands and is able to create and delete a folder with a trailing period on Windows. But for the Windows system and the file explorer this folder is inaccessible. 

[Microsoft Learning: Naming Files, Paths, and Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

I know my problem is a bit specific, but i can imagine there are other youtube channels which end in a period (like "company inc.").

I also tested it with a channelname that ends in a question mark (for example DidYouKnowGaming?) and here the folder is created without the question mark and thus accessible in Windows explorer...

**Comment by bbilly1** [comment]
Honestly, as we have established that Tube Archivist works without any problems with Docker on Windows, these folder names are handled correctly and all functionality of Tube Archivist works as expected, I'm inclined to accept that.

Changing how filepaths are build now is extremely tricky, see #419. I'm not prepared to tackle that in the foreseeable future, there are many more pressing items that will take priority.

I'm sorry, but I'm closing this as *won't fix*, if somebody want's to work on that, please reopen.
