### ISSUE TITLE
[Bug]: All videos of a channel queued instead of those from a playlist

### ISSUE THREAD

**Issue by janaxhell** [tubearchivist/tubearchivist#466]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

OpenMediaVault/Docker

## Describe the bug
This is the [Fueled by Ramen](https://www.youtube.com/@fueledbyramen/playlists) playlists page. Each playlist is a list of music videos by a certain artist. They all have different IDs. But if I try to add one of those to TA, ALL the Fueled by Ramen videos are added to Download Queue, not only those from the playlist I have selected.

I want to add these playlists because some artist (not only on Fueled by Ramen) doesn't have a personal page, but only a playlist on its distributor channel.

## Steps To Reproduce
Go to above URL, 
copy an artist playlist URL
add it to TA
Scan downloads

## Expected behavior
Only the videos from playlist should appear in download list
Instead ALL videos from the channel are added to download queue

### Relevant log output

```shell
[2023-04-18 10:00:22,277: WARNING/ForkPoolWorker-2] 4-TMAZBskOM: [192/201]: add to queue
[2023-04-18 10:00:23,293: WARNING/ForkPoolWorker-2] 4QDECwqKE0g: [193/201]: add to queue
[2023-04-18 10:00:24,234: WARNING/ForkPoolWorker-2] uJxWa-Z1P2k: [194/201]: add to queue
[2023-04-18 10:00:25,268: WARNING/ForkPoolWorker-2] B2FWgpfID3U: [195/201]: add to queue
[2023-04-18 10:00:26,274: WARNING/ForkPoolWorker-2] TUTDZOIdMbw: [196/201]: add to queue
[2023-04-18 10:00:27,324: WARNING/ForkPoolWorker-2] LkBxcmxWKAA: [197/201]: add to queue
[2023-04-18 10:00:28,688: WARNING/ForkPoolWorker-2] ARxWeeWWUfY: [198/201]: add to queue
[2023-04-18 10:00:29,806: WARNING/ForkPoolWorker-2] 5hkauBI-o2Q: [199/201]: add to queue
[2023-04-18 10:00:31,364: WARNING/ForkPoolWorker-2] eCeBNwBUkcI: [200/201]: add to queue
[2023-04-18 10:00:32,352: WARNING/ForkPoolWorker-2] IzKK9_wH5EA: [201/201]: add to queue
[2023-04-18 10:00:33,463: WARNING/ForkPoolWorker-2] 1364ab95-3ead-4555-9cd5-538eaaa4b493 success callback
[2023-04-18 10:00:33,467: INFO/ForkPoolWorker-2] Task extract_download[1364ab95-3ead-4555-9cd5-538eaaa4b493] succeeded in 213.46101084101247s: None
```

### Anything else?

I have set TA to scan the last 200 videos, in most cases it covers the whole production of an artist. For Fueled by Ramen this cannot work because all the videos of the channel are way more than 200, so single artist might have videos that are beyond the 200 threshold. Maybe that confuses the parser? Maybe an artist has the first 5 videos below 200 and the rest over 200 because they are older and this makes TA scan the whole archive of the channel?

**Comment by bbilly1** [comment]
This sounds like a misunderstanding between subscribing and downloading, refere to the docs for clarification.

It's unclear from your log output, but I assume you copy a video ID instead of the playlist ID? hence you subscribe to the channel instead of the playlist. again, docs has you covered.

**Comment by janaxhell** [comment]
I am not copying a video ID, I'm smart enough to tell a video from a playlist and subscribing from downloading.

I think I have identified the issue.
I have tried the same procedure on Napalm Records and it worked fine, only the videos of a playlist were added.

Go to this page https://www.youtube.com/@napalmrecords/playlists

If you right click on any **playlist Title**, like i.e "Delain - Music Videos", you get a link in this form
https://www.youtube.com/watch?v=U5W2dBQHpxI&list=PLidIjcybOMhx7Fp0eUYJFZhkmUFt4n7yM

If you right click on the line below where it says **View Full Playlist**, you get a link in this form
https://www.youtube.com/playlist?list=PLidIjcybOMhx7Fp0eUYJFZhkmUFt4n7yM

The ID is the same and they are both **playlists**. 
BUT, if you subscribe using the first format OR the ID alone, ALL the videos of the channel will be added to download queue and NO playlist will be added to TA.
If you use the second format, the playlist will be added and only its videos will be added to download queue.

**Comment by janaxhell** [comment]
Ok, I was looking at this page [https://docs.tubearchivist.com/playlists/](https://docs.tubearchivist.com/playlists/) and thought that was all about playlists.

**Comment by bbilly1** [comment]
It's all connected. :-)

But you are not wrong, we should consolidate that. I've opened a separate issue on the docs repo, if you want to work on that: https://github.com/tubearchivist/docs/issues/7

Closing this here for now.

**Comment by janaxhell** [comment]
You mean explaining about this Thumbnail vs Play Full List thing? How do I do that? I don't see any Edit button/link in the Wiki linked.. BTW should I just use the above example and generalize it in the Playlist page?
