### ISSUE TITLE
[Bug]: Can not kill download queue, only stop after next download

### ISSUE THREAD

**Issue by Stefomat** [tubearchivist/tubearchivist#468]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Debian 11

## Describe the bug
Since the update to 0.3.5 there is no kill button in the download queue anymore. There is only the stop button, which ends the queue after the current download. I did not find any hint in the changelog that this is an intended change.
## Steps To Reproduce
Install version 0.3.5, queue some videos and then try to find the kill button.
## Expected behavior
There should be a kill button that cancels the current download and stops the queue.

### Relevant log output

```shell
n/a
```

**Comment by bbilly1** [comment]
Known issue: https://docs.tubearchivist.com/downloads/#download-queue

Currently broken with the new task backend, will hopefully be back in the future.
