### ISSUE TITLE
[Feature Request]: Accept members-only/paid-content playlists

### ISSUE THREAD

**Issue by mglinski** [tubearchivist/tubearchivist#470]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

I cannot currently add members-only playlists to my TubeArchiver install due to members only playlists having a different uuid length then the currently accepted lengths of `34, 18`. The playlist I have been testing with has a UUID length of `26`. Otherwise it is a normal YouTube playlist, just with protected content that can only be accessed with a youtube account that is paying for that access.

## Describe the solution you'd like

I would like to be able to add members only playlists to Tube Archiver so they can be archived locally on my machine for later viewing.

## Additional context

I have submitted a draft PR for this feature change here: https://github.com/tubearchivist/tubearchivist/pull/469

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Very nice! Thanks for looking into that, wasn't aware that there are other playlist ID lengths out there.
