### ISSUE TITLE
[Bug][HOTFIX]: Stream metadata extraction failes for video files where the audio doesn't have bitrate

### ISSUE THREAD

**Issue by Jay4242** [tubearchivist/tubearchivist#476]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux, Ubuntu 22.04.2 LTS, docker-compose

## Describe the bug
Upgraded from 0.3.5 to 0.3.6.
I run into the bitrate error pasted into the 'relevant log output' section.
## Steps To Reproduce
docker-compose pull && docker-compose up
## Expected behavior
TubeArchivist to run through the rescan as mentioned in the notes then eventually load up.

### Relevant log output

```shell
tubearchivist      | [MIGRATION] setup snapshots
tubearchivist      | snapshot: run setup
tubearchivist      | snapshot: repo ta_snapshot already created
tubearchivist      | snapshot: policy is set.
tubearchivist      | snapshot: last snapshot is up-to-date
tubearchivist      | [MIGRATION] index streams and media size
tubearchivist      |     start filesystem rescan
tubearchivist      |     progress 0/1708
tubearchivist      | Traceback (most recent call last):
tubearchivist      |   File "/app/manage.py", line 23, in <module>
tubearchivist      |     main()
tubearchivist      |   File "/app/manage.py", line 19, in main
tubearchivist      |     execute_from_command_line(sys.argv)
tubearchivist      |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
tubearchivist      |     utility.execute()
tubearchivist      |   File "/root/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
tubearchivist      |     self.fetch_command(subcommand).run_from_argv(self.argv)
tubearchivist      |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
tubearchivist      |     self.execute(*args, **cmd_options)
tubearchivist      |   File "/root/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
tubearchivist      |     output = self.handle(*args, **options)
tubearchivist      |   File "/app/config/management/commands/ta_startup.py", line 45, in handle
tubearchivist      |     self._mig_set_streams()
tubearchivist      |   File "/app/config/management/commands/ta_startup.py", line 178, in _mig_set_streams
tubearchivist      |     "streams": media.extract_metadata(),
tubearchivist      |   File "/app/home/src/index/video_streams.py", line 88, in extract_metadata
tubearchivist      |     self.process_stream(stream)
tubearchivist      |   File "/app/home/src/index/video_streams.py", line 98, in process_stream
tubearchivist      |     self._extract_audio_metadata(stream)
tubearchivist      |   File "/app/home/src/index/video_streams.py", line 126, in _extract_audio_metadata
tubearchivist      |     "bitrate": int(stream["bit_rate"]),
tubearchivist      | KeyError: 'bit_rate'
tubearchivist exited with code 1
```

### Anything else?

That's the tail end of the log, let me know if you need anything else regarding this.  
Thanks

**Comment by bbilly1** [comment]
tagged the wrong issue: https://github.com/tubearchivist/tubearchivist/commit/f848e73251d59de75671aeb97e08f064601a6042

If pushed an hotfix to deal with that, please pull again.

**Comment by bbilly1** [comment]
After some debugging on Discord, it looks like videos without a bit rate may be cases where `yt-dlp` failed download or where the streams didn't mix properly or there was a hiccup on YouTube at the time of download...

Whatever the reason, after completing the migration you'll be able to identify these videos:

Open a bash shell in the TA container, e.g.:
```bash
docker exec -it tubearchivist bash
```

Then from within the container query the index for videos with a bit rate of `0` (zero) like this:
```bash
curl -u elastic:$ELASTIC_PASSWORD -H "Content-Type: application/json" $ES_URL/ta_video/_search?pretty -d '{
  "size": 1000,
  "query": {
    "term": {
      "streams.bitrate": {
        "value": 0
      }
    }
  },
  "_source": ["media_url", "youtube_id"]
}'
```

You might want to download these videos again.

**Comment by Jay4242** [comment]
> after completing the migration
I think this is blocking the migration.
It's endlessly restarting.

> Whatever the reason
I do have an SMR drive in the mix.  The TubeArchive may not understand just how high-latency life can get.

**Comment by bbilly1** [comment]
the hot fix pushed will alow the migration to complete, defaulting the bitrate to 0, so you'll be able to identify these cases with the commands described above.

**Comment by Jay4242** [comment]
Okay, going to close this as idk if there's really anything to do other than sort out my archive.  I guess you can re-open it if you think it needs to open.

I appreciate the help, thanks.
