### ISSUE TITLE
[Bug]: Public "favorites" playlists don't identify as a playlists

### ISSUE THREAD

**Issue by ultrawyde** [tubearchivist/tubearchivist#484]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker on Ubuntu 22.04

## Describe the bug
When adding a "Favorites" playlist to the playlist subscription page, this error is returned: "add subscription: task failed"
In the console for the docker container, the following is shown:

`ValueError: FL<redacted> not of expected type playlist`

This appears to be due to the fact that "Favorites" playlist IDs start with "FL" rather than the expected "PL". 

## Steps To Reproduce
1. Go to playlists pages
2. Click Plus button
3. Paste a link to any user's public "Favorites" playlist.
4. Press subscribe
5. Error

## Expected behavior

"Favorites" playlists that are public should be handled like normal playlists.

### Relevant log output

```shell
[2023-06-11 11:19:51,194: INFO/MainProcess] Task subscribe_to[e5c39f0d-0b25-413c-85ef-3f52df7297e1] received

[2023-06-11 11:19:51,196: WARNING/ForkPoolWorker-2] subscribe_to create callback

[2023-06-11 11:19:51,202: WARNING/ForkPoolWorker-2] e5c39f0d-0b25-413c-85ef-3f52df7297e1 Failed callback

[2023-06-11 11:19:51,204: ERROR/ForkPoolWorker-2] Task subscribe_to[e5c39f0d-0b25-413c-85ef-3f52df7297e1] raised unexpected: ValueError('<redacted> not of expected type playlist')

Traceback (most recent call last):

  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task

    R = retval = fun(*args, **kwargs)

  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__

    return self.run(*args, **kwargs)

  File "/app/home/tasks.py", line 326, in subscribe_to

    SubscriptionHandler(url_str, task=self).subscribe()

  File "/app/home/src/download/subscriptions.py", line 339, in subscribe

    self.to_subscribe = Parser(self.url_str).parse()

  File "/app/home/src/ta/urlparser.py", line 26, in parse

    identified = self.process_url(parsed)

  File "/app/home/src/ta/urlparser.py", line 54, in process_url

    return self._validate_expected(youtube_id, "playlist")

  File "/app/home/src/ta/urlparser.py", line 74, in _validate_expected

    raise ValueError(

ValueError: FL<redacted> not of expected type playlist`
```

**Comment by bbilly1** [comment]
that is working as expected, please see the docs what personal playlists are implemented and accessible over your cookie: https://docs.tubearchivist.com/settings/#cookie

**Comment by ultrawyde** [comment]
I am using my imported cookie, it still does not work.

**Comment by bbilly1** [comment]
yes, as mentioned, please read the documentation linked above this describes what is implemented.

**Comment by ultrawyde** [comment]
This is zero explicit mention of the "Favorites" playlist in that document, only "watch later" and "liked videos".
And again, I have imported my cookie and checked to make sure it validated and still receive this error.

**Comment by ultrawyde** [comment]
I have found the issue, but not a viable solution just yet.

In urlparser.py, it determines whether the type of playlist based on the length of the parsed id_str.

`        len_id_str = len(id_str)
        if len_id_str == 11:
            item_type = "video"
        elif len_id_str == 24:
            item_type = "channel"
        elif len_id_str in (34, 26, 18):
            item_type = "playlist"
        else:
            raise ValueError(f"not a valid id_str: {id_str}")`

However, my favorites playlist ID is 24 characters long, therefore is parsed as a channel. I modified this section to return the item_type as playlist for strings of length 24, and now it can subscribe to this playlist.

The issue now is there will need to be a section that determines whether a 24 character ID is a playlist or a channel. The playlists still start with "list=", so I imagine this shouldn't be that hard to implement?

**Comment by ultrawyde** [comment]
Here's my proposed solution:
Instead of reworking the string length section, I modified the section that determines whether the ID starts with LL/WL, since this skips length check.
I've added FL in this check which resolves the issue, and used startswith since the FL IDs are 24 characters and not just "LL" or "WL". 
This should also prevent accidents if another ID included "FL" somewhere other than the beginning of the ID.

```
    def _find_valid_id(self, id_str):
        """detect valid id from length of string"""
        """Set prefix list for Watch Later, Liked videos, and Favorite videos playlists"""
        private_lists_prefix=["WL", "LL", "FL"]
        """Check if ID starts with appropriate prefixes above"""
        if id_str.startswith(tuple(private_lists_prefix)):
            return {"type": "playlist", "url": id_str}
```

**Comment by bbilly1** [comment]
> This is zero explicit mention of the "Favorites" playlist in that document, only "watch later" and "liked videos".

There seems to be a logical misunderstanding. The docs describe what is implemented, if it's not documented, it's not implemented. Therefore per account playlists "watch later" and "liked videos" playlists are implemented through the cookie, others are not.

I originally thought the `FL` is the whole playlist ID, but as it looks like you trimmed the rest from there? I was not able to find a favorites playlist in my account, some searching showed that google has removed that functionality some years ago, see [here](https://support.google.com/youtube/thread/12460749/where-are-my-favorites-playlist?hl=en) or [here](https://support.google.com/youtube/thread/46682218/the-favorite-playlist-is-missing?hl=en). I'm sure you'll find other mentions out there. 

I'd rather not mess with the url parser there, your solution seems to work from what I can see, but I'm sure now or at some point in the future somebody will find a playlist starting with an unexpected character that will mess that up.

So I suggest either create a new regular private/unlisted/public playlist in your account, call it "Favorites" or what ever or use the implemented watch later or liked videos playlists to accomplish what you want to do.

**Comment by ultrawyde** [comment]
`There seems to be a logical misunderstanding. The docs describe what is implemented, if it's not documented, it's not implemented.`

I understand now, my mistake was assuming this would already have a been a feature considering the favorites playlist was a default autogenerated playlist until a few years ago.

Regarding parsing for "FL", every favorites playlist starts with "FL" and then has a unique 22 characters after it. Considering all youtube playlists thus far follow a strict naming scheme (LL: liked vids, WL: watch later, FL: favorites, PL: playlist, you can actually find this on the wiki as well: https://youtube.fandom.com/wiki/Playlist) I find it really hard to believe youtube would deviate from this in the future and start putting FL at the beginning other types of IDs. Besides, earlier in the parser it makes a determination of "expected type" by checking the URL for "list". I can't think of a scenario where something could get past both checks incorrectly.

I think it would be pretty safe to include this minor change, but I won't push it. I've forked it and can push a PR if you'd consider it.

**Comment by bbilly1** [comment]
Had some time to think about that. As long as this is not coming officially from YouTube, I think we are better off sticking with our current implementation of detecting type from the length of the ID. 

There is already a lot of variables and assumptions in this project that I don't want to add to it unnecessarily. I suggest to use any of the outlined workaround above instead.
