### ISSUE TITLE
[Feature Request]: Add adopters to main site or docs

### ISSUE THREAD

**Issue by jonasrosland** [tubearchivist/tubearchivist#489]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Currently no adopters of TubeArchivist are displayed. It's common for larger open source projects to show adoption from external parties to help drive use cases and engagement.

## Describe the solution you'd like
Me and my team have implemented adopters for other projects, either as ADOPTERS.md or visible on the main site (Harbor)
* [Velero](https://github.com/vmware-tanzu/velero/blob/main/ADOPTERS.md)
* [Carvel](https://github.com/carvel-dev/carvel/blob/develop/ADOPTERS.md)
* [Harbor](https://goharbor.io/)

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by jonasrosland** [comment]
Something like this, perhaps?
<img width="1106" alt="image" src="https://github.com/tubearchivist/tubearchivist/assets/1690215/7d9e37b9-7e6a-465a-8d1e-ff63614c5bce">

**Comment by bbilly1** [comment]
probably difficult to establish who is an adopter. unlike other SaaS platforms, as a free and self-hosted project, there isn't really a way to know.

but I have been meaning to make a sponsorship tier that gets you your logo on the website, that would be nice!

**Comment by jonasrosland** [comment]
> probably difficult to establish who is an adopter
Yup! Which is why we've made it opt-in, as can be [seen here for instance](https://github.com/vmware-tanzu/velero/blob/main/ADOPTERS.md#adding-a-logo-to-veleroio). Organizations and companies add PRs themselves, or we help them with that. All open source software I and my team work on are self-hosted, just like TA.

**Comment by bbilly1** [comment]
will revisit that and implement a sponsor tier for that when creating a proper tubearchivist.com website. Closing here for now.
