### ISSUE TITLE
[Bug]: NFS share mount as youtube volume has incorrect owner

### ISSUE THREAD

**Issue by kriss6557** [tubearchivist/tubearchivist#493]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu 22.04.1 LTS / Docker version 20.10.22 

## Describe the bug
Hello, 
First congratulation for your good work and allow us manage our YouTube video collection. 
I have an issue using an NFS share for the YouTube volume. 
Folders created by TA have nobody as owner, then chown fails.

```
os.chown(new_folder, host_uid, host_gid)
PermissionError: [Errno 1] Operation not permitted: '/youtube/CREAPOLE'
```

 This doesn’t happen when using a folder of the host as the volume, only when using an NFS mount.

## Steps To Reproduce
**On the NFS server** (192.168.0.10), I have checked the attributes

```
cd /share
lsattr
--------------e----- ./youtube
ls -l 
drwxrwsrwx+  3 1002   users  4096 Jul  8 10:17 youtube 
```
Owner ID is **1002**
 
```
more /etc/exports 
 /export/share 192.168.0.20(fsid=8,rw,subtree_check,insecure)
```

**On the docker host (NFS client)**

The nfs share is mounted on the docker host (192.168.0.20) via fstab:
`192.168.0.10:/share /mnt/share nfs     defaults        0       0`

In docker-compose.yml: 
```
image: bbilly1/tubearchivist:v0.3.6
 	environment:           
          - HOST_UID=1002 <— uses the same UID as on the folder
          - HOST_GID=1000
	volume:
          - /mnt/share/youtube:/youtube
```

```
ls -l /mnt/share 
drwxrwsrwx  3     1002 users  4096 Jul  8 08:17 youtube/  
```
When downloading videos from TA, a folder by channel is created but the folder owner is **nobody instead of 1002**: 
```
ls -l /mnt/share/youtube 
drwxrwsrwx 2 nobody users 4096 Jul  8 07:14 CREAPOLE 
```
 Then TA tries to change ownership and fails as this is impossible to change even by root.  

-  When creating a folder from the host in the share, owner is ok: 
 `drwxrwsrwx 2 1002 users 4096 Jul  8 19:18 testHost/`

- When creating from inside the tubearchivist container, owner is nobody: 
`drwxrwsrwx 2 nobody users 4096 Jul  8 07:18 testTA/
`
## Expected behavior
I expect to see this instead:
`drwxrwsrwx 2 1002 users 4096 Jul  8 07:18 testTA/`

### Relevant log output

```shell
[2023-07-08 09:56:56,680: INFO/MainProcess] Task download_pending[c8cba84b-44b9-4577-aa6a-5b1956e12064] received
[2023-07-08 09:56:56,681: WARNING/ForkPoolWorker-1] download_pending create callback
[2023-07-08 09:56:56,914: WARNING/ForkPoolWorker-1] 1woNl-2sVaQ: Downloading video
[2023-07-08 09:57:00,830: WARNING/ForkPoolWorker-1] 1woNl-2sVaQ: get metadata from youtube
[2023-07-08 09:57:04,752: WARNING/ForkPoolWorker-1] UChbw_SBfIu7PSG77rOAl9uw: get metadata from es
[2023-07-08 09:57:05,107: WARNING/ForkPoolWorker-1] c8cba84b-44b9-4577-aa6a-5b1956e12064 Failed callback
[2023-07-08 09:57:05,112: ERROR/ForkPoolWorker-1] Task download_pending[c8cba84b-44b9-4577-aa6a-5b1956e12064] raised unexpected: PermissionError(1, 'Operation not permitted')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 193, in download_pending
    VideoDownloader(task=self).run_queue(auto_only=auto_only)
  File "/app/home/src/download/yt_dlp_handler.py", line 187, in run_queue
    self.move_to_archive(vid_dict)
  File "/app/home/src/download/yt_dlp_handler.py", line 373, in move_to_archive
    os.chown(new_folder, host_uid, host_gid)
PermissionError: [Errno 1] Operation not permitted: '/youtube/CREAPOLE'
```

**Comment by lamusmaser** [comment]
Thank you for the submission. We have previously identified this as a known issue with NFS and we do have a workaround listed [here](https://docs.tubearchivist.com/installation/docker-compose/#overview).

As noted: 
> The environment variables `HOST_UID` and `HOST_GID` allows Tube Archivist to `chown` the video files to the main host system user instead of the container user. Those two variables are optional, not setting them will disable that functionality. That might be needed if the underlying filesystem doesn't support `chown` like NFS.

Since this is an issue with NFS and how it interacts with TubeArchivist, we don't currently have a way to remediate the issue. We have asked for people who are knowledgeable in this area to help with resolving this issue.

**Comment by kriss6557** [comment]
ok thank you for your very prompt answer.
All files saved are now nobody:users
As per your link, you can change the owner on a subfolder of an NFS share, but when owner is set to nobody then you cannot change to another owner.

**Comment by tiritibambix** [comment]
I'm sorry for how uneducated I am on the subject, but does that mean I can't use an NFS mount with TA ?

**Comment by lamusmaser** [comment]
You can, you just have to follow the instructions previously provided or else it will have problems with copying the files after TA downloads them.

**Comment by tiritibambix** [comment]
I'm not sure to understand very well technical English, so correct me of I'm wrong.

I can just remove uid and gid variables and it should work ?

I tried that and TA just won't launch.

**Comment by tiritibambix** [comment]
I'm not sure to understand very well technical English, so correct me of I'm wrong.

I can just remove uid and gid variables and it should work ?

I tried that and TA just won't launch.
