### ISSUE TITLE
[Feature Request]: ability to scan private playlists if it makes sense

### ISSUE THREAD

**Issue by kriss6557** [tubearchivist/tubearchivist#494]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Hi,
This is not an issue but a wish to authenticate and scan/download private playlists

## Describe the solution you'd like
Google credentials need to be provided to TA. 
TA will use these credentials to access specific playlists

## Additional context
I don't know if this makes any sense for others, otherwise my playlists just need to go public, this is the workaround.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
This has already been implemented via the [cookie import feature](https://docs.tubearchivist.com/settings/#cookie). As noted, there is both a manual and automated method, depending on what you want to use.

As specifically noted:
> Importing your YouTube Cookie into Tube Archivist allows yt-dlp to bypass age restrictions, gives access to private videos and your watch later or liked videos.
