### ISSUE TITLE
[Feature Request]: Mark Playlist/Channel/etc. as Unwatched

### ISSUE THREAD

**Issue by Aeristoka** [tubearchivist/tubearchivist#495]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Describe the solution you'd like
Basically the title. The "Mark Watched" buttons are extremely handy. Requesting we also have "Mark Unwatched" to mark videos Unwatched en masse in the case we want to go back through and watch again (and track progress nicely).

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by helmutundarnold** [comment]
Actually I had the same problem. In my case the  container log shows:

` {"@timestamp":"2023-07-10T21:49:58.821Z", "log.level": "WARN", "message":"flood stage disk watermark [95%] exceeded on [BeYOEDxVT8Snrunq5aoT4g][7a4f6fca96b4][/usr/share/elasticsearch/data] free: 3.9gb[4.7%], all indices on this node will be marked read-only",`

Filesystem indeed showed 96% -  thanks to LVM I could extend, did a restart and now the problem has been solved.

May be it helps :-)

**Comment by Aeristoka** [comment]
> Actually I had the same problem. In my case the container log shows:
> 
> ` {"@timestamp":"2023-07-10T21:49:58.821Z", "log.level": "WARN", "message":"flood stage disk watermark [95%] exceeded on [BeYOEDxVT8Snrunq5aoT4g][7a4f6fca96b4][/usr/share/elasticsearch/data] free: 3.9gb[4.7%], all indices on this node will be marked read-only",`
> 
> Filesystem indeed showed 96% - thanks to LVM I could extend, did a restart and now the problem has been solved.
> 
> May be it helps :-)

That's not even remotely related to my Mark Unwatched feature request.

**Comment by lamusmaser** [comment]
Feature is noted, we'll wait to get a closer look at this until later. It might sit open for a while until we get the time to push through some of the backlog/roadmap items.

**Comment by bbilly1** [comment]
that's a good first issue to contribute to this project! Please make a PR implementing this.

**Comment by bbilly1** [comment]
that's now implemented in v0.4.2.
