### ISSUE TITLE
Limit the size (length) of a video

### ISSUE THREAD

**Issue by jimmisavage** [tubearchivist/tubearchivist#497]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
I'd like the ability to limit the legnth of a video - so it will ignore the video when scanning the channel/playlist (channel for my case use) if the video is longer that, say 40 minutes long. 

## Additional context
I use channels to download videos for the kids. This works great for most channels but some clump content together in really long videos - I don't want these videos so it would be great to just skip them. 

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
There are quite a few things planned to make this more configurable, e.g. in #189, but nobody wanted to take this on so far.

As you have seen, there is a multi year backlog of ideas for this project. Keeping this here, reach out if you want to work on this in the mean time.

**Comment by bbilly1** [comment]
This would be better implemented as part of a per channel customization of video/stream/shorts page size, this would allow you to ignore streams from some channel for example. doing this on a size level like this will not be reliable as yt-dlp detects size per stream, e.g. size of video stream or size of the audio stream, and doesn't know the total size the final file is going to be once it's merged, at least not before it's downloaded. 

Closing this as won't fix for now, in favor of more flexibility with per channel page sizes down the road.
