### ISSUE TITLE
[Bug]: Task failed : wrong channel ID detected on music video

### ISSUE THREAD

**Issue by hafx** [tubearchivist/tubearchivist#499]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux Ubuntu 22.04

## Describe the bug
I didn't find info about this issue here. 
It's why I create this bug because I don't understand what happened. 

Version used: 
- 0.3.6 (docker) 
- archivist-redis : latest
- archivist-es : latest

The first vid in the queue blocked all others and I had this error : **task failed** in the UI.

## Steps To Reproduce
- I had a lot of vid (110 videos) in queue to download. 
- Url of the vid : https://www.youtube.com/watch?v=9m6ogS57sc8 (I don't know if it matters and why this vid)

## Workaround 
- ignore this vid and TA was able to download all others in the queue. 

## Expected behavior
If this error appears, continue to download others in the queue. 

### Relevant log output

```shell
`[2023-07-18 20:46:09,373: WARNING/ForkPoolWorker-4] 465d87f9-0dbd-47f6-ad15-0eccbde57449 Failed callback
[2023-07-18 20:46:09,375: ERROR/ForkPoolWorker-4] Task download_pending[465d87f9-0dbd-47f6-ad15-0eccbde57449] raised unexpected: KeyError('thumbnails')
Traceback (most recent call last):
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/home/tasks.py", line 193, in download_pending
    VideoDownloader(task=self).run_queue(auto_only=auto_only)
  File "/app/home/src/download/yt_dlp_handler.py", line 178, in run_queue
    vid_dict = index_new_video(
  File "/app/home/src/index/video.py", line 430, in index_new_video
    video.build_json()
  File "/app/home/src/index/video.py", line 154, in build_json
    self._add_channel()
  File "/app/home/src/index/video.py", line 211, in _add_channel
    channel.build_json(upload=True, fallback=self.youtube_meta)
  File "/app/home/src/index/channel.py", line 50, in build_json
    self.process_youtube_meta()
  File "/app/home/src/index/channel.py", line 58, in process_youtube_meta
    self.youtube_meta["thumbnails"].reverse()
KeyError: 'thumbnails'`
```

**Comment by bbilly1** [comment]
I can reproduce that. The channel extraction fails. I think there is something strange going on, yt-dlp detects a wrong channel ID `UCf1weKUE9iUaTW7YEgR3qlA` which should be `UCVpJ6eGdknSR4mlExF1bytA`. Probably a music video artist vs producer thing.

Thanks for reporting, will need to see if we can find a work around for that.

**Comment by hafx** [comment]
No problem thanks to you.

**Comment by bbilly1** [comment]
hehe old issue, i know, but tested this again after looking into another channel id extraction issue. This now works without issues. Probably has been fixed in yt-dlp at some point in the past.

Closing this as complete.
