### ISSUE TITLE
[Bug] / [Improvement]: Missing video's on youtube error out Rescan Filesystem

### ISSUE THREAD

**Issue by RicardoCst** [tubearchivist/tubearchivist#501]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug

If Rescan Filesystem encounters a file that is removed on youtube, it cancels the Filesystem scan and errors out

## Steps To Reproduce

Rescan filesystem: have a video not be available on youtube anymore

## Expected behavior

Skipping the removed video and continue with Rescan Filesystem

### Relevant log output

```shell
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    | [2023-07-23 19:30:59,445: WARNING/ForkPoolWorker-4] ERROR: [youtube] mXczwPeUpFE: Video unavailable. This video has been removed by the uploader
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    | [2023-07-23 19:30:59,446: WARNING/ForkPoolWorker-4] https://www.youtube.com/watch?v=mXczwPeUpFE: failed to get info from youtube
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    | [2023-07-23 19:30:59,454: WARNING/ForkPoolWorker-4] e5cb0b9e-915b-4cf2-8130-5666f4e76986 Failed callback
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    | [2023-07-23 19:30:59,461: ERROR/ForkPoolWorker-4] Task rescan_filesystem[e5cb0b9e-915b-4cf2-8130-5666f4e76986] raised unexpected: ValueError('failed to get metadata for mXczwPeUpFE')
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    | Traceback (most recent call last):
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |     R = retval = fun(*args, **kwargs)
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |   File "/root/.local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |     return self.run(*args, **kwargs)
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |   File "/app/home/tasks.py", line 293, in rescan_filesystem
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |     Filesystem(task=self).process()
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |   File "/app/home/src/index/filesystem.py", line 136, in process
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |     self.add_missing()
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |   File "/app/home/src/index/filesystem.py", line 203, in add_missing
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |     index_new_video(youtube_id)
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |   File "/app/home/src/index/video.py", line 432, in index_new_video
tubearchivist_tubearchivist.1.9o8przvfl7na@megalodon    |     raise ValueError("failed to get metadata for " + youtube_id)
```

**Comment by RicardoCst** [comment]
I know its in the docs but it still should be handled differently, having to restart each time after deleting a file gets annoying.

**Comment by bbilly1** [comment]
This is an unsolvable problem for that task. If it doesn't have metadata, it can't succeed, hence the error thrown. Otherwise this would silently say in your filesystem and you'd be none the wiser that it didn't succeed.

You have the manual import task where you can provide metadata if you have it but as mentioned in the docs, this task is meant for cases where you have restored from yesterdays backup and you need to import a days worth of videos. Or you delete files from the filesystem and also want to delete them from the index.

This is not meant for a complete restore of the index, even though you *could* use it for that, with the mentioned caveat.

So ultimately this is working as documented and as expected, telling you exactly which file failed so you can deal with that separately.
