### ISSUE TITLE
[Docs]: two letter codes doesn't match with chinese subtitles

### ISSUE THREAD

**Issue by youngoris** [tubearchivist/tubearchivist#505]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

YT auto translated subtitles are important for non-english users, please help to make this feature happen. Thank you!

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by youngoris** [comment]
> that has been implemented for a long time. you checked that you have read the how to gide so you know that are expected to read the docs first before opening any issues here.

hold on! 
please make sure you understand the title before you close this feature request.
it's auto-translate subtitle, not the subtiles user created.
when there's only english or auto generated english subtile, auto-translate can be used to generated other language subtitles!

**Comment by bbilly1** [comment]
like this? https://docs.tubearchivist.com/settings/#subtitles

> Source Settings: User created subtitles are provided from the uploader and are usually the video script. Auto generated is from YouTube, quality varies, particularly for auto translated tracks.

**Comment by youngoris** [comment]
> like this? https://docs.tubearchivist.com/settings/#subtitles
> 
> > Source Settings: User created subtitles are provided from the uploader and are usually the video script. Auto generated is from YouTube, quality varies, particularly for auto translated tracks.
> 
> or what is `auto-translate`?

auto-translate subtitle is like this:
![2023-07-28 at 10 32 56](https://github.com/tubearchivist/tubearchivist/assets/20574134/642d9d26-b513-437a-83b2-6214159f3b12)

**Comment by bbilly1** [comment]
We are talking about the same thing. Add you preferred language(s) under *Subtitles download setting*, e.g. `en, de` for English and German, set source to include auto to also get the auto generated/translated subtitles and TA will grab them at download if it finds them.

See example screenshot with video in English translated to German. 

![Screenshot 2023-07-28 at 09-49-07 TA I used a MAC for 30 days and I’m glad it’s over](https://github.com/tubearchivist/tubearchivist/assets/35427372/d4c4f235-36a2-4df7-b00b-1596090c13fe)

**Comment by youngoris** [comment]
<img width="801" alt="image" src="https://github.com/tubearchivist/tubearchivist/assets/20574134/66ff47c5-b7b4-4f11-ba18-26da16d65039">
same settings but no auto-translate subtitle downloaded only english, don't know why.
my understand of the preferred language(s) under Subtitles is just suitable for user created subtitles. and the subtitle source settings only download the subtilte from the video generated which usually only english.

**Comment by bbilly1** [comment]
ah, looks like in the case of chinese you'll have to specify the variant too, e.g `zh-Hans`.

Looks like our docs are inaccurate here in the case of chinese, e.g. this gives the language codes:

```bash
yt-dlp --list-subs gVtjsd00fWo
```

most but not all are the two letter codes. I don't have the right fonts installed, but this downloads it for me:
![Screenshot 2023-07-28 at 10-27-19 TA LogJam Attack - Computerphile](https://github.com/tubearchivist/tubearchivist/assets/35427372/ed60d678-32b3-45fb-b670-f518c78d5eca)

Please make a PR in the docs and the the settings page markup to fix that.

**Comment by youngoris** [comment]
Thanks for solving this issue. I have test it successfully.
PR, done.

**Comment by bbilly1** [comment]
excellent, thanks for your addition, and please excuse my initial harsh response.
