### ISSUE TITLE
[Feature Request]: Human readable channel/video titles in file structure.

### ISSUE THREAD

**Issue by hadecake** [tubearchivist/tubearchivist#509]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
First of all, loving the 4.0 update.  Getting my library to work with JF was a breeze and opened up a lot of viewing options. That said, I can no longer navigate my library through the filesystem to find particular videos I'm looking for.  When my server goes down and I'm left with only a hard drive and a video player, navigating is an impossibility and my archive almost useless. 
## Describe the solution you'd like
ideally just using something like:
 channel [channel id]/video title [video id]
that way everything is human readable but the id information is still included.
## Additional context
sorry for this request, I'm sure it's immensely frustrating to get it after ages of people begging for the filesystem rework.
For example:
I go to work for 30 days at a time without internet where I will copy a chunk of videos to watch on a laptop while I'm out. I'm no longer able to do that.
I also keep my archive both to watch through the interface and to have an archive of media when power/internet goes down (which is regular here). it's essential that it is navigable without extra software/a server.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
Unfortunately, until we get additional people who can support naming structures that are different than what we chose for v0.4.0, this will have to be marked that we won't fix this. It is possible that sometime in the future we can add some level of human readable language to the channel and video names again, but it was currently unsupportable and we had too much disagreement on the naming schema that would be used.

There is some potential here, but it'll have to be discussed further and we'll need help to understand what will work best to support the largest amount of users (or have some level of capability to customize that allows tracking still).

**Comment by hadecake** [comment]
> Unfortunately, until we get additional people who can support naming structures that are different than what we chose for v0.4.0, this will have to be marked that we won't fix this. It is possible that sometime in the future we can add some level of human readable language to the channel and video names again, but it was currently unsupportable and we had too much disagreement on the naming schema that would be used.
> 
> There is some potential here, but it'll have to be discussed further and we'll need help to understand what will work best to support the largest amount of users (or have some level of capability to customize that allows tracking still).

10-4, appreciate the fast reply.
Is some kind of option/script to create empty txt documents named "id - video title" an option? That way the files actually used by ta stay the same but in the file system you can see the video title?

**Comment by bbilly1** [comment]
Any customization like that you can do through the API, but that's outside of the scope of this project.

**Comment by Cyph3r** [comment]
> Unfortunately, until we get additional people who can support naming structures that are different than what we chose for v0.4.0, this will have to be marked that we won't fix this. It is possible that sometime in the future we can add some level of human readable language to the channel and video names again, but it was currently unsupportable and we had too much disagreement on the naming schema that would be used.
> 
> There is some potential here, but it'll have to be discussed further and we'll need help to understand what will work best to support the largest amount of users (or have some level of capability to customize that allows tracking still).

No agreement on naming structure is required. It should (imho) be input fields that allow for variables such as:
channel
playlist
video name
video id
...etc...

No one needs to battle it out over naming convention. Make the ID a required part of the name. Parse it for internal use. Win.
My personal preference is: "channel - video name - id.mp4", represented possibly like: "%channel% - %video_name% - %video_id%".

**Comment by lamusmaser** [comment]
This is my expectation, and was the plan in my head, for the next step of the convention, but I have been busy with another project and we need someone who can build and work to maintain those as we get more requests. Because of the integrations that are being built out, we will also need to expose that configuration within the API, which could be fairly easily added.

Again, this isn't being ignored but we don't have the current resources to implement this. It will get done when someone steps up to implement it. Before that point, we needed to simplify.

**Comment by Cyph3r** [comment]
I'm not sure if this is a significant incentive, but I'll buy whoever does this a coffee.
Looking for this solution pushed to the docker plus some method/script to rename old filenames into new format without breaking anything.

**Comment by bbilly1** [comment]
you will want to do this outside of TA through the API with for example symlinks. Unlikely that we will implement this anytime soon.
