### ISSUE TITLE
[Bug]: Old (?) Playlist types are not supported and throw "not of expected type playlist"

### ISSUE THREAD

**Issue by EpicLPer** [tubearchivist/tubearchivist#512]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology DS916+

## Describe the bug
I have an old (~2010) Favorites playlist that Tube Archivist does not seem to recognize as a playlist. When I try to add it into the download queue it throws the following error: ```Task failed: FLUrRyZ5lFmkTHgCTNGE3bog not of expected type playlist```

## Steps To Reproduce
1. Simply try to add the following Playlist URL: https://www.youtube.com/playlist?list=FLUrRyZ5lFmkTHgCTNGE3bog

## Expected behavior
Subscription should be added.

### Relevant log output

```shell
2023-08-08 10:14:12,097: WARNING/ForkPoolWorker-2] WARNING: [youtube] unable to extract initial player response; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
2023-08-08 10:14:11,403: WARNING/ForkPoolWorker-2] 4YwoRFFiqsQ: [389/876]: add to queue
2023-08-08 10:14:09,159: WARNING/ForkPoolWorker-2] 2b_febT3kwg: [388/876]: add to queue
2023-08-08 10:14:06,378: WARNING/ForkPoolWorker-2] 3Uq0npMwH-E: [387/876]: add to queue
2023-08-08 10:14:00,711: WARNING/ForkPoolWorker-4] a860f631-b790-438b-9ca0-c05c6376c4ec return callback
ValueError: FLUrRyZ5lFmkTHgCTNGE3bog not of expected type playlist
    raise ValueError(
  File "/app/home/src/ta/urlparser.py", line 74, in _validate_expected
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self._validate_expected(youtube_id, "playlist")
  File "/app/home/src/ta/urlparser.py", line 54, in process_url
                 ^^^^^^^^^^^^^^^^^^^^^^^^
    identified = self.process_url(parsed)
  File "/app/home/src/ta/urlparser.py", line 26, in parse
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self.to_subscribe = Parser(self.url_str).parse()
  File "/app/home/src/download/subscriptions.py", line 339, in subscribe
    SubscriptionHandler(url_str, task=self).subscribe()
  File "/app/home/tasks.py", line 348, in subscribe_to
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.run(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
                 ^^^^^^^^^^^^^^^^^^^^
    R = retval = fun(*args, **kwargs)
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
Traceback (most recent call last):
[1;31m[2023-08-08 10:14:00,703: ERROR/ForkPoolWorker-4] Task subscribe_to[a860f631-b790-438b-9ca0-c05c6376c4ec] raised unexpected: ValueError('FLUrRyZ5lFmkTHgCTNGE3bog not of expected type playlist')
2023-08-08 10:14:00,673: WARNING/ForkPoolWorker-4] a860f631-b790-438b-9ca0-c05c6376c4ec Failed callback
2023-08-08 10:14:00,569: WARNING/ForkPoolWorker-4] subscribe_to create callback
[2023-08-08 10:14:00,564: INFO/MainProcess] Task subscribe_to[a860f631-b790-438b-9ca0-c05c6376c4ec] received
https://www.youtube.com/playlist?list=FLUrRyZ5lFmkTHgCTNGE3bog
```

### Anything else?

I know this is probably a "very edge-case" since it's a old-style playlist that, apparently, YouTube/Google discontinued a few years ago. Tho there's no easy way to just copy-paste about 5000 videos into a new playlist afaik, so it'd be a bit of a hassle to get them otherwise before they get deleted at some point.

**Comment by bbilly1** [comment]
looks like you found the duplicate issue #484 and generously gave it a thumbs down there already, very nice! :-)

In any case, that goes into detail that the application logic expects an ID length to identify what type if item that is. This is also documented [here](https://docs.tubearchivist.com/urls/).

If you just want to add the videos to TA, you could use standalone yt-dlp first to extract these IDs and pass them to the downloads form. If you really need them in a playlist, you could still automate that through the YouTube API to create a new playlist first, or maybe there are other tools out there that can do that.

**Comment by EpicLPer** [comment]
The downvote shouldn't be taken personally as I was just not really happy with the outcome of that issue, since there are a few old playlists still out there. I really like this project as a whole and it's similar to what I've been trying to accomplish via command line automations, where this project comes in really handy now :)

Maybe it would be possible to add an experimental option to add the detection of old playlists so people know it might break something, but the manual playlist ID download and adding them would also work, since I haven't used that playlist actively for years now anyways.

**Comment by bbilly1** [comment]
Something like that would do:
```bash
yt-dlp --flat-playlist --print id 'https://www.youtube.com/playlist?list=FLUrRyZ5lFmkTHgCTNGE3bog' > ids.txt
```

to generate an file called ids.txt. Then you can feed that to the queue, all at once, or maybe better something like 1k at a time. 

Easiest solution is usually best.

**Comment by EpicLPer** [comment]
> Something like that would do:
> 
> ```shell
> yt-dlp --flat-playlist --print id 'https://www.youtube.com/playlist?list=FLUrRyZ5lFmkTHgCTNGE3bog' > ids.txt
> ```
> 
> to generate an file called ids.txt. Then you can feed that to the queue, all at once, or maybe better something like 1k at a time.
> 
> Easiest solution is usually best.

Thanks! This worked like a treat :)
Sorry for the initial miscommunication, keep up the good work with this project.
