### ISSUE TITLE
[Feature Request]: Option to store playlist videos into subfolders that contain the playlist name

### ISSUE THREAD

**Issue by heldiho53** [tubearchivist/tubearchivist#513]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Describe the solution you'd like
Title should be pretty self explanatory.
## Additional context
Right now TA just downloads all the videos in the "root" channel folder. That isn't a problem per se in the gui as there you can watch each playlist individually. But for moving, copying watching the videos externally this isn't so great. Yt-dlp allows to download playlists into subfolders with the playlist name, so I think this shouldn't be too difficult to implement and would be enjoyed by many users.

**Comment by bbilly1** [comment]
please follow the "how to" that you have checked that you have read. 

there is no filesystem flexibility, that's known and doesn't need another reminder.

customizations like that you can do through the API.

**Comment by heldiho53** [comment]
>please follow the "how to" that you have checked that you have read.
> there is no filesystem flexibility,

"There is no flexibility in naming of the media files."
That's not the same thing as naming the sub folders. Also no filesystem flexibility isn't the same thing as naming of the media files. So yes I've read the how to. I just didn't interpret it in the way it was intended.

**Comment by RoninTech** [comment]
You might find this useful: https://github.com/RoninTech/ta-helper
It creates a set of mirror folders/files with human readable names (and some other features you might not care about).  Everything is symlinked to the original files so it doesn't add much disk usage.
