### ISSUE TITLE
[Feature Request]: Option to globally turn on indexing of playlists when subscribing to a channel

### ISSUE THREAD

**Issue by danieljue** [tubearchivist/tubearchivist#515]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
There has never been a time when I did not want to use the playlist of a site I archived with yt-dlp. Most large channels are useless without playlist organization.
## Describe the solution you'd like
A flag in the global settings that causes the playlists to be indexed whenever a new channel is subscribed to.  This at least provides the option of a sensible default.  
## Additional context
Right now the default is "false".

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
as you have read in the docs, you will only want to do this for channels where you care about playlists, there are a good amount of channels, which have a huge amount of mostly irrelevant playlists. if you activate that for channels like that, everytime you download a video from that channel, TA needs do go out and scan all playlists do check if that video needs to be added somewhere. that's very slow and you can easily see how this will create a lot of potentially useless requests.

that option is there intentionally only on a per channel basis to avoid that problem.
