### ISSUE TITLE
[Feature Request]: IPv6 support out of the box

### ISSUE THREAD

**Issue by coraxosm** [tubearchivist/tubearchivist#516]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

It's real pain in the ass to make it run in docker on ipv6.
UI also is far from perfect, clicking on video thumbnail and clicking on header leads to two completely different places.
Wasted half an hour searching how to delete videos. =)

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Some suggestions on how to make a better feature request:
- read the how to, ipv6 (container internal?) is probably not relevant for a wide range of users. 
- *Pain in the \*\*\**: be specific, what exactly that is part of this project makes it difficult to do this? As probably not many people need or want to use ipv6 for their LAN, the initiative would be on you to find the problem, offer solutions on how this could be improved without breaking existing instances.
- *Far from perfect*: Yes, only very few things are in this world, what does that mean? Again be specific how something could be done better, don't just complain without solutions, that is not at all a useful contribution to this project.
- When in doubt, the docs are your friend, e.g [general navigation](https://docs.tubearchivist.com/#general-navigation), or the little search bar on top there, if you type in there `delete video` this brings you to the video [detail page](https://docs.tubearchivist.com/video/) with all explanation, but I get it, sometimes I'd rather wast half an hour too, than to do a quick search through the docs.
