### ISSUE TITLE
[Bug]: "Download now" button restarts previous queue, does not prioritize intended video

### ISSUE THREAD

**Issue by danieljue** [tubearchivist/tubearchivist#520]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker, Windows

## Describe the bug
The download now button doesn't seem to work at all.
I do see in the logs, the "change status to priority", but it is not apparent in the download page's queue, even on refresh.

## Steps To Reproduce
Have a queue.  Mine is 8000 videos long.
Optional: stop processing of the queue, wait for current download to finish.

Go to some other page of the download queue, for example the last page.
Click "Download Now" on a video we'll call V.  The Download Now button disappears, as expected.

"change status to priority" is seen in the docker logs, 

However it proceeds to continue the old queue.
Refreshing the page shows the video V in the same spot it was, and the "Download Now" button is enabled.

## Expected behavior
I expect, when the "Download Now" button is pressed on a video in the queue, that it is moved to the front/top of the queue to be processed next.

I may have a subscription of 1000's of videos that is queued up, but there may be an important new one that I want to prioritize to be downloaded first without deleting the entire queue.

### Relevant log output

```shell
2023-08-20 14:20:00 tubearchivist    | [2023-08-20 14:20:00,067: WARNING/ForkPoolWorker-64] 835371e7-1415-431e-8cd3-300f7b552c26 return callback
2023-08-20 14:26:14 tubearchivist    | 4hzxx2zbkjg: change status to priority
2023-08-20 14:26:14 tubearchivist    | [2023-08-20 14:26:14,389: INFO/MainProcess] Task download_pending[406cf6f5-ade7-4af1-af7b-eb02b6c6b69e] received
2023-08-20 14:26:14 tubearchivist    | [2023-08-20 14:26:14,390: WARNING/ForkPoolWorker-64] download_pending create callback
2023-08-20 14:26:14 tubearchivist    | [2023-08-20 14:26:14,913: WARNING/ForkPoolWorker-64] NX-tdvLd0RA: Downloading video
```

**Comment by bbilly1** [comment]
I can't seem to reproduce that. E.g first example, have many videos in the queue, but queue is not running currently, then *download now* on a video with id `NdTLj-xcqGM` on last page:
```
tubearchivist    | NdTLj-xcqGM: change status to priority
tubearchivist    | [2023-08-21 20:43:56,944: INFO/MainProcess] Task download_pending[44210744-a530-4479-9634-50eada30df68] received
tubearchivist    | [2023-08-21 20:43:56,945: WARNING/ForkPoolWorker-4] download_pending create callback
tubearchivist    | [2023-08-21 20:43:56,986: WARNING/ForkPoolWorker-4] NdTLj-xcqGM: Downloading video
tubearchivist    | [2023-08-21 20:44:21,765: WARNING/ForkPoolWorker-4] NdTLj-xcqGM: get metadata from youtube
tubearchivist    | [2023-08-21 20:44:23,561: WARNING/ForkPoolWorker-4] UC5UAwBUum7CPN5buc-_N1Fw: get metadata from es
tubearchivist    | [2023-08-21 20:44:23,604: WARNING/ForkPoolWorker-4] NdTLj-xcqGM: get ryd stats
tubearchivist    | [2023-08-21 20:44:24,036: WARNING/ForkPoolWorker-4] NdTLj-xcqGM: get sponsorblock timestamps
tubearchivist    | [2023-08-21 20:44:24,566: WARNING/ForkPoolWorker-4] NdTLj-xcqGM-en: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:44:24,567: WARNING/ForkPoolWorker-4] NdTLj-xcqGM-en: get auto generated subtitles
tubearchivist    | [2023-08-21 20:44:24,567: WARNING/ForkPoolWorker-4] NdTLj-xcqGM-de: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:44:24,567: WARNING/ForkPoolWorker-4] NdTLj-xcqGM-de: get auto generated subtitles
tubearchivist    | [2023-08-21 20:44:27,432: WARNING/ForkPoolWorker-4] PLqmbcbI8U55E93XSDFQQ-ERtbr5TeKh8U: get metadata from es
tubearchivist    | [2023-08-21 20:44:27,435: WARNING/ForkPoolWorker-4] PLqmbcbI8U55E93XSDFQQ-ERtbr5TeKh8U: get metadata from youtube
tubearchivist    | [2023-08-21 20:44:28,983: WARNING/ForkPoolWorker-4] NdTLj-xcqGM: get comments
tubearchivist    | [2023-08-21 20:44:38,700: WARNING/ForkPoolWorker-4] NdTLj-xcqGM: upload comments
tubearchivist    | [2023-08-21 20:44:38,766: WARNING/ForkPoolWorker-4] 44210744-a530-4479-9634-50eada30df68 success callback
tubearchivist    | [2023-08-21 20:44:38,767: INFO/ForkPoolWorker-4] Task download_pending[44210744-a530-4479-9634-50eada30df68] succeeded in 41.82093821700073s: 'downloaded 1 videos.'
tubearchivist    | [2023-08-21 20:44:38,767: WARNING/ForkPoolWorker-4] 44210744-a530-4479-9634-50eada30df68 return callback
```

That downloads that single video, then exits as expected.

Second example, have the queue running, video `r6tH55syq0o` on the top of the queue is downloading, then change `cXlxMP9PU8I` from the last page to priority, you'll see the first video to finish, then straight to the prioritized, after that continue as before:
```
tubearchivist    | [2023-08-21 20:45:07,347: INFO/MainProcess] Task download_pending[241c63d1-595d-4ce9-97e2-ac00673d1db6] received
tubearchivist    | [2023-08-21 20:45:07,348: WARNING/ForkPoolWorker-4] download_pending create callback
tubearchivist    | [2023-08-21 20:45:07,395: WARNING/ForkPoolWorker-4] r6tH55syq0o: Downloading video
tubearchivist    | cXlxMP9PU8I: change status to priority
tubearchivist    | [2023-08-21 20:45:16,621: INFO/MainProcess] Task download_pending[90cb8c3e-0852-4a32-9f6e-3b8432d9f6c2] received
tubearchivist    | [2023-08-21 20:45:16,621: WARNING/ForkPoolWorker-2] download_pending create callback
tubearchivist    | [2023-08-21 20:45:16,623: WARNING/ForkPoolWorker-2] [task][download_pending] download queue already running
tubearchivist    | [2023-08-21 20:45:16,625: WARNING/ForkPoolWorker-2] 90cb8c3e-0852-4a32-9f6e-3b8432d9f6c2 success callback
tubearchivist    | [2023-08-21 20:45:16,626: INFO/ForkPoolWorker-2] Task download_pending[90cb8c3e-0852-4a32-9f6e-3b8432d9f6c2] succeeded in 0.003312441998787108s: None
tubearchivist    | [2023-08-21 20:45:16,626: WARNING/ForkPoolWorker-2] 90cb8c3e-0852-4a32-9f6e-3b8432d9f6c2 return callback
tubearchivist    | [2023-08-21 20:45:21,931: WARNING/ForkPoolWorker-4] r6tH55syq0o: get metadata from youtube
tubearchivist    | [2023-08-21 20:45:23,944: WARNING/ForkPoolWorker-4] UCsBjURrPoezykLs9EqgamOA: get metadata from es
tubearchivist    | [2023-08-21 20:45:23,981: WARNING/ForkPoolWorker-4] r6tH55syq0o: get ryd stats
tubearchivist    | [2023-08-21 20:45:24,396: WARNING/ForkPoolWorker-4] r6tH55syq0o: get sponsorblock timestamps
tubearchivist    | [2023-08-21 20:45:24,945: WARNING/ForkPoolWorker-4] r6tH55syq0o-en: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:45:24,945: WARNING/ForkPoolWorker-4] r6tH55syq0o-en: get auto generated subtitles
tubearchivist    | [2023-08-21 20:45:24,946: WARNING/ForkPoolWorker-4] r6tH55syq0o-de: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:45:24,946: WARNING/ForkPoolWorker-4] r6tH55syq0o-de: get auto generated subtitles
tubearchivist    | [2023-08-21 20:45:25,653: WARNING/ForkPoolWorker-4] cXlxMP9PU8I: Downloading video
tubearchivist    | [2023-08-21 20:45:33,613: WARNING/ForkPoolWorker-4] cXlxMP9PU8I: get metadata from youtube
tubearchivist    | [2023-08-21 20:45:36,084: WARNING/ForkPoolWorker-4] UCsBjURrPoezykLs9EqgamOA: get metadata from es
tubearchivist    | [2023-08-21 20:45:36,113: WARNING/ForkPoolWorker-4] cXlxMP9PU8I: get ryd stats
tubearchivist    | [2023-08-21 20:45:40,486: WARNING/ForkPoolWorker-4] cXlxMP9PU8I: get sponsorblock timestamps
tubearchivist    | [2023-08-21 20:45:40,928: WARNING/ForkPoolWorker-4] cXlxMP9PU8I-en: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:45:40,928: WARNING/ForkPoolWorker-4] cXlxMP9PU8I-en: get auto generated subtitles
tubearchivist    | [2023-08-21 20:45:40,928: WARNING/ForkPoolWorker-4] cXlxMP9PU8I-de: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:45:40,928: WARNING/ForkPoolWorker-4] cXlxMP9PU8I-de: get auto generated subtitles
tubearchivist    | [2023-08-21 20:45:41,768: WARNING/ForkPoolWorker-4] kxT8-C1vmd4: Downloading video
tubearchivist    | [task][241c63d1-595d-4ce9-97e2-ac00673d1db6]: received STOP signal.
tubearchivist    | [2023-08-21 20:45:47,351: WARNING/ForkPoolWorker-4] kxT8-C1vmd4: get metadata from youtube
tubearchivist    | [2023-08-21 20:45:48,749: WARNING/ForkPoolWorker-4] UCsBjURrPoezykLs9EqgamOA: get metadata from es
tubearchivist    | [2023-08-21 20:45:48,772: WARNING/ForkPoolWorker-4] kxT8-C1vmd4: get ryd stats
tubearchivist    | [2023-08-21 20:45:49,624: WARNING/ForkPoolWorker-4] kxT8-C1vmd4: get sponsorblock timestamps
tubearchivist    | [2023-08-21 20:45:50,237: WARNING/ForkPoolWorker-4] kxT8-C1vmd4: sponsorblock failed: 404
tubearchivist    | [2023-08-21 20:45:50,238: WARNING/ForkPoolWorker-4] kxT8-C1vmd4-en: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:45:50,238: WARNING/ForkPoolWorker-4] kxT8-C1vmd4-en: get auto generated subtitles
tubearchivist    | [2023-08-21 20:45:50,238: WARNING/ForkPoolWorker-4] kxT8-C1vmd4-de: get user uploaded subtitles
tubearchivist    | [2023-08-21 20:45:50,238: WARNING/ForkPoolWorker-4] kxT8-C1vmd4-de: get auto generated subtitles
tubearchivist    | [2023-08-21 20:45:52,019: WARNING/ForkPoolWorker-4] kxT8-C1vmd4: get comments
tubearchivist    | [2023-08-21 20:46:08,096: WARNING/ForkPoolWorker-4] kxT8-C1vmd4: upload comments
tubearchivist    | [2023-08-21 20:46:08,139: WARNING/ForkPoolWorker-4] r6tH55syq0o: get comments
tubearchivist    | [2023-08-21 20:46:16,599: WARNING/ForkPoolWorker-4] r6tH55syq0o: upload comments
tubearchivist    | [2023-08-21 20:46:16,640: WARNING/ForkPoolWorker-4] cXlxMP9PU8I: get comments
tubearchivist    | [2023-08-21 20:46:27,897: WARNING/ForkPoolWorker-4] cXlxMP9PU8I: upload comments
tubearchivist    | [2023-08-21 20:46:27,946: WARNING/ForkPoolWorker-4] 241c63d1-595d-4ce9-97e2-ac00673d1db6 success callback
tubearchivist    | [2023-08-21 20:46:27,947: INFO/ForkPoolWorker-4] Task download_pending[241c63d1-595d-4ce9-97e2-ac00673d1db6] succeeded in 80.59733924399916s: 'downloaded 3 videos.'
tubearchivist    | [2023-08-21 20:46:27,947: WARNING/ForkPoolWorker-4] 241c63d1-595d-4ce9-97e2-ac00673d1db6 return callback
```

Is anybody else able to reproduce that? Or any other input?

**Comment by danieljue** [comment]
I tried it again just now.  I've been letting it process a queue for a day or so.  Pressed stop (it still continues downloading of course--known issue), and then went to the last page in the queue and selected a file I want to prioritize.  Here's the log:


2023-08-22 02:23:33 archivist-redis  | 7:M 22 Aug 2023 06:23:33.000 * 100 changes in 300 seconds. Saving...
2023-08-22 02:23:33 archivist-redis  | 7:M 22 Aug 2023 06:23:33.001 * Background saving started by pid 822
2023-08-22 02:23:33 archivist-redis  | 822:C 22 Aug 2023 06:23:33.014 * DB saved on disk
2023-08-22 02:23:33 archivist-redis  | 822:C 22 Aug 2023 06:23:33.016 * RDB: 0 MB of memory used by copy-on-write
2023-08-22 02:23:33 archivist-redis  | 7:M 22 Aug 2023 06:23:33.101 * Background saving terminated with success
2023-08-22 02:23:37 tubearchivist    | [2023-08-22 02:23:37,336: WARNING/ForkPoolWorker-64] UCaTznQhurW5AaiYPbhEA-KA: get metadata from es
2023-08-22 02:23:56 tubearchivist    | [2023-08-22 02:23:56,793: WARNING/ForkPoolWorker-64] NVnlQ7KMGa8: Downloading video
2023-08-22 02:24:28 tubearchivist    | [task][406cf6f5-ade7-4af1-af7b-eb02b6c6b69e]: received STOP signal.
2023-08-22 02:24:55 tubearchivist    | xAiqX6utmYE: change status to priority
2023-08-22 02:24:55 tubearchivist    | Tue Aug 22 02:24:55 2023 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /api/download/xAiqX6utmYE/ (ip 172.19.0.1) !!!
2023-08-22 02:24:55 tubearchivist    | [2023-08-22 02:24:55,572: INFO/MainProcess] Task download_pending[1f74836a-7ec2-4ecb-9759-f21505508523] received
2023-08-22 02:24:55 tubearchivist    | [2023-08-22 02:24:55,573: WARNING/ForkPoolWorker-1] download_pending create callback
2023-08-22 02:24:55 tubearchivist    | [2023-08-22 02:24:55,605: WARNING/ForkPoolWorker-1] [task][download_pending] download queue already running
2023-08-22 02:24:55 tubearchivist    | [2023-08-22 02:24:55,616: WARNING/ForkPoolWorker-1] 1f74836a-7ec2-4ecb-9759-f21505508523 success callback
2023-08-22 02:24:55 tubearchivist    | [2023-08-22 02:24:55,624: INFO/ForkPoolWorker-1] Task download_pending[1f74836a-7ec2-4ecb-9759-f21505508523] succeeded in 0.043426765012554824s: None
2023-08-22 02:24:55 tubearchivist    | [2023-08-22 02:24:55,625: WARNING/ForkPoolWorker-1] 1f74836a-7ec2-4ecb-9759-f21505508523 return callback

**Comment by lamusmaser** [comment]
I can see the call come through, and since the download process was still in-progress, it properly flags it as still running here:
```
2023-08-22 02:24:55 tubearchivist    | [2023-08-22 02:24:55,605: WARNING/ForkPoolWorker-1] [task][download_pending] download queue already running
```

This is a safety mechanism to not let two download processes run simultaneously. Once the other download process is fully stopped, then it should let you download it now.

**Comment by danieljue** [comment]
I discovered a new condition in where the "download now" actually works as intended:
I had some files in the queue which encountered a download error (I don't think that the particular error mattered, but it was "ERROR: [download] Got error: <urlopen error [Errno -2] Name or service not known>. Giving up after 10 retries" )
I had maybe half a dozen of these errors in my queue and I figured I'd stop the docker instance and restart it.

So let the Queue start processing, and it starts from the first non-error video in the queue, which is fine.  While it was downloading a video, I tried the "download now" on one of the error videos.
To my delight, after it was done with the current download, it started on the newly prioritized one, and completed it just fine.

However when I try to do "download now" on any other (non errored) video in the queue, it seemingly gets ignored.  
Note that both show the task being received in the UI.
<img width="1152" alt="Untitled" src="https://github.com/tubearchivist/tubearchivist/assets/1234595/9bd1721a-2ea6-42e2-b269-d727cb087f77">

**Comment by bbilly1** [comment]
I think some of the confusion is coming from the auto start functionality, as in if everything is priority, nothing is priority. So we can reset autostart if you stop the queue, so this will become just a regular video, and should avoid any confusions after the fact.

**Comment by bbilly1** [comment]
that should now be improved in v0.4.1, please update.
