### ISSUE TITLE
[Bug]: Support NFS mounted directory from Synology NAS

### ISSUE THREAD

**Issue by justsomebody42** [tubearchivist/tubearchivist#523]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Kubernetes v1.26.4

## Describe the bug
On a Synology NAS a hidden folder with the name @eaDir is created. I don't know it's exact purpose, but gets recreated automatically on a regular basis.
Unfortunately, TA fails to start with the following error, if it's present.
Deleting the folder before restarting TA works fine as a workaround, but is quite cumbersome...

## Steps To Reproduce
Mount download folder via NFS from a Synology NAS.
I'm currently running TA in kubernetes and use this PV:

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: tubearchivist-data
    namespace: tubearchivist
    labels:
        volume: tubearchivist-data
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 10Gi
    nfs:
        server: 192.168.1.2
        path: "/volume1/video/tubeArchivist"
```

## Expected behavior
TA can start, even if a folder named @eaDir is present, but cannot be deleted by TA.
Maybe even ignore any folder that cannot be deleted during startup and only log a warning?

### Relevant log output

```shell
[5] clear leftover files from dl cache
clear download cache
Traceback (most recent call last):
  File "/app/manage.py", line 23, in <module>
    main()
  File "/app/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/config/management/commands/ta_startup.py", line 41, in handle
    self._clear_dl_cache()
  File "/app/config/management/commands/ta_startup.py", line 121, in _clear_dl_cache
    leftover_files = clear_dl_cache(config)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/home/src/ta/helper.py", line 116, in clear_dl_cache
    os.remove(to_delete)
IsADirectoryError: [Errno 21] Is a directory: '/cache/download/@eaDir'
```

**Comment by bbilly1** [comment]
Sounds good, we already have a ignore_filelist function, we can add that there.

**Comment by justsomebody42** [comment]
Thanks for the prompt feedback!
Looking forward to update to the next version without deleting the folder first 😉

**Comment by bbilly1** [comment]
that's now out in v0.4.1. please update.

**Comment by justsomebody42** [comment]
Did the update just now, worked like a charm!
Thanks a lot!
