### ISSUE TITLE
[Feature Request]: Hook system/run script before or after action

### ISSUE THREAD

**Issue by barrelltitor** [tubearchivist/tubearchivist#527]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
I currently have a bash script that handles quite a bunch of post processing, hardlinking files, some api calls etc

## Describe the solution you'd like
A hook system to be able to call a python script after an action

After a video is found/downloaded/deleted/viewed/etc, call a script with some environment variables/arguments/location of some json file with details of the video, as well as the action that happened, or maybe have a separate script for each action.

## Additional context

I'm a noob in python, and I haven't looked much at the code, but I think this might be pretty easily achievable with subprocess.run and a scripts/ folder

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
We have the apprise integration now, that's meant to use for things like that. You'll probably want to run external scripts like that from outside the container to be able to get access to whatever you need.

Also this project doesn't support modifying the *official* files, so you'll want to do this outside of the TA folder structure. If you need inspiration how you could set up a listener that can take apprise notifications, you could take a look of the jellyfin integration, that's doing just that: https://github.com/tubearchivist/tubearchivist-jf/blob/master/app/server.py.
