### ISSUE TITLE
[Bug]: Dead Link for Client Container for Sponsors.

### ISSUE THREAD

**Issue by Wh1t3Rose** [tubearchivist/tubearchivist#530]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

N/A

### Your Bug Report

Just become a sponsor. I love this project!

Unfortunately the link you provide to the Client Container install instructions does not work.

Can you please update the link?

![image](https://github.com/tubearchivist/tubearchivist/assets/4251482/c721a623-aaab-459d-b7cf-f83680f98b0e)
![image](https://github.com/tubearchivist/tubearchivist/assets/4251482/c33f32f4-c011-4f2a-bfc6-68204680d359)

### Relevant log output

```shell
N/A
```

**Comment by bbilly1** [comment]
very unfortunate, thanks for pointing it out. just in case you haven't found it yet: https://github.com/tubearchivist/members

**Comment by Wh1t3Rose** [comment]
No worries. Thank you for this amazing project. I've been using it for a year or so now and I am having a daughter in a month. This is project in combination with Plex/Jellyin is gonna be so handy when she gets older. 

Thanks for the link!
