### ISSUE TITLE
[Feature Request]: Modify download format in playlists

### ISSUE THREAD

**Issue by tehniemer** [tubearchivist/tubearchivist#532]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Some playlists I only want to download audio and not video. But other playlists or videos from that channel I want the video as well as the audio.

## Describe the solution you'd like
Add customizable download formats to playlists similar to how it's implemented in channels.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Playlist is just metadata in TA. All is organized through channels, so that wouldn't be possible. Particularly as a video can be in multiple playlists at the same time. 

Audio download is another thing, that's on the roadmap, that will happen at some point.

**Comment by tehniemer** [comment]
@bbilly1 will audio be able to be specified at the playlist level?

**Comment by bbilly1** [comment]
that's unclear at that point in time.

**Comment by tehniemer** [comment]
@bbilly1 I don't know if this helps development of TA or not, but this project has the option to download either video or audio streams of a playlist. Just thought I would throw that out there.

https://github.com/meeb/tubesync
