### ISSUE TITLE
[Feature Request]: can I save the mp4 files in video name instead of youtube ID?

### ISSUE THREAD

**Issue by dg9999cn** [tubearchivist/tubearchivist#534]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
can I save the mp4 files in video name instead of youtube ID like EViSmcCPK5g.mp4?
### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
read the how to before opening any issues here.

**Comment by Hussienfahmy** [comment]
could you please mention where is how to or provide a link for that section?
