### ISSUE TITLE
[Question] Documentation about ERROR

### ISSUE THREAD

**Issue by Dontkickmi22** [tubearchivist/tubearchivist#542]
Hi, thanks in advance.

Stuck at Validating download format, had to restart container to stop. 
Shows ERROR : The downloaded file is empty.

Wondering what that means, and how to proceed from there.

Got this from v.0.4.0 with ES 8.7.0
Now V0.4.1 with ES 8.9.0.

I got two machines hitting this, while others on v0.4.0 with ES 8.7.0 seems fine.

**Comment by lamusmaser** [comment]
Can you please reopen this using our template? This contains none of the necessary details to help.

**Comment by Dontkickmi22** [comment]
> Can you please reopen this using our template? This contains none of the necessary details to help.

Shall I file it under Bug?

**Comment by lamusmaser** [comment]
That probably seems appropriate.
