### ISSUE TITLE
[Bug]: Dead Wiki Link?

### ISSUE THREAD

**Issue by lue30499** [tubearchivist/tubearchivist#545]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
Version: v0.4.1
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux - Docker 24.0.5 on ubuntu 22.04.3 LTS

## Describe the bug
The link to the wiki page under the application tab and under the snapshot heading is pointing to:
`https://docs.tubearchivist.com/settings/#snapshots`

Screenshot attached below.

## Steps To Reproduce
Go to: "Settings" -> "Application" - Scroll to "Snapshots" -> Click on the hyperlink called "Wiki".
Observe 403 (As seen in screenshot below).

## Expected behavior
Go to: "Settings" -> "Application" - Scroll to "Snapshots" -> Click on the hyperlink called "Wiki".
Observe a loaded page.

### Relevant log output

```shell
N/A - External to the TA application itself.
```

### Anything else?

<img width="1426" alt="ta-wiki-403" src="https://github.com/tubearchivist/tubearchivist/assets/63104612/6eaa4cc3-47b2-4d28-b933-080bdf04181e">

**Comment by MerlinScheurer** [comment]
This has been fixed with https://github.com/tubearchivist/tubearchivist/pull/535
Just wait for the next release 😉

**Comment by bbilly1** [comment]
fixed in v0.4.2.
