### ISSUE TITLE
[Bug]: ERROR: The downloaded file is empty

### ISSUE THREAD

**Issue by Dontkickmi22** [tubearchivist/tubearchivist#548]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker on Raspberry Pi 4 Debian ES=8.9.0 TA=0.4.1

## Describe the bug
Download status bar stuck on validating download format. After manual stop button pushed, video thumbnail shows ERROR: The downloaded file is empty.

Multiple videos experiencing this issue when the original video link on youtube still valid. 
  

## Steps To Reproduce
Please add below link to your TA and download it. 
*removed

## Expected behavior
Should pass validating download format, then begins downloading, showing speed size time.

### Relevant log output

```shell
tubearchivist41  | [2023-09-11 20:57:08,181: INFO/MainProcess] Task download_pending[b9ab2687-c2b9-42f6-92d8-52051f298de1] received
tubearchivist41  | [2023-09-11 20:57:08,186: WARNING/ForkPoolWorker-4] download_pending create callback
tubearchivist41  | [2023-09-11 20:57:10,089: WARNING/ForkPoolWorker-4] *removed: Downloading video
tubearchivist41  | [2023-09-11 20:57:38,815: WARNING/ForkPoolWorker-4] ERROR: The downloaded file is empty
tubearchivist41  | [2023-09-11 20:57:38,816: WARNING/ForkPoolWorker-4] *removed: failed to download with message ERROR: The downloaded file is empty
```

### Anything else?

Thank you. 
Could this relates to yt-dlp issue? 
I experienced this from TA=0.4.0, ES=8.8.0, waited till update, still. 
I have another host shares this issue while multiple others on 0.4.0 and 8.8.0 have yet to.

**Comment by Ultr0n556** [comment]
I'm having this issue too, sometimes I get 403 errors, and sometimes it says the file is empty. I can't get anything to download.

**Comment by Ultr0n556** [comment]
Actually, I just did some testing on my own. I tried creating a new youtube account and importing the cookies using the browser extension and it got rid of my error. It may be some kind of account ban related issue? Try it and see if it works

**Comment by Dontkickmi22** [comment]
Appreciate your findings, my machines currently runs without cookies. I will try your method and report back.

**Comment by Dontkickmi22** [comment]
> Actually, I just did some testing on my own. I tried creating a new youtube account and importing the cookies using the browser extension and it got rid of my error. It may be some kind of account ban related issue? Try it and see if it works

Hi, does this solve other errors too? like 403? 500? 503?  Thanks

**Comment by Ultr0n556** [comment]
I think someone else mentioned that in another issue or on the discord, but there is no way I can think of. There may be other ways to fix this, I think it has to do with a change made on Youtube's end. It did solve the 403 error for me as well, I didn't see any 50x errors on mine. I did notice some 403 errors temporarily, but I refreshed the cookie and it worked. I agree that this is a far from ideal solution.

**Comment by Dontkickmi22** [comment]
> I think someone else mentioned that in another issue or on the discord, but there is no way I can think of. There may be other ways to fix this, I think it has to do with a change made on Youtube's end. It did solve the 403 error for me as well, I didn't see any 50x errors on mine. I did notice some 403 errors temporarily, but I refreshed the cookie and it worked. I agree that this is a far from ideal solution.

I disabled cookie, restarted my router to get another address. Works too.

**Comment by Dontkickmi22** [comment]
How do you go about re-downloading your 403s? I have hundreds of them and not wanting to do it manually. You know a better way to put them back to queue?

**Comment by lamusmaser** [comment]
Did they leave your queue? They should have remained and skipped if they were prevented from downloading previously. You'd see their error reason listed and a Download Queue would allow them to download again.

**Comment by Dontkickmi22** [comment]
> Did they leave your queue? They should have remained and skipped if they were prevented from downloading previously. You'd see their error reason listed and a Download Queue would allow them to download again.

Hi Thanks for your time. 

They still listed in download queue, but skipped when the download button is pushed again.
In another words, TA skips all the error-ed files and go straight to the "clean" ones.

**Comment by lamusmaser** [comment]
Was the previous download action stopped or killed before pressing the button? There can only be one running at a time.

**Comment by Dontkickmi22** [comment]
> Was the previous download action stopped or killed before pressing the button? There can only be one running at a time.

By the time I noticed, I've got a bunch of them already. At the end I had to kill to stop.

**Comment by bbilly1** [comment]
consolidating all yt-dlp errors in #522.

**Comment by Dontkickmi22** [comment]
> > Was the previous download action stopped or killed before pressing the button? There can only be one running at a time.
> 
> By the time I noticed, I've got a bunch of them already. It was as if TA got stuck there long enough to move on to next file, got same error and stuck there, moved on and stuck....so on... IIRC, stop button wouldn't cut it. So I had to restart host from portainer to stop. So yea, but I only killed it once.

Will go over below for the issue mentioned above. Looks like the solution what I have been looking for.

'''
https://docs.tubearchivist.com/advanced/#manual-yt-dlp-update

Erase errors from download queue[#](https://docs.tubearchivist.com/advanced/#erase-errors-from-download-queue)

Sometimes the download queue might have some videos that have errored due to rate limits. Videos that have errors won't be retried in a future download queue re-run unless you individually click "Download now" for each individual video. In order to bulk clear the errors from the download queue one needs to execute the following command from within the Tube Archivist container:

curl -X POST "$ES_URL/ta_download/_update_by_query?pretty" -u elastic:$ELASTIC_PASSWORD -H 'Content-Type: application/json' -d'
{
  "script": {
    "source": "ctx._source.message = null",
    "lang": "painless"
  },
  "query": {
    "match_all": {}
  }
}
'
'''
