### ISSUE TITLE
[Feature Request]: Disable CSRF Checking

### ISSUE THREAD

**Issue by AddoSolutions** [tubearchivist/tubearchivist#549]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Sort-of, several issues when behind a reverse proxy

## Describe the solution you'd like
Ability to disable CSRF completely – this install is not publicly accessable and I don't really care about CSRF

## Additional context
I have a pretty complicated reverse proxy setup and I'd really like to be able to just disable CSRF entirely.  Is this supported if not where would I go about doing this?

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by AddoSolutions** [comment]
So I have a reverse docker reverse proxy hitting the app which is a docker container on another box.

The error:

> CSRF verification failed. Request aborted.
> Reason given for failure:
>     Origin checking failed - https://tubearchivist.mydomain.com:8123 does not match any trusted origins.


Docker config:

```
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
#      - HOST_UID=1000
#      - HOST_GID=1000
      - TA_HOST=10.1.2.3 tubearchivist.mydomain.com:8123 tubearchivist.mydomain.com:8123        # set your host name
      - TA_USERNAME=xxx           # your initial TA credentials
      - TA_PASSWORD=xxx              # your initial TA credentials
      - ALLOWED_HOSTS=[http://10.1.2.3:8000, https://tubearchivist.mydomain.com:8123, https://tubearchivist.mydomain.com, tubearchivist.mydomain.com]
      - ELASTIC_PASSWORD=xxxx         # set password for Elasticsearch
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://tubearchivist.mydomain.com:8123
      - TZ=America/New_York                 # set your time zone
      - DJANGO_DEBUG=True
```



nginx config:

```
# main server block
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    http2 on;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    server_name tubearchivist.mydomain.com;

    include {ssl config path}

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://10.1.2.3:8000;
    }
}

```

**Comment by lamusmaser** [comment]
Remove the port from the `TA_HOST` and restart the TA container. See if that allows the pass-through.

**Comment by AddoSolutions** [comment]
So I have it set as follows:

```
TA_HOST=10.1.2.3 tubearchivist.mydomain.com:8123 tubearchivist.mydomain.com:8123
```

Same error:

> Origin checking failed - https://tubearchivist.mydomain.com:8123/ does not match any trusted origins

**Comment by lamusmaser** [comment]
Ah, `https` as a prefix should be included. So, if update it to the following: 

`TA_HOST=10.1.2.3 https://tubearchivist.mydomain.com`

**Comment by AddoSolutions** [comment]
Just tried

```
TA_HOST=10.1.2.3 https://tubearchivist.mydomain.com
```

and also (just for kicks)...

```
TA_HOST=10.1.2.3 https://tubearchivist.mydomain.com:8123
```

Unfortunately, neither worked.  When I dug into it previously, it had something to do with all the port number changes and Django not liking that with it's CSRF processing...

**Comment by lamusmaser** [comment]
Based on your NGINX config, you should be accessing with https://tubearchivist.mydomain.com, no additional port number. Do you have s second proxy handling is connection to 8123?

**Comment by AddoSolutions** [comment]
Well, it's being NATed

**Comment by lamusmaser** [comment]
Can you attempt to hit it again and then post the TA logs? We should see that response come from TA. With that configuration, it should still work, as long as you are accessing via https://tubearchivist.mydomain.com:8123 and not another referenced domain to access through.

**Comment by AddoSolutions** [comment]
Logs:

```
tubearchivist      | Forbidden (Origin checking failed - https://tubearchivist.mydomain.com:8123/ does not match any trusted origins.): /login/
tubearchivist      | [pid: 41|app: 0|req: 1836/1836] 10.3.5.1 () {74 vars in 1388 bytes} [Wed Sep 13 18:00:38 2023] POST /login/ => generated 2579 bytes in 5 msecs (HTTP/1.0 403) 7 headers in 229 bytes (1 switches on core 0)
```

**Comment by MerlinScheurer** [comment]
Did you change the DJANGO_CSRF_TRUSTED_ORIGINS enviroment variable when you did the changes to TA_HOST?
removing port from both.

**Comment by AddoSolutions** [comment]
> Did you change the `DJANGO_CSRF_TRUSTED_ORIGINS` & `ALLOWED_HOSTS `enviroment variable when you did the changes to `TA_HOST`? removing port from both.

No – I will try that now with more detail on results

> From within the TA container, can you print out the environment variables and confirm that the TA_HOST is setting properly? It should have seen it come through.

```
# set
...
TA_HOST='TA_HOST=10.1.2.3 https://tubearchivist.mydomain.com'
...
```

**Comment by AddoSolutions** [comment]
> Did you change the `DJANGO_CSRF_TRUSTED_ORIGINS` & `ALLOWED_HOSTS `enviroment variable when you did the changes to `TA_HOST`? removing port from both.

Ok, trying this, will keep trying more...

```
TA_HOST=TA_HOST=10.1.2.3 https://tubearchivist.mydomain.com
ALLOWED_HOSTS=[http://10.1.2.3:8000, https://tubearchivist.mydomain.com]
DJANGO_CSRF_TRUSTED_ORIGINS=https://tubearchivist.mydomain.com
```

Result: CSRF verification failed. Request aborted  ... does not match any trusted origins.

**Comment by lamusmaser** [comment]
I mean, the value is incorrect, but that would only affect the 10.1.2.3 connection. 

[This](https://github.com/tubearchivist/tubearchivist/blob/8fa9e23c6ef3b24c96a385b810b86cc5f133892d/tubearchivist/config/settings.py#L36C8-L36C8) is the line that is affecting what you are doing. That calls the [ta_host_parser()](https://github.com/tubearchivist/tubearchivist/blob/8fa9e23c6ef3b24c96a385b810b86cc5f133892d/tubearchivist/home/src/ta/helper.py#L144-L163) function, which should be seeing it as you have it set. CSRF should allow it to connect based on that host being allowed, but I guess I would probably set it to be this:
`10.1.2.3 https://tubearchivist.mydomain.com https://tubearchivist.mydomain.com:8123`

See if that allows it to connect properly. There might be an issue with how both are handling the connection.

I would remove the other two environment variables for right now, as DJANGO might be using them as overrides in some way that we don't account for.

**Comment by AddoSolutions** [comment]
Is it possibly related to the fact that you are not passing the port number to the `CSRF_TRUSTED_ORIGINS` here?

https://github.com/tubearchivist/tubearchivist/blob/8fa9e23c6ef3b24c96a385b810b86cc5f133892d/tubearchivist/home/src/ta/helper.py#L161

**Comment by MerlinScheurer** [comment]
can you try this:
```
environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
#      - HOST_UID=1000
#      - HOST_GID=1000
      - TA_HOST=tubearchivist.mydomain.com
      - TA_USERNAME=xxx           # your initial TA credentials
      - TA_PASSWORD=xxx              # your initial TA credentials
      - ELASTIC_PASSWORD=xxxx         # set password for Elasticsearch
      - TZ=America/New_York                 # set your time zone
```

**Comment by AddoSolutions** [comment]
> I mean, the value is incorrect, but that would only affect the 10.1.2.3 connection.
> 
> [This](https://github.com/tubearchivist/tubearchivist/blob/8fa9e23c6ef3b24c96a385b810b86cc5f133892d/tubearchivist/config/settings.py#L36C8-L36C8) is the line that is affecting what you are doing. That calls the [ta_host_parser()](https://github.com/tubearchivist/tubearchivist/blob/8fa9e23c6ef3b24c96a385b810b86cc5f133892d/tubearchivist/home/src/ta/helper.py#L144-L163) function, which should be seeing it as you have it set. CSRF should allow it to connect based on that host being allowed, but I guess I would probably set it to be this: `10.1.2.3 https://tubearchivist.mydomain.com https://tubearchivist.mydomain.com:8123`
> 
> See if that allows it to connect properly. There might be an issue with how both are handling the connection.
> 
> I would remove the other two environment variables for right now, as DJANGO might be using them as overrides in some way that we don't account for.

Ok, so I updated it as follows:


```
TA_HOST=TA_HOST=10.1.2.3 https://tubearchivist.mydomain.com https://tubearchivist.mydomain.com:8123
# ALLOWED_HOSTS=[http://10.1.2.3:8000, https://tubearchivist.mydomain.com:8123]
# DJANGO_CSRF_TRUSTED_ORIGINS=https://tubearchivist.mydomain.com
```

Also for kicks, per https://docs.djangoproject.com/en/4.2/ref/settings/#csrf-trusted-origins I tried:

```
TA_HOST=TA_HOST=10.1.2.3 https://tubearchivist.mydomain.com https://tubearchivist.mydomain.com:8123 https://* http://*
# ALLOWED_HOSTS=[http://10.1.2.3:8000, https://tubearchivist.mydomain.com:8123]
# DJANGO_CSRF_TRUSTED_ORIGINS=https://tubearchivist.mydomain.com
```

... still no luck

**Comment by AddoSolutions** [comment]
> From within the TA container, can you print out the environment variables and confirm that the TA_HOST is setting properly? It should have seen it come through.

Yes, for each change I an doing a `docker-compose up -d` – I just confirmed it's changing

> Did you change the DJANGO_CSRF_TRUSTED_ORIGINS & ALLOWED_HOSTS enviroment variable when you did the changes to TA_HOST? removing port from both.

From this point on I have `DJANGO_CSRF_TRUSTED_ORIGINS` and `ALLOWED_HOSTS` commented out entirely.

**Comment by AddoSolutions** [comment]
> can you try this:
> 
> ```
> environment:
>       - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
>       - REDIS_HOST=archivist-redis          # don't add protocol
> #      - HOST_UID=1000
> #      - HOST_GID=1000
>       - TA_HOST=tubearchivist.mydomain.com
>       - TA_USERNAME=xxx           # your initial TA credentials
>       - TA_PASSWORD=xxx              # your initial TA credentials
>       - ELASTIC_PASSWORD=xxxx         # set password for Elasticsearch
>       - TZ=America/New_York                 # set your time zone
> ```

Just tried this, negative results, other rthan I can no longer access it directly from http://10.1.2.3:8000

**Comment by MerlinScheurer** [comment]
Interesting, but thats exactly how i setup my instance...
So maybe its something outside of tubearchivist that messing something up 🤔

**Comment by AddoSolutions** [comment]
Possible, but Django is reporting the exact URL I am putting in (so there is no hostname conversion) and it is a Django error.  I also do this with multiple (same proxy instance) other apps with no problem.

I am suspect of that line I sent above, I am going to test later to see.

Nick

**Comment by lamusmaser** [comment]
At this point, I think we should enable the `DJANGO_DEBUG=True` variable. 

In regards to here:

> Is it possibly related to the fact that you are not passing the port number to the `CSRF_TRUSTED_ORIGINS` here?
> 
> https://github.com/tubearchivist/tubearchivist/blob/8fa9e23c6ef3b24c96a385b810b86cc5f133892d/tubearchivist/home/src/ta/helper.py#L161

This could very well be an issue. We are using a `urllib.parse.urlparse()` before then, which I have confirmed is removing the hostname. See tests below:
```
>>> test_name = "https://tubearchivist.mydomain.com"
>>> test_name_port = test_name + ":8123"
>>> test_name_port
'https://tubearchivist.mydomain.com:8123'
>>> urllib.parse.urlparse(test_name).hostname
'tubearchivist.mydomain.com'
>>> urllib.parse.urlparse(test_name_port).hostname
'tubearchivist.mydomain.com'
```

I'll update the tags to indicate that this is a bug.

**Comment by bbilly1** [comment]
Any progress on this one? As stated above, setting the debug var will give more output, what origin the request is actually coming from, from the perspective of django.

The django docs do not mention that this expects a port, so I have my doubts that this is a bug. Otherwise you can easily change it by modifying settings.py to verify that.

**Comment by bbilly1** [comment]
closing this as inactive.

**Comment by Jypy** [comment]
Hi, had the same issue today (using nginx as ssl proxy with an uncommon port).
My fix was to change:
csrf_trusted_origins.append(f"{parsed.scheme}://{parsed.hostname}")
TO
csrf_trusted_origins.append(f"{parsed.scheme}://{parsed.**netloc**}")
IN home/src/ta/helper.py

and set TA_HOST=https://sub.domain.com:23521 as environment.
Hope that helps.
(btw thanks for the great app!)

**Comment by Cyberes** [comment]
I would like this feature as well. I am unable to proxy using two Nginx proxies. The first is on the local machine and does SSL and the second one is the edge web proxy. I am getting endless CSRF errors and had to set this in my Nginx config for it to even work on the first Nginx proxy:
```
      proxy_set_header Host 127.0.0.1:8000;
      proxy_set_header Referer "";
      proxy_hide_header X-Real-IP;
      proxy_set_header Origin http://127.0.0.1:8000;
      proxy_pass http://127.0.0.1:8000;
      proxy_set_header X-Real-IP "";
      proxy_set_header x-forwarded-scheme "";
```

This CSRF feature causes more headache than its worth.
