### ISSUE TITLE
Seems to break after 15 Subcriptions

### ISSUE THREAD

**Issue by ItsNoted** [tubearchivist/tubearchivist#55]
This has happened on two different installations on two different servers. I don't know if it's coincidence, but the app seems to break and stop scraping downloads after I add 15 subscriptions. I try to add several and it adds them and they show in subscriptions but nothing downloads no matter what channel I add. Here are the logs. https://snip.lol/JipE3/ROkakuzA63.txt

Sorry to keep making issues, but I think it's important to the development of the app. Maybe it's something simple I'm missing. Let me know if you have any questions for me.

[_tubearchivist_logs.txt](https://github.com/bbilly1/tubearchivist/files/7358037/_tubearchivist_logs.txt)

**Comment by bbilly1** [comment]
That took me a second to figure out. It looks like you are trying to download an empty download queue. :-) So after you subscribe to a new channel, click on "Rescan subscriptions" first to add missing videos to the queue. Or if you want to download the whole channel, add the channel with "Add to download queue". Then once you have it all in the download queue, "Start download" will get all that sweet sweet Spongebob. 

I'll put a error message there for that.

No, please keep the issues coming, that's very helpful to get direct feedback like that. No promises that I can fix *everything*, but I also can't test everything. So thanks for your help!

**Comment by geekedtv** [comment]
Ha! I just recreated all three containers and it works. But that didn't tell me the issue so I am glad you figured it out! It just so happened I looked down and noticed there was an update too. I'm happy! Thank you for figuring this one out. I'll keep you posted if there's any other issues.

**Comment by geekedtv** [comment]
Awesome. I've been extensively testing today so I think it's fair to say this is fixed. I'll close it. Thanks again!
