### ISSUE TITLE
[Feature Request]: Full search in comments

### ISSUE THREAD

**Issue by s1lverkin** [tubearchivist/tubearchivist#556]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

I would like to be able to index and search comments.

## Additional context

Right now the comments are not being indexed and not being able to be searched.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Unlikely that this will happen any time soon, there are many more pressing tasks that will take priority before that. As you have seen, we have a multi year backlog in this project. I've added it to the roadmap, so if somebody wants to take this on, please do.

But just to clarify, comments are getting indexed, just there is currently no search functionality exposed for that, but you could already do something through the ES API directly.
