### ISSUE TITLE
[Bug]: Regression in current `testing` branch when handling thumbails

### ISSUE THREAD

**Issue by ajgon** [tubearchivist/tubearchivist#557]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux, kubernetes

## Describe the bug

The current code in `testing` branch uses incorrect thumbail URLs, and fetches them directly from youtube CDN instead of local cache. The wrong URLs are used in `<img src=...>` attributes, not sure if this happens somewhere else under the hood.

Example URL on `testing` branch: `https://i.ytimg.com/vi/NZlFkeyAAAc/maxresdefault.jpg`
Example URL on current master: `https://tubearchivist.mydomain.local/cache/videos/N/NZlFkeyAAAc.jpg`

## Steps To Reproduce

- Deploy `testing` branch
- Visit tuberarchivist homepage and sign in
- Using devtools check URL of any video thumbnail

## Expected behavior

- Thumbnail URLs should point to local TA instance and use cache dir.

### Relevant log output

```shell
Doesn't apply.
```

**Comment by bbilly1** [comment]
doing all these refactoring here. :-) Thanks for pointing it out, had it fixed locally but not yet pushed.
