### ISSUE TITLE
[Feature Request]:  Sort by video durations and filesize

### ISSUE THREAD

**Issue by Decrease0202** [tubearchivist/tubearchivist#559]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
no
## Describe the solution you'd like
Id like to have the option to sort videos that have been downloaded by video duration.

I tend to bulk download whole channels, and its very difficult to try and sort out compilation videos, or 8 hour live streams for a channel.

The easiest way to go back and remove them would be to sort by duration longest to shortest and be able to remove them.

## Additional context
The option to sort by file size would also be useful, but would still prefer to sort by duration if givent he choice between the 2.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by ThaMunsta** [comment]
I don't know if it would be outside the scope of this feature request but I think incorporating this into the search would be huge.
For example:
`filesize: >100m filesize: <2000m` 
or
`larger: 100 smaller: 2000`
as a search term to show videos larger than 100mb but smaller than 2gb.

**Comment by bbilly1** [comment]
> incorporating this into the search

yes, that's a different thing, this is about sorting, as with the drop down.

for extending the search, other things like pagination will take priority before extending that further with additional keywords.

**Comment by bbilly1** [comment]
shipped in v0.4.4, thanks for implementing this.
