### ISSUE TITLE
[Feature Request]: Playlists sort by feature

### ISSUE THREAD

**Issue by tech101us** [tubearchivist/tubearchivist#562]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Not particularly, unless I am overlooking something. I've looked through the documentation regarding playlists and do not see any reference to a "Sort By" feature as found in the "Channels" page.  

## Describe the solution you'd like
Ability to "Sort By" videos in playlists. Ideally sort by the date posted to YouTube in ascending or descending order.

## Additional context
Go easy on me. This is the very first time I've opened a feature request on GitHub. P.S. I'm not a developer, but have some working knowledge of Linux and Docker. Truly am grateful for this project and would love to contribute some time if there is something a non-developer type like myself can assist with.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Playlists already have a predefined sort order, the same way as they are on Youtube, usually that's as intended by the uploader, as in sorted in order as they are expected to be watched. That's why this project doesn't overwrite that.

**Comment by mobamoba** [comment]
> Playlists already have a predefined sort order, the same way as they are on Youtube, usually that's as intended by the uploader, as in sorted in order as they are expected to be watched. That's why this project doesn't overwrite that.

I'd like to reopen this if possible because they above may be true in some cases but definitely not in all. For example, my playlists are entirely created by me using various videos on Youtube and the order I add them is absolutely not the order I want them in since I add them as I find them and sort them by duration.

I'd certainly like a playlist sort option since everyone has different use cases for the home Youtube archive and even Youtube itself allowed limited sorting within playlists (or additional options via addons).

**Comment by bbilly1** [comment]
Unlikely that we'll revisit that any time soon, as we are about to rewrite the frontend. If you insist, please open a PR once that is done.

**Comment by mobamoba** [comment]
Okay but in the meantime is there a way to do this manually? Like I'm not even sure where the playlist references are kept within TA (in the DB? Elasticsearch?) as I move videos between playlist all the time on YT and change order and would like to do that on TA as well even if it means a bit of extra work for now. Is there a way I can do that on my own - move items between playlists and set manually sort the playlist order based on duration? Thanks.
