### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by LeoPadre** [tubearchivist/tubearchivist#568]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Specify the number of downloaded videos for each channel separately. For some channel it is enough to have a couple of recent videos, and some channel should have the whole channel. To do this now, need to manually download the necessary videos and disable automatic downloading, but there can be thousands of such videos and it is quite inconvenient to download them manually.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
That's already on the [roadmap](https://github.com/tubearchivist/tubearchivist/tree/master#roadmap) and will happen at some point:

> Show total video downloaded vs total videos available in channel
