### ISSUE TITLE
[Bug]: docker-compose version should be minimum 3.4 to use start_period in healthcheck

### ISSUE THREAD

**Issue by thomasfifer** [tubearchivist/tubearchivist#569]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu Server 22.04

## Describe the bug
The docker-compose file uses start_period in healthcheck yet specifies a version of 3.3; however, start_period was not added until [version 3.4](https://docs.docker.com/compose/compose-file/compose-versioning/#version-34). Changing the first line of the docker-compose file to version 3.4 allows docker-compose to successfully build the image.

## Steps To Reproduce
sudo docker-compose up -d

## Expected behavior
docker-compose to successfully build and deploy image

### Relevant log output

```shell
ERROR: The Compose file './docker-compose.yml' is invalid because: services.tubearchivist.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
```

**Comment by bbilly1** [comment]
You are right, according to the docs. It doesn't throw any error for me though, strangely enough... But in any case, best to update it.
