### ISSUE TITLE
[Feature Request]: Replace YouTube links in video description with locally stored videos if available

### ISSUE THREAD

**Issue by ccfman2004** [tubearchivist/tubearchivist#570]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
I would like to see the ability to replace YouTube links in video descriptions with their local copy if already downloaded.
## Describe the solution you'd like
Either have a setting or easy manual way to have TubeArchivist scan video descriptions for YouTube video links and replace the link if the video linked is already downloaded and archived.
## Additional context
Many YouTube videos have links to other YouTube videos, channels, or playlists and it would be nice if that video, channel or playlist link would be replaced with a local link if that video, channel or playlist has already been downloaded.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
An archival project should archive as is and not modify things, so that wouldn't be in the spirit of this project.

If you want to accomplish something like that, you could do that on a DNS level or I think there are various projects out there like *privacy friendly redirect* or something like that. That would fit in there better.

**Comment by ccfman2004** [comment]
I only want it to point to a TA video ONLY if it's archived so DNS redirection won't do. I'm trying to save data due to stupid ISP data caps. I know I can't directly modify the video page as it would get restored periodically.
