### ISSUE TITLE
[Installation]: Cannot Log In After Installation No Errors in Console Log

### ISSUE THREAD

**Issue by StreckerCM** [tubearchivist/tubearchivist#572]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Linux/Docker

### Your installation or setup question

Cannot Log In After Installation No Errors in Console Log.  I have tried using the default and custom TA_USERNAME and TA_PASSWORD values and both give me the same error.

### Relevant log output

```shell
version: '3.5'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    ports:
      - 8050:8000
    volumes:
      - /nfs/media/YouTube:/youtube
      - /opt/tubearchivist:/cache
    environment:
      - ES_URL=http://archivist-es:9200           # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis                # don't add protocol
      - HOST_UID=0
      - HOST_GID=0
      - TA_HOST=192.168.1.129 https://tubearchivist.mydomain.com         # set your host name
      - TA_USERNAME=myusername           # your initial TA credentials
      - TA_PASSWORD=verysecret              # your initial TA credentials
      - ALLOWED_HOSTS=[http://192.168.1.129:8000, http://192.168.1.129:8050, https://tubearchivist.mydomain.com]
      - ELASTIC_PASSWORD=verysecret@7rdhtWjGjcLo # set password for Elasticsearch
      - TZ=America/New_York                       # set your time zone
      - ENABLE_CAST=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
  volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.9.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:
```

**Comment by bbilly1** [comment]
did you tried password reset? https://docs.tubearchivist.com/users/#reset

otherwise you'll have to be more specific than "can not login".

**Comment by nicolasshu** [comment]
Yeah, I tried to do a password reset as well, and I did check the environment variables TA_USERNAME and TA_PASSWORD, and everything was all good, but I still haven't been able to login. The error that I've been getting is a 403 Forbidden, with:

```
Forbidden (403)

CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
```

Have you seen this error before? Right now I can't change any environment variables as I made the container via docker-compose, and I can't access my machine's terminal

**Comment by StreckerCM** [comment]
@bbilly1 the password reset worked for me when going direct to IP.

@nicolasshu I got that as well after fixing it and verifying I could login by IP.  It gave me that with the reverse proxy login.  Adding the domain name that forwards to my Nginx Proxy Manager instance to the allowed list seems to have solve that.

**Comment by nicolasshu** [comment]
Ahh interesting. Hmm, that's new. Just to make sure I'm understanding correctly.  You're saying that the subdomain name (e.g. `tube.example.com`) should be added to the Access List as allowed in the Nginx Proxy Manager? (None of the below images are mine. They are screenshots taken from the internet)

![image](https://github.com/tubearchivist/tubearchivist/assets/12994607/55203132-6955-451f-836e-6d94b93b338b)
![image](https://github.com/tubearchivist/tubearchivist/assets/12994607/3ea68dc9-a8d1-43b1-ba9c-ce9b67fd898d)

If I understood it correctly, is that not redundant to say that the subdomain should be proxied to the IP address that you're assigning it to? I'm not trying to say you're wrong or to be a contrarian. I'm just confused as I haven't seen this before.

**Comment by StreckerCM** [comment]
In the tubearchivist docker compose

For exmaple my DNS has wildcard.domain.com pointing to my proxy manger instance.  I had to add the following to the ALLOWED_HOSTS environmental variable in the docker compose

`-ALLOWED_HOSTS=[http://192.168.1.xxx:8000, http://192.168.1.xxx:8050, https://tube.domain.com, https:\\wildcard.domain.com:8000, https:\\wildcard.domain.com:8050]`

After recreating with that it allowed me to login using the reverse proxy subdomain that I setup.

You can probably ignore my overkill of adding multiple ports. My container had to be mapped to 8050 but the internal port is 8000.  I was having issues connecting without bad gateway errors at first so I added all possible combinations.
