### ISSUE TITLE
[Feature Request]: Download / Extract audio layer after download (into seperate store)

### ISSUE THREAD

**Issue by BAAAASS** [tubearchivist/tubearchivist#576]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
No, feature request.

## Describe the solution you'd like
In the perfect world, I can enjoy my music videos, as videos.  However, sometimes I am driving or running (or ...) and would enjoy listening to music as .mp3 or .aac (etc.).  To be clear, the request is to download the video (as it is now), but to add the option to extract the audio layer into a seperate store.

## Additional context
Above.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
That's already on the roadmap, audio will be implemented with the podcast mode.
