### ISSUE TITLE
[Feature Request]: custom settings on channels

### ISSUE THREAD

**Issue by bats77** [tubearchivist/tubearchivist#579]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Settings specific to a channel isn't complete

## Describe the solution you'd like
Each channels shall have all settings customizable, as quality, playlists index... but also shorts, livestream...
Ideally a list of words excluded is also an interesting option

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
for the page sizes per channel, that has come up a few times on discord already, but nobody wanted to take this on so far. I've added it to the roadmap, to not clutter up the issues here. Then keyword filtering is on the roadmap already.

So, as you saw, there are already a lot of ideas how to improve things, but this project needs your help implementing these things.
