### ISSUE TITLE
[Feature Request]: URL improved ?

### ISSUE THREAD

**Issue by bats77** [tubearchivist/tubearchivist#580]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
I wonder if TubeArchivist will work with other sites than Youtube, but if not, URL shall be shorten

## Describe the solution you'd like
As TubeArchivist is working only on youtube, [ https://www.youtube.com/ ] shall be preset as it's always needed. I don't think that it's to be shorten, in order to prevent the case of url changes from youtube ; in this way, the entire url shall be inputed surely without updating TubeArchivist in this hypothetical case.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
You can already do that by providing the IDs only, as documented here: https://docs.tubearchivist.com/urls/
