### ISSUE TITLE
[Feature Request]: Track Deleted Videos

### ISSUE THREAD

**Issue by apiweb** [tubearchivist/tubearchivist#584]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Describe the solution you'd like

Tube Archivist could add a feature to check video status during agent runs on a channel or playlist. If a video was previously downloaded but is now deleted on YouTube, Tube Archivist could label or flag it as "Deleted On Origin".

This feature will be particularly useful when (for example) we add a "Watch Later" list or playlist with videos from multiple channels. YouTube informs us of deleted videos without specifying which ones. With this feature, Tube Archivist will flag or label the deleted videos. And we can identify quickly if the owner deleted the video.

## Additional context

![image](https://github.com/meeb/tubesync/assets/5881027/33134c9e-b20e-4fa4-be46-2c84e03e5e05)
Screenshot from a video deleted from the playlist, we can't identify which video was deleted.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
That's happening already. Videos will get deactivated with the refresh task. Check the docs for more details.
