### ISSUE TITLE
[Feature Request]: Upgrade Video when available

### ISSUE THREAD

**Issue by apiweb** [tubearchivist/tubearchivist#585]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
There are instances when YouTube delays the availability of Enhanced Bitrate versions for premium users. 
Additionally, when our agent runs, it retrieves the video in the best quality at that moment but doesn't automatically upgrade it when YouTube releases the enhanced version.

## Describe the solution you'd like

I suggest incorporating a feature that allows for automatic quality upgrades to Enhanced Bitrate when higher-quality versions become accessible on YouTube during the next agent's run. 
YouTube occasionally takes some time to release these enhanced versions, and with this feature, users can configure their channels/playlists' agents to perform this upgrade seamlessly during the subsequent run.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
There is already an open feature request for periodically chdck for better quality. Please follow the how to, don't create duplicates and do some basic research before opening issues here.
