### ISSUE TITLE
tubearchivist does not support other video platforms (Odysse, rumble, Instagram...) 

### ISSUE THREAD

**Issue by Mike6547** [tubearchivist/tubearchivist#586]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

Hello, thank you for this project, but tubearchivist only supports YouTube but not other platforms (Odysse, rumble, Instagram...). While yt-dlp supports a lot of websites https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md

I know that tubearchivist uses yt-dlp, so it shouldn't be a problem to make it compatible with other platforms!

Is this a working feature? When do you plan to implement this feature?

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Don't just check the *I have read* button, while obviously not even reading the FAQ of this project. This is a quick way of getting banned for wasting maintainers time.

**Comment by Mike6547** [comment]
In this case I will not use tubearchivest, it is obsolete.  Tubesync is better :)
