### ISSUE TITLE
[Feature Request]: User created playlist

### ISSUE THREAD

**Issue by greg321321** [tubearchivist/tubearchivist#590]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

I would like to build a Watch Offline feature into this project. 

Use Case: When at a location where there is no internet connection, I would like to view videos on my PED (Personal Electronic Device).

User Stories:

1. As a user, I want to create a custom playlist. (existing roadmap feature)
2. As a user, I want to toggle a custom playlist for Watch Offline.
3. As a user, when I am at a location where there is no internet connection, I want to view my 'Watch Offline custom playlist' videos.

I believe all this work can be done simply using web caching. Let me know if you think this is a good idea. I can build the feature with your direction and knock out one or two of your roadmap features/bugs in the process. I am a software developer familiar with web technologies/gitlab.

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Well, this *is* already an offline application. TA doesn't need internet connection to work, after you have downloaded and indexed your videos obviously. Should also be portable, like move a portion of TA to you laptop temporarily, all persistent data is in the volume, or if you know you'll be offline later, sync your data first, then you can use TA offline perfectly well. Just saying that you can do that already.

To the rest, obviously, please go ahead, any of the documented bug reports or feature requests are ready to be taken on by you.

**Comment by greg321321** [comment]
ok I think I will start on the playlist idea first (existing roadmap feature).  The offline scenario is for an Android phone. I goto the gym and they don't have good WiFi, I don't have an unlimited cell data plan, but would still like to watch videos from my phone.

**Comment by bbilly1** [comment]
Ah, I see, you mean offline from the TA server and not from the internet. Honestly that sounds like [out of scope](https://docs.tubearchivist.com/faq/#what-is-the-scope-of-this-project) for this project, I don't see how this could be done with caching alone, as the interface constantly interacts with the backend.

Maybe some sort of static site generator would be a better approach? Or some sort of export script that can just get the video files you want and makes a copy to your phone? So you can use the phones built in media player?

**Comment by greg321321** [comment]
thanks you've given me some good ideas to refine the use case. Maybe something simple like 'download playlist'. In the meantime, I played around with the dev code and propose this menu organization for custom playlists:
![Screenshot from 2023-11-12 09-24-52](https://github.com/tubearchivist/tubearchivist/assets/134153833/4a2cb773-076d-4611-b0a2-e4e700ec38ef)

**Comment by greg321321** [comment]
simple ui for now to create and remove playlists
![Screenshot from 2023-11-12 15-45-03](https://github.com/tubearchivist/tubearchivist/assets/134153833/7fc78a57-87a7-432a-be24-22848dcf0d45)

**Comment by greg321321** [comment]
simple menu to add video to a playlist
![Screenshot from 2023-11-12 23-40-52](https://github.com/tubearchivist/tubearchivist/assets/134153833/e8ac1d0a-86f2-4588-8eb8-74e6ae867482)

**Comment by pairofcrocs** [comment]
Looks great!

A lot of people have been asking for this feature, and will make a great addition :)

**Comment by bbilly1** [comment]
Nice, some great progress here!

Not sure how well this is going to work once you have a dozen plus playlists? That will mess up the layout there. Maybe the controls for adding a video to a playlist would be better suited on the video detail page? That already has the playlist navigation there too...

**Comment by greg321321** [comment]
take a look at how youtube does this. It is similar to this approach. I can add scrollbar to drawer menu to limit impact on layout. If it turns out the drawer is a problematic, I can switch it to a popup centered around the tile, but I imagine that will come with it's own complexity to solve. I'm trying to limit this feature to 3 days or less (24 hrs or less) so the idea here is to get some basic features working so we can take a look at it on the testing branch.

**Comment by greg321321** [comment]
playlist controls
![Screenshot from 2023-11-16 06-46-02](https://github.com/tubearchivist/tubearchivist/assets/134153833/e43f17ec-9dee-47e2-aad8-87d2a5fa56bc)

**Comment by greg321321** [comment]
I sent a preview pull request for this feature. I didn't see an option to associate the pull request to this ticket. Can you tell me how to do that?

**Comment by bbilly1** [comment]
Are you still working on this? Ideally this should be tied together with #609, to make playlists extendible by type. I'd suggest to set a `playlist_type` field so this can be filtered similarly how the channel subpages are implemented.

So `playlist_type` could be any of `regular` (default), `custom`, `album` and whatever we come up with later down the road.

**Comment by greg321321** [comment]
yes. playlist_type makes sense seeing the other feature request. I chose an is_custom boolean field, but I can refactor into the playlist_type. One issue that came up when inspecting the code is how we want to handle the existing playlists. I'd like to create a routine during the upgrade process that will add this field if it does not exist. Otherwise the elastic search queries and view logic contain many conditional statements.

**Comment by greg321321** [comment]
agree will do. this will need a good testcase

**Comment by K1Hyve** [comment]
I prefer to use Jellyfin to watch the TA videos. In there I can download the videos before going out to my phone or ask it to transcode it to a lower bitrate if I want to watch it with limited data plan.

**Comment by greg321321** [comment]
> I prefer to use Jellyfin to watch the TA videos. In there I can download the videos before going out to my phone or ask it to transcode it to a lower bitrate if I want to watch it with limited data plan.

Thanks K1 I will have to install Jellyfin and take a look. I recall looking at their documentation and not seeing what I wanted. I like watching the youtube content from a list. So the concept I am looking for is: add/remove content from a list. Sync a device (once) with a list. Device auto downloads the list, device auto updates the list. I think this can be done with a combination of this feature, plus a real small new feature that provides a link to the 'podcast' format of the list. I think there are a lot of apps out there that understand the podcast format. Podcasts genre is update frequently (weekly basis for example), so I imagine the app developers have thought of this and have an offline solution to my use case. I'll have to see if there is a simple solution out there.

**Comment by greg321321** [comment]
code update complete. Pull request issued at: https://github.com/tubearchivist/tubearchivist/pull/620

**Comment by greg321321** [comment]
requested additional permissions from admin so I can resolve merge conflict on testing branch.

**Comment by bbilly1** [comment]
implemented and merged with v0.4.7, shutout to @greg321321
