### ISSUE TITLE
[Feature Request]: Add Loop Functionality to Player

### ISSUE THREAD

**Issue by xInsertx** [tubearchivist/tubearchivist#600]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
I think for short's style content - having the default ability to loop them makes sense.

## Describe the solution you'd like
Ability to loop videos - with default settings for short style content to loop (this could be an option in settings).

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Easy enough to just restart the video if you really want to watch it again. Maybe we'll lave loop functionality at a later point with better playlists controls.

**Comment by EpicLPer** [comment]
@xInsertx At least on Desktop (and Chromium based browsers) there is a loop-function when right clicking the video player: 
![image](https://github.com/tubearchivist/tubearchivist/assets/8442196/d153f078-2d9a-4220-800b-791fa4c3bce4)
