### ISSUE TITLE
[Bug]: YouTube Playlist ID cannot be parsed

### ISSUE THREAD

**Issue by CommanderRedYT** [tubearchivist/tubearchivist#604]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
When I put this ID / URL ([OLAK5uy_meaM_pcONkasoKJ8HZsOQpGlMiXQiIDuM](https://www.youtube.com/playlist?list=OLAK5uy_meaM_pcONkasoKJ8HZsOQpGlMiXQiIDuM)) into the "Add Video/Playlist/Channel" field, I get an error message in the Network Tab of the Dev tools saying "failed to parse".

## Steps To Reproduce
Copy the URL / ID from above into the "Add Video" text field and click download

## Expected behavior
The ID should not be treated as invalid

### Relevant log output

```shell
not a valid id_str: OLAK5uy_meaM_pcONkasoKJ8HZsOQpGlMiXQiIDuM

failed to parse: https://www.youtube.com/playlist?list=OLAK5uy_meaM_pcONkasoKJ8HZsOQpGlMiXQiIDuM

[pid: 40|app: 0|req: 9/9] 192.168.0.202 () {62 vars in 1087 bytes} [Fri Nov 17 17:57:29 2023] POST /api/download/ => generated 110 bytes in 14 msecs (HTTP/1.0 400) 8 headers in 279 bytes (1 switches on core 0)

is url

playlist from list query str

not a valid id_str: OLAK5uy_meaM_pcONkasoKJ8HZsOQpGlMiXQiIDuM

failed to parse: https://www.youtube.com/playlist?list=OLAK5uy_meaM_pcONkasoKJ8HZsOQpGlMiXQiIDuM

[pid: 40|app: 0|req: 12/12] 192.168.0.202 () {62 vars in 1087 bytes} [Fri Nov 17 17:58:33 2023] POST /api/download/ => generated 110 bytes in 14 msecs (HTTP/1.0 400) 8 headers in 279 bytes (1 switches on core 0)
```

### Anything else?

Maybe the IDs got longer?

**Comment by bbilly1** [comment]
The docs cover how this project defines playlists: 
https://docs.tubearchivist.com/urls/#playlist

Looks like the link you provided isn't really a playlist on YouTube, but an album. E.g. these are playlists and implemented in this project:
https://www.youtube.com/@Thenewtonbros/playlists

and these are Releases/Albums and not currently implemented:
https://www.youtube.com/@Thenewtonbros/releases

Is the only difference just the playlist ID length? Are all album playlists 41 characters long?

**Comment by CommanderRedYT** [comment]
I can check more albums:

```
https://www.youtube.com/playlist?list=OLAK5uy_muCUoG58NR5uk5PPLc_Mdg790DLzLtUCI
https://www.youtube.com/playlist?list=OLAK5uy_mc9X-8-rEwvbb6PophqhaSOHU3oKrRZe4
https://www.youtube.com/playlist?list=OLAK5uy_nDtMg7aqY7HVT1TDWZ6bN_dT_VXHg5kqQ
https://www.youtube.com/playlist?list=OLAK5uy_meWCZNCwRQt6bo4PH7UXG9wHIwCcQwtNI
```
(All length of 41)

So yea, these seem to be 41 characters long

**Comment by bbilly1** [comment]
OK, please reopen this as a Feature request and add our findings there.
