### ISSUE TITLE
How to set subscribe channel only latest x days

### ISSUE THREAD

**Issue by xinmans** [tubearchivist/tubearchivist#607]
Ex: just only latest 3 days for channel, only download newest videos.

**Comment by bbilly1** [comment]
All functionality is documented in the docs, you can get a good overview there what is implemented.

**Comment by xinmans** [comment]
you are right, i have seek this FAQ

Why does subscribing to a channel not download the complete channel?#
https://docs.tubearchivist.com/faq/

	For Tube Archivist, these are two different things: To download a complete channel, add it to the download queue with the form or with Tube Archivist Companion, the browser extension. This is meant for a complete archival.
	Subscribing to a channel is for downloading new videos as they come out. That is designed to be as quick as possible, to allow you to efficiently rescan your favourite channels frequently. This will add videos to your download queue based on your channel page size.
	If you want to archive the complete channel and any future videos, you can do both.
