### ISSUE TITLE
Support set output name format on Application

### ISSUE THREAD

**Issue by xinmans** [tubearchivist/tubearchivist#608]
Like set yt-dlp.conf config parameters for yt-dlp cli.

-o "/youTube/%(uploader)s (%(uploader_id)s)/%(upload_date)s - %(title)s - (%(duration)ss) [%(resolution)s] [%(id)s].%(ext)s"

**Comment by bbilly1** [comment]
Stop spamming this repo and read the how to, don't just check the box, people get banned like that.
