### ISSUE TITLE
Playing downloads on Safari

### ISSUE THREAD

**Issue by deanpribetic** [tubearchivist/tubearchivist#61]
Hey there – I am finding that downloaded videos won't play in Safari browsers (Mac or iOS). This seems to be an issue with how the webserver provides 'range' data to clients. This is beyond my expertise to fix. Any thoughts?

Oh…works great on Chrome though :)

**Comment by bbilly1** [comment]
No need to tell the kids that the shortcut you have created on the home screen of the iPad is actually open Tube Archivist with mobile Firefox.

But in all seriousness, somebody with a mac wanting to look into it, please let me know.

**Comment by pairofcrocs** [comment]
> Hey there – I am finding that downloaded videos won't play in Safari browsers (Mac or iOS). This seems to be an issue with how the webserver provides 'range' data to clients. This is beyond my expertise to fix. Any thoughts?
> 
> 
> 
> Oh…works great on Chrome though :)

I can play videos on safari via a Mac Mini but not on my IPhone 12 Pro Max.

**Comment by bbilly1** [comment]
OK, a little bit of research regarding [Webkit](https://webkit.org/blog/6784/new-video-policies-for-ios/) showed, that for the \<video\> tag to work on mobile, it needs the attribute `playsinline` set. If that is the case, this will require that to be added at two different places:

1. The [video.html](https://github.com/bbilly1/tubearchivist/blob/09584e43b897f04ec13babfb671f0ef2336dab01/tubearchivist/home/templates/home/video.html#L12) template that generates the video tag from html,
2. Additionally [script.js](https://github.com/bbilly1/tubearchivist/blob/09584e43b897f04ec13babfb671f0ef2336dab01/tubearchivist/static/script.js#L233) where the `createPlayer` function is responsible to, well, create the player. That gets called on click on any thumbnail. So this function will need the line `videoPlayer.setAttribute('playsinline', true);` added there.

I didn't just want to push the changes without knowing if that is doing anything. Is somebody able to verify that this solves the problem? @borgmanJeremy  @scottyb2210

**Comment by borgmanJeremy** [comment]
@bbilly1 Actually I don't think that's the (only) root cause. If i download the .mp4 directly and try to serve that in a minimal flask app I still can't play it. It also doesn't play with quicktime, so I wonder if the ffmpeg settings need to change.

**Comment by deanpribetic** [comment]
I think you an update to the README should be enough.

**Comment by cpt-kuesel** [comment]
can confirm "bestvideo[height<=1080][VCODEC=avc1]+bestaudio[ACODEC=mp4a]/mp4" is now downloading 1080p videos that my ipad can play.
thank you for looking into this guys!
