### ISSUE TITLE
[Feature Request]: Add Copy button for API Key

### ISSUE THREAD

**Issue by stevenhorner** [tubearchivist/tubearchivist#610]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Not a bug or a problem, but it can be hard to select the API key with a laptop trackpad or on a phone and the Revoke button is quite close and easy to press accidently. Presumably the button asks to confirm anyway, didn't test this due to not wanting to revoke my current keys.

## Describe the solution you'd like
Add a simple Copy button that allows copying the API key to the clipboard and/or put the key in a text box that makes it slightly easier to select.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Some more explanations in the linked PR, but as it looks like, this can't be reliably implemented without SSL, I'm closing this as won't fix.
