### ISSUE TITLE
[Bug]: Issue downloading files

### ISSUE THREAD

**Issue by njdowdy** [tubearchivist/tubearchivist#621]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Unraid Docker

## Describe the bug

When I attempt to download a video I get the following error:

```
[{timestamp}: WARNING/ForkPoolWorker-8] [info] Testing format {format_id}
[download] Got error: HTTP Error 403: Forbiddenr-8] ERROR: 
[{timestamp}: WARNING/ForkPoolWorker-8] [info] Unable to download format {format_id}. Skipping...
....
ERROR: [youtube] {video_id}: Requested format is not available. Use --list-formats for a list of available formats
```

This was triggered after updating to version 0.4.4. I had a lot of issues with this update. The rebuild of the `ta_video` and `ta_playlist` index was unfortunately not automatic, and I had to manually fix it using `Settings > Actions > Rescan filesystem` (which was painful because a lot of videos have apparently changed to private and TubeArchivist doesn't skip these; an issue for another day). 

But now that this process is complete, I am seeing the above error whenever I try to download any new videos. The videos are fine otherwise.

I tried to edit the Python files in the docker container to add `--list-formats`. To do this, I went to `/app/home/src/download` and edited `yt_dlp_base.py` and added `"listformats": True` to `OBS_BASE`. This does list the formats in the log, but does not fix the issue. 

My TubeArchivist quality settings are: `0: deactivate and download the best quality possible as decided by yt-dlp.` so, I don't see how it is possible that yt-dlp is getting hung up on quality.

Any assistance getting back up and running would be much appreciated. My library is already large, so nuking and starting over would be a massive pain.

## Steps To Reproduce

1. Update to 0.4.4 from 0.4.3
2. Find that your library is empty
3. Settings > Actions > Rescan filesystem to restore your library
4. Try to download a new video
5. Fail

## Expected behavior

I expect videos to download without issue, since there should be no quality limits set on the videos.

### Relevant log output

```shell
see above
```

**Comment by clb92** [comment]
I got it too for a while when not using cookies. I think it's a rate-limiting maneuver by Youtube. Then I refreshed my cookie and I could download again for a while. But then it started happening again, even with cookies, so I turned TubeArchivist off for a few days, and now I can download again.

Except, currently I've started getting "We're processing this video. Check back later" error from Youtube instead.

**Comment by njdowdy** [comment]
> I got it too for a while when not using cookies. I think it's a rate-limiting maneuver by Youtube. Then I refreshed my cookie and I could download again for a while. But then it started happening again, even with cookies, so I turned TubeArchivist off for a few days, and now I can download again.
> 
> Except, currently I've started getting "We're processing this video. Check back later" error from Youtube instead.

That makes sense. I had just hammered them with over 20,000 requests during the rescan. I'll wait a few days, try again, and see if it is resolved. If so, I'll come back and close this issue. Thanks!

**Comment by PhuriousGeorge** [comment]
> That makes sense. I had just hammered them with over 20,000 requests during the rescan. I'll wait a few days, try again, and see if it is resolved. If so, I'll come back and close this issue. Thanks!

Yeah, this is not an issue related to TA, you're being rate-limited or soft-banned by Google.  Typically lasts a day or so, but can go out to a week in my experience.  Either hop behind a VPN or let things cool off.

**Comment by Dontkickmi22** [comment]
Let me join the discussion with somewhat related topic by wondering if there can be an option for TA to go thru the download queue in a mixed way? Currently it's whole channel by added time, can the queue be "shaked"?

Above reason being I am under soft ban ATM on a host processing thru a channel with consecutive short clips. I believe that host has reached "amount of clips downloaded within a certain time" threshold.

**Comment by bbilly1** [comment]
You can increase the sleep interval between on the settings page to sleep between downloads. But currently there is no indication that YT detects what videos in what order you download. You can easily see that somebody would watch multiple shorts in a row for example.

**Comment by njdowdy** [comment]
The rate limiting from Google was exactly my issue. It took many days to resolve though. Happy to report things are back to normal. Thanks!
