### ISSUE TITLE
[Feature Request]: Auto-add playlist videos that have been removed by youtube to the ignore list

### ISSUE THREAD

**Issue by svuong-dev** [tubearchivist/tubearchivist#625]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
I'm consistently hitting [this bug](https://github.com/tubearchivist/tubearchivist/issues/619) and I think this request might help address it. My subscription rescans are trying to go through a large playlist and there's like 300 videos that have been removed by youtube on that list. It seems like for whatever reason, if a `ForkPoolWorker` goes through too many bad videos (around 250 for me), it gets a signal 9 SIGKILL. Something like this (sorry, synology logs are in time reversed order)
```
######## | stdout | Gracefully   killing worker 1 (pid: 4535)...
######## | stdout | [task][66fe3253-f690-4c49-8464-2c5eea88a478]:   received STOP signal.
######## | stdout | "[0m                    
2023/12/06 00:48:01,stdout,billiard.exceptions.WorkerLostError: Worker   exited prematurely: signal 9 (SIGKILL) Job: 5.                    
2023/12/06 00:48:01,stdout,    raise   WorkerLostError(                    
2023/12/06 00:48:01,stdout,  File   \"/root/.local/lib/python3.11/site-packages/billiard/pool.py\" | line 1264 | in mark_as_worker_lost 
2023/12/06 00:48:01,stdout,Traceback (most recent call last):                    
2023/12/06 00:48:01,stdout," |
######## | stdout | billiard.einfo.ExceptionWithTraceback: 
######## | stdout | raise WorkerLostError( 
######## | stdout | File   \/root/.local/lib/python3.11/site-packages/billiard/pool.py\" | line 1264 | in mark_as_worker_lost |   |   |   |  
2023/12/06 00:48:01,stdout,Traceback (most recent call last):                    
2023/12/06 00:48:01,stdout,[1;31m[
2023-12-06 00:48:01 | 362: ERROR/MainProcess] Task   handler raised error: WorkerLostError('Worker exited prematurely: signal 9   (SIGKILL) Job: 5.')
2023/12/06 00:48:00,stdout,[1;31m[2023-12-06 00:48:00 | 648: ERROR/MainProcess] Process   'ForkPoolWorker-8' pid:53 exited with 'signal 9 (SIGKILL)'[0m
2023/12/06 00:47:55,stdout,[1;33m[2023-12-06 00:47:55 | 355:   WARNING/ForkPoolWorker-8] <example-id257>: [257/296]: add to queue[0m 
2023/12/06 00:47:55,stdout,[1;33m[2023-12-06 00:47:55 | 353: WARNING/ForkPoolWorker-8]   <example-id256>: failed to get info from youtube with message ERROR: [youtube]   <example-id256>: Video unavailable[0m |  
2023/12/06 00:47:55,stdout,[1;33m[2023-12-06 00:47:55 | 353: WARNING/ForkPoolWorker-8]   ERROR: [youtube] <example-id256>: Video unavailable[0m 
2023/12/06 00:47:55,stdout,[1;33m[2023-12-06 00:47:54 | 926: WARNING/ForkPoolWorker-8]  <example-id256>: [256/296]: add to queue[0m 

```
After this happens, tubearchivist becomes unresponsive or crashes. The playlist parsing gets stuck like at (257/350) and I'm not able to stop it. Sometimes it will also throw the celery/redis errors like in [the issue linked above](https://github.com/tubearchivist/tubearchivist/issues/619). 

## Describe the solution you'd like
It's not clear to me what causes the `ForkPoolWorker` to die but it seems like one of the issues is that as the playlist is being scanned, a bad video gets processed, fails, and skipped over. So the next time the playlist gets scanned again, TubeArchivist will again try to look up those videos even though it should know there's no point. So a large playlist will eventually build up a long list of mostly deleted videos over time that keeps getting reprocessed every rescan. It would be nice if we could add a bad video to the ignore list or something so that once metadata shows it's gone, subsequent rescans won't bother trying to query it. 

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Ultimately that goes into the [know limitation](https://github.com/tubearchivist/tubearchivist/tree/master#known-limitations) that if yt-dlp can't extract it, this project won't either. 

Ignoring these videos is unexpected and makes assumptions, videos might just not be available now, and will be later again, or might be regional blocking and once you switch your VPN it's becoming available again, there are probably more scenarios like that...

Not sure why your worker crashes there, you might want to look into who is sending this kill signal there, as the errors are handled within TA.

**Comment by bbilly1** [comment]
Additionally what you can do is to reduce the page size, so you don't always have to rescan the whole playlist. Also if a playlist has 250 out of 300 videos unavailable, maybe subscribing to that is not the best thing to do.
