### ISSUE TITLE
[Feature Request]: Support non-YouTube video services

### ISSUE THREAD

**Issue by salimfadhley** [tubearchivist/tubearchivist#627]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

Yes, I'm aware your FAQ states that you have no plans to support services other than YouTube. Let me explain my requirement:

I research far-right wing and conspiracy theory groups. Part of this research involves downloading content posted by these groups on their video channels. They tend not to be on YT. I would like to be able to automatically download certain channels on BitChute, Rumble, Telegram and a bunch of other lesser YT clones. 

Content posted by these groups tends to be volatile. They post a thing and then almost immediately delete their own content. It's really useful to have the ability to automatically download their content for safe keeping so that I can refer to it even if they later delete their posts.

## Describe the solution you'd like

I would like to be able to past the URL of a channel on Rumble, BitChute etc into tubearchivist and have it automatically download the content of that channel. I'd like to to automatically download new content when it becomes available. 

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Scope of this project is defined, you read the FAQ, there are currently no plans to extend this to any other platforms.
