### ISSUE TITLE
[Bug]: Manual import does not add all the stats

### ISSUE THREAD

**Issue by dot-mike** [tubearchivist/tubearchivist#629]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker

## Describe the bug

When manual import runs it is not adding all the statistics present in the `info.json` file.

Missing keys:
- like_count
- dislike_count
- average_rating

## Steps To Reproduce

- Have an old `info.json` file from before removal of dislike_count in the API from YT and import the video.
- Check the data in the ES document by doing a curl towards it: `curl elastic:$ELASTIC_PASSWORD@archivist-es:9200/ta_video/_doc/<video_id>` (replace `<video_id>` with actual video ID from YT).
- In the output see that `dislike_count` is set to 0

## Expected behavior

Manual import should try to import as much data as possible from the `info.json` file

## Example data

[ta_video_elastic.json](https://github.com/tubearchivist/tubearchivist/files/13628445/ta_video_elastic.json)
[example_ta_video.json](https://github.com/tubearchivist/tubearchivist/files/13628443/example_ta_video.json)

### Relevant log output

```shell
NA
```

**Comment by bbilly1** [comment]
The importer will always assume remote metadata is more relevant newer as local. So if a video is still available on YT, local metadata will only be used to identify the ID, if needed, and remote metadata will take priority.

For things like dislike count and average rating you have the [returnyoutubedislike](https://www.returnyoutubedislike.com/) integration, they have a good amount of videos archived there, including the one you link in your info json file: https://returnyoutubedislikeapi.com/votes?videoId=1_fvyyf6gIs.

Changing that behavior is not feasible, as this also ties into the metadata refresh task.
