### ISSUE TITLE
[Feature Request]: manually trigger rescan playlists

### ISSUE THREAD

**Issue by malfroid** [tubearchivist/tubearchivist#637]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
there seems to be no method to manually trigger rescan playlists

## Describe the solution you'd like

1. in the playlists view, add a button to trigger rescan of all playlists 
2. in the playlist detail view, add a button to trigger rescan of the current playlist

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by hawkrives** [comment]
I believe that the "rescan subscriptions" button in the Downloads tab will also rescan subscribed playlists. 

I'm not sure how to rescan an unsubscribed playlist (maybe adding it a second time? I have not tried.)

Good luck!

**Comment by bbilly1** [comment]
That's correct, subscribed playlist get rescanned for new videos on the downloads page. This project priorities automatic and bulk actions, not on an item by item basis.

**Comment by malfroid** [comment]
@hawkrives @bbilly1 this does not work for me. When I click on the "Rescan subscriptions" button on the Downloads page, my "Watch later" playlist is not refreshed. 

I am unable to refresh my "Watch later" playlist since December. According to the TubeArchivist interface, it has 12 videos. In reality, it now has 22 videos.

Example video showing the problem:

https://github.com/tubearchivist/tubearchivist/assets/3715399/8fe201a2-262c-4f7a-9e1d-4b30baee97f8

Any idea what is going wrong here?

**Comment by lamusmaser** [comment]
@malfroid: Please open a new issue with associated logs. This is not associated to this issue.

**Comment by malfroid** [comment]
I opened a new "Bug" issue: https://github.com/tubearchivist/tubearchivist/issues/653
