### ISSUE TITLE
[Feature Request]: Truenas app

### ISSUE THREAD

**Issue by Ammoton** [tubearchivist/tubearchivist#638]
It would be great to have an official app in the TrueNAS or TrueCharts catalog for easier installation in TrueNAS.

**Comment by bbilly1** [comment]
There is a very comprehensive set of instructions linked here: https://docs.tubearchivist.com/installation/truenas-scale/.

If anybody wants to add this as a community app (I think that's what it's called), please do, but this would have to be created by a TrueNAS user and supported and maintained through the TrueNAS community.

**Comment by v2thegreat** [comment]
@bbilly1 the link is broken. Do you have an updated link?

**Comment by lamusmaser** [comment]
This is no longer maintained. See PR https://github.com/tubearchivist/docs/pull/44.

**Comment by v2thegreat** [comment]
Hi, I just saw the post. Thanks for responding so quickly! I'm fairly new to truenas and everything. Could you point to where I can install tubearchivist? I've reviewed the README, tried using the helm charts, and a bunch of other things, but I've gotten nowhere
