### ISSUE TITLE
[Bug]: Downloaded videos contain no audio while played on macOS/Safari

### ISSUE THREAD

**Issue by jpm** [tubearchivist/tubearchivist#641]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology Container Manager / Docker

## Describe the bug

Thanks for the incredible work on this tool -- it was a breeze to set up, and I got going test driving Tube Archivist really quickly. I used a random channel from my subscriptions as a test, and it downloaded one of the videos successfully. When I tried to play the downloaded video, it worked as far as the video stream itself goes, but no audio plays.

Weirdly enough, the sound icon does appear on the browser window as expected, in the activated/blue color like usual, but again, no audio actually plays. I tried it with different Youtube videos and the same result on all of them.

Everything worked perfectly fine when I tested it on Google Chrome on the same Mac.

## Steps To Reproduce

* Use Safari 17.2.1 on macOS Ventura 13.6.3
* Download a Youtube video
* Play video within Safari
* Video stream plays fine, but no audio is actually present

## Expected behavior

* Audio plays as expected when the video is viewed.

### Relevant log output

```shell
The following is the only error on the web inspector console:

Unhandled Promise Rejection: Error: Error response received for message <get-frame-manager-configuration>
```

**Comment by bbilly1** [comment]
See "getting started" in the Readme or on your settings page, you'll have examples of compatible codecs for safari.

**Comment by jpm** [comment]
Ugh, my apologies. I tried the documented format value (`bestvideo[vcodec*=avc1]+bestaudio[acodec*=mp4a]/mp4`) and it's working as expected now.

Thanks again for the great work here! 😄
