### ISSUE TITLE
[Feature Request]: Ability to remove stored notification links

### ISSUE THREAD

**Issue by Nonoss117** [tubearchivist/tubearchivist#642]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
I read the doc here https://docs.tubearchivist.com/settings/scheduling/#notifications
But I didn't find the way to remove stored notification links
## Describe the solution you'd like
Add the ability to remove stored notification links

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by snailwaffles** [comment]
I can't either, it would be nice to be able to delete them.  I tried setting it to an empty string, or one with white space but nothing worked.

@Nonoss117  The title of this feature request is empty so this was hard to find.  can you please update the title?

**Comment by Nonoss117** [comment]
@snailwaffles , done. I searched few days ago to edit the title, but I didn't find the option. Today I found it :-)

**Comment by bbilly1** [comment]
With all (most) config vars, set it to `0`, zero the number to remove it. At least until we can come up with some better UI/UX there.

**Comment by Nonoss117** [comment]
Of course, I should have try this. Yes, most of var set to 0 remove the value.
It works, notifications url are removed.

I close the request

Thank's @bbilly1
