### ISSUE TITLE
[Feature Request]: Stylized Subtitles (Low Priority)

### ISSUE THREAD

**Issue by tonizombie** [tubearchivist/tubearchivist#643]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Possibly, not sure if the current video player supports stylized subtitles.

## Describe the solution you'd like
Adding support for stylized subtitles (For example RGB subtitles or where some parts show up in custom point on screen.)

## Additional context
This should be already possible with yt-dlp as it can download stylized subtitles.
Best bet would be VTT subtitle format as it already supports HTML players

Comparison of its currently displayed
![TA](https://github.com/tubearchivist/tubearchivist/assets/30530331/be4a2e75-ce51-4462-b351-c1f2909869b0)
![Youtube](https://github.com/tubearchivist/tubearchivist/assets/30530331/dd68f898-f8a7-448b-97c3-4a97576c4ca9)

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Subtitles are directly uses in the full text index, adding additional things there like html tags is going to mess up search. Besides, I doubt that this is a widely used thing on youtube.

Unlikely that we will tinker with things like that anytime soon.
