### ISSUE TITLE
[Feature Request]: Download Playlist button

### ISSUE THREAD

**Issue by mglaske** [tubearchivist/tubearchivist#645]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

Would be nice to just queue a single playlist to be downloaded.   Also, status of videos per playlist (available/downloaded)

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
You already can do that: https://docs.tubearchivist.com/downloads/#add-to-download-queue

Video progress in the Playlist like that wouldn't be feasible as videos get added to Playlist only after the download queue is finished.
