### ISSUE TITLE
[Installation]: Configure iOS 4K possible?

### ISSUE THREAD

**Issue by mietzen** [tubearchivist/tubearchivist#652]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Synology

### Your installation or setup question

This is more a Question about configuration. I set the download quality according to https://github.com/tubearchivist/tubearchivist?tab=readme-ov-file#getting-started.
But now I only get 720p with compression artifacts. 

I was wondering if it is possible to get a higher resolution. Especially because when I enable the "stats for nerds" on a youtube on my iPhone 14 it says that it is playing vp9 / opus??? I thought that this isn't possible. 

![How light can appear faster than c, why it bends, and other questions  Optics puzzles 4 - YouTube](https://github.com/tubearchivist/tubearchivist/assets/31704359/22583327-5ea6-467a-8903-1474c66ad0ee)

### Relevant log output

```Shell
-
```

**Comment by bbilly1** [comment]
This looks like a question about format selection, see the yt-dlp repo for a very extensive overview how that works, these details are beyond the scope of this repo here, the example in the readme is just a quick way how you can target a compatible codec for mac devices so these videos can be played in the browser, but you can obviously adjust that to your liking.

The video you took a screenshot off, downloaded with the format string in the example `bestvideo[vcodec*=avc1]+bestaudio[acodec*=mp4a]/mp4` gives a very crisp 1080p video as expected, at least for me:

![2024-01-15_13-22-14-screenshot](https://github.com/tubearchivist/tubearchivist/assets/35427372/135d992c-6f1a-46f0-99c7-a29a913c1742)

Not sure about 4k though...

You can experiment with using standalone yt-dlp and use the `--simulate` flag while specifying the `--format`. Use `--list-formats` to get a list of all available. Again, yt-dlp repo has all the details. Also sometimes YT doesn't process all formats for all videos...

**Comment by basdp** [comment]
I know this is closed and I hate to bump an old thread, but I also know this ranks high on Google if you search for 4K support in iOS. This is the string that works for me on the latest iOS version:
`bestvideo[vcodec*=vp9]+bestaudio[acodec~='^(mp?4a|aac|opus)']/mp4`
