### ISSUE TITLE
[Installation]: Rescan Subscriptions and Start Download via Commandline

### ISSUE THREAD

**Issue by TjohAGq6VQWLt7gKMo** [tubearchivist/tubearchivist#656]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Debian

### Your installation or setup question

Hi All - 

Can you manually start the "Rescan Subscriptions" and "Start Download" processes via the command line?

I would like to have a bit more control than the current built-in schedule configuration options.

Much appreciated.

### Relevant log output

```Shell
N/A
```

**Comment by bbilly1** [comment]
There is an API for such occasions. The docs has you covered.
