### ISSUE TITLE
[Feature Request]: Create Playlist in Jellyfin that matches playlist on youtube.

### ISSUE THREAD

**Issue by theblujuice** [tubearchivist/tubearchivist#659]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Describe the solution you'd like
Thank you for your amazing work.
I currently download youtube music videos based off a playlist I have on youtube. This is then added to Jellyfin with the tubearchivist-jf container. Is there any way it can automatically create / manage a playlist in Jellyfin that matches the youtube playlist it is actively downloading?
### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
Discussed and answered here: https://github.com/tubearchivist/tubearchivist-jf/issues/25
