### ISSUE TITLE
[Feature Request]: Preserve Playlist position of videos removed from youtube

### ISSUE THREAD

**Issue by BobanAliBrz** [tubearchivist/tubearchivist#661]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Im using Tube Archivist to backup my Favorites playlist on yt, as this playlist is full of hundreds of random videos it is very common for many videos to just be deleted by creators or removed by youtube. Right now when a video is removed and the playlist is reindexed the video loses it's position in the playlist and drops to the bottom of the list. 
For me preserving the positions of videos is very important as i see my favorites playlist as a kind of personal history, more than that tho i imagine this would be a very useful feature to have in general for people archiving series playlists on youtube that is not numbered in the title.
## Describe the solution you'd like
**I think there are two ways this can be done:**
1. For youtube to allow youtube-dl to detect a removed videos position and id, which im pretty sure it can't do right?
2. What could work is manually setting the position via a dummy video, for example a video gets removed and i copy it's id from tube archivist and then on my channel upload an unlisted video(contents dont matter) and set the title as the removed videos id and maybe a keyword to detect it's on purpose, then put that video where the removed video was in the playlist. Then tube archivist could basically set that videos position and existence to the removed video. If you were wondering how to determine where that video was if multiple were removed you could just show unavailable vids on yt and see in what order Archivist put those vids and determine which one goes where. 

What do you guys think?
### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
youtube hides unavailable videos in the playlists, you can click on the three dots then "Show unavailabe videos" on the YT interface, but I'm not aware that yt-dlp implements the same. Without that, the position will become undefined. Ultimately, a workaround for that would have to come from yt-dlp's side. 

For TA, the video will still be associated with the playlist, but as you said, won't have a position. 

Closing this as won't fix as this would have to be implemented upstream.
