### ISSUE TITLE
[Installation]: domain subfolder possible?

### ISSUE THREAD

**Issue by lgwapnitsky** [tubearchivist/tubearchivist#668]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Linux

### Your installation or setup question

Piggybacking off of #400 , is it possible to configure this to run behind a proxy as a subfolder instead of its own subdomain, e.g. pharlap.horse/tubearchiver?

### Relevant log output

```Shell
n/a
```

**Comment by bbilly1** [comment]
Not officially, most people will use subdomains with their proxy to avoid the plexity with paths like that.

This has an example: https://github.com/tubearchivist/tubearchivist/pull/664
