### ISSUE TITLE
[Bug]: Cookies acting weird when enabling when it's already enabled

### ISSUE THREAD

**Issue by Iliannnn** [tubearchivist/tubearchivist#672]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
When enabling cookies when it's already enabled through the Companion extension it throws an error and revokes the cookies:
https://github.com/tubearchivist/tubearchivist/assets/72648901/286d855c-708e-4329-b611-2c5fef638d9e

## Steps To Reproduce
1. Enable 'Sync YouTube cookies' in TubeArchivist Companion.
3. Reload YouTube so the cookies can take effect.
4. Now the cookies are enabled in TubeArchivist.
5. Go to Settings > Application > Cookie in TubeArchivist and set 'enable cookie'.
6. Update Application Configurations
7. It will now throw the error 'Cookie import failed. Cookie file not found' and revoke the cookies.
8. The cookies are now disabled, revoked and can't be enabled again (see Settings > Application > Cookie in TubeArchivist)
9. To re-enable the cookies re-enable 'Sync YouTube cookies' in TubeArchivist Companion and reload YouTube for the cookies to take effect.

## Expected behavior
Instead of revoking and disabling the cookies it should just ignore the update because the cookies are already enabled, just like any other option handles this.

### Relevant log output

```shell
{'subscriptions_channel_size': None, 'subscriptions_live_channel_size': None, 'subscriptions_shorts_channel_size': None, 'subscriptions_auto_start': '', 'downloads_limit_speed': None, 'downloads_throttledratelimit': None, 'downloads_sleep_interval': None, 'downloads_autodelete_days': None, 'downloads_format': '', 'downloads_format_sort': '', 'downloads_extractor_lang': '', 'downloads_add_metadata': '', 'downloads_add_thumbnail': '', 'downloads_subtitle': '', 'downloads_subtitle_source': '', 'downloads_subtitle_index': '', 'downloads_comment_max': '', 'downloads_comment_sort': '', 'downloads_cookie_import': '1', 'downloads_integrate_ryd': '', 'downloads_integrate_sponsorblock': '', 'application_enable_snapshot': ''}
cookie: /cache/import/cookies.google.txt file not found
cookie: import failed, file not found
cookie: revoked
```

### Anything else?

As seen on Discord: https://discord.com/channels/920056098122248193/1214929974851674112

**Comment by bbilly1** [comment]
That's expected, you might want to update your cookie as that can get revoked on YT server side. I've updated the wording slightly to clarify.

**Comment by Iliannnn** [comment]
Sounrs good
