### ISSUE TITLE
[Feature Request]: Improve /api/task-name/update_subscribed/ to Return Found Videos

### ISSUE THREAD

**Issue by Iliannnn** [tubearchivist/tubearchivist#675]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Currently, the `/api/task-name/update_subscribed/` task returns limited information, making it challenging to retrieve details about found videos. This poses a problem for users who wish to track new video uploads efficiently.

## Describe the solution you'd like
I propose improving the `/api/task-name/update_subscribed/` endpoint to include detailed information about the videos it finds. This could involve modifying the response to include a list of found videos along with relevant metadata such as video IDs, titles, timestamps, etc.

## Additional context
The current response from `/api/task-name/update_subscribed/` only provides basic information:
```json
{
    "message": {
        "task_id": "de6bb10c-9aa3-4d1b-9139-a561c20b71f8",
        "status": "PENDING",
        "task_name": null
    }
}
```
This lack of descriptive information makes it difficult to track new video uploads effectively. By improving the API to return details about found videos, users would be able to create scripts for scheduling rescans and sending notifications, thereby improving their ability to monitor updates.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
That is not feasible. That API endpoint triggers a background task and returns immediately, without knowing how many items will be found. That will take an arbitrary amount of time, so we can't wait for that.

You can query the task ID returned and monitor that until the task finishes to get more info out of that.
