### ISSUE TITLE
[Bug]: Custom banner not updating immediately on client side

### ISSUE THREAD

**Issue by Iliannnn** [tubearchivist/tubearchivist#679]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
Setting a custom banner via `/cache/channels/` does not immediately update the banner on the client side. However, after a few days, the banner appears to update.

This is likely related to caching in either Nginx or Django, browser has been eliminated as seen in [this Discord thread](https://discord.com/channels/920056098122248193/1215018106003398707).

## Steps To Reproduce
1. Set a custom banner via `/cache/channels/`.
2. Observe that the banner does not update immediately on the client side.
3. After a few days, check again to see if the banner has updated.

## Expected behavior
The custom banner set via `/cache/channels/` should update immediately on the client side without any delay.

### Relevant log output

```shell
Not applicable here.
```

### Anything else?

![image](https://github.com/tubearchivist/tubearchivist/assets/72648901/368ae94c-6080-4385-8d60-5722e3034274)
![image](https://github.com/tubearchivist/tubearchivist/assets/72648901/08b060ce-f121-4f41-8d09-667cd855134e)

**VS.**

![image](https://github.com/tubearchivist/tubearchivist/assets/72648901/9ec07253-c222-4709-b11d-807a1a9698c0)

**Comment by bbilly1** [comment]
That will get cached in the browser. Full refresh e.g. Ctrl+Shift+r in Firefox, or clearing cache should work.

You'll probably also want to overwrite `/app/static/img/default-channel-banner.jpg` in the container by mounting your own, as that will get updated with the metadata refresh. 

But ultimately, not a bug as that is not a feature.

**Comment by Iliannnn** [comment]
Yeah, browser refresh without cache does nothing. Like mentioned it looks like Django caches it. Updating default-channel-banner.jpg will work for me though.
