### ISSUE TITLE
[Bug]: Channels with 'Index playlist' enabled: Unsubscribe button is displayed for the playlists that I don't subscribe

### ISSUE THREAD

**Issue by trinhit** [tubearchivist/tubearchivist#684]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker on Synology

## Describe the bug
For the playlists that I don't subscribe to, it should display the Subscribe button. However, for the channels that have the feature 'Index playlist' enabled, the playlists of that channel have the Unsubscribe buttons while I don't subscribe to those playlists.

See the following screenshot:
![2024-03-16_18-25-44](https://github.com/tubearchivist/tubearchivist/assets/7093092/04e79e7c-64bb-47a1-aa08-fd8964e8b0d4)
I don't subscribe to any of those playlists. However, the Unsubscribe buttons are displayed.

To make sure, I click on one of those playlists. This is what I saw:
![2024-03-16_18-29-12](https://github.com/tubearchivist/tubearchivist/assets/7093092/fb947e16-872f-46e2-a161-97e8c2f04ffe)
The Subscribe button is displayed for the playlist. It is correct because I don't subscribe to it.

From here, I can tell that the Playlists page of a specific channel is incorrectly displaying the Subscribe/Unsubscribe buttons.

## Steps To Reproduce
Step 1: Go to **Downloads** page. Click on **Add to download queue** button. Paste a channel link into it (ex: https://www.youtube.com/channel/UCOmHUn--16B90oW2L6FRR3A). Click on **Download Now** button. Wait for it to extract all items.

Step 2: Go to **Channels** page. Click on the page that you've just added on Step 1. Go to **About** page. On the 'Index playlists' combo box, change to **Enable playlist index**. Click on **Save Channel Overwrites** button.

Step 3: Wait for a few (or all) videos to be downloaded.

Step 4: Go to the page of that channel again. Now, the **Playlists** tab should be populated. Click on it. You'll see the Unsubscribe buttons being displayed for the playlists while you don't subscribe to any.

## Expected behavior
The Subscribe/Unsubscribe buttons should be correctly displayed for playlists.

### Relevant log output

```shell
None
```

**Comment by bbilly1** [comment]
Thanks for reporting, that's now fixed through v0.4.8. please update.
