### ISSUE TITLE
[Feature Request]: Better UX Flow that matches Youtube's flow.

### ISSUE THREAD

**Issue by ns-mglaske** [tubearchivist/tubearchivist#685]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

Problem:
With large channels or playlists, or channels with playlists, I feel like I don't have a lot of control over what it is doing, or is going to do.  For instance, take these scenarios, which seem cumbersome to manage:
- I want to add a channel, and see the playlists associated with it, and download all of one playlists, and watch some others for new media.
- I want to go back to a channel, and download another entire playlist.
- After adding a playlist, that had 7 videos, only (3) showed on the playlist page, so the current view is more of a status than an activity page (eg, I can't really tell it what to do with this playlist).
- Scrolling through huge lists of episodes without knowing which channel / playlist they're in is not imo very useful.
- The downloads page, shows the 'queue', but these are not really in the 'queue' for downloading, they're just available.

## Describe the solution you'd like
My personal suggestion would be to follow a flow for adding content:
- Add the channel should be the first step, from there,  you can select everything else, since all videos have a channel.
- TA pulls the channel details, but not content (videos, playlists, shorts)
- There is a screen for the channel that shows videos, playlists, etc (just like youtube),  but the option to exclude videos from the video list that are already in a playlist.
- There is an option for each (Channel, Playlist, Video) for add-to-queue, and whether or not to download new videos.
- Playlists should show the date range that they cover, and the number of episodes, and the file storage size.
- When playlists are added to Plex, they should use the playlist name as the season name, and import the playlist description as the summary for the season. 
- There is a screen that shows the current download queue (what videos are being actively downloaded).
- There is an option to pause downloads in the queue for a given Channel, or Playlist.
- I can navigate down the tree easily (select a channel, select a playlist, show videos and their current status).  For instance, I would like to view a playlist, and then show which videos I've downloaded already, and which are available to be added to the queue.
- Allow delete all videos for (channel, playlist), and individuals.

## Additional context
I love a lot about the platform you've built, please take my comments as constructive criticism.  Please keep up the good work!  I might be way off base with this, but all I ask is to get the community feedback on my suggestions and see where it goes.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
A good amount of these things are already implemented like that or you can already do with other steps or are planned and will happen at some point.

Please follow the "how to", a huge wall of things like that will never be completed and is ultimately not really useful as a feature request for this project. You saw, current list of planned things is likely going to keep us busy for years to come.

This project will improve, but probably in small iterations.

**Comment by ns-mglaske** [comment]
Totally agree.  I just felt it warranted a big-picture view, otherwise wouldn't make much sense.  Thanks for the response!

I think the primary thing, is that I'd like to see all items in a playlist, regardless of whether I've archived them or not, and I can't seem to find out how to do that.

Thanks again!

**Comment by bbilly1** [comment]
Only items archived will be able to show, as that is what gets indexed. This project doesn't try to be an alternative front-end to YT.
