### ISSUE TITLE
[Bug]: Downloaded videos disappearing from filesystem

### ISSUE THREAD

**Issue by PhuriousGeorge** [tubearchivist/tubearchivist#687]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Unraid

## Describe the bug
During container restart, console identifies that videos are not being found in expected location.

Each time this has occurred the vtt files are still in the folder and their `date modified` has been updated.  I've not seen anything suspicious within logs I've been able to capture.

Don't want to lead the jury, but I highly suspect this is occurring during refresh activities due to file modification and the fact that none of my non-live channels have been affected.  I suspect that thumbnail or metadata embeds are occurring and potentially failing, causing the videos to not be re-deployed to the folder?  I've also noticed this typically coincides with when my subscribed channel scan fails and stops with the celery worker being killed mid-scan.

Reference [Discord discussion](https://discord.com/channels/920056098122248193/1216929393885052958)

## Steps To Reproduce
I've not been able to force failure to occur.

## Expected behavior
Never loose a file except if auto-delete is selected, manually deleted, or filesystem/hardware failure.

### Relevant log output

```shell
# Filesystem Migration #
########################

    migrating channels
    created 1 channels
    migrating 13 videos
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/v6zgmhsCLnc.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/utIl6b5-KPE.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/ngEhgqGlyjQ.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/nbfgFyfHSMU.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/n07D23Y-OG8.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/n0v0jUeFGQ0.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/llwwKkuy5gI.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/lhSjYT7pWkw.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/rbFYsYMA3No.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/pUanS5OWy_k.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/pMXwFlp9IoI.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/qNQ2kV1OTPU.mp4
did not find expected video at /youtube/UC-0dXntqR76zT7b3-iB7Q1g/l8ayD71cXYs.mp4
    update videos in index
nothing to update
    cleanup old folders
```

**Comment by lamusmaser** [comment]
Acknowledged and discussing here: https://discord.com/channels/920056098122248193/1216929393885052958

**Comment by bbilly1** [comment]
I'm guessing this is happening because of the filesystem migration check that is running at application startup. That shouldn't be finding any new things to migrate.

We can remove that, that has been a few months ago by now.

**Comment by PhuriousGeorge** [comment]
Still been trying to figure this out, but not having any luck.  The videos were confirmed in the location prior to this happening.  Does any of the prior migration steps potentially remove files?

**Comment by bbilly1** [comment]
The only ting that would delete videos on a filesystem level would be this migration path.

All other places deleting something will also delete it from the index, e.g. auto delete watched, or delete from the video detail page.

From the log output, the migration shouldn't get triggered anymore, but still does for some reason, so that makes me think this should be the culprit.

**Comment by bbilly1** [comment]
v0.4.7 removes the migration from startup, hopefully fixing that. if not, please reopen with more details.
