### ISSUE TITLE
[Feature Request]: More option for yt-dlp

### ISSUE THREAD

**Issue by farjar** [tubearchivist/tubearchivist#689]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Describe the solution you'd like
I have subscribed to some playlists, and it is set up to automatically download new videos when they are published. However, there are few videos with a duration of less than 1 minute. Is there an option to set a filter condition for yt-dlp to ignore these videos?
### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by RafaelSchridi** [comment]
I was also looking for this to exclude music, streams and shorts from my liked playlist.

**Comment by CommanderRedYT** [comment]
I was also looking for this to be able to skip multiple-hour long videos

**Comment by bbilly1** [comment]
There are a bunch of ideas like that, on the roadmap and other issues, by duration or by keywords, regex, these kind of things.

There are a lot of pending requests already, including #415.

Adding major things like that is probably quite far away and unlikely to happen before we had the time to implement a proper testing suite.

This project is currently focusing on overall application improvements and probably won't add major new features.

Please help with overall improvements, maybe you want to take a stab at: #564?

**Comment by bbilly1** [comment]
closing this for now. there are other issues already open for additional yt-dlp filtering options. but current focus is on improving existing functionality, not adding more.
