### ISSUE TITLE
[Feature Request]: Add new menu to show recently downloads videos not yet viewed

### ISSUE THREAD

**Issue by ccfman2004** [tubearchivist/tubearchivist#692]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request
To be able to easily see newly archived videos that haven't been viewed.

## Is your feature request related to a problem? Please describe.
There is currently no way to see unwatched newly archived video in TA.

## Describe the solution you'd like
Add a new section that shows recently added videos that haven't been viewed similar to the "Continue to watch section AKA the Home menu". As I am subscribed to over 150 channels it would be nice to be able to see what's new without having to check each channel manually. 

If there is already a way to show recently archived unwatched videos please let me know.

## Additional context
YouTube shows a dot in the channel list next the each channel that has a new unwatched video.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
You can already do that. on the homepage sort by date downloaded and hide watched.

**Comment by ccfman2004** [comment]
I didn't even know that section existed as it's so far down. I never had a reason to scroll that far down as I didn't care about the "Continue to Watch" section and didn't know anything else existed after that section.

Maybe an option to hide the "Continue to watch" section?

**Comment by bbilly1** [comment]
If you get too many times there, you can always mark them as watched, or toggle them back to unmatched.

Also next release has some improvements to only send progress after a few seconds and not immediately. That should help too.

**Comment by ccfman2004** [comment]
I have over 66,000 unwatched videos right now. so that is not really an option. A way to hide the "Continue to Watch" is really the only option. Many sites and apps would use a "sideways and downward arrows for expanding and collapsing sections.  Is that a possibility.

**Comment by bbilly1** [comment]
Continue watching only shows the videos you have started watching.
