### ISSUE TITLE
[Feature Request]: Support for Whisper Transcription

### ISSUE THREAD

**Issue by apiweb** [tubearchivist/tubearchivist#693]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
TubeArchivist is fantastic for managing and enjoying YouTube videos offline, but it will be very nice if adds support for [Whisper](https://github.com/openai/whisper) transcription.

## Describe the solution you'd like
I'd love to see TubeArchivist integrate whisper transcription support into its feature set. Specifically, when a video finishes downloading, it would be fantastic if TubeArchivist could automatically generate accurate text transcriptions for the content. This feature would greatly enhance the accessibility and usability of TubeArchivist.

## Additional context
It's worth noting that TubeArchivist already utilizes Python, which makes it well-suited for incorporating whisper transcription functionality.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
There is already autocaption from YT implemented, kind of like whispers but generated from YT.

Unlikely that we'll ever implement additional integrations like that.
