### ISSUE TITLE
[Bug]: Downloads page stop button ambiguous

### ISSUE THREAD

**Issue by erentar** [tubearchivist/tubearchivist#694]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
the square shaped stop button here looks like a checkbox
![image](https://github.com/tubearchivist/tubearchivist/assets/40326736/42a6d434-6952-433e-9481-32f7861ae68d)

maybe use another shape like https://unpkg.com/ionicons@7.1.0/dist/svg/close-circle-outline.svg

## Steps To Reproduce
navigate to the downloads page

## Expected behavior
better distinguishable action from the icon, less ambiguity

### Relevant log output

```shell
irrelevant
```

**Comment by pairofcrocs** [comment]
I never noticed it, but I tend to agree.

@bbilly1 would you like me put in a PR for this?

**Comment by bbilly1** [comment]
I mean, that looks like a stop button, no? If you google "stop button icon", that's what you you'll get.

We had a cancel button there at some point, looking like that in red: https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/static/img/icon-close.svg. But that functionality got lost during refactoring the background task handling, not offering a convenient cancel interface any more. 

But I plan to implement that again, at least at some point. At least for the download task.

So any icon suggestions would have to be able to live *next* to the cancel icon. But I'm open for suggestions.

**Comment by bbilly1** [comment]
Closing this, Don't think that is a problem. Also you have the title info there as well on hover, when in doubt. And once we have the cancel button back, that will become even clearer.
