### ISSUE TITLE
[Feature Request]: Video selection for (batch) actions

### ISSUE THREAD

**Issue by xusiai** [tubearchivist/tubearchivist#695]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Actions - like deleting videos or marking items as watched - are applicable on an entire channel or an individual video but offer no in between e.g. removing a selection of videos (at once).
## Describe the solution you'd like
Ability to select (multiple) videos for an action. 
## Additional context
It is extremely tedious having to navigate to each individual video's page in order to delete it when you want to remove more than a few - but not all - videos. Even more so when you want to remove all videos of a certain topic (i.e. also requiring the use of the search function in between each video removal). 

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by supertom44** [comment]
This would be awesome, I like to manually delete videos in batches, but it's very tedious to do so at the moment.
I've wondered if there should be an action to force delete all videos marked as watched.

**Comment by bbilly1** [comment]
In general a good idea, but that's unlikely to happen without some more sophisticated frontend than what we have now.

That may or may not happen at some point in the future, but currently that is not realistic to be implemented any time soon.
