### ISSUE TITLE
[Feature Request]: get a formated video name when downloading

### ISSUE THREAD

**Issue by org0000h** [tubearchivist/tubearchivist#698]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
The downloaded video is also named as an id which is not nice to find and manage for user . Is it posible to rename the downloading video ?
## Describe the solution you'd like
I know tubearchivist save videos as ids for index and management,but I think it is better to give user a renamed downloading video.
As to an implement way for example ,create an nice named symbolic file before downloading ,delete it after downloading.
iI think it is greate if can be done.
### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
We tried and failed to make naming more flexible. Ultimately title can be any unicode character and we can't assume where this file will go, what OS, what filesystem and what capability that will have.

If you want to do something like that, you'll have to do that through the API and adapt it to your requirements. Maybe a bash function?

But we won't touch that again here in the foreseeable future.
