### ISSUE TITLE
Airplay not working on Apple TV. Any ideas why?

### ISSUE THREAD

**Issue by trick77** [tubearchivist/tubearchivist#703]
When I'm trying to route the video playback over Airplay directly from the TubeArchivist UI in Safari on my Mac or iPad, my Apple TV only shows a red circle/forbidden icon. However, if I download the exact same file first and play it in Safari, Airplay just works.

I use the recommended Apple-compatible yt-dlp settings (avc/aac) in TubeArchivist (or the videos wouldn't even play on the iPad).

Does anyone have an idea what could be going on here?

**Comment by bbilly1** [comment]
Any logs on TA docker when the TV tries to play that? Don't skip the issue template, that's there for a reason.

**Comment by trick77** [comment]
Didn't want to use it since it's neither a Bug or Feature :-) 
I will have a look and report back.

**Comment by bbilly1** [comment]
any progress?

**Comment by trick77** [comment]
Nothing in the log, nothing in the browser console. I extracted the video page including the scripts and it Airplays fine in a docker nginx. Same html page served through TA doesn't. Some headers seemed different though but I was unable to determine if that is the cause.

**Comment by puppe** [comment]
Maybe AirPlay (like Google Cast) does not support authentication? Just a thought.

**Comment by bbilly1** [comment]
Does it load just the video? E.g. just he mp4 file? Or does it pass the whole TA interface to the TV?

Would have thought that auth might not get passed correctly. You can activate cast, that removes the authentication.

**Comment by puppe** [comment]
I just tried it. Setting ENABLE_CAST did the trick for me.

**Comment by trick77** [comment]
Yay, that was it! Or part of it. I was sure I played around with ENABLE_CAST before but the same error showed up. I didn't realise Airplay, like Google Cast, just passes the video URL to the device and nothing else.

Since I'm using a combination of Traefik and Authentik in forward auth mode in front of TA, TA is in TA_ENABLE_AUTH_PROXY=true mode. Authentik intercepts the unauthenticated direct calls to the video URLs.
I needed to add a regex in Authentik's TA provider in the unauthenticated paths section (advanced settings):
^/cache/videos/\d+/\w+\.jpg$
^/media/[a-zA-Z0-9_-]+/\w+\.mp4(?:#\S+)?$

Not sure if the poster URL is required but I added it anyway. The Regexes probably can be improved but seem to work for the time being. I don't mind passing these URLs through unauthenticated, there's enough random characters in the path and/or filename.

**Comment by bbilly1** [comment]
OK, glad you got it working. And thanks for sharing your findings.

**Comment by bjappler** [comment]
I tried it too. Unfortunately Setting ENABLE_CAST is not working for me. I am running on v0.5.0.

**Comment by bbilly1** [comment]
That is outdated now. See the release for v0.5.0 with all the changes: https://github.com/tubearchivist/tubearchivist/releases/tag/v0.5.0

Disable authentication can now be done explicitly: https://docs.tubearchivist.com/installation/env-vars/#disable_static_auth

**Comment by bjappler** [comment]
I enabled "Enable Cast" under Application Settings and I added the enviromental variable DISABLE_STATIC_AUTH=true, but I it is still not possible to use airplay.
Can I do anything else?

**Comment by trick77** [comment]
I haven't look in great detail but it seems that 
https://github.com/tubearchivist/tubearchivist/blob/ac7ce2ce3c169276b5fd6416da943f75d60a5db0/backend/config/management/commands/ta_envcheck.py#L180
is not triggered, even though the env-var is set. The auth_request lines are still present in the nginx config.
Which leads to a api/ping response 403 on my Apple TV. But again, that was just a very quick assessment and I could be wrong.

**Comment by bjappler** [comment]
Is Airplay working in your configuration? Otherwise I would reopen this issue.

**Comment by trick77** [comment]
I just submitted a small PR which will fix it.

**Comment by bjappler** [comment]
Great, thank you very much. Will you inform me, when the update ist available for testing?
