### ISSUE TITLE
[Feature Request]: Button to immediately delete all watched videos

### ISSUE THREAD

**Issue by V4ler1an** [tubearchivist/tubearchivist#705]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Describe the solution you'd like
A button which immediately deletes all watched videos.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by DevonDekhran** [comment]
Adding to this bulk delete request, it would be very useful and less time consuming if we could have check-boxes (say, when inside a channel or playlist), to multi-select and delete specific videos without going through each of them individually.

**Comment by bbilly1** [comment]
Delete watched after x days is implemented as a download post processing step. So this can be mostly automatic and doesn't need another button.

Focus of this project is archiving, that's where the focus will be.
