### ISSUE TITLE
[Feature Request]: ability to subscribe to channel in rolling fashion (ie, subscribe, but delete after x weeks to only keep the latest videos)

### ISSUE THREAD

**Issue by arisenfromtheashes** [tubearchivist/tubearchivist#706]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
no
## Describe the solution you'd like
I see this as an alternate to the current archive method. Currently you pick a channel to subscribe to, and in settings how many videos to grab and whether to delete after watching. 
This would be a setting or checkbox under each subscription where you could chose a 'rolling' subscription method. It would ignore the global settings for download and retention. Instead it would grab the latest X days/weeks of videos and keep that list current, adding new ones as released and removing old ones as they expire even if not watched. (odds are if you haven't watched it yet, you wont  -  and if it was so important, you wouldn't have the channel set to rolling)
## Additional context
I foresee an issue where you have a channel on a rolling subscription, and normally you consume and then never again consider watching. However randomly or every so often the creator has a profound video you want to keep. If you download that video using regular settings, and then the 'rolling' functionality kicks in, how do you make it ignore older videos you intend to keep?

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
That would be a major change with how this application functions. So that is unlikely going to be implemented like that.

Autodelete is implemented already with the watched list. If you want to regularly clear your channels, you could mark them as watched, then that would get deleted automatically.

But focus of future improvements will be on archiving, which means keeping the videos.

**Comment by arisenfromtheashes** [comment]
I’m guessing that when you subscribe to a channel there is a function that looks at the current retention settings (ie how many historical videos to go back and grab) and then does a search and grabs them. My issue is that when I sub to a channel for archival it grabs everything. I don’t really want that for these type of videos. TA does the archive part perfectly for me. At least it’d be nice to have if not per channel retention settings at least two sets of settings. Then when it looks for retentions settings if some flag is set it looks at a different set of settings. On the delete side I’m guessing your auto process scans the library(if enabled) and looks for watched status? Could there be a similar process that looks for videos that have the aforementioned different settings flag and it has them, looks at the date downloaded and if date downloaded - todays date >= “X”weeks/days delete itYou are correct I don’t know your code and how you have it architected. But I am from a scripting background and am just trying to help think through possible logic for the process. I love the product as it is and it works well for me. I’m just trying to see if it can do more for what I’d like to do with it. On May 6, 2024, at 3:49 PM, Simon ***@***.***> wrote:﻿
That would be a major change with how this application functions. So that is unlikely going to be implemented like that.
Autodelete is implemented already with the watched list. If you want to regularly clear your channels, you could mark them as watched, then that would get deleted automatically.
But focus of future improvements will be on archiving, which means keeping the videos.

**Comment by arisenfromtheashes** [comment]
That right there is definitely half the battle. That would take care of part one. Part two would just be if there’s another way to mark episodes for deletion other than just watch status. Again thank you for the work you’re putting into it.On May 6, 2024, at 4:08 PM, Simon ***@***.***> wrote:﻿
Per channel page size is coming up, there is a proposal here: #702. That will happen at some point.

**Comment by arisenfromtheashes** [comment]
is there a way to automatically mark videos as watched? i watch in plex via the TA plex plugin. either sync watch status or just mark in TA automatically. i have videos set to delete after 3 weeks if watched, so in effect this would accopmplish what i was after.  
also sorry to hit up my old thread. just wanted to ask

**Comment by arisenfromtheashes** [comment]
Awesome. Thank you so muchOn Nov 25, 2024, at 9:31 PM, lamusmaser ***@***.***> wrote:﻿
A feature request for this capability is already opened.

**Comment by arisenfromtheashes** [comment]
I know you said you didnt want to create this, and Im sorry to resurrect an old thread, but.....

You kinda already are half way there with the auto remove 'watched' videos setting. I have a selection of channels to archive completely, and some that I want to download, watch, and then can be discarded. Those I already have set the remove after watching, to a week or so. 
So, my situation is I consume my content via Plex and the plugin, and I know that there is a solution in the works for syncing watch status, but that wont work for all of my content. Some of the creators I subscribe to, I dont watch every video. Id like a solution that doesnt require me to click on every single video and mark watched or go into every single channel and mark whole channels as watched. Itd be nice to have a page or list of channels, where you can mark or otherwise choose channels to 'auto mark watched' via a daily cron job or something similar. 

I dont know your code well, and Django is way over my head, but I did try to use chatgpt to pull in your code and make a suggestion for this. Im trying to contribute, I hope this is useful:

import requests

# Replace with your TubeArchivist instance URL
base_url = 'http://localhost:8000'

# List of channel IDs to mark as watched
channel_ids = ['CHANNEL_ID_1', 'CHANNEL_ID_2']

# Function to mark all videos in a channel as watched
def mark_channel_as_watched(channel_id):
    url = f'{base_url}/api/channels/{channel_id}/mark_watched/'
    response = requests.post(url)
    if response.status_code == 200:
        print(f'Successfully marked all videos in channel {channel_id} as watched.')
    else:
        print(f'Failed to mark videos in channel {channel_id} as watched. Status code: {response.status_code}')

# Iterate over the list of channels and mark as watched
for channel_id in channel_ids:
    mark_channel_as_watched(channel_id)



I know this is basic code and the list is explicitly enumerated at the top of the code but I wonder if it could be a page with checkboxes that populates this list. 

If you still dont want to put time to this I understand. I just thought Id ask.
