### ISSUE TITLE
[Bug]: Cannot index playlists

### ISSUE THREAD

**Issue by CrazyWolf13** [tubearchivist/tubearchivist#710]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu

## Describe the bug

I'm trying to subscribe to a channel, enabled the index playlist, it scans 12 playlists, I see the correct names in the terminal of the container, but they are nowhere to be found on tubearchivist, nor can they be downloaded, so where are they indexed to?

I'd like to subscribe to a channel and let tubearchivist automatically download and update that playlist to local NAS, also do this by default for any new playlist, is that possible?

### Relevant log output

```shell
| [2024-05-06 15:37:02,730: WARNING/ForkPoolWorker-8] PLCvX74b4S-GsbfTEOQXVl3-9EW59lJaRI: get metadata from es
tubearchivist    | [2024-05-06 15:37:02,734: WARNING/ForkPoolWorker-8] {"_index":"ta_playlist","_id":"PLCvX74b4S-GsbfTEOQXVl3-9EW59lJaRI","found":false}
tubearchivist    | [2024-05-06 15:37:02,735: WARNING/ForkPoolWorker-8] PLCvX74b4S-GsbfTEOQXVl3-9EW59lJaRI: get metadata from youtube
tubearchivist    | [2024-05-06 15:37:03,222: WARNING/ForkPoolWorker-8] WARNING: [youtube:tab] YouTube said: INFO - Unavailable videos are hidden
tubearchivist    | [2024-05-06 15:37:03,865: WARNING/ForkPoolWorker-8] add playlist: Malle Party
tubearchivist    | [2024-05-06 15:37:03,869: WARNING/ForkPoolWorker-8] PLCvX74b4S-GsCwkok1zIbdtHmethtvjaM: get metadata from es
tubearchivist    | [2024-05-06 15:37:03,873: WARNING/ForkPoolWorker-8] {"_index":"ta_playlist","_id":"PLCvX74b4S-GsCwkok1zIbdtHmethtvjaM","found":false}
tubearchivist    | [2024-05-06 15:37:03,873: WARNING/ForkPoolWorker-8] PLCvX74b4S-GsCwkok1zIbdtHmethtvjaM: get metadata from youtube
tubearchivist    | [2024-05-06 15:37:04,799: WARNING/ForkPoolWorker-8] add playlist: Christmas mix
```

### Anything else?

Probably again a user config error -_-

**Comment by CrazyWolf13** [comment]
> Please review the documentation for playlists. If your question is still unanswered, please let us know and reopen.
> 
> https://docs.tubearchivist.com/playlists/

Hi after carefully reading through this wiki, they seem not to cover my issue/question, although still thanks for linking.

Thank you for taking a look at this.

**Comment by bbilly1** [comment]
Also look at the channel doc page, it's mentioned that playlist will get added once there is at least one video downloaded.

In general, spend a few days, playing around, when in doubt check out the docs. Then for generic questions like that, we also have a discord.

**Comment by CrazyWolf13** [comment]
> Also look at the channel doc page, it's mentioned that playlist will get added once there is at least one video downloaded.
> 
> In general, spend a few days, playing around, when in doubt check out the docs. Then for generic questions like that, we also have a discord. 

Thanks, yeah was not sure if it's a bug or not as the terminal log told me it added the playlist but i never saw them in any queue or so.

Thank you for the hint with the discord.
