### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Profomedia** [tubearchivist/tubearchivist#711]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
downloads the video with id, 

## Describe the solution you'd like
 I would prefer it to be slapped with its name.  the code in ytldp .

## Additional context
muchas gracias

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by Profomedia** [comment]
the downloaded video to have it's Youtube name instead of id.

**Comment by bbilly1** [comment]
That's not desired, we had lots of problem with that before. Also see FAQ and read Contributing.md.
