### ISSUE TITLE
[Bug]: Youtube Streams that are in the future should not be added to queue yet

### ISSUE THREAD

**Issue by Emporea** [tubearchivist/tubearchivist#714]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux Docker

### Your Bug Report

When rescanning subscriptions manually or via cron i am getting the message that some new videos got found and that they will be added to the queue. But the queue is empty afterwards. 

I suspect thats because of videos / streams that are in the future, thats also what the logs suggest.

Whats important is that its misleading when i get an apprise notification that 3 videos have been added , but the queue is empty.

If videos are in the future or still _live_ there shouldnt be an attempt to add them to the queue. 

### Relevant log output

```shell
[2024-05-10 11:27:53,171: WARNING/ForkPoolWorker-2] VhzPaOsYmbM: [1/3]: add to queue

[2024-05-10 11:27:54,182: WARNING/ForkPoolWorker-2] ERROR: [youtube] VhzPaOsYmbM: This live event will begin in 4 hours.
```

**Comment by bbilly1** [comment]
Well the video doesn't get added to the queue, no? It will show an error in the logs but should skip it?

The notification will trigger if the task had any results, which means, if the task added a video to the queue. Your log is cut off, but it looks like you are adding 3 videos, skipping one, then assuming adding two?

TA won't know if it can add the video before it tries, because all it knows is the video ID at that point, there isn't really a way around this.

**Comment by bbilly1** [comment]
At the stage of rescanning, the task doesn't know yet if that is going to be able to add, as that just returns a list of video IDs. That then gets passed to the add to queue task, that will know what can or can't be added.

Tasks are modular like that, so they can be invoked from different places, e.g. add to queue after a subscription rescan, or add to queue after a form post through the user on the download page. 

So yeah, that is not something that can be changed again easily. I'm closing this as wont fix.

**Comment by bbilly1** [comment]
Alternatively we can also add another notification option for "Add to the download Queue" task, that might be more relevant. But could send too many notifications, e.g. also when you add an item through the form... But then you'd have the option.

**Comment by bbilly1** [comment]
v0.4.8 ships a notification hook for add to queue task.
