### ISSUE TITLE
[Feature Request]: Keep "Similar Videos" when deleting video

### ISSUE THREAD

**Issue by Rupp3r** [tubearchivist/tubearchivist#716]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

Hi there,

The "Similar Videos" section when watching a video, disappears when deleting the video. It would be nice to somehow keep this after video deletion so you won't have to open it in a new tab before deleting. The problem is being forgetfull of opening the video in a new tab AND forgetting the title of the similar video - real first vorld problems... 🤣😅

My two only thoughts for a "fix" is:
1. "Similar Videos" gets added to the channel page after video deletion but not otherwise. Probably annoying to make/upkeep and just a bit weird.

2. A page confirming that the video have been deleted while also giving a breif overview of the watched channel - maybe accompanied by a few of the channels recent videos, the latest downloaded videos/newest videos in general and the "Similar Videos" section from before video deletion. To sum it up for the deleted video/keep watching page:
Notification confirming video deletion
1/2 top left screen with channel info, links and a few recent videos
1/2 top right screen with latest downloaded/new videos
Bottom screen with the "Similar Videos" from before video deletion

Maybe you(or someone else) have a better idea or get inspired by the suggustion. I know it is not mayor problem and probably won't get prioritized. None the less i thank you for allowing me to submit my idea and for bringing this amazing project to life 🙏🏻😄

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
When the video is deleted, the full reference is deleted. We aren't keeping residual references to other videos and it is removed from the filesystem, channel, and any associated playlists. 

I'm not sure I understand the value of retaining the suggested videos list for a video that has been removed. Can you detail more about the use case and why it would seem to be important?

**Comment by bbilly1** [comment]
lamusmaser is correct. once a video is deleted, the metadata is also deleted. we don't keep that any longer. You also have auto delete watched, if you want to implement some kind of delayed deleting. closing this as won't fix.
