### ISSUE TITLE
[Feature Request]: Add sort option "Recent/Oldest Video" in "all" subscribed section of Download Queue

### ISSUE THREAD

**Issue by anarqist** [tubearchivist/tubearchivist#717]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

Feature request to add a sorting option of the queued downloads when "all" channels is open

## Describe the solution you'd like

When I go to the Download Section, I see all queued Downloads. I can change the view by grid or list view and if multiple channels have queued videos I can choose them in the drop down menu. The "all" section shows all videos from all channels in a row, but all videos from one channel and then the next ones etc... Is there a way to add the sort by button from the "home" section to the Download (queue) section as well? Because I prefer to manually initialize the download of specific videos?

## Additional context

Thanks for this great project! 

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
The queue is sorted by priority. As in first item will download next.

Searching the queue is on the roadmap, that will happen at some point, but not any time soon. but you saw in the "how to" guide, we don't take new feature requests at the moment.
