### ISSUE TITLE
[Frontend Migration]: Add API endpoint /api/config/application/

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#718]
### Domain

Backend

## Is your feature request related to a problem? Please describe.
Data for the page `/settings/application/` is missing in the api endpoints.

## Describe the solution you'd like
The Api endpoint `/api/config/application/` has been implemented simmilar to `/api/config/user/`

## Additional context
`/api/config/application/` ( POST, GET )

GET response body & POST body:
 ```JSON
{
  "api_token": "<token>",
  "subscriptions": {
    "channel_size": 69,
    "live_channel_size": 69,
    "shorts_channel_size": 69,
    "auto_start": false
  },
  "downloads": {
    "limit_speed": false,
    "sleep_interval": 3,
    "autodelete_days": false,
    "format": false,
    "format_sort": false,
    "add_metadata": false,
    "add_thumbnail": false,
    "subtitle": false,
    "subtitle_source": false,
    "subtitle_index": false,
    "comment_max": false,
    "comment_sort": "top",
    "cookie_import": false,
    "throttledratelimit": false,
    "extractor_lang": false,
    "integrate_ryd": false,
    "integrate_sponsorblock": false
  },
  "application": {
    "enable_snapshot": true
  }
}

```

**Comment by bbilly1** [comment]
Implemented at: /api/appsettings/config/, for details see doc string: https://github.com/tubearchivist/tubearchivist/blob/192d518c2b452435dca8ded9f0fe1f38387316b8/backend/appsettings/views.py#L29-L34

**Comment by MerlinScheurer** [comment]
What about the `api_token` for the browser extension?

**Comment by MerlinScheurer** [comment]
Updating the user config seems to fail silently now.
( POST, `/api/user/me/` )

```
tubearchivist    | {"_index":"ta_config","_id":"appsettings","found":false}
tubearchivist    | {"error":{"root_cause":[{"type":"parsing_exception","reason":"[_na] query malformed, must start with start_object","line":1,"col":34}],"type":"x_content_parse_exception","reason":"[1:34] [bool] failed to parse field [must]","caused_by":{"type":"parsing_exception","reason":"[_na] query malformed, must start with start_object","line":1,"col":34}},"status":400}
tubearchivist    | {'error': {'root_cause': [{'type': 'parsing_exception', 'reason': '[_na] query malformed, must start with start_object', 'line': 1, 'col': 34}], 'type': 'x_content_parse_exception', 'reason': '[1:34] [bool] failed to parse field [must]', 'caused_by': {'type': 'parsing_exception', 'reason': '[_na] query malformed, must start with start_object', 'line': 1, 'col': 34}}, 'status': 400}
```

**Comment by bbilly1** [comment]
updating user config through POST /api/user/me/ works fine for me on latest commit from refactor-react-migration branch. Maybe your migrations didn't run correctly in the backend? e.g. `python manage.py ta_startup`.

**Comment by MerlinScheurer** [comment]
Hmm, yeah it works, but the exception is still thrown 😅 
( even after nuking all docker volumes and applying the migration in a running container )

**Comment by MerlinScheurer** [comment]
Should work now.
Frontend implementation in https://github.com/tubearchivist/tubearchivist/pull/790
