### ISSUE TITLE
Temporary Failure in Name Resolution

### ISSUE THREAD

**Issue by Brancliff** [tubearchivist/tubearchivist#72]
Downloading seems to be shot for me. I've tried a few different videos, and I've cleared up over 1TB of space. I've also tried restarting the containers. Here are the logs:

https://pastebin.com/83QhKYEM

I've also been unable to get any videos through rescanning my subscriptions. Here are the logs for that too:

https://pastebin.com/cMge0z30

**Comment by voarsh2** [comment]
I'm getting this too.
host can ping youtube, but TubeArchivist isn't able to reach it.

**Comment by bbilly1** [comment]
docker csn get confused where the internet is sometimes. see here for a fix: https://github.com/tubearchivist/tubearchivist/issues/302
