### ISSUE TITLE
[Frontend Migration]: Repo Restructure

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#720]
### Domain

Combined

### Description

Reorganizing the repo structure into:

- root
    - backend: all backend related code
      - manage.py: application entry point
      - requirements.txt: dependencies definition
    - frontend: all front end application code
      - package.json: package definition file
      - node_modules: all node modules
    - Dockerfile: build steps for frontend/backend -> load into final image
    - docker-compose.yml: compose file for reference

**Comment by MerlinScheurer** [comment]
Do you want the ability to update the frontend independently of the backend?
( if yes, then putting the frontend into its own docker container is a possibility, which would allow updates to the frontend container without the backend needing to be re-build and published. )

**Comment by bbilly1** [comment]
So repo restructure is mostly a matter of file organizations not how it's packaged and shipped. The frontend should still be packaged together with the backend in the same container. But now clearly separated in the repo.

**Comment by MerlinScheurer** [comment]
Frontend + build steps are setup.

**Comment by komali2** [comment]
Re: separate containers, is the intention for the backend system to serve a static frontend package? I'm trying to find architecture info cause I'd love to help. 

If that isn't the intention, a simple docker container with nginx or whatever could work quite well for separating and allowing the two containers to be separately updated (or torn down in case of issues)

**Comment by MerlinScheurer** [comment]
@komali2 we changed this to be a build step for the tubearchivist docker container which will serve the static files.

**Comment by bbilly1** [comment]
this is now mostly completed.
