### ISSUE TITLE
[Frontend Migration]: Backend application splitup

### ISSUE THREAD

**Issue by bbilly1** [tubearchivist/tubearchivist#721]
### Domain

Backend

### Description

Split the backend into more manageable and smaller django apps. App names become root path for API endpoints.

- config: as is, main django app with root settings.py
- common: All common functionality shared between apps
  - probably doesn't have any API endpoints...
- channel: all channel functionality
  - `/api/channel/`: channel list
  - `/api/channel/<id>/`: channel detail
  - `/api/channel/<id>/playlist/`: channel playlists
  - `/api/channel/<id>/shorts/`: channel shorts
  - `/api/channel/<id>/streams/`: channel live streams
  - `/api/channel/<id>/about/`: channel metadata and config
- playlist: manage all playlists
  - `/api/playlist/`: playlist list
  - `/api/playlist/<id>/`: playlist detail
- downloads: all download functionality
- settings: all application and scheduler configurations

**Comment by MerlinScheurer** [comment]
The `shorts` and `streams` endpoints could be a searchparam/query `?type=short` on the `/api/channel/<id>/video/` endpoint.

**Comment by bbilly1** [comment]
Completed. Tracking API changes in this gist [here](https://gist.github.com/bbilly1/7b6abc52ab689f56671bf9011879379a).
