### ISSUE TITLE
[Frontend Migration]: Update API endpoint /api/video/ add videos in progress (continue_vids) and more

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#722]
### Domain

Backend

### Problem
Currently there is no way in the api to get all videos in progress and filters are not taken into account.
In the python html template there is a variable named: `continue_vids`  ( `tubearchivist\home\views.py` => `get_in_progress` )

### Solution
Add `continue_vids` (`get_in_progress`) to the response of the `/api/video/` endpoint.

Add SearchParams:
`filter`: "hide_watched"
`sort_by`: "published"  | "downloaded"  | "views"  | "likes"  | "duration"  | "filesize"
`sort_order`: "asc" | "desc"
`page`: "0"

**Comment by bbilly1** [comment]
Implemented through /api/video/ and query param filtering. See doc string here for details: https://github.com/tubearchivist/tubearchivist/blob/192d518c2b452435dca8ded9f0fe1f38387316b8/backend/video/views.py#L11-L21
