### ISSUE TITLE
[Frontend Migration]: Add API endpoint /api/channel/{channel-id}/playlist/

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#724]
### Domain

Backend

## Is your feature request related to a problem? Please describe.
Data for the page `/channel/{channel-id}/playlist` is missing in the api endpoints.

## Describe the solution you'd like
The Api endpoint `/api/channel/{channel-id}/playlist/` has been implemented simmilar to `/api/playlist/`

## Additional context
`/api/channel/{channel-id}/playlist/` ( GET )

SearchParams:
`filter`: `show_subed_only`
`page`: `0`

Possibly implemented in a module way as described in https://github.com/tubearchivist/tubearchivist/issues/721

**Comment by bbilly1** [comment]
Implemented with `/api/playlist/` and channel query param. See doc string here: https://github.com/tubearchivist/tubearchivist/blob/192d518c2b452435dca8ded9f0fe1f38387316b8/backend/playlist/views.py#L13-L21
