### ISSUE TITLE
[Frontend Migration]: Update API endpoint /api/channel/{channel_id}/ add missing key "aggs"

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#726]
### Domain

Backend

### Problem
"aggs" is missing missing in `/api/channel/{channel_id}/`, but is provided to the template view.

### Solution
Add aggs to `/api/channel/{channel_id}/`

```Json
"aggs": {
  "total_items": { "value": 0 },
  "total_duration": { "value_str": "" },
  "total_size": { "value": "" }
}
```

**Comment by bbilly1** [comment]
Implemented at `/api/channel/<channel_id>/aggs/`.
