### ISSUE TITLE
[Frontend Migration]: Add API endpoint /api/channel/{channel-id}/nav/

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#727]
### Domain

Backend

## Is your feature request related to a problem? Please describe.
There is currently no way to get to get is a channel has Videos, Streams, Shorts or Playlists.
But the navigation is build in a way that hides parts of it when a channel has no shorts.

## Describe the solution you'd like
The Api endpoint `/api/channel/{channel-id}/nav/` has been implemented.

## Additional context
![image](https://github.com/tubearchivist/tubearchivist/assets/4706504/ce288bef-4f2c-4680-8696-91c387ff0e7a)

`/api/channel/{channel-id}/nav/` ( GET )

POST body:
 ```Json
{
	"has_videos": false,
	"has_playlists": false,
	"has_streams": false,
	"has_shorts": false,
	"has_pending" : false,
}
```

Possibly implemented in a module way as described in https://github.com/tubearchivist/tubearchivist/issues/721

**Comment by bbilly1** [comment]
Implemented at `/api/channel/<channel_id>/nav/`.
