### ISSUE TITLE
[Frontend Migration]: Update API endpoint /api/playlist/ add searchparam filter for subbed playlists

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#729]
### Domain

Backend

## Is your feature request related to a problem? Please describe.
A filter searchparam for the page `/playlist` is missing in the api.

## Describe the solution you'd like
The searchparam filter `show_subed_only` has been added to the Api endpoint `/api/playlist/`

## Additional context
`/api/playlist/` ( GET )

SearchParams:
`filter`: "show_subed_only"
`page`: "0"

Possibly implemented in a module way as described in https://github.com/tubearchivist/tubearchivist/issues/721

**Comment by bbilly1** [comment]
Implemented at `/api/playlist/`, see doc string here for details: https://github.com/tubearchivist/tubearchivist/blob/192d518c2b452435dca8ded9f0fe1f38387316b8/backend/playlist/views.py#L13-L21
