### ISSUE TITLE
[Frontend Migration]: Update API endpoint /api/video/{youtubeId}/ add missing playlist_nav

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#730]
### Domain

Backend

## Is your feature request related to a problem? Please describe.
The endpoint `/api/video/{youtubeId}/` is missing data for playlist_nav

## Describe the solution you'd like
Add playlist_nav to `/api/video/{youtubeId}/`

## Additional context
`/api/video/{youtubeId}/` ( GET )

```Json
"playlist_nav ": [
  {
    "playlist_meta": {
      "current_idx": "string",
      "playlist_id": "string",
      "playlist_name": "string",
      "playlist_channel": "string"
    },
    "playlist_previous": {
      "youtube_id": "string",
      "vid_thumb": "string",
      "idx": "number",
      "title": "string"
    },
    "playlist_next": {
      "youtube_id": "string",
      "vid_thumb": "string",
      "idx": "number",
      "title": "string"
    }
  }
]
```

Possibly implemented in a module way as described in https://github.com/tubearchivist/tubearchivist/issues/721

**Comment by bbilly1** [comment]
Implemented at `/api/video/<video-id>/nav/`.
