### ISSUE TITLE
[Frontend Migration]: Add endpoint to get the list of channels in the download queue

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#731]
### Domain

Backend

## Is your feature request related to a problem? Please describe.
Currently there is no way to get a list of channels in the download queue for the channel select filter.

## Describe the solution you'd like
Add an endpoint to get the channels in the download queue.

## Additional context
Current implementation keyword: `channel_agg_list`

![image](https://github.com/tubearchivist/tubearchivist/assets/4706504/bf4af75c-7c3a-4c81-ba9c-f9bd888a3e5f)

Possibly implemented in a module way as described in https://github.com/tubearchivist/tubearchivist/issues/721

**Comment by bbilly1** [comment]
implemented at `/api/download/aggs/`.
