### ISSUE TITLE
[Frontend Migration]: Update API endpoint /api/playlist/{playlist-id}/video/ add searchparam filter for hide_watched videos

### ISSUE THREAD

**Issue by MerlinScheurer** [tubearchivist/tubearchivist#732]
### Domain

Backend

## Is your feature request related to a problem? Please describe.
A filter searchparam for the page `/api/playlist/{playlist-id}/video/` is missing in the api.

## Describe the solution you'd like
The searchparam filter `hide_watched` has been added to the Api endpoint `/api/playlist/{playlist-id}/video/`

## Additional context
`/api/playlist/{playlist-id}/video/` ( GET )

SearchParams:
`filter`: "hide_watched"
`page`: "0"

Possibly implemented in a module way as described in https://github.com/tubearchivist/tubearchivist/issues/721

**Comment by bbilly1** [comment]
Implemented at `/api/video/` with playlist query param. See doc string here: https://github.com/tubearchivist/tubearchivist/blob/192d518c2b452435dca8ded9f0fe1f38387316b8/backend/video/views.py#L11-L21

**Comment by MerlinScheurer** [comment]
`watch=continue` without any videos to continue seems to cause the endpoint to respond with http 500 and "Server Error (500)"


```{
  "error": {
    "root_cause": [
      {
        "type": "parsing_exception",
        "reason": "[_na] query malformed, must start with start_object",
        "line": 1,
        "col": 34
      }
    ],
    "type": "x_content_parse_exception",
    "reason": "[1:34] [bool] failed to parse field [must]",
    "caused_by": {
      "type": "parsing_exception",
      "reason": "[_na] query malformed, must start with start_object",
      "line": 1,
      "col": 34
    }
  },
  "status": 400
}
```

**Comment by MerlinScheurer** [comment]
{"error":"'filesize' not in SortEnum"}
in backend\video\src\constants.py its `media_size`

But in /backend/user/src/user_config.py its `filesize`
```    
VALID_SORT_BY = [
        "published",
        "downloaded",
        "views",
        "likes",
        "duration",
        "filesize",
    ]
    ```
    
    Can we change one of them to have them in sync?

**Comment by MerlinScheurer** [comment]
Works in https://github.com/tubearchivist/tubearchivist/pull/790
