### ISSUE TITLE
[Bug]: FFMPEG binary broken on arm64

### ISSUE THREAD

**Issue by barrelltitor** [tubearchivist/tubearchivist#736]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Raspbian 

## Describe the bug
The FFMPEG binary is broken on arm64. When attempting to download a video or do anything ffmpeg related, you will get an exec format error

## Steps To Reproduce
Install tubearchivist on ARM64 and attempt to download a video.

## Expected behavior
The video should download

### Relevant log output

```shell
OSError: [Errno 8] Exec format error: 'ffprobe'
OSError: [Errno 8] Exec format error: 'ffmpeg'
```

### Anything else?

Some more information [here](https://discord.com/channels/920056098122248193/1243636798073208902)

For anyone wanting a quick solution until this is fixed in an update: download the latest FFMPEG inside the container, extract the tar(you will need to install xz-utils), then move everything inside into /usr/bin. This will get reverted when you recreate the container, but it should only be a temporary fix.

**Comment by anarqist** [comment]
I have the same issue on Apple Silicon M2 Max, when I try to download a Video I receive: 

`ERROR: You have requested merging of multiple formats but ffmpeg is not installed. Aborting due to --abort-on-error`

**Comment by bbilly1** [comment]
OK, I think I see what happend, must have been the ARG keyword being places incorrectly in the Dockefile. 

I've pushed an unstable build, potentially fixing it. Please test it and report back.

**Comment by bbilly1** [comment]
On a side note:

I do not have access to any ARM based devices, so I do not have any way to test things for ARM. If we want to keep doing ARM builds for the very few people using this project on ARM based platform, please step up and help with testing. That's why we make the regular unstable builds. 

Join the discord and add yourself to the beta tester role to get notifications.

**Comment by bbilly1** [comment]
OK, rebuild and pushed. Pull again if you are on ARM64. 

I've also clarified the untested nature of ARM64 builds in the docs.

let's keep this issue open for a few days, so people can easily see it.
