### ISSUE TITLE
[Feature Request]: More modern UI styles and browser extension theme

### ISSUE THREAD

**Issue by drajabr** [tubearchivist/tubearchivist#738]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.
Thankfully its the merged pull request #583.

## Describe the solution you'd like
Adapt better set of stylesheets by default.

## Additional context
Tubearchivist does a great job, but its UI feels like its coming from the 90s era, with no disrespect at all, can we get a more modern theme by default?

I'm happily wanting to contribute, even though I'm just a dump electrical engineer, my experimentation with css led me to come up with this stylesheet, that shockingly to me it works.  

[tubearchivist-custom-style](https://github.com/drajabr/tubearchivist-custom-style)

If someone can clean the stylesheet and adapt it in the code to be there by default that would be great.

Next step for me: figure out how to theme the browser extension :) 

### Your help is needed!

- [x] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
As you read, this project doesn't take new feature request. Design preferences are personal. You can modify things as you wish.

**Comment by drajabr** [comment]
Oh my bad, I don't know how I missed that first line in the page, anyway I'm happy to know that `Going forward, this project will focus on developing a new modern frontend.`
