### ISSUE TITLE
[Feature Request]: Make ignored videos searchable with elasticsearch query

### ISSUE THREAD

**Issue by Emporea** [tubearchivist/tubearchivist#742]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

When having lots of ignored videos its difficult to scroll through all of them to 'unignore' them.

Lets say one subscribed to a channel, but ignored most of those 50 videos on first scan. Now one also subscribe to a playlist of that channel which happens to include 30 videos that were previously ignored. 

It would be super useful to either search all ignored videos by name and channel or other tags.
It could also come in handy to be able to search by playlist or by channel and list all videos that have been ignored.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
Download queue searching is on the road map already, no need for another feature request. That will happen at some point.
