### ISSUE TITLE
[Feature Request]: Select videos of search result -> apply action

### ISSUE THREAD

**Issue by Emporea** [tubearchivist/tubearchivist#743]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

It could be useful to add the option to select a bunch of videos in thr search result list and a apply an action like delete or 'delete and ignore' to it.

Or maybe something like hovering over videos in a search result to show buttons to quickly 'delete' or 'delete and ignore' or other actions. Maybe this is already planned in the ui rework?

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
UI reworks is happening. As stated in the how to, no need to open any feature requests for that at the time being.
