### ISSUE TITLE
[Feature Request]: Changing the Placement of YouTube IDs in Descriptions

### ISSUE THREAD

**Issue by ralle947** [tubearchivist/tubearchivist#744]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

Is it possible to change the placement of YouTube IDs to the bottom of the description so that it looks nicer in Plex?

![image](https://github.com/tubearchivist/tubearchivist/assets/104146423/29316a46-af72-421a-b326-931cff144fe5)

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
Please open this in the tubearchivist-plex Github.
