### ISSUE TITLE
[Feature Request]: Multiple download directories

### ISSUE THREAD

**Issue by drinksomewhiskey** [tubearchivist/tubearchivist#749]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

I personally use Tube Archivist to save videos and watch via Plex. This works great however, all downloads go to one location, which means all downloads are also within one library within Plex. This works fine for a single user, but it would be nice to have multiple download directories through Tube Archivist (e.g. two separate download locations) to have the ability to specify where a subscription should be saved to once downloaded through TA. Given this, you could then have multiple libraries within Plex by selecting each download location separately, which will let you separate the video library within Plex it by user or even by category.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
There is no flexibility on the filesystem, that is know: https://github.com/tubearchivist/tubearchivist?tab=readme-ov-file#known-limitations, and doesn't need another reminder.
