### ISSUE TITLE
[Bug]: FileNotFoundError when fetching metadata for downloaded video.

### ISSUE THREAD

**Issue by AdamGaffney96** [tubearchivist/tubearchivist#752]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Synology

## Describe the bug
When attempting to download any YouTube video manually, I get the log output below and the video just remains in the queue undownloaded. I have tried restarting the containers, plus re-pulling the images also using my attached docker-compose to no success. I specify manual because my scheduled downloads still work, I wake up every day to a couple new videos successfully downloaded by the scheduled process overnight from my subscriptions. However if I try to manually add videos using the "Add to download queue" button this happens every time.

## Steps To Reproduce
- Copy a YouTube link
- Click "Add to download queue" and paste link
- Click either "Add to queue" then hit "Start download", or just use "Download now", both have the same issue

## Expected behavior
Video should download normally

### Relevant log output

```shell
20/06/2024
11:00:40
[2024-06-20 11:00:40,869: INFO/MainProcess] Task extract_download[111a0cae-0db8-4453-85fe-f532a8a0a4a0] received
20/06/2024
11:00:41
[2024-06-20 11:00:40,870: WARNING/ForkPoolWorker-5] extract_download create callback
20/06/2024
11:00:41
[2024-06-20 11:00:41,782: WARNING/ForkPoolWorker-5] HwF229U2ba8: [1/1]: add to queue
20/06/2024
11:00:46
[2024-06-20 11:00:46,882: INFO/MainProcess] Task download_pending[fe5ad2d1-ccda-4eba-85df-daf48af3bf0e] received
20/06/2024
11:00:46
[2024-06-20 11:00:46,884: WARNING/ForkPoolWorker-2] download_pending create callback
20/06/2024
11:00:46
[2024-06-20 11:00:46,928: WARNING/ForkPoolWorker-5] 111a0cae-0db8-4453-85fe-f532a8a0a4a0 success callback
20/06/2024
11:00:46
[2024-06-20 11:00:46,935: INFO/ForkPoolWorker-5] Task extract_download[111a0cae-0db8-4453-85fe-f532a8a0a4a0] succeeded in 6.057595910038799s: 'added 1 Videos to Queue'
20/06/2024
11:00:46
[2024-06-20 11:00:46,935: WARNING/ForkPoolWorker-5] 111a0cae-0db8-4453-85fe-f532a8a0a4a0 return callback
20/06/2024
11:00:46
[2024-06-20 11:00:46,940: WARNING/ForkPoolWorker-2] 4u78DVLEnvw: Downloading video
20/06/2024
11:00:52
[2024-06-20 11:00:52,024: WARNING/ForkPoolWorker-2] 4u78DVLEnvw: get metadata from youtube
20/06/2024
11:00:56
[2024-06-20 11:00:56,453: WARNING/ForkPoolWorker-2] UCPDXXXJj9nax0fr0Wfc048g: get metadata from es
20/06/2024
11:00:56
[2024-06-20 11:00:56,463: WARNING/ForkPoolWorker-2] fe5ad2d1-ccda-4eba-85df-daf48af3bf0e Failed callback
20/06/2024
11:00:56
[2024-06-20 11:00:56,466: ERROR/ForkPoolWorker-2] Task download_pending[fe5ad2d1-ccda-4eba-85df-daf48af3bf0e] raised unexpected: FileNotFoundError()
20/06/2024
11:00:56
Traceback (most recent call last):
20/06/2024
11:00:56
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task
20/06/2024
11:00:56
    R = retval = fun(*args, **kwargs)
20/06/2024
11:00:56
                 ^^^^^^^^^^^^^^^^^^^^
20/06/2024
11:00:56
  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__
20/06/2024
11:00:56
    return self.run(*args, **kwargs)
20/06/2024
11:00:56
           ^^^^^^^^^^^^^^^^^^^^^^^^^
20/06/2024
11:00:56
  File "/app/home/tasks.py", line 128, in download_pending
20/06/2024
11:00:56
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20/06/2024
11:00:56
  File "/app/home/src/download/yt_dlp_handler.py", line 73, in run_queue
20/06/2024
11:00:56
  File "/app/home/src/index/video.py", line 398, in index_new_video
20/06/2024
11:00:56
    video.build_json()
20/06/2024
11:00:56
    self.add_player(media_path)
20/06/2024
11:00:56
  File "/app/home/src/index/video.py", line 248, in add_player
```

### Anything else?

[Here is the docker compose I used to create the containers](https://github.com/user-attachments/files/15912143/docker-compose.txt)
I'm trying to think of anything else I have changed since this began but I can't think of anything. I updated directly from v0.4.2 to v0.4.8 a couple weeks ago, however I only noticed this start happening in the last couple of days. I only found one issue previously referencing a FileNotFoundError but it didn't seem to be the same issue and the fixes didn't work if I recall right.

**Comment by jmurchie88** [comment]
I'm new to TA, did a fresh install last weekend and everything worked as expected. Started observing a "Task failed" error in the GUI when manually downloading videos today and checked my container logs and am getting the same error as @AdamGaffney96

```
[2024-06-26 16:11:28,537: ERROR/ForkPoolWorker-8] Task download_pending[989a005e-20d3-4b7b-96fa-4485f7eb589d] raised unexpected: FileNotFoundError()

Traceback (most recent call last):

  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 453, in trace_task

    R = retval = fun(*args, **kwargs)

                 ^^^^^^^^^^^^^^^^^^^^

  File "/root/.local/lib/python3.11/site-packages/celery/app/trace.py", line 736, in __protected_call__

    return self.run(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/home/tasks.py", line 128, in download_pending

    videos_downloaded = downloader.run_queue(auto_only=auto_only)

                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/home/src/download/yt_dlp_handler.py", line 73, in run_queue

    vid_dict = index_new_video(youtube_id, video_type=video_type)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/home/src/index/video.py", line 398, in index_new_video

    video.build_json()

  File "/app/home/src/index/video.py", line 148, in build_json

    self.add_player(media_path)

  File "/app/home/src/index/video.py", line 248, in add_player

    vid_path = media_path or self.build_dl_cache_path()

                             ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/app/home/src/index/video.py", line 244, in build_dl_cache_path

    raise FileNotFoundError

FileNotFoundError
```

**Comment by lamusmaser** [comment]
Well, notably, that function which is raising the error hasn't changed within the past 8 months: https://github.com/tubearchivist/tubearchivist/blame/master/tubearchivist/home/src/index/video.py#L228-L244

This usually means that something else is happening with the cache path location.

This has two checks that can occur:
Cache location (where it was downloaded to) or channel path (where it will end up). I would have expected this to fail during the `download_video` phase if the video did not have permissions. However, this can be easily checked by verifying if there is a downloaded file in the `/cache/download` location (or its equivalent mounted persistent storage location). If yes, then that means it had permission to download the initial file but had an issue with determining the path afterward.

I suspect it is either a permissions issue with the file or another, similar issue with the host filesystem. Can either of you provide how your files are mounted? Based on the original post, it looks like it is a Synology deployment, so that should be local filesystem, but I want to verify.

**Comment by trafficman** [comment]
I'm pretty sure I've had similar behavior recently (including `FileNotFound` specifically) resulting from random singular 403 Forbidden errors leaving orphaned partial downloads in `/cache/download` (I suspect it's a weird edge case where the video portion downloads, but the audio portion fails for whatever reason).

Make sure there's no files left in that folder, and if there are, manually delete them and then try downloading the video(s) in question again.

**Comment by jmurchie88** [comment]
I found a webm.part and webm.part.mp4 file sitting in `/cache/download` that were owned by root, despite leaving HOST_UID and HOST_GID set as 1000, corresponding to my user, in my compose file. I deleted the two files and have reattempted several downloads and everything seems to be working as advertised. I'm using bind mounts for the internal cache and video storage directories with the host paths set as owner/group 1000, permission wise those all seem correct.

**Comment by trafficman** [comment]
How I've personally seen this manifest, in case it sheds light on root causes/helps with reproducibility:

1: Manually download videos until one of them returns a 403 Forbidden error in the GUI
2: The video in question will be left in the manual download queue, subsequent attempts to manually download anything will first attempt to redownload it, failing with `Task failed:<blank>` in the GUI and throwing the `FileNotFound` error in the logs
3: Ignoring the problematic video in the GUI allows the manual download queue to progress, but the video will not be able to be downloaded until the `/cache/download` folder is cleared of orphaned files

**Comment by lamusmaser** [comment]
Fortunately, the `/cache` location is cleared on a restart of TA, so that is always a potential option, rather than manual intervention.

The exact check is here: https://github.com/tubearchivist/tubearchivist/blob/master/tubearchivist/home/src/index/video.py#L232-L234

Since the file does not complete its download, that seems to be why it is occurring that way. I don't believe we currently have a methodology to allow `yt-dlp` debugging to come through, but that does seem to be where the issue is coming from. As pointed out by @trafficman, I would expect that the videos are missing some aspect. If the last bit of the `.part` file still exists and hasn't been incorporated into the video, it is very likely that the video download process was interrupted, causing it to not finish. That could be due to a multitude of options that will be very, very hard to troubleshoot until we get some logs of the activity.

If someone could replicate the issue with `yt-dlp` natively, that would be the most helpful.

**Comment by AdamGaffney96** [comment]
Sorry for the delay in getting back, but it's good to see at least it's an issue others are having. I can confirm that I'm using a Synology docker deployment, with a local folder on the server being bound to the container. I can try investigate the issue using a local version of yt-dlp, as the video causing the issue has still been unsuccessful in downloading.

**Comment by lamusmaser** [comment]
The inconsistency in being able to replicate the issue also indicates to me that this is a download issue. Very likely could be a temp block from YouTube as it sees the request come in, but then allows later requests through, mostly to inhibit automatic downloaders.

**Comment by AdamGaffney96** [comment]
One thing I'll also mention, the video I got the initial error on was a members only video. I've been using previously manual imports, and now the TubeArchivist extension to sync my cookies and this has been no problem (including with `yt-dlp`). However it's also possibly another factor that caused my specific download break.

I suppose this can probably be marked as resolved since it's likely not something TubeArchivist can really solve on the apps end, outside of perhaps some auto cache-clearing feature (not that just deleting the files is particularly challenging anyway).

**Comment by bbilly1** [comment]
There is a potential fix with retry logic in the newest unstable build. This should also allow to continue from cache properly, as in if the video succeeded but you can a 403 on the audio, you'll only have to retry the audio.

Please give it a try and report back.

**Comment by joshrivers** [comment]
I was just starting to trace down this issue when I tripped across this issue. `docker compose pull` and the issue was gone.

Fantastic work!
