### ISSUE TITLE
[Feature Request]: get video/channel ID from alternative frontend URLs

### ISSUE THREAD

**Issue by acidghost** [tubearchivist/tubearchivist#753]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

It would be handy if TA was able to parse video/channel IDs from alternative frontend URLs.
I know that I can just copy the ID from the URL and use that, but it's just so much quicker (especially on mobile) to just copy-paste the entire link.

## Describe the solution you'd like

Give the ability to users to configure alternative YT domains just to parse video/channel URLs.

This feature request is just for alternative frontends that use the same URL schema as YT.

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
Which one or ones are you having difficulty parsing? We have a variety that can be parsed, so we'd need examples of ones having issues before we could determine if we could parse it.

**Comment by acidghost** [comment]
Sorry, I should have included an example for clarity.

If I try to insert an URL like `https://example.com/watch?v=videoid` in the download page on TA I get `Task failed: invalid domain: example.com`, which I think comes from https://github.com/tubearchivist/tubearchivist/blob/64016389f727a1cd219ec26c0cf3a53db1c5a256/tubearchivist/home/src/ta/urlparser.py#L45-L47

To add more context, I'm running a Piped instance and most of its URLs are compatible with YouTube (i.e. have the same format).

**Comment by lamusmaser** [comment]
We validate that all links come from YouTube before passing them to `yt-dlp`. This keeps our project properly scoped.

For something like this, we'd recommend something to find-and-replace to the appropriate links.

**Comment by acidghost** [comment]
It seems to me that, in the case of URLs to videos, TA uses `urllib` to get the query string (`parse_qs`) and manually validates that w/o calling into `yt-dlp`.

https://github.com/tubearchivist/tubearchivist/blob/64016389f727a1cd219ec26c0cf3a53db1c5a256/tubearchivist/home/src/ta/urlparser.py#L49-L53
https://github.com/tubearchivist/tubearchivist/blob/64016389f727a1cd219ec26c0cf3a53db1c5a256/tubearchivist/home/src/ta/urlparser.py#L74-L82
https://github.com/tubearchivist/tubearchivist/blob/64016389f727a1cd219ec26c0cf3a53db1c5a256/tubearchivist/home/src/ta/urlparser.py#L84-L104

It should just work with any URL that has a valid `v` query string parameter.

**Comment by bbilly1** [comment]
We only support YouTube, as stated in the FAQs here: https://docs.tubearchivist.com/faq/#what-is-the-scope-of-this-project.

URL parsing has been finicky and error prone, I don't want to add complexity to that, especially as it's explicitly out of scope.

But as you noted, if the alternate frontend uses the same YT IDs, you can just grab those and add them like that.

I'm closing this as won't fix.
