### ISSUE TITLE
[Bug]: SponsorBlock segments still skipped despite set to False

### ISSUE THREAD

**Issue by ccfman2004** [tubearchivist/tubearchivist#755]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Unraid

## Describe the bug
TA will still skip sponsor segments even though I have it set to disabled for that channel.

## Steps To Reproduce
Have the Global SponsorBlock setting as True.
Set a Channel's SponsorBlock override setting to False.
Sometimes when watching a video with SponsorBlock segments the segments will still get skipped even though the SponsorBlock setting for that channel is set to False.

This bug doesn't always happen.

## Expected behavior
When a channel's SponsorBlock override setting is set to False, SponsorBlock segments should not be skipped.

### Relevant log output

```shell
UCXuqSBlHAE6Xw-yeJA0Tunw: set overwrites {'download_format': '', 'autodelete_days': None, 'index_playlists': '', 'integrate_sponsorblock': ''}
UCXuqSBlHAE6Xw-yeJA0Tunw: get metadata from es
```

### Anything else?

lamusmaser — Today at 5:12 AM
Hmm... I wonder if this is a bug similar to the video retention issue we have open, where a channel specific configuration of false is seen as "No channel override", rather than "Channel override: false".

**Comment by bbilly1** [comment]
That works fine for me:
Enable sponsorblock globally, disable with channel overwrite, does not add the timestamps.

That happens at index time, so you'll have to reindex if you change settings like that after the fact and want to have it apply immediatly.

**Comment by ccfman2004** [comment]
Reindexing doesn't ix it for me.

**Comment by bbilly1** [comment]
Then share the log output of the reindex task. Also share the API output of the given video, e.g. /api/video/<video-id>/. Then from your output above it shows that you have "Unset" the sponsorblock on that channel, not deactivated. That would result into going back to the default. See here: https://docs.tubearchivist.com/channels/#about

**Comment by bbilly1** [comment]
assuming this has been solved.
