### ISSUE TITLE
[Feature Request]: Add umask support

### ISSUE THREAD

**Issue by joncol** [tubearchivist/tubearchivist#756]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

I'm using a Docker bind-mount for my video directory. When I download videos through TA, the permissions for files is 0644 and the permission for directories is 0755.

I'd like to be able to easily change this to 0664 and 0775 respectively, to have the files and directories be writeable by anyone in my `media` group.

## Describe the solution you'd like

Some solution using `umask` would be nice.

## Additional context

Other containers (e.g. https://hub.docker.com/r/linuxserver/radarr) use a `UMASK` environment variable for this purpose, I guess it's used with the `umask` command.

I'm sorry if this has been asked before, but I could not find anything based on an issue search.

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
You should be able to achieve that by adding the user 1000:1000 (assuming you haven't changed that) to the media group. You shouldn't need to set umask for that.

**Comment by joncol** [comment]
@bbilly1: All video files and folders have non write access for the group:

Example:
```
➜ ls -lag /data/media/youtube/UCZDfnUn74N0WeAPvMqTOrtA/
.rw-r--r-- 1.3G tubearchivist media 27 Jun 12:35  krAZcUIP3YE.mp4
~
➜ ls -lag /data/media/youtube/
drwxr-xr-x - tubearchivist media  1 Jul 10:33  UC--TKxqP8xJNymgrLe-thhA
drwxr-xr-x - tubearchivist media 27 Jun 09:44  UCJ5gh06UMoz-c0R4EhqQMwg
drwxr-xr-x - tubearchivist media 27 Jun 19:36  UCUUTdohVElFLSP4NBnlPEwA
drwxr-xr-x - tubearchivist media 27 Jun 17:16  UCvpNIQlTMpDfR8kv9Z64f5g
drwxr-xr-x - tubearchivist media 27 Jun 19:26  UCwT-01b-VJ0U3dViux7beeg
drwxr-xr-x - tubearchivist media 27 Jun 12:35  UCZDfnUn74N0WeAPvMqTOrtA
```

So only the `tubearchivist` user itself has write access. I'd want anyone in the `media` group to have write access.

**Comment by bbilly1** [comment]
You can still use the `HOST_UID` and `HOST_GID` env vars to control what user and group is owning the files and folders.

**Comment by joncol** [comment]
@bbilly1: Thanks, but that still does not solve my problem, since I would like write access for the group, not only the user.

**Comment by bbilly1** [comment]
Sorry, I don't get it. You can assign the files to any group. You can have the files owned by anyone. Closing this, we have other priorities.
