### ISSUE TITLE
[Bug]: Requested format is not available

### ISSUE THREAD

**Issue by uninstall-your-browser** [tubearchivist/tubearchivist#760]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug
![image](https://github.com/tubearchivist/tubearchivist/assets/170106706/9c7c7cbe-c4a2-41e3-b886-f661c6bb0de1)

## Steps To Reproduce
Download https://youtu.be/VJnureuZ6Ts

## Expected behavior
Video is downloaded somehow

### Relevant log output

```shell
tubearchivist-1    | [2024-07-11 10:30:54,081: INFO/MainProcess] Task download_pending[bd689127-99b9-44eb-91b0-9e6bf4b61721] received
tubearchivist-1    | [2024-07-11 10:30:54,082: WARNING/ForkPoolWorker-16] download_pending create callback
tubearchivist-1    | [2024-07-11 10:30:54,119: WARNING/ForkPoolWorker-16] VJnureuZ6Ts: Downloading video
tubearchivist-1    | �[2024-07-11 10:30:56,156: WARNING/ForkPoolWorker-16] WARNING: [youtube] VJnureuZ6Ts: nsig extraction failed: You may experience throttling for some formats
tubearchivist-1    |          n = Sy4PUzWkAq-qvjRV ; player = https://www.youtube.com/s/player/9ed4a7e1/player_ias.vflset/en_US/base.js
tubearchivist-1    | �[2024-07-11 10:30:56,158: WARNING/ForkPoolWorker-16] WARNING: [youtube] VJnureuZ6Ts: nsig extraction failed: You may experience throttling for some formats
tubearchivist-1    |          n = ie2sk43sN_-bsn3o ; player = https://www.youtube.com/s/player/9ed4a7e1/player_ias.vflset/en_US/base.js
tubearchivist-1    | �[2024-07-11 10:30:56,268: WARNING/ForkPoolWorker-16] ERROR: [youtube] VJnureuZ6Ts: Requested format is not available. Use --list-formats for a list of available formats
tubearchivist-1    | �[2024-07-11 10:30:56,268: WARNING/ForkPoolWorker-16] VJnureuZ6Ts: failed to download with message ERROR: [youtube] VJnureuZ6Ts: Requested format is not available. Use --list-formats for a list of available formats
tubearchivist-1    | [2024-07-11 10:30:56,281: WARNING/ForkPoolWorker-16] VJnureuZ6Ts: Downloading video
tubearchivist-1    | �[2024-07-11 10:30:58,277: WARNING/ForkPoolWorker-16] WARNING: [youtube] VJnureuZ6Ts: nsig extraction failed: You may experience throttling for some formats
tubearchivist-1    |          n = SANmqU8BIRtKKaoH ; player = https://www.youtube.com/s/player/9ed4a7e1/player_ias.vflset/en_US/base.js
tubearchivist-1    | �[2024-07-11 10:30:58,279: WARNING/ForkPoolWorker-16] WARNING: [youtube] VJnureuZ6Ts: nsig extraction failed: You may experience throttling for some formats
tubearchivist-1    |          n = SXN_yX7H95YzmpoE ; player = https://www.youtube.com/s/player/9ed4a7e1/player_ias.vflset/en_US/base.js
tubearchivist-1    | �[2024-07-11 10:30:58,392: WARNING/ForkPoolWorker-16] ERROR: [youtube] VJnureuZ6Ts: Requested format is not available. Use --list-formats for a list of available formats
tubearchivist-1    | �[2024-07-11 10:30:58,392: WARNING/ForkPoolWorker-16] VJnureuZ6Ts: failed to download with message ERROR: [youtube] VJnureuZ6Ts: Requested format is not available. Use --list-formats for a list of available formats
tubearchivist-1    | [2024-07-11 10:30:58,407: WARNING/ForkPoolWorker-16] [download] reset auto start on 1 videos.
```

### Anything else?

yt-dlp probably needs to be updated, or a format other than mp4 may need to be used. ~~I tried setting the "Download Format" to 0, but it didn't have any effect.~~ Nevermind, it seems to work, I must have done something wrong. 

Importing the files downloaded by yt-dlp externally still gave the same error.

This has only started happening since a day or 2 ago.

**Comment by uninstall-your-browser** [comment]
Manually entering the docker container and updating yt-dlp doesn't seem to help unfortunately

**Comment by bbilly1** [comment]
That's mentioned in the FAQ: https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled

The nsig errors you see should be fixed in the latest yt-dlp build.

**Comment by ihatemyisp** [comment]
> That's mentioned in the FAQ: https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled
> 
> The nsig errors you see should be fixed in the latest yt-dlp build.

@uninstall-your-browser I can confirm that shifting to the unstable image fixed this issue for me.
