### ISSUE TITLE
[Feature Request]: Support file based docker secrets.

### ISSUE THREAD

**Issue by raldone01** [tubearchivist/tubearchivist#765]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

### Your Feature Request

Passing secrets via the environment is workable but docker has a secret system which provides secrets via files.

Usually environment variables which contain secrets can have `_FILE` appended and then the application loads the actual secret from a file.

This can be implemented by the application itself or via a simple bash entrypoint script that just reads all `_FILE` variables into their respective plain variants.

## Describe the solution you'd like

I am not very familiar with the code but I can contribute a simple entrypoint script that adds `_FILE` support to all variables.

## Additional context

Committing and pushing secrets is a serious issue and docker secrets help manage secrets centrally outside of version control.

### Your help is needed!

- [X] Yes I will work on this in the next few days or weeks.

I can also try to contribute adding a supervisor to the docker image to manage the multiple processes inside the container.
A supervisor can attempt to restart a process X times in X time if it crashes.

For both additions the changes should be quite minimal.

**Comment by bbilly1** [comment]
Docker can read env files, directly as part of the compose definition: https://docs.docker.com/compose/environment-variables/set-environment-variables/#use-the-env_file-attribute

Then you can easily ignore these files from version control.

**Comment by raldone01** [comment]
I guess env files are fine.

Are you interested in me adding a supervisor for the docker image?

**Comment by bbilly1** [comment]
I don't think adding supervisor to the mix would be very beneficial. If things crash, it's intentional, mostly because of impossible configuration from the user. Most tasks already are recovering on error, like uwsgi and celery.

But there is a good list of open tasks for the react frontend migration if you want to help! :-)
