### ISSUE TITLE
[Feature Request]: Add grouping of channels

### ISSUE THREAD

**Issue by jfroebe** [tubearchivist/tubearchivist#766]
### I've read the documentation

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [feature request](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#feature-request) section.

## Is your feature request related to a problem? Please describe.

Not an issue

## Describe the solution you'd like

Allow for the grouping of channels into categories/collections to organize the channels and alleviate having to try and remember the name of the channel or find the page number in the listing of channels.

e.g.
====
Category: Miniatures
- Groundeffected
- Goobertown Hobbies

Category: Computers/Technology
- Chris Titus Tech
- Linus Tech Tips
- Techno Dad Life

Category: Maker
-Make Everything
-CNA Insider
=====

### Your help is needed!

- [ ] Yes I will work on this in the next few days or weeks.

**Comment by bbilly1** [comment]
You'll be able to do that with the searchable notes. That is on the roadmap already. Besides, we are in project freeze while refactoring, and aren't taking new feature requests.

**Comment by jfroebe** [comment]
Awesome :). thanks!
