### ISSUE TITLE
Question: YT WatchLater to Archivist Download queue

### ISSUE THREAD

**Issue by ewoks** [tubearchivist/tubearchivist#771]
Thanks for this amazing project!!!
I just found out about it and wonder if following already exist and if not is it feasable (because of YT API) to have something like it in the future.

Sometimes I add youtube videos to WatchLater feature of YT, so I wonder if as a user, I could connect TubeArchivist to my YT account, which will occasionally check this WatchLater list and if there are new items download those in a background for me.

cc: @bbilly1 not a feature request just wonder about feature feasability
Thanks a lot and keep rocking :rocket: this great project

**Comment by bbilly1** [comment]
The docs define what is implemented:

- [FAQ](https://docs.tubearchivist.com/faq/#does-this-project-implement-feature-x)
- [cookies](https://docs.tubearchivist.com/settings/application/#cookie)
