### ISSUE TITLE
[Bug]: No method to add missing comments?

### ISSUE THREAD

**Issue by ericbarch** [tubearchivist/tubearchivist#775]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug

I recently needed to restore TA with only a backup of my media files. I performed a filesystem rescan and encountered a few videos that have been deleted on YT, which caused the rescan to stop. Not a big deal, as I read about this in the docs. I removed each deleted video and restarted the scan.

I hit another deleted video with about 30 remaining videos out of my ~1500 video library. After deleting this video and completing the rescan, comments were only added for the last ~30 videos that were scanned.

Looking through the docs and the UI, I can't seem to find an option to perform a comment re-index. Is there any way to get my comments back for the other 1400+ videos? I see there is a command to relink comments already in Elasticsearch, but my issue is that I don't have any comment data to begin with.

## Steps To Reproduce

Described above.

## Expected behavior

Have an option to requery missing comments from YT.

### Relevant log output

```shell
N/A
```

**Comment by bbilly1** [comment]
Not a bug. 

Reindex will do that.
