### ISSUE TITLE
[Feature Request]: How to use the specified HTTP/HTTPS/SOCKS proxy?

### ISSUE THREAD

**Issue by arbdevml** [tubearchivist/tubearchivist#776]
### This project doesn't accept any new feature requests for the forseeable future. There is no shortage of ideas and the next development steps are clear for years to come.

- [X] I understand that this issue will be closed without comment.

Hello, First of all very big thank you for this project.
yt-dlp provides the ability to download using a proxy:

```
--proxy URL                     Use the specified HTTP/HTTPS/SOCKS proxy. To
                                enable SOCKS proxy, specify a proper scheme,
                                e.g. socks5://user:pass@127.0.0.1:1080/.
                                Pass in an empty string (--proxy "") for
                                direct connection

```
How to use a proxy in Tube Archivist?
Thank you for your answers.

**Comment by bbilly1** [comment]
https://docs.tubearchivist.com/faq/#how-do-i-tunnel-all-traffic-from-this-container

**Comment by mietzen** [comment]
> https://docs.tubearchivist.com/faq/#how-do-i-tunnel-all-traffic-from-this-container

I'm also getting lots of these errors:

> ERROR: [youtube]: Sign in to confirm you’re not a bot. This helps protect our community. Learn more

and came here with a similar request, I did some digging through the code and I think that this might be easy to implement:

If we would put a config option for a list of proxies in the web UI, were we could pick a random proxy and set it in the 
[`obs`](https://github.com/tubearchivist/tubearchivist/blob/8550421a9a212bc97129e54ac40e47f10c4001fe/tubearchivist/home/src/download/yt_dlp_handler.py#L161) as [`proxy` option](https://github.com/ytdl-org/youtube-dl/blob/71223bff39551a11b6959a3de2dd9e2f070f3c4f/youtube_dl/YoutubeDL.py#L248).

@bbilly1 would you be open for such an option if it was provided via PR?

**Comment by bbilly1** [comment]
Requests to YT happen on multiple places, and not only through yt-dlp, also with the `requests` library for some things that aren't supported with yt-dlp. 

Container networking is not an application level problem. All complexity that we can avoid implementing, we should avoid implementing. There are lot's of options out there where you can pass all requests through a proxy, docker itself offers that functionality natively. 

Some more thoughts about the matter [here](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#contributions-beyond-the-scope).

**Comment by mietzen** [comment]
Thanks for the clarification! I developed a solution myself and I'm getting now why you didn't document one, my solution is highly specific to my use case: 
https://github.com/mietzen/docker-redsocks-proxy

For me [redsocks](https://github.com/darkk/redsocks) was a good starting point, my Docker Image should also be transferable to any other VPN Provider that offers SOCKS5 proxies, so feel free to fork.
