### ISSUE TITLE
[Bug]: Homepage (gethomepage/homepage) integration with API falsly reports the number of videos in Tube Archivist when reaching 10,000+ videos.

### ISSUE THREAD

**Issue by Unnamed0834** [tubearchivist/tubearchivist#779]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

TubeArchivist v0.4.9, Docker Engine - Community 27.1.1, API 1.46, SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15)

## Describe the bug
When the TA API is used with homepage dashboard (gethomepage/homepage), and the number of videos in TA exceeds 10,000, homepage will report 10,000 rather than the true amount.
## Steps To Reproduce
Create a Service in Homepage with API integration for TA.
![image](https://github.com/user-attachments/assets/1dfbb638-00f8-46d7-a3ea-f5821dbb8220)
TA instance must have more than 10,000 videos.
![image](https://github.com/user-attachments/assets/50c38599-20a3-4ef9-b2a7-26458692baf2)
Service API integration will not report anything higher than 10,000.
![image](https://github.com/user-attachments/assets/358836b5-17ee-4b77-b5a6-e5efc6b6d100)
## Expected behavior
Displaying the correct number of total videos in the API integration.

### Relevant log output

```shell
#Neither Produce any logs showing an error has occurred

#TubeArchivist Log
[2024-08-03 08:46:25,739: INFO/MainProcess] mingle: searching for neighbors
[2024-08-03 08:46:26,745: INFO/MainProcess] mingle: all alone
[2024-08-03 08:46:26,755: INFO/MainProcess] celery@f400f3e51adb ready.
  warnings.warn(
you should set broker_connection_retry_on_startup to True.
whether broker connection retries are made during startup in Celery 6.0 and above.
[2024-08-03 08:46:25,736: WARNING/MainProcess] /root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
If you wish to retain the existing behavior for retrying connections on startup,
[2024-08-03 08:46:25,735: INFO/MainProcess] Connected to redis://tubearchivist-redis:6379//
  . update_subscribed
[2024-08-03 08:46:25,731: WARNING/MainProcess] /root/.local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
  . version_check
  . thumbnail_check
[tasks]
  . check_reindex
  . download_pending
  . extract_download
  . index_playlists
  . manual_import
  . rescan_filesystem
  . restore_backup
  . resync_thumbs
  . run_backup
  . subscribe_to
                
                .> celery           exchange=celery(direct) key=celery
 -------------- [queues]
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
- *** --- * --- .> concurrency: 24 (prefork)
- ** ---------- .> results:     redis://tubearchivist-redis:6379/
- ** ---------- .> transport:   redis://tubearchivist-redis:6379//
- ** ---------- [config]
- ** ---------- .> app:         tasks:0x7fad2e4b56d0
- *** --- * --- 
-- ******* ---- Linux-6.1.0-23-amd64-x86_64-with-glibc2.36 2024-08-03 08:46:24
 -------------- celery@f400f3e51adb v5.4.0 (opalescent)
--- ***** ----- 
 
[2024-08-03 08:46:24,701: INFO/MainProcess] beat: Starting...
    . maxinterval -> 5.00 seconds (5s)
    . logfile -> [stderr]@%INFO
    . broker -> redis://tubearchivist-redis:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
Configuration ->
LocalTime -> 2024-08-03 08:46:24

#Homepage Log
Listening on port 3000
```

**Comment by bbilly1** [comment]
You've opened that on the wrong repo, You should open this issue on the homepage repo, this project isn't affiliated with them.

I didn't check, but I'm guessing they are using the pagination API for that. TA builds pagination links for up to 10k items: https://docs.tubearchivist.com/#general-navigation, so that's what you see.

The dashboard is build with the stats endpoints as documented here: https://docs.tubearchivist.com/api/stats/, that will show correct totals.
