### ISSUE TITLE
[Installation]: yt-dlp

### ISSUE THREAD

**Issue by SKILHUNT** [tubearchivist/tubearchivist#793]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Linux ubuntu 24.04

### Your installation or setup question

When I use TA i have problem with cookies. I need sync it every downloaded video. How i cen add google account to yt-dlp?

### Relevant log output

```Shell
[2024-08-21 15:44:08,659: WARNING/ForkPoolWorker-4] kvtIpl2ukIE: failed to get info from youtube with message ERROR: [youtube] kvtIpl2ukIE: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
```

**Comment by SKILHUNT** [comment]
Help recheck box sync cookies before add to download.

**Comment by ololoshka2871** [comment]
I just tried to provide cookies file: [yt-dlp --cookies cookies.txt ...](https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp) but no success. 
[yt-dlp --cookies-from-browser edge ...](https://github.com/yt-dlp/yt-dlp/issues/7271) works for me.

**Comment by bbilly1** [comment]
Adding the cookie is adding the google account. It is a know and documented yt-dlp limitation, that YT will invalidate your cookie sometimes frequently if it's used outside of a browser context, e.g. see here: https://github.com/yt-dlp/yt-dlp/issues/8227 .

Not much we can do about that. See our [FAW](https://docs.tubearchivist.com/faq/#am-i-getting-blockedthrottled) with additional workarounds that has been working for some people.

**Comment by p6002** [comment]
Any fix? Or project is death?
