### ISSUE TITLE
[Bug]: CSRF requires protocol in TA_HOST

### ISSUE THREAD

**Issue by skynet-gh** [tubearchivist/tubearchivist#809]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

## Describe the bug

In TubeArchivist v0.4.10, CSRF based on the `TA_HOST` config requires the `https://` protocol on the hostname. ([this might've been fixed in the past](https://github.com/tubearchivist/tubearchivist/issues/441#issuecomment-1501427896) so maybe a regression)

The docker-compose example has a `TA_HOST` *without* protocol: https://github.com/tubearchivist/tubearchivist/blob/cfe94c8dacca3b4f1f8d874d6ddf66553d6dcbd7/docker-compose.yml#L18
but maybe requiring protocol is expected.

There are some issues people are having with CSRF, and some suggestions to set `TA_HOST` *without* protocol: [example 1](https://github.com/tubearchivist/tubearchivist/issues/400#issuecomment-1371606982) [example 2](https://github.com/tubearchivist/tubearchivist/issues/549#issuecomment-1718396106)
but I believe it does currently require `https://` to be included.

So I think the docs/examples should be explicitly clear, or the code should be changed to not require protocol.

## Steps To Reproduce

Set `TA_HOST=<fqdn>` then start the server and navigate to `https://<fqdn>/login` and get this in the browser:

```
Forbidden (403)

CSRF verification failed. Request aborted.
Help

Reason given for failure:

    Origin checking failed - https://<fqdn> does not match any trusted origins.
```
And in the server log:
```
c70deb0f85b6 Forbidden (Origin checking failed - https://<fqdn> does not match any trusted origins.): /login/
```

The only way it works currently is by using the protocol: `TA_HOST=https://<fqdn>`

## Expected behavior

`<fqdn>` works for `TA_HOST` with or without protocol.

### Relevant log output

```shell
c70deb0f85b6 Forbidden (Origin checking failed - https://<fqdn> does not match any trusted origins.): /login/
```

### Anything else?

I am running the docker-compose setup.

**Comment by lamusmaser** [comment]
This is documented here: https://docs.tubearchivist.com/installation/docker-compose/#overview

It should be more distinctive, and that is something we are intending to be clearer about in documentation updates. Let's have this ticket opened in https://github.com/tubearchivist/docs/issues.
