### ISSUE TITLE
[Bug]: Error: Asked to "Sign in to confirm your age" despite using TubeArchivist Companion Browser Plugin

### ISSUE THREAD

**Issue by jlar0che** [tubearchivist/tubearchivist#810]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Docker via Synology (DSM 7.2.1-69057 Update 5)

## Describe the bug
When downloading playlists a few videos are returning the following error:

> ERROR: [youtube] CLtMjsMqJ6Q: Sign in to confirm your age. This video may be inappropriate for some users.

I am running TubeArchivist Companion in my browser and no other videos are returning errors. Tube Archivist Companion Version 0.3.2 (Last Updated September 16, 2024). My browser is Firefox, running the latest version -- version 130.0.

## Steps To Reproduce

1. Add a Playlist with content that may be deemed "inappropriate".
2. Click on "Downloads" button, then click on "Rescan Submissions" button, then click on the "Start download" button.
3. Content begins to download, but a few videos return the error outlined above.

## Expected behavior
All videos in my added Playlist download without issue.
![Issue](https://github.com/user-attachments/assets/591d7a9e-861a-4fe1-87a4-7659cf165ba6)

### Relevant log output

```shell
[2024-09-17 10:34:34,968: WARNING/ForkPoolWorker-39] ERROR: [youtube] CLtMjsMqJ6Q: Sign in to confirm your age. This video may be inappropriate for some users.
[2024-09-17 10:34:34,968: WARNING/ForkPoolWorker-39] CLtMjsMqJ6Q: failed to download with message ERROR: [youtube] CLtMjsMqJ6Q: Sign in to confirm your age. This video may be inappropriate for some users.
[2024-09-17 10:34:35,028: WARNING/ForkPoolWorker-39] CLtMjsMqJ6Q: Downloading video
```

**Comment by Zulux91** [comment]
Since you're using the browser extension, I'm assuming you have the sync cookies option enabled. If not , please do so, that should take car of the problem. If you do have it enabled can only think that the account you're sending the cookies hasn't been verified as +18. Maybe a date of birth or any other verifications needs to be done. I'd check in https://myaccount.google.com/personal-info just to make sure.

**Comment by jlar0che** [comment]
Thanks for the link! I double-checked and my info was correct. I decided to reject my cookie within the Tube Archivist web interface, then got it reconnected by clicking on the "import cookie" option under "Settings" --> "Application" --> "Cookie".

Long story short, after rejecting the cookie and getting it reset everything worked!

Thanks for your help!
