### ISSUE TITLE
[Bug]: Shorts not visible in application (not downloaded?)

### ISSUE THREAD

**Issue by Cyberes** [tubearchivist/tubearchivist#815]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux

### Your Bug Report

Sorry to bother you guys during the project freeze. 

## Describe the bug

I added a channel that contains mostly shorts but they do not appear to have been added to the archive or downloaded by the application.

![image](https://github.com/user-attachments/assets/595a66a8-34a8-46da-b374-da22d700646a)

## Steps To Reproduce

1. Add this channel to the archive: `https://www.youtube.com/@BChungus`
2. Download videos.

## Expected behavior

Shorts are downloaded.

### Relevant log output

```shell
[2024-09-22 21:01:13,365: WARNING/ForkPoolWorker-19] UC6hTmuCnroRL_DTbKKUlYeg: find missing videos.
```

**Comment by Styloy** [comment]
this is a known issue and is fixed in the [yt-dlp nightlies](
https://github.com/yt-dlp/yt-dlp/commit/9431777b4c37129a6093080c77ca59960afbb9d7). however there is not currently a yt-dlp release with this fix. 

you can follow [this](https://docs.tubearchivist.com/advanced/#manual-yt-dlp-update) guide to update your yt-dlp build. this has fixed the issue for my instances. however just keep in mind that this has the (however unlikely) potential to break other features.

**Comment by Dontkickmi22** [comment]
Try use "Add to queue" instead of  "Download Now", and report back.
Me experienced similar situation like you, wanted to know whats going on too. Peace.

**Comment by Cyberes** [comment]
Doing the add to queue thing doesn't download the shorts when I enter the channel URL. But if I add a short's URL, it's added to the queue.

**Comment by Dontkickmi22** [comment]
I see, thanks. 
I got some channels missing shorts too. Will try.

**Comment by Dontkickmi22** [comment]
adding shorts URL using 'add to queue' yields different result; some channel would, some not.
Interesting.

**Comment by bashman83** [comment]
There has been a couple of yt-dlp releases that have fixed this issue. You would need to do a manual upgrade however to get these, at this stage.

**Comment by bbilly1** [comment]
As stated, upstream should have the fix for that already, This looks like it: https://github.com/yt-dlp/yt-dlp/issues/10936

If you are brave you can fallow our manual update instructions [here](https://docs.tubearchivist.com/advanced/#manual-yt-dlp-update), otherwise wait for an update.

**Comment by Dontkickmi22** [comment]
Yea, I am aware of that yt-dlp release fix awhile ago. I will pass doing manual update myself and choose to  wait for the update. Thanks for your time.

**Comment by bbilly1** [comment]
[v0.4.11](https://github.com/tubearchivist/tubearchivist/releases/tag/v0.4.11) ships latest yt-dlp. Please update.
