### ISSUE TITLE
[Bug]: 400 Bad request in fresh Docker Compose build

### ISSUE THREAD

**Issue by QuAzI** [tubearchivist/tubearchivist#820]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu 24.04.1

### Your Bug Report

I just tried a clean setup with this config https://github.com/tubearchivist/tubearchivist/blob/master/docker-compose.yml
And it just shows 400 Bad request

Nothing special in logs
[docker-compose logs](https://github.com/user-attachments/files/17268634/docker-compose.zip)

### Relevant log output

```shell
"Relevant log output" can't fit log but always required?
```

### Anything else?

Images versions
```shell
$ docker inspect $(docker compose ps -q) | grep "Image"
        "Image": "sha256:7a6696851b5f88347cb94e158f007d4e166db72845ed69ea7d69e22b07c34753",
            "Image": "bbilly1/tubearchivist-es",
        "Image": "sha256:d0058500d8dc8454bbd2e4ea6b718bf30f77ed4467073ffb85dd278ee83d5707",
            "Image": "redis/redis-stack-server",
        "Image": "sha256:6cc998de69ffa72a6245a38d913e5808d97fa1ae0e9c781c59d78ecf37cec6cb",
            "Image": "bbilly1/tubearchivist"
```

**Comment by bbilly1** [comment]
404 is "not found", do you mean 403?

If that's the case, see our docs for TA_HOST configuration.

**Comment by QuAzI** [comment]
Sorry, not 404 but 400
![image](https://github.com/user-attachments/assets/3bd9c0a8-93f4-40c6-a68a-51f0699bad3b)

**Comment by bbilly1** [comment]
yes, you need to configure TA_HOST.

**Comment by QuAzI** [comment]
A bit unclean, why users in local playground should set up hostname while in result it should be managed by reverse proxy like nginx or traefic

**Comment by bbilly1** [comment]
Well *should* maybe, but we can't know that you are running this in a local playground. 

Assume this is solved.

**Comment by QuAzI** [comment]
I don't think it will work in the wild the same way as public video hostings. So you know defaults
