### ISSUE TITLE
[Bug]: "not of expected type playlist" for 24-character playlist Ids

### ISSUE THREAD

**Issue by douglasg14b** [tubearchivist/tubearchivist#824]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux Docker

### Your Bug Report

# Description
This is similar to the follow, but unrelated to "Albums"?:
- https://github.com/tubearchivist/tubearchivist/issues/512
- https://github.com/tubearchivist/tubearchivist/issues/796

I have playlists that follow the `https://www.youtube.com/playlist?list=<playlist_id>` format but which do not work with this project. Such as playlist Ids with 24 characters.

These appear to be _identical_ to playlists with `34` character Ids in every way I have checked.

Example: `https://www.youtube.com/playlist?list=FLWgx-LFSrh9QF7AHOPZqDRQ`

<hr>

The reasoning in the previous issues appear to be `"It doesn't work because it's by design"`. However, that appears to be directed at albums, not playlists. And 24-character one appears to be exactly the same as other playlists.

- This appears to be the same as any other playlist
-  `yt-dlp` doesn't appear to have any problems with this playlist
- Can the length of `24` be added to the constraints? Is there some unsupported behavior here?

### Relevant log output

```shell
N/A
```

**Comment by douglasg14b** [comment]
Oh, I just re-read the docs here: https://docs.tubearchivist.com/urls/

It states that channel Ids are `24` characters long. However, I'm seeing the linked playlist as an actual playlist. Not a channel. The channel with Id `FLWgx-LFSrh9QF7AHOPZqDRQ` does not actually exist, it's a playlist 🤔

**Comment by lamusmaser** [comment]
All general playlists start with PL identifiers. This one starting with FL indicates that it is a Favorites List, which is hard to reference. We attempted this in #484 but ultimately closed as Not Planned. 

The API is documented within those same docs. If you need help, please let us know and we can provide you with more details related to that specific effort.

**Comment by bbilly1** [comment]
Just to clarify:

Identifying videos, playlists and channels happens through length of ID. These old Favorites playlists are as you noted 24 characters long, same as channels. So the workaround proposed in the duplicate issue you have found, even though might have worked, would have broken that. I didn't want to do that just to be able to support these old favorites playlists, that you can't even create anymore now.

So that's why this is marked as "not planned".

Regarding the docs: The url page you have found clearly indicates what URLs are supported.

**Comment by douglasg14b** [comment]
> Regarding the docs: The url page you have found clearly indicates what URLs are supported.

Let me clarify.

A list of supported features that omit mention of unsupported features which are explicitly not supported leads to issues that ask for support for those features since it's very much not obvious that they are not supported intentionally as opposed to unsupported in the way most people are familiar with unsupported software features, by unintentional omission.

The communication can help avoid issues like this from being raised.

<hr>

All that said, I'm mostly saddened not by the fact that archival software doesn't support historical archiving, but more that it will never support it and specifically does not want to.

Thank you for the reply, I know you're not obligated to respond to issues, so I really do appreciate it.

**Comment by bbilly1** [comment]
We had this section in the FAQ for some time now: https://docs.tubearchivist.com/faq/#does-this-project-implement-feature-x, ultimately its just easier and less time consuming to document what is implemented than what is not. 

But i see your point, this should clarify it: https://github.com/tubearchivist/docs/commit/a318e34890777200f4935e4ffbc5efce07707042

And yes, as a maintainer it is my responsibility to make sure new additions to this project will not limit future expansions, will not impact reliability and stability of existing archives. For decisions like when it's about balancing between handling obscure edge cases like these old playlists vs existing functionality, stability and ease of maintenance, I will always prioritize existing functionality. Hope you can understand.
