### ISSUE TITLE
[Installation]: cloudflare tunnel TA_HOST Issues

### ISSUE THREAD

**Issue by Zyzto** [tubearchivist/tubearchivist#828]
### Installation instructions

- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [installation help](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#installation-help) section.

### Operating System

Unraid

### Your installation or setup question

I am running on unraid and I had no issue with local network, I've tried to use tailscale and had issues with passing the ip.

and now I am trying to tunnel through cloudflare (it's protected with zero trust) but I keep getting Error 502.

TA_HOST :  https://sub.domain.tld  http://sub.domain.tld https://cloudflare.com https://cloudflareaccess.com 10.0.0.10
*I hid my domain

![image](https://github.com/user-attachments/assets/0d145c67-db6d-4f17-9cd7-fb17dd82b3ca)

### Relevant log output

```Shell
no logs are provided for this issue
```

**Comment by bbilly1** [comment]
What 502 error? Is the request comming through to TA? Activate debug and share some logs.

**Comment by Zyzto** [comment]
> What 502 error? Is the request comming through to TA? Activate debug and share some logs.

Thanks for the fast reply, my bad I just spent 4h debugging the issue and after I posted I noticed tubearchivist runs on http not https, so I just edited the tunnel to http not https
