### ISSUE TITLE
[Bug]: Force sort missed av1 once in awhile and went for vp9 

### ISSUE THREAD

**Issue by Dontkickmi22** [tubearchivist/tubearchivist#830]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Debian docker with RPi4

## Describe the bug
Configured for av1. Discovered instance where vp9 clip were downloaded when av1 is available. Delete and re-adding back in queue gets me that av1 the second pass. 
  
I have got force sort set to : res,codec:av1,proto:https,vext:webm

## Expected behavior
should go for av1 when available.

### Relevant log output

```shell
Wasn't around when it happened. 
gonna try catching it in action, then share it here with you buddies.
```

### Anything else?

Anyone using force sort experiencing this too?

**Comment by bbilly1** [comment]
That can happen if YT hasn't processed all formats yet, but the video is available. So that is a timing issue. Sorting is one part, If you only want one specific codec, you can also define that in the format selection, so it won't fallback to the next available.

For periodic rescan an check for a "better" format available, see here: #265.

**Comment by Dontkickmi22** [comment]
Appreciated your time.
By means hasn't processed, would be listed in query (-F)? 
A couple scenarios, ones which with the new as in recent release videos that I understand the above could happen. I also am going thru database re-downloading a better codec version (downsizing), and these are not new. With these I did -F query to confirm each of them has a better smaller sized version prior to delete and re-add. I got some of these omitting the av1 and went for the vp9.

**Comment by bbilly1** [comment]
No, if a format is not processed by YT at the time of downloading, it wouldn't be available when checking with the -F option.

Also TA checks of a format is actually downloadable first, so if that fails, then the next in line would be picked by yt-dlp. 

Crucial, that's at time of downloading and not at time of rechecking after the fact.

So lots of variables here.

**Comment by Dontkickmi22** [comment]
-F listed av1 vp9
delete, readd
got vp9
delete again, readd
got av1

I encountered above.

**Comment by bbilly1** [comment]
Logs?

If you can reproduce that consistently, you'll probably want to reach out to the yt-dlp team.

**Comment by Dontkickmi22** [comment]
Yea, will do, I am trying to catch that, meanwhile raised to see anyone else got it.

**Comment by Dontkickmi22** [comment]
```
270     mp4   1920x1080   30    │ ~  2.96GiB 4716k m3u8  │ avc1.640028   4716k video only
137     mp4   1920x1080   30    │    1.51GiB 2403k https │ avc1.640028   2403k video only          1080p, mp4_dash
614     mp4   1920x1080   30    │ ~  2.25GiB 3584k m3u8  │ vp09.00.40.08 3584k video only
248     webm  1920x1080   30    │  940.46MiB 1464k https │ vp09.00.40.08 1464k video only          1080p, webm_dash
616     mp4   1920x1080   30    │ ~  3.66GiB 5827k m3u8  │ vp09.00.40.08 5827k video only          Premium
```
Encounterd a situation today, saw downloading an 1.8g file, did a follow up -F query to check. Return above result. Should have been downloading 248 (940M) instead. I proceed to restart container, and start download again. This time fetched 248 (940M).  Log shows the usual stuff, nothing.
