### ISSUE TITLE
[Bug]: unable to download age restricted videos even with valid cookie

### ISSUE THREAD

**Issue by gebi** [tubearchivist/tubearchivist#836]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Ubuntu 22.04 with docker compose

## Describe the bug
age restricted video is not downloaded even with valid cookies

## Steps To Reproduce
trying to download video `zJRxCPLPlgs`

## Expected behavior
download the video :)

### Relevant log output

```shell
tubearchivist    | [2024-11-16 18:49:15,031: WARNING/ForkPoolWorker-1] zJRxCPLPlgs: [213/511]: add to queue
tubearchivist    | [2024-11-16 18:49:16,350: WARNING/ForkPoolWorker-1] WARNING: [youtube] YouTube said: ERROR - The caller does not have permission
tubearchivist    | [2024-11-16 18:49:16,351: WARNING/ForkPoolWorker-1] WARNING: [youtube] Unable to download API page: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
tubearchivist    | [2024-11-16 18:49:16,353: WARNING/ForkPoolWorker-1] ERROR: [youtube] zJRxCPLPlgs: Sign in to confirm your age. This video may be inappropriate for some users.
tubearchivist    | [2024-11-16 18:49:16,353: WARNING/ForkPoolWorker-1] zJRxCPLPlgs: failed to get info from youtube with message ERROR: [youtube] zJRxCPLPlgs: Sign in to confirm your age. This video may be inappropriate for some users.
```

**Comment by gebi** [comment]
oh, maybe i should add that with the account that provided the cookie the video in question plays without additional questions or age verifications.

**Comment by bbilly1** [comment]
This goes back to the known limitations: https://github.com/tubearchivist/tubearchivist?tab=readme-ov-file#known-limitations, if yt-dlpt can't download it, TA won't be able to either.

Sometimes the ytdlp team has more insights if you ask nicely on their repo.

**Comment by calscoo** [comment]
Yeah this is a tough one because you could solve it with a cookie from your age verified account, but if you wanna really protect yourself from youtube banning you, then you should only be supplying a cookie from a guest account (sign out of all google apps, including youtube) behind an anonymous IP (use a VPN).
