### ISSUE TITLE
[Question]: Redownload all videos in cache

### ISSUE THREAD

**Issue by QuAzI** [tubearchivist/tubearchivist#837]
Is there any way to redownload all the videos which were in /media again? I used an external HDD for /media and at one moment ext4 partition was ruined. So I need all the videos back but don't want to add one-by-one manually

**Comment by lamusmaser** [comment]
Ignoring our templates is an automatic close. Please open again while following our associated template.

**Comment by bbilly1** [comment]
Please read our docs first before opening any issues, to avoid getting banned here.

E.h. here: https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue
https://docs.tubearchivist.com/faq/#does-this-project-implement-feature-x

Obviously, as you can see we don't have a question template, you are expected to read the docs, most is answered there. If something ist answer, there is always the discord server.

Respect the time people put in here.
