### ISSUE TITLE
[Bug]: Upon disconnecting drive, wslg fills up with downloads dedicated to disconnected drive.

### ISSUE THREAD

**Issue by VooDisss** [tubearchivist/tubearchivist#845]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Windows 10, tubearchivist installed in WSL2 Ubuntu distro via docker

## Describe the bug
Below mentioned directory fills up with downloading videos, which should not be downloaded there if the drive required is not found or not mounted correctly
\\wsl.localhost\Ubuntu\mnt\wslg\distro\mnt\f\ACloud\Youtube Backup\TubeArchivist\youtube 

## Steps To Reproduce
1. Setup your tube archiver docker-compose-yml.txt with these lines changing the directory to another drive than where WSL is installed:
`    ports:
      - 8000:8000
    volumes:
      - **/mnt/f**/ACloud/Youtube Backup/TubeArchivist/youtube:/youtube
      - **/mnt/f**/ACloud/Youtube Backup/TubeArchivist/cache:/cache
`
2. cmd enter wsl, go to the directory containing docker-compose-yml.txt and enter `docker compose up --detach`
3. Wait till tube archiver works and boots up, then shut down/unmount the drive mentioned in #1 (mine is using usb-sata cable and powered by external PSU 12V). 
4. download videos in any way

## Expected behavior

Videos will download to `\\wsl.localhost\Ubuntu\mnt\**wslg**\distro\mnt\f\ACloud\Youtube Backup\TubeArchivist\youtube `  and `\\wsl.localhost\Ubuntu\mnt\**wslg**\distro\mnt\f\ACloud\Youtube Backup\TubeArchivist\cache` fills up with cache instead of downloading to F drive where expected.

It fills up the C drive (where wsl is installed) and then one needs to manually copy the files to the directory in F drive. After moving files and rescanning filesystem using tube archiver UI, one wants to delete the unecessary files in `\\wsl.localhost\Ubuntu\mnt\wslg\distro\mnt\f\ACloud\Youtube Backup\TubeArchivist` , but cannot do that in any way. I tried deleting by:

1. going through command line WSL to that directory and writing `rm -rf *`. Getting error:
`rm: cannot remove 'UCc05bDpqGAooTMalXbalaOA/mki_YdQqwo8.mp4': Read-only file system`
2. going to that directory using windows explorer, getting error "The disk is write-protected." "Remove the write-protection or use another disk."
I tried removing write-only via properties menu, but it did not affect the ability to delete the files. 

Another bug:
After this, one cannot "delete all queued" in settings>actions. It just does not react and writes `delete queue by status: pending`. New channels queue just fine.

### Relevant log output

```shell
Nothing suspicious when "rescan subscribtions":
tubearchivist    | [2024-12-08 05:13:52,420: INFO/MainProcess] Task update_subscribed[82f89452-a913-4378-b8c2-ffbf0b90185c] received
tubearchivist    | [2024-12-08 05:13:52,420: WARNING/ForkPoolWorker-13] update_subscribed create callback
tubearchivist    | [2024-12-08 05:13:52,468: WARNING/ForkPoolWorker-13] UCc05bDpqGAooTMalXbalaOA: find missing videos.
tubearchivist    | [2024-12-08 05:13:53,284: WARNING/ForkPoolWorker-13] ERROR: [youtube:tab] UCc05bDpqGAooTMalXbalaOA: This channel does not have a shorts tab
tubearchivist    | [2024-12-08 05:13:53,332: WARNING/ForkPoolWorker-13] 82f89452-a913-4378-b8c2-ffbf0b90185c success callback
tubearchivist    | [2024-12-08 05:13:53,336: INFO/ForkPoolWorker-13] Task update_subscribed[82f89452-a913-4378-b8c2-ffbf0b90185c] succeeded in 0.911978463999958s: None
tubearchivist    | [2024-12-08 05:13:53,336: WARNING/ForkPoolWorker-13] 82f89452-a913-4378-b8c2-ffbf0b90185c return callback
```

### Anything else?

More context with some screenshots about what led me here:
https://discord.com/channels/920056098122248193/1315081365297041491/1315081365297041491

**Comment by lamusmaser** [comment]
This isn't an issue with TubeArchivist, but rather operating within the confines of how WSL operates with Docker.

Essentially, when a mount is missing for a Docker container, the location on the container's filesystem still exists. Docker doesn't provide the container a method for detecting if a specific location is or is not mounted and any workaround would cause issues with either existing or new installations.

If you have questions, we can go into more detail on the Discord Support case, which you have already linked.
