### ISSUE TITLE
[Bug]: non-original audio tracks being returned/downloaded as default

### ISSUE THREAD

**Issue by eblechschmidt** [tubearchivist/tubearchivist#847]
### I've read the documentation

- [X] I'm running the latest version of Tube Archivist and have read the [release notes](https://github.com/tubearchivist/tubearchivist/releases/latest).
- [X] I have read the [how to open an issue](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#how-to-open-an-issue) guide, particularly the [bug report](https://github.com/tubearchivist/tubearchivist/blob/master/CONTRIBUTING.md#bug-report) section.

### Operating System

Linux/docker

## Describe the bug

Since a few weeks for some German channels the AI generated English audio track is downloaded instead of the original which is quite anyoing.

## Steps To Reproduce

Run TubeArchivist v0.4.11 and add a channel that provides AI generated content that is not English.

## Expected behavior

Download the video with the original Language audio track instead of the AI generated English one.

### Relevant log output

```shell
N/A
```

### Anything else?

This seems to be a bug in `yt-dlp` that has been fixed: https://github.com/yt-dlp/yt-dlp/issues/3766. It might be just bumping `yt-dpl`to version 2024.12.13.

**Comment by kymograph** [comment]
I have the same issue

**Comment by eblechschmidt** [comment]
I forked the repo, bumped the `yt-dlp` version to 2024-12-13 and build the docker image. That seems to do the trick. Could make a pull request but I'm unsure how to ensure the new version does not break anything else.

**Comment by bbilly1** [comment]
Yeah, I've noticed the same. Even on YT directly, they prioritize AI duped voice over. You can pull the newest unstable image shipping updated yt-dlp.

**Comment by bbilly1** [comment]
TA v0.4.12 ships newest yt-dlp, fixing that issue.
